name: doasvm_demo
dependencies:
- certifi=2015.9.6.2=py34_0
- openssl=1.0.2d=0
- pip=7.1.2=py34_0
- python=3.4.3=2
- readline=6.2=2
- setuptools=18.5=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- tornado=4.2.1=py34_1
- wheel=0.26.0=py34_1
- xz=5.0.5=0
- zlib=1.2.8=0

