Import("env")

doasvm_feature_extraction = env.SharedLibrary(
    ['doasvm_feature_extraction.cpp', 'hann.cpp', 'ifftshift.cpp'],
    SHLIBPREFIX='', srcdir='doasvm_feature_extraction'
)
doasvm_classification = env.SharedLibrary(
    ['doasvm_classification.cpp'], SHLIBPREFIX='',
    srcdir='doasvm_classification'
)
ac_pooling = env.SharedLibrary('acPooling_wave.cpp', SHLIBPREFIX='',
                               srcdir='acPooling_wave')

ac_transform = env.SharedLibrary('acTransform_wave.cpp', SHLIBPREFIX='',
                               srcdir='acTransform_wave')
Return('doasvm_feature_extraction', 'doasvm_classification', 'ac_pooling',
       'ac_transform')
