function sLib = libclientdb()
% LIBCLIENTDB - function handle library
%
% Usage:
% libclientdb()
%
% Help to function "fun" can be accessed by calling
% clientdb.help.fun()
%

% This file was generated by "bake_mlib clientdb".
% Do not edit! Edit sources clientdb_*.m instead.
%
% Date: 09-Jun-2017 11:50:56
sLib = struct;
assignin('caller','clientdb',sLib);


