openMHA Manual: MHA_TCP::Connection Class Reference
MHA_TCP::Connection Class Reference
#include <mha_tcp.hh>
Public Member Functions
Sockread_Event * get_read_event ()
Sockwrite_Event * get_write_event ()
std::string get_peer_address ()
unsigned short get_peer_port ()
SOCKET get_fd () const
virtual ~Connection ()
bool eof ()
bool can_read_line (char delim= '\n')
bool can_read_bytes (unsigned howmany)
std::string read_line (char delim= '\n')
std::string read_bytes (unsigned howmany)
void try_write (const std::string &data="")
void write (const std::string &data="")
bool needs_write ()
unsigned buffered_incoming_bytes () const
unsigned buffered_outgoing_bytes () const
Protected Member Functions
Connection (SOCKET _fd) throw (MHA_Error)
Protected Attributes
SOCKET fd
Private Member Functions
void init_peer_data ()
bool can_sysread ()
bool can_syswrite ()
std::string sysread (unsigned bytes)
std::string syswrite (const std::string &data)
Private Attributes
std::string outbuf
std::string inbuf
Sockread_Event * read_event
Sockwrite_Event * write_event
bool closed
struct sockaddr_in peer_addr
Friends
class Server
Detailed Description
Connection handles Communication between client and server, is used on both sides.
Constructor & Destructor Documentation
MHA_TCP::Connection::Connection (SOCKET _fd) throw (MHA_Error) protected
Create a connection instance from a socket filedescriptor.
Parameters
_fd The file descriptor of the TCP Socket. This file descriptor is closed again in the destructor.
Exceptions
MHA_Error If the file descriptor is < 0.
References fd, INVALID_SOCKET, peer_addr, read_event, SOCKET_ERROR, and write_event.
Connection::~Connection () virtual
Destructor closes the underlying file descriptor
References closesocket, fd, INVALID_SOCKET, read_event, and write_event.
Member Function Documentation
void MHA_TCP::Connection::init_peer_data () private
determine peer address and port
bool Connection::can_sysread () private
Determine wether at least 1 byte can be read without blocking.
References get_read_event(), and MHA_TCP::Wakeup_Event::status().
Referenced by can_read_bytes(), can_read_line(), and eof().
bool Connection::can_syswrite () private
Determine wether at least 1 byte can be written without blocking.
References get_write_event(), and MHA_TCP::Wakeup_Event::status().
Referenced by try_write().
std::string Connection::sysread (unsigned bytes) private
Call the system's read function and try to read bytes. This will block in a situation where can_sysread returns false.
Parameters
bytes The desired number of characters.
Returns
The characters read from the socket. The result may have fewer characters than specified by bytes. If the result is an empty string, then the socket has been closed by the peer.
References closed, fd, get_read_event(), MHA_TCP::N_ERRNO(), MHA_TCP::Event_Watcher::observe(), SOCKET_ERROR, MHA_TCP::STRERROR(), and MHA_TCP::Event_Watcher::wait().
Referenced by can_read_bytes(), can_read_line(), and eof().
std::string Connection::syswrite (const std::string & data) private
Call the system's write function and try to write all characters in the string data. May write fewer characters, but will at least write one character.
Parameters
data A string of characters to write to the socket.
Returns
The rest of the characters that have not yet been written.
References fd, MHA_TCP::N_ERRNO(), SOCKET_ERROR, MHA_TCP::STRERROR(), and write().
Referenced by try_write(), and write().
Sockread_Event * Connection::get_read_event ()
References read_event.
Referenced by can_sysread(), io_tcp_t::connection_loop(), read_bytes(), read_line(), and sysread().
Sockwrite_Event * Connection::get_write_event ()
References write_event.
Referenced by mhaserver_t::acceptor_started(), can_syswrite(), and io_tcp_t::connection_loop().
std::string Connection::get_peer_address ()
Get peer's IP Address
References peer_addr.
Referenced by io_tcp_t::connection_loop(), and mhaserver_t::run().
unsigned short Connection::get_peer_port ()
Get peer's TCP port
References peer_addr.
Referenced by io_tcp_t::connection_loop(), and mhaserver_t::run().
SOCKET MHA_TCP::Connection::get_fd () const inline
Return the (protected) file descriptor of the connection. Will be required for SSL.
References MHA_TCP::OS_EVENT_TYPE::fd.
bool Connection::eof ()
Checks if the peer has closed the connection. As a side effect, this method fills the internal "incoming" buffer if it was empty and the socket is readable and not eof.
References can_sysread(), inbuf, and sysread().
Referenced by can_read_line(), io_tcp_t::connection_loop(), and mhaserver_t::run().
bool Connection::can_read_line (char delim = '\n')
Checks if a full line of text has arrived by now. This method reads data from the socket into the internal "incoming" buffer if it can be done without blocking.
Parameters
delim The line delimiter.
Returns
true if at least one full line of text is present in the internal buffer after this method call, false otherwise.
References buffered_incoming_bytes(), can_sysread(), eof(), inbuf, and sysread().
Referenced by read_line().
bool Connection::can_read_bytes (unsigned howmany)
Checks if the specified ammount of data can be read. This method reads data from the socket into an internal "incoming" buffer if it can be done without blocking.
Parameters
howmany The number of bytes that the caller wants to have checked.
Returns
true if at least the specified ammount of data is present in the internal buffer after this method call, false otherwise
References buffered_incoming_bytes(), can_sysread(), inbuf, and sysread().
Referenced by io_tcp_t::connection_loop(), and read_bytes().
std::string Connection::read_line (char delim = '\n')
Reads a single line of data from the socket. Blocks if necessary.
Parameters
delim The line delimiter.
Returns
The string of characters in this line, including the trailing delimiter. The delimiter may be missing if the last line before EOF does not have a delimiter.
References can_read_line(), get_read_event(), inbuf, MHASignal::min(), MHA_TCP::Event_Watcher::observe(), and MHA_TCP::Event_Watcher::wait().
Referenced by mhaserver_t::run().
std::string Connection::read_bytes (unsigned howmany)
Reads the specified ammount of dat from the socket. Blocks if necessary.
Parameters
howmany The number of bytes to read.
Returns
The string of characters read. The string may be shorter if EOF is encountered.
References can_read_bytes(), closed, get_read_event(), inbuf, MHA_TCP::Event_Watcher::observe(), and MHA_TCP::Event_Watcher::wait().
Referenced by io_tcp_t::connection_loop().
void Connection::try_write (const std::string & data = "")
Adds data to the internal "outgoing" buffer, and then tries to write as much data from that buffer to the socket as possible without blocking.
Parameters
data data to send over the socket.
References can_syswrite(), needs_write(), outbuf, and syswrite().
Referenced by mhaserver_t::acceptor_started(), and io_tcp_t::connection_loop().
void Connection::write (const std::string & data = "")
Adds data to the internal "outgoing" buffer, and then writes that that buffer to the socket, regardless of blocking.
Parameters
data data to send over the socket.
References needs_write(), outbuf, and syswrite().
Referenced by mhaserver_t::run(), and syswrite().
bool Connection::needs_write ()
Checks if the internal "outgoing" buffer contains data.
References buffered_outgoing_bytes().
Referenced by mhaserver_t::acceptor_started(), io_tcp_t::connection_loop(), try_write(), and write().
unsigned Connection::buffered_incoming_bytes () const
Returns the number of bytes in the internal "incoming" buffer.
References inbuf.
Referenced by can_read_bytes(), can_read_line(), and io_tcp_t::connection_loop().
unsigned Connection::buffered_outgoing_bytes () const
Returns the number of bytes in the internal "outgoing" buffer.
References outbuf.
Referenced by needs_write().
Friends And Related Function Documentation
friend class Server friend
Member Data Documentation
std::string MHA_TCP::Connection::outbuf private
Referenced by buffered_outgoing_bytes(), try_write(), and write().
std::string MHA_TCP::Connection::inbuf private
Referenced by buffered_incoming_bytes(), can_read_bytes(), can_read_line(), eof(), read_bytes(), and read_line().
Sockread_Event* MHA_TCP::Connection::read_event private
Referenced by Connection(), get_read_event(), and ~Connection().
Sockwrite_Event* MHA_TCP::Connection::write_event private
Referenced by Connection(), get_write_event(), and ~Connection().
bool MHA_TCP::Connection::closed private
Referenced by read_bytes(), and sysread().
struct sockaddr_in MHA_TCP::Connection::peer_addr private
Referenced by Connection(), get_peer_address(), and get_peer_port().
SOCKET MHA_TCP::Connection::fd protected
The file descriptor of the TCP Socket.
Referenced by Connection(), sysread(), syswrite(), and ~Connection().
The documentation for this class was generated from the following files:
mha_tcp.hh
mha_tcp.cpp