openMHA Manual: MHA_AC::ac2matrix_t Class Reference
MHA_AC::ac2matrix_t Class Reference
Communication between algorithms
Copy AC variable to a matrix.
#include <mha_algo_comm.h>
Public Member Functions
ac2matrix_t (algo_comm_t ac, const std::string &name)
Constructor.
void update ()
Update contents of the matrix from the AC space.
const std::string & getname () const
Return name of AC variable/matrix.
const std::string & getusername () const
Return user specified name of AC variable/matrix.
void insert (algo_comm_t ac)
Insert matrix into an AC space (other than source AC space)
Public Member Functions inherited from MHASignal::matrix_t
matrix_t (unsigned int nrows, unsigned int ncols, bool b_is_complex=true)
Create a two-dimensional matrix.
matrix_t (const mha_spec_t &spec)
Create a two-dimensional matrix from a spectrum, copy values.
matrix_t (const MHASignal::uint_vector_t &size, bool b_is_complex=true)
Create n-dimensional matrix, descriped by size argument.
matrix_t (const MHASignal::matrix_t &)
matrix_t (const uint8_t *buf, unsigned int len)
Construct from memory area.
~matrix_t ()
MHASignal::matrix_t & operator= (const MHASignal::matrix_t &)
MHASignal::matrix_t & operator= (const comm_var_t &v)
Fill matrix with data of an AC variable object.
comm_var_t get_comm_var ()
Return a AC communication variable pointing to the data of the current matrix.
unsigned int dimension () const
Return the dimension of the matrix.
unsigned int size (unsigned int k) const
Return the size of the matrix.
unsigned int get_nelements () const
Return total number of elements.
bool is_same_size (const MHASignal::matrix_t &)
Test if matrix has same size as other.
bool iscomplex () const
Return information about complexity.
mha_real_t & real (const MHASignal::uint_vector_t &index)
Access real part of an element in a n-dimensional matrix.
mha_real_t & imag (const MHASignal::uint_vector_t &index)
Access imaginary part of an element in a n-dimensional matrix.
mha_complex_t & operator() (const MHASignal::uint_vector_t &index)
Access complex value of an element in a n-dimensional matrix.
const mha_real_t & real (const MHASignal::uint_vector_t &index) const
Access real part of an element in a n-dimensional matrix.
const mha_real_t & imag (const MHASignal::uint_vector_t &index) const
Access imaginary part of an element in a n-dimensional matrix.
const mha_complex_t & operator() (const MHASignal::uint_vector_t &index) const
Access complex value of an element in a n-dimensional matrix.
mha_real_t & real (unsigned int row, unsigned int col)
Access real part of an element in a two-dimensional matrix.
mha_real_t & imag (unsigned int row, unsigned int col)
Access imaginary part of an element in a two-dimensional matrix.
mha_complex_t & operator() (unsigned int row, unsigned int col)
Access complex value of an element in a two-dimensional matrix.
const mha_real_t & real (unsigned int row, unsigned int col) const
Access real part of an element in a two-dimensional matrix.
const mha_real_t & imag (unsigned int row, unsigned int col) const
Access imaginary part of an element in a two-dimensional matrix.
const mha_complex_t & operator() (unsigned int row, unsigned int col) const
Access complex value of an element in a two-dimensional matrix.
unsigned int get_nreals () const
unsigned int get_index (unsigned int row, unsigned int col) const
unsigned int get_index (const MHASignal::uint_vector_t &index) const
unsigned int numbytes () const
Return number of bytes needed to store into memory.
unsigned int write (uint8_t *buf, unsigned int len) const
Copy to memory area.
const mha_real_t * get_rdata () const
Return pointer of real data.
const mha_complex_t * get_cdata () const
Return pointer of complex data.
Additional Inherited Members
Private Member Functions inherited from MHA_AC::ac2matrix_helper_t
ac2matrix_helper_t (algo_comm_t, const std::string &)
void getvar ()
Private Attributes inherited from MHA_AC::ac2matrix_helper_t
algo_comm_t ac
std::string name
std::string username
MHASignal::uint_vector_t size
bool is_complex
comm_var_t acvar
Detailed Description
Copy AC variable to a matrix.
This class constructs a matrix of same size as an AC variable and can copy the AC variable to itself. The update() function is real-time safe.
Constructor & Destructor Documentation
MHA_AC::ac2matrix_t::ac2matrix_t (algo_comm_t ac, const std::string & name)
Constructor.
Parameters
ac AC handle
name Name of AC variable to be copied
References update().
Member Function Documentation
void MHA_AC::ac2matrix_t::update ()
Update contents of the matrix from the AC space.
This function is real-time safe. The copy operation performance is of the order of the number of elements in the matrix.
References MHA_AC::ac2matrix_helper_t::acvar, MHA_AC::ac2matrix_helper_t::getvar(), and MHASignal::matrix_t::operator=().
Referenced by ac2matrix_t().
const std::string& MHA_AC::ac2matrix_t::getname () const inline
Return name of AC variable/matrix.
References MHA_AC::spectrum_t::name.
Referenced by insert().
const std::string& MHA_AC::ac2matrix_t::getusername () const inline
Return user specified name of AC variable/matrix.
References MHA_AC::spectrum_t::insert().
void MHA_AC::ac2matrix_t::insert (algo_comm_t ac)
Insert matrix into an AC space (other than source AC space)
Parameters
ac AC space handle to insert data
Note
The AC variable data buffer points to the data of the matrix. Modifications of the AC variable directly modify the data of the matrix; after deletion of the matrix, the data buffer is invalid.
References MHASignal::matrix_t::get_comm_var(), getname(), algo_comm_t::handle, and algo_comm_t::insert_var.
The documentation for this class was generated from the following files:
mha_algo_comm.h
mha_algo_comm.cpp