openMHA Manual: adm_if_t Class Reference
adm_if_t Class Reference
Public Member Functions
adm_if_t (const algo_comm_t &ac, const std::string &thread_name, const std::string &algo_name)
mha_wave_t * process (mha_wave_t *in)
virtual void prepare (mhaconfig_t &)
virtual void release ()
Public Member Functions inherited from MHAPlugin::plugin_t< adm_rtconfig_t >
plugin_t (const std::string &, const algo_comm_t &)
Constructor of plugin template.
virtual ~plugin_t ()
void prepare_ (mhaconfig_t &)
void release_ ()
bool is_prepared () const
Flag, if the prepare method is successfully called (or currently evaluated)
mhaconfig_t input_cfg () const
Current input channel configuration.
mhaconfig_t output_cfg () const
Current output channel configuration.
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from MHAPlugin::config_t< adm_rtconfig_t >
config_t ()
~config_t ()
Private Member Functions
void update ()
bool is_prepared ()
Private Attributes
MHASignal::waveform_t * out
MHAParser::vint_t front_channels
MHAParser::vint_t rear_channels
MHAParser::vfloat_t distances
MHAParser::int_t lp_order
MHAParser::int_t decomb_order
MHAParser::int_t bypass
MHAParser::float_t beta
MHAParser::vfloat_mon_t coeff_lp
MHAParser::vfloat_mon_t coeff_decomb
unsigned input_channels
mha_real_t srate
MHAEvents::patchbay_t< adm_if_t > patchbay
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Member Functions inherited from MHAPlugin::config_t< adm_rtconfig_t >
adm_rtconfig_t * poll_config ()
Receive the latest run time configuration.
adm_rtconfig_t * last_config ()
Receive the latest run time configuration.
void push_config (adm_rtconfig_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Protected Attributes inherited from MHAPlugin::plugin_t< adm_rtconfig_t >
mhaconfig_t tftype
Member for storage of plugin interface configuration.
algo_comm_t ac
AC handle of the chain.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Protected Attributes inherited from MHAPlugin::config_t< adm_rtconfig_t >
adm_rtconfig_t * cfg
Constructor & Destructor Documentation
adm_if_t::adm_if_t (const algo_comm_t & ac, const std::string & thread_name, const std::string & algo_name)
References beta, bypass, coeff_decomb, coeff_lp, MHAEvents::patchbay_t< receiver_t >::connect(), decomb_order, distances, MHAParser::parser_t::insert_item(), insert_member, lp_order, patchbay, update(), and MHAParser::base_t::writeaccess.
Member Function Documentation
mha_wave_t * adm_if_t::process (mha_wave_t * in)
References adm_rtconfig_t::adm(), beta, bypass, MHAPlugin::config_t< adm_rtconfig_t >::cfg, MHAParser::int_t::data, MHAParser::float_t::data, adm_rtconfig_t::front_channel(), input_channels, MHAPLUGIN_CALLBACKS, MHAPLUGIN_DOCUMENTATION, mha_wave_t::num_channels, mha_wave_t::num_frames, out, MHAPlugin::config_t< adm_rtconfig_t >::poll_config(), ADM::ADM< F >::process(), adm_rtconfig_t::rear_channel(), value(), and MHASignal::waveform_t::value().
void adm_if_t::prepare (mhaconfig_t & cfg) virtual
Implements MHAPlugin::plugin_t< adm_rtconfig_t >.
References adm_fir_decomb(), adm_fir_lp(), mhaconfig_t::channels, coeff_decomb, coeff_lp, MHAParser::int_t::data, MHAParser::vfloat_t::data, MHAParser::vfloat_mon_t::data, decomb_order, distances, mhaconfig_t::domain, mhaconfig_t::fragsize, input_channels, is_prepared(), lp_order, MHA_ErrorMsg, MHA_WAVEFORM, out, release(), mhaconfig_t::srate, srate, std_vector_float(), and update().
void adm_if_t::release () virtual
Reimplemented from MHAPlugin::plugin_t< adm_rtconfig_t >.
References out.
Referenced by prepare().
void adm_if_t::update () private
References MHAParser::int_t::data, MHAParser::vfloat_t::data, decomb_order, distances, input_channels, is_prepared(), lp_order, MHA_ErrorMsg, mha_wave_t::num_channels, out, MHAPlugin::config_t< adm_rtconfig_t >::push_config(), and srate.
Referenced by adm_if_t(), and prepare().
bool adm_if_t::is_prepared () inline private
Referenced by prepare(), and update().
Member Data Documentation
MHASignal::waveform_t* adm_if_t::out private
Referenced by prepare(), process(), release(), and update().
MHAParser::vint_t adm_if_t::front_channels private
MHAParser::vint_t adm_if_t::rear_channels private
MHAParser::vfloat_t adm_if_t::distances private
Referenced by adm_if_t(), prepare(), and update().
MHAParser::int_t adm_if_t::lp_order private
Referenced by adm_if_t(), prepare(), and update().
MHAParser::int_t adm_if_t::decomb_order private
Referenced by adm_if_t(), prepare(), and update().
MHAParser::int_t adm_if_t::bypass private
Referenced by adm_if_t(), and process().
MHAParser::float_t adm_if_t::beta private
Referenced by adm_if_t(), and process().
MHAParser::vfloat_mon_t adm_if_t::coeff_lp private
Referenced by adm_if_t(), and prepare().
MHAParser::vfloat_mon_t adm_if_t::coeff_decomb private
Referenced by adm_if_t(), and prepare().
unsigned adm_if_t::input_channels private
Referenced by prepare(), process(), and update().
mha_real_t adm_if_t::srate private
Referenced by prepare(), and update().
MHAEvents::patchbay_t<adm_if_t> adm_if_t::patchbay private
Referenced by adm_if_t().
The documentation for this class was generated from the following file:
adm.cpp