openMHA Manual: mhachain::chain_base_t Class Reference
mhachain::chain_base_t Class Reference
#include <mha_generic_chain.h>
Public Member Functions
chain_base_t (algo_comm_t, const std::string &, const std::string &)
void process (mha_wave_t *, mha_wave_t **)
void process (mha_spec_t *, mha_wave_t **)
void process (mha_wave_t *, mha_spec_t **)
void process (mha_spec_t *, mha_spec_t **)
void prepare (mhaconfig_t &)
void release ()
Public Member Functions inherited from MHAPlugin::plugin_t< mhachain::plugs_t >
plugin_t (const std::string &, const algo_comm_t &)
Constructor of plugin template.
virtual ~plugin_t ()
void prepare_ (mhaconfig_t &)
void release_ ()
bool is_prepared () const
Flag, if the prepare method is successfully called (or currently evaluated)
mhaconfig_t input_cfg () const
Current input channel configuration.
mhaconfig_t output_cfg () const
Current output channel configuration.
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from MHAPlugin::config_t< mhachain::plugs_t >
config_t ()
~config_t ()
Protected Attributes
MHAParser::bool_t bprofiling
MHAParser::vstring_t algos
Protected Attributes inherited from MHAPlugin::plugin_t< mhachain::plugs_t >
mhaconfig_t tftype
Member for storage of plugin interface configuration.
algo_comm_t ac
AC handle of the chain.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Protected Attributes inherited from MHAPlugin::config_t< mhachain::plugs_t >
mhachain::plugs_t * cfg
Private Member Functions
void update ()
Private Attributes
std::vector< std::string > old_algos
MHAEvents::patchbay_t< mhachain::chain_base_t > patchbay
mhaconfig_t cfin
mhaconfig_t cfout
bool b_prepared
std::string chain
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Member Functions inherited from MHAPlugin::config_t< mhachain::plugs_t >
mhachain::plugs_t * poll_config ()
Receive the latest run time configuration.
mhachain::plugs_t * last_config ()
Receive the latest run time configuration.
void push_config (mhachain::plugs_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Constructor & Destructor Documentation
mhachain::chain_base_t::chain_base_t (algo_comm_t iac, const std::string & ichain, const std::string & ialgo)
References algos, patchbay, MHAParser::base_t::set_node_id(), update(), and MHAParser::base_t::writeaccess.
Member Function Documentation
void mhachain::chain_base_t::process (mha_wave_t * sin, mha_wave_t ** sout)
void mhachain::chain_base_t::process (mha_spec_t * sin, mha_wave_t ** sout)
void mhachain::chain_base_t::process (mha_wave_t * sin, mha_spec_t ** sout)
void mhachain::chain_base_t::process (mha_spec_t * sin, mha_spec_t ** sout)
void mhachain::chain_base_t::prepare (mhaconfig_t & cf) virtual
Implements MHAPlugin::plugin_t< mhachain::plugs_t >.
References b_prepared, MHAPlugin::config_t< mhachain::plugs_t >::cfg, cfin, cfout, MHA_ErrorMsg, MHAPlugin::config_t< mhachain::plugs_t >::poll_config(), mhachain::plugs_t::prepare(), and mhachain::plugs_t::prepared().
void mhachain::chain_base_t::release () virtual
Reimplemented from MHAPlugin::plugin_t< mhachain::plugs_t >.
References b_prepared, MHAPlugin::config_t< mhachain::plugs_t >::cfg, MHAPlugin::config_t< mhachain::plugs_t >::cleanup_unused_cfg(), MHA_ErrorMsg, MHAPlugin::config_t< mhachain::plugs_t >::poll_config(), mhachain::plugs_t::prepared(), and mhachain::plugs_t::release().
void mhachain::chain_base_t::update () private
References MHAPlugin::plugin_t< mhachain::plugs_t >::ac, algos, b_prepared, bprofiling, cfin, cfout, chain, MHAParser::vstring_t::data, MHAParser::bool_t::data, MHAParser::parser_t::force_remove_item(), MHAParser::expression_t::lval, old_algos, MHAPlugin::config_t< mhachain::plugs_t >::poll_config(), MHAPlugin::config_t< mhachain::plugs_t >::push_config(), and MHAParser::expression_t::rval.
Referenced by chain_base_t().
Member Data Documentation
MHAParser::bool_t mhachain::chain_base_t::bprofiling protected
Referenced by mhachain::mhachain_t::mhachain_t(), and update().
MHAParser::vstring_t mhachain::chain_base_t::algos protected
Referenced by chain_base_t(), mhachain::mhachain_t::mhachain_t(), and update().
std::vector<std::string> mhachain::chain_base_t::old_algos private
Referenced by update().
MHAEvents::patchbay_t< mhachain::chain_base_t > mhachain::chain_base_t::patchbay private
Referenced by chain_base_t().
mhaconfig_t mhachain::chain_base_t::cfin private
Referenced by prepare(), and update().
mhaconfig_t mhachain::chain_base_t::cfout private
Referenced by prepare(), and update().
bool mhachain::chain_base_t::b_prepared private
Referenced by prepare(), release(), and update().
std::string mhachain::chain_base_t::chain private
Referenced by update().
The documentation for this class was generated from the following files:
mha_generic_chain.h
mha_generic_chain.cpp