openMHA Manual: MHA_TCP::Server Class Reference
MHA_TCP::Server Class Reference
#include <mha_tcp.hh>
Public Member Functions
Server (unsigned short port=0, const std::string &iface="0.0.0.0")
Server (const std::string &iface, unsigned short port=0)
~Server ()
std::string get_interface () const
unsigned short get_port () const
Sockaccept_Event * get_accept_event ()
Connection * accept ()
Connection * try_accept ()
Private Member Functions
void initialize (const std::string &iface, unsigned short port)
Private Attributes
sockaddr_in sock_addr
SOCKET serversocket
std::string iface
unsigned short port
Sockaccept_Event * accept_event
Constructor & Destructor Documentation
Server::Server (unsigned short port = 0, const std::string & iface = "0.0.0.0")
Create a TCP server socket.
Parameters
port The TCP port to listen to.
iface The network interface to bind to.
Server::Server (const std::string & iface, unsigned short port = 0)
Create a TCP server socket.
Parameters
port The TCP port to listen to.
iface The network interface to bind to.
Server::~Server ()
Close the TCP server socket.
References closesocket, and INVALID_SOCKET.
Member Function Documentation
void Server::initialize (const std::string & iface, unsigned short port) private
References closesocket, host_port_to_sock_addr(), INVALID_SOCKET, MHA_ErrorMsg, MHA_TCP::N_ERRNO(), SOCKET_ERROR, and MHA_TCP::STRERROR().
std::string Server::get_interface () const
Get the name given in the constructor for the network interface.
unsigned short Server::get_port () const
Get the port that the TCP server socket currently listens to.
Referenced by mhaserver_t::acceptor_started(), and io_tcp_t::prepare().
Sockaccept_Event * Server::get_accept_event ()
Produces an event that can be observed by an Event_Watcher. This event signals incoming connections that can be accepted.
Referenced by io_tcp_t::accept_loop().
Connection * Server::accept ()
Accept an incoming connection. blocks if necessary.
Returns
The new TCP connection. The connection has to be deleted by the caller.
References MHA_TCP::Event_Watcher::observe(), and MHA_TCP::Event_Watcher::wait().
Referenced by mhaserver_t::run().
Connection * Server::try_accept ()
Accept an incoming connection if it can be done without blocking.
Returns
The new TCP connection or 0 if there is no immediate connection. The connection has to be deleted by the caller.
References INVALID_SOCKET, MHA_TCP::N_ERRNO(), and MHA_TCP::STRERROR().
Referenced by io_tcp_t::accept_loop().
Member Data Documentation
sockaddr_in MHA_TCP::Server::sock_addr private
SOCKET MHA_TCP::Server::serversocket private
std::string MHA_TCP::Server::iface private
unsigned short MHA_TCP::Server::port private
Sockaccept_Event* MHA_TCP::Server::accept_event private
The documentation for this class was generated from the following files:
mha_tcp.hh
mha_tcp.cpp