openMHA Manual: MHA_TCP::Event_Watcher Class Reference
MHA_TCP::Event_Watcher Class Reference
#include <mha_tcp.hh>
Public Types
typedef std::set< Wakeup_Event * > Events
typedef std::set< Wakeup_Event * >::iterator iterator
Public Member Functions
void observe (Wakeup_Event *event)
void ignore (Wakeup_Event *event)
std::set< Wakeup_Event * > wait ()
\ Wait for some event to occur.
virtual ~Event_Watcher ()
Private Attributes
std::set< Wakeup_Event * > events
Detailed Description
OS-independent event watcher, uses select on Unix and WaitForMultipleObjects on Windows.
Member Typedef Documentation
typedef std::set<Wakeup_Event*> MHA_TCP::Event_Watcher::Events
typedef std::set<Wakeup_Event*>::iterator MHA_TCP::Event_Watcher::iterator
Constructor & Destructor Documentation
Event_Watcher::~Event_Watcher () virtual
Member Function Documentation
void Event_Watcher::observe (Wakeup_Event * event)
Add an event to this observer.
References MHA_ErrorMsg.
Referenced by MHA_TCP::Server::accept(), io_tcp_t::accept_loop(), mhaserver_t::acceptor_started(), io_tcp_t::connection_loop(), MHA_TCP::Connection::read_bytes(), MHA_TCP::Connection::read_line(), io_tcp_t::release(), MHA_TCP::Wakeup_Event::status(), MHA_TCP::Connection::sysread(), tcp_connect_to_with_timeout(), and MHA_TCP::Timeout_Watcher::Timeout_Watcher().
void Event_Watcher::ignore (Wakeup_Event * event)
Remove an event from this observer
References MHA_ErrorMsg.
std::set< Wakeup_Event * > Event_Watcher::wait ()
\ Wait for some event to occur.
Return all events that are ready
References MHA_TCP::dtime(), MHA_TCP::OS_EVENT_TYPE::fd, MHA_TCP::G_ERRNO(), MHASignal::max(), MHA_ErrorMsg, MHA_TCP::OS_EVENT_TYPE::mode, MHA_TCP::STRERROR(), and MHA_TCP::OS_EVENT_TYPE::timeout.
Referenced by MHA_TCP::Server::accept(), io_tcp_t::accept_loop(), mhaserver_t::acceptor_started(), io_tcp_t::connection_loop(), MHA_TCP::Connection::read_bytes(), MHA_TCP::Connection::read_line(), io_tcp_t::release(), MHA_TCP::Wakeup_Event::status(), MHA_TCP::Connection::sysread(), and tcp_connect_to_with_timeout().
Member Data Documentation
std::set<Wakeup_Event*> MHA_TCP::Event_Watcher::events private
The list of events to watch.
The documentation for this class was generated from the following files:
mha_tcp.hh
mha_tcp.cpp