openMHA Manual: MHAPlugin::config_t< runtime_cfg_t > Class Template Reference
MHAPlugin::config_t< runtime_cfg_t > Class Template Reference
Template class for thread safe configuration.
#include <mha_plugin.hh>
Public Member Functions
config_t ()
~config_t ()
Protected Member Functions
runtime_cfg_t * poll_config ()
Receive the latest run time configuration.
runtime_cfg_t * last_config ()
Receive the latest run time configuration.
void push_config (runtime_cfg_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Protected Attributes
runtime_cfg_t * cfg
Private Member Functions
void remove_all_cfg ()
Private Attributes
MHAPlugin::cfg_chain_t< runtime_cfg_t > * cfg_chain
MHAPlugin::cfg_chain_t< runtime_cfg_t > * cfg_chain_current
Friends
class ::Test_mha_plugin_rtcfg_t
Detailed Description
template<class runtime_cfg_t>
class MHAPlugin::config_t< runtime_cfg_t >
Template class for thread safe configuration.
This template class provides a mechanism for the handling of thread safe configuration which is required for run time configuration changes of the MHA plugins.
The template parameter runtime_cfg_t is the run time configuration class of the MHA plugin. The constructor of that class should transform the MHAParser variables into derived runtime configuration. The constructor should fail if the configuration is invalid by any reason.
A new runtime configuration is provided by the function push_config(). In the processing thread, the actual configuration can be received by a call of poll_config().
Schematic drawing of runtime configuration update: configuration updated, but not used yet.
Schematic drawing of runtime configuration update: configuration in use.
Constructor & Destructor Documentation
template<class runtime_cfg_t > MHAPlugin::config_t< runtime_cfg_t >::config_t ()
template<class runtime_cfg_t > MHAPlugin::config_t< runtime_cfg_t >::~config_t ()
References Getmsg, and mha_debug().
Member Function Documentation
template<class runtime_cfg_t > runtime_cfg_t * MHAPlugin::config_t< runtime_cfg_t >::poll_config () protected
Receive the latest run time configuration.
This function stores the latest run time configuration into the protected class member variable `cfg'. If no configuration exists, then an exception will be thrown. If no changes occured, then the value of `cfg' will be untouched. This function should be called before any access to the `cfg' variable, typically once in each signal processing call.
This function should be only called from the processing thread.
Exceptions
MHA_Error if the resulting runtime configuration is NULL. This usually means that no push_config has occured.
References MHA_ErrorMsg, MHAPlugin::cfg_chain_t< runtime_cfg_t >::next, and MHAPlugin::cfg_chain_t< runtime_cfg_t >::not_in_use.
Referenced by MHAFilter::adapt_filter_t::filter(), and calibrator_t::process().
template<class runtime_cfg_t > runtime_cfg_t * MHAPlugin::config_t< runtime_cfg_t >::last_config () protected
Receive the latest run time configuration.
This function stores the latest run time configuration into the protected class member variable `cfg'. If no configuration exists, then an exception will be thrown. If no changes occured, then the value of `cfg' will be untouched. This function may be called instead of poll_config.
The difference between poll_config and last_config is that poll_config marks previous configurations as ready for deletion, while this function does not. Therefore, memory usage of all runtime configurations will accumulate if only this function is called, but it enables safe access to previous runtime configurations.
Also, last_config does not raise an Exception when the latest run time configuration is NULL.
template<class runtime_cfg_t> void MHAPlugin::config_t< runtime_cfg_t >::push_config (runtime_cfg_t * ncfg) protected
Push a new run time configuration into the configuration fifo.
This function adds a new run time configuration. The next time poll_config is called, this configuration will be available. Configurations which are not in use or are outdated will be removed.
This function should be only called from the configuration thread.
Parameters
ncfg pointer on a new configuration
Warning
The runtime configuration passed to this function will be removed by the internal garbage collector. Do not free manually.
References MHAPlugin::cfg_chain_t< runtime_cfg_t >::next.
Referenced by calibrator_t::update(), MHAFilter::adapt_filter_t::update_mu(), MHAFilter::adapt_filter_t::update_ntaps(), and calibrator_t::update_tau_level().
template<class runtime_cfg_t > void MHAPlugin::config_t< runtime_cfg_t >::cleanup_unused_cfg () protected
References MHAPlugin::cfg_chain_t< runtime_cfg_t >::next.
template<class runtime_cfg_t > void MHAPlugin::config_t< runtime_cfg_t >::remove_all_cfg () private
References MHAPlugin::cfg_chain_t< runtime_cfg_t >::next.
Friends And Related Function Documentation
template<class runtime_cfg_t> friend class ::Test_mha_plugin_rtcfg_t friend
Member Data Documentation
template<class runtime_cfg_t> runtime_cfg_t* MHAPlugin::config_t< runtime_cfg_t >::cfg protected
Referenced by calibrator_t::read_levels().
template<class runtime_cfg_t> MHAPlugin::cfg_chain_t<runtime_cfg_t>* MHAPlugin::config_t< runtime_cfg_t >::cfg_chain private
template<class runtime_cfg_t> MHAPlugin::cfg_chain_t<runtime_cfg_t>* MHAPlugin::config_t< runtime_cfg_t >::cfg_chain_current private
The documentation for this class was generated from the following file:
mha_plugin.hh