openMHA Manual: mha_fifo_thread_platform_t Class Reference
mha_fifo_thread_platform_t Class Reference abstract
Abstract base class for synchronizing multithreaded (producer/consumer) fifo operations.
#include <mha_fifo.h>
Public Member Functions
virtual void aquire_mutex ()=0
Calling thread waits until it aquires the lock.
virtual void release_mutex ()=0
Calling thread releases the lock.
virtual void wait_for_decrease ()=0
Calling producer thread must own the lock.
virtual void wait_for_increase ()=0
Calling consumer thread must own the lock.
virtual void increment ()=0
To be called by producer thread after producing.
virtual void decrement ()=0
To be called by consumer thread after consuming.
virtual ~mha_fifo_thread_platform_t ()
Make destructor virtual.
mha_fifo_thread_platform_t ()
Make default constructor accessible.
Private Member Functions
mha_fifo_thread_platform_t (const mha_fifo_thread_platform_t &)
mha_fifo_thread_platform_t & operator= (const mha_fifo_thread_platform_t &)
Detailed Description
Abstract base class for synchronizing multithreaded (producer/consumer) fifo operations.
Works only with single producer and single consumer.
Constructor & Destructor Documentation
virtual mha_fifo_thread_platform_t::~mha_fifo_thread_platform_t () inline virtual
Make destructor virtual.
References mha_fifo_t< T >::operator=().
mha_fifo_thread_platform_t::mha_fifo_thread_platform_t (const mha_fifo_thread_platform_t &) private
mha_fifo_thread_platform_t::mha_fifo_thread_platform_t () inline
Make default constructor accessible.
Member Function Documentation
virtual void mha_fifo_thread_platform_t::aquire_mutex () pure virtual
Calling thread waits until it aquires the lock.
Must not be called when the lock is already aquired.
Implemented in mha_fifo_posix_threads_t.
Referenced by mha_fifo_thread_guard_t::mha_fifo_thread_guard_t().
virtual void mha_fifo_thread_platform_t::release_mutex () pure virtual
Calling thread releases the lock.
May only be called when lock is owned.
Implemented in mha_fifo_posix_threads_t.
Referenced by mha_fifo_thread_guard_t::~mha_fifo_thread_guard_t().
virtual void mha_fifo_thread_platform_t::wait_for_decrease () pure virtual
Calling producer thread must own the lock.
Method releases lock, and waits for consumer thread to call decrease(). Then reaquires lock and returns
Implemented in mha_fifo_posix_threads_t.
virtual void mha_fifo_thread_platform_t::wait_for_increase () pure virtual
Calling consumer thread must own the lock.
Method releases lock, and waits for producer thread to call increase(). Then reaquires lock and returns
Implemented in mha_fifo_posix_threads_t.
virtual void mha_fifo_thread_platform_t::increment () pure virtual
To be called by producer thread after producing.
Producer thread needs to own the lock to call this method.
Implemented in mha_fifo_posix_threads_t.
Referenced by mha_fifo_lw_t< T >::set_error().
virtual void mha_fifo_thread_platform_t::decrement () pure virtual
To be called by consumer thread after consuming.
Consumer thread needs to own the lock to call this method.
Implemented in mha_fifo_posix_threads_t.
Referenced by mha_fifo_lw_t< T >::set_error().
mha_fifo_thread_platform_t& mha_fifo_thread_platform_t::operator= (const mha_fifo_thread_platform_t &) private
The documentation for this class was generated from the following file:
mha_fifo.h