openMHA Manual: MHA_TCP::Timeout_Event Class Reference
MHA_TCP::Timeout_Event Class Reference
#include <mha_tcp.hh>
Public Member Functions
Timeout_Event (double interval)
virtual OS_EVENT_TYPE get_os_event ()
Public Member Functions inherited from MHA_TCP::Wakeup_Event
Wakeup_Event ()
virtual void observed_by (Event_Watcher *observer)
virtual void ignored_by (Event_Watcher *observer)
virtual ~Wakeup_Event ()
virtual void reset ()
virtual bool status ()
Private Attributes
double end_time
Additional Inherited Members
Protected Attributes inherited from MHA_TCP::Wakeup_Event
OS_EVENT_TYPE os_event
bool os_event_valid
Constructor & Destructor Documentation
Timeout_Event::Timeout_Event (double interval)
References MHA_TCP::dtime(), MHA_TCP::G_ERRNO(), MHA_TCP::STRERROR(), and MHA_TCP::OS_EVENT_TYPE::T.
Member Function Documentation
OS_EVENT_TYPE Timeout_Event::get_os_event () virtual
Reimplemented from MHA_TCP::Wakeup_Event.
References MHA_TCP::dtime(), MHA_TCP::Wakeup_Event::get_os_event(), MHASignal::max(), and MHA_TCP::OS_EVENT_TYPE::timeout.
Member Data Documentation
double MHA_TCP::Timeout_Event::end_time private
The documentation for this class was generated from the following files:
mha_tcp.hh
mha_tcp.cpp