openMHA Manual: fftfilterbank::fftfb_plug_t Class Reference
fftfilterbank::fftfb_plug_t Class Reference
Public Member Functions
fftfb_plug_t (MHAOvlFilter::overlap_save_filterbank_t::vars_t &, mhaconfig_t chcfg, algo_comm_t ac, std::string alg, bool return_imag)
mha_spec_t * process (mha_spec_t *)
mha_wave_t * process (mha_wave_t *)
void insert ()
Public Member Functions inherited from MHAOvlFilter::overlap_save_filterbank_analytic_t
overlap_save_filterbank_analytic_t (MHAOvlFilter::overlap_save_filterbank_t::vars_t &fbpar, mhaconfig_t channelconfig_in)
void filter_analytic (const mha_wave_t *sIn, mha_wave_t **fltRe, mha_wave_t **fltIm)
Public Member Functions inherited from MHAOvlFilter::overlap_save_filterbank_t
overlap_save_filterbank_t (MHAOvlFilter::overlap_save_filterbank_t::vars_t &fbpar, mhaconfig_t channelconfig_in)
mhaconfig_t get_channelconfig () const
Public Member Functions inherited from MHAOvlFilter::fftfb_t
fftfb_t (MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
Constructor for a FFT-based overlapping filter bank.
~fftfb_t ()
void apply_gains (mha_spec_t *s_out, const mha_spec_t *s_in, const mha_wave_t *gains)
void get_fbpower (mha_wave_t *fbpow, const mha_spec_t *s_in)
void get_fbpower_db (mha_wave_t *fbpow, const mha_spec_t *s_in)
std::vector< mha_real_t > get_ltass_gain_db () const
unsigned int bin1 (unsigned int band) const
Return index of first non-zero filter shape window.
unsigned int bin2 (unsigned int band) const
Return index of first zero filter shape window above center frequency.
unsigned int get_fftlen () const
Return fft length.
mha_real_t w (unsigned int k, unsigned int b) const
Return filter shape window at index k in band b.
Public Member Functions inherited from MHAOvlFilter::fspacing_t
fspacing_t (const MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
std::vector< unsigned int > get_cf_fftbin () const
std::vector< mha_real_t > get_cf_hz () const
std::vector< mha_real_t > get_ef_hz () const
unsigned int nbands () const
Return number of bands in filter bank.
Public Member Functions inherited from MHAFilter::fftfilterbank_t
fftfilterbank_t (unsigned int fragsize, unsigned int inputchannels, unsigned int firchannels, unsigned int fftlen)
Constructor.
~fftfilterbank_t ()
void update_coeffs (const mha_wave_t *h)
Update the set of coefficients.
void filter (const mha_wave_t *s_in, mha_wave_t **s_out, const mha_wave_t *h)
Apply filter with changing coefficients to a waveform fragment.
void filter (const mha_wave_t *s_in, mha_wave_t **s_out)
Apply filter to waveform fragment, without changing the coefficients.
const mha_wave_t * get_irs () const
Return the current IRS.
Private Attributes
MHAOvlFilter::fftfb_ac_info_t fb_acinfo
MHASignal::spectrum_t s_out
MHA_AC::waveform_t imag
bool return_imag_
Additional Inherited Members
Protected Member Functions inherited from MHAOvlFilter::fspacing_t
void fail_on_nonmonotonic_cf ()
void fail_on_unique_fftbins ()
Protected Attributes inherited from MHAOvlFilter::fspacing_t
std::vector< MHAOvlFilter::band_descriptor_t > bands
mha_real_t(* symmetry_scale)(mha_real_t)
Constructor & Destructor Documentation
fftfilterbank::fftfb_plug_t::fftfb_plug_t (MHAOvlFilter::overlap_save_filterbank_t::vars_t & vars, mhaconfig_t chcfg, algo_comm_t ac, std::string alg, bool return_imag)
Member Function Documentation
mha_spec_t * fftfilterbank::fftfb_plug_t::process (mha_spec_t * s)
References MHAOvlFilter::fftfb_t::bin1(), MHAOvlFilter::fftfb_t::bin2(), mha_spec_t::buf, mha_complex_t::im, MHAOvlFilter::fspacing_t::nbands(), mha_spec_t::num_channels, mha_spec_t::num_frames, mha_complex_t::re, s_out, and MHAOvlFilter::fftfb_t::w().
mha_wave_t * fftfilterbank::fftfb_plug_t::process (mha_wave_t * s)
References MHASignal::waveform_t::copy(), MHAFilter::fftfilterbank_t::filter(), MHAOvlFilter::overlap_save_filterbank_analytic_t::filter_analytic(), imag, MHAPLUGIN_CALLBACKS, MHAPLUGIN_DOCUMENTATION, MHAPLUGIN_PROC_CALLBACK, and return_imag_.
void fftfilterbank::fftfb_plug_t::insert ()
References fb_acinfo, imag, MHA_AC::waveform_t::insert(), MHAOvlFilter::fftfb_ac_info_t::insert(), and return_imag_.
Member Data Documentation
MHAOvlFilter::fftfb_ac_info_t fftfilterbank::fftfb_plug_t::fb_acinfo private
Referenced by insert().
MHASignal::spectrum_t fftfilterbank::fftfb_plug_t::s_out private
Referenced by process().
MHA_AC::waveform_t fftfilterbank::fftfb_plug_t::imag private
Referenced by insert(), and process().
bool fftfilterbank::fftfb_plug_t::return_imag_ private
Referenced by insert(), and process().
The documentation for this class was generated from the following file:
fftfilterbank.cpp