openMHA Manual: fw_t Class Reference
fw_t Class Reference
#include <mhafw_lib.h>
Public Member Functions
fw_t ()
~fw_t ()
bool exit_request () const
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Protected Attributes
int proc_error
int io_error
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Private Types
enum state_t {
fw_unprepared, fw_stopped, fw_starting, fw_running,
fw_stopping, fw_exiting
}
Private Member Functions
void prepare ()
preparation for processing
void start ()
start of processing
void stop ()
stop/pause of processing
void release ()
release of IO device
void quit ()
controlled quit
void stopped (int, int)
void started ()
int process (mha_wave_t *, mha_wave_t **)
void exec_fw_command ()
void load_proc_lib ()
void load_io_lib ()
void fw_sleep_cmd ()
void fw_until_cmd ()
void get_input_signal_dimension ()
void async_read ()
void async_poll_msg ()
void get_parserstate ()
Static Private Member Functions
static void stopped (void *h, int proc_err, int io_err)
static void started (void *h)
static int process (void *h, mha_wave_t *sIn, mha_wave_t **sOut)
Private Attributes
fw_vars_t prepare_vars
MHAParser::int_mon_t nchannels_out
MHAParser::string_t proc_name
MHAParser::string_t io_name
MHAParser::bool_t exit_on_stop
MHAParser::int_t fw_sleep
MHAParser::string_t fw_until
MHAParser::kw_t fw_cmd
MHAParser::string_mon_t parserstate
MHAParser::string_t errorlog
MHAParser::string_t fatallog
MHAParser::vstring_t plugins
MHAParser::vstring_t plugin_paths
MHAParser::bool_t dump_mha
MHAParser::string_t inst_name
A variable for naming MHA instances.
MHAKernel::algo_comm_class_t ac
PluginLoader::mhapluginloader_t * proc_lib
io_lib_t * io_lib
mhaconfig_t cfin
mhaconfig_t cfout
state_t state
bool b_exit_request
MHAParser::string_mon_t proc_error_string
MHAEvents::patchbay_t< fw_t > patchbay
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Member Enumeration Documentation
enum fw_t::state_t private
Enumerator
fw_unprepared
fw_stopped
fw_starting
fw_running
fw_stopping
fw_exiting
Constructor & Destructor Documentation
fw_t::fw_t ()
References async_poll_msg(), async_read(), MHAEvents::patchbay_t< receiver_t >::connect(), dump_mha, errorlog, exec_fw_command(), fatallog, fw_cmd, fw_sleep, fw_sleep_cmd(), fw_until, fw_until_cmd(), get_parserstate(), MHAParser::parser_t::insert_item(), inst_name, io_name, load_io_lib(), load_proc_lib(), nchannels_out, parserstate, patchbay, plugin_paths, plugins, MHAParser::base_t::prereadaccess, proc_error_string, proc_name, MHAParser::base_t::readaccess, and MHAParser::base_t::writeaccess.
fw_t::~fw_t ()
References Getmsg, io_lib, proc_lib, and quit().
Member Function Documentation
bool fw_t::exit_request () const inline
References io_lib_t::prepare(), io_lib_t::release(), io_lib_t::start(), and io_lib_t::stop().
Referenced by mha_exit_request(), mhamain(), and mhaserver_t::run().
void fw_t::prepare (void) private
preparation for processing
References cfin, cfout, mhaconfig_t::channels, MHAParser::int_mon_t::data, mhaconfig_t::domain, mhaconfig_t::fragsize, fw_exiting, fw_running, fw_starting, fw_stopped, fw_stopping, fw_unprepared, get_input_signal_dimension(), io_lib, fw_vars_t::lock_channels(), MHA_ErrorMsg, MHA_WAVEFORM, nchannels_out, io_lib_t::prepare(), PluginLoader::mhapluginloader_t::prepare(), prepare_vars, proc_lib, PluginLoader::mhapluginloader_t::release(), mhaconfig_t::srate, and state.
Referenced by exec_fw_command(), and start().
void fw_t::start () private
start of processing
References fw_exiting, fw_running, fw_starting, fw_stopped, fw_stopping, fw_unprepared, io_lib, MHA_ErrorMsg, prepare(), io_lib_t::start(), and state.
Referenced by exec_fw_command().
void fw_t::stop () private
stop/pause of processing
References fw_exiting, fw_running, fw_starting, fw_stopped, fw_stopping, fw_unprepared, io_lib, MHA_ErrorMsg, mha_msleep, state, and io_lib_t::stop().
Referenced by exec_fw_command(), and release().
void fw_t::release () private
release of IO device
References MHAParser::int_mon_t::data, fw_exiting, fw_running, fw_starting, fw_stopped, fw_stopping, fw_unprepared, io_lib, MHA_ErrorMsg, nchannels_out, prepare_vars, proc_lib, io_lib_t::release(), PluginLoader::mhapluginloader_t::release(), state, stop(), and fw_vars_t::unlock_channels().
Referenced by exec_fw_command(), and quit().
void fw_t::quit () private
controlled quit
References b_exit_request, fw_exiting, fw_running, fw_starting, fw_stopped, fw_stopping, fw_unprepared, release(), and state.
Referenced by exec_fw_command(), and ~fw_t().
static void fw_t::stopped (void * h, int proc_err, int io_err) inline static private
Referenced by load_io_lib().
static void fw_t::started (void * h) inline static private
static int fw_t::process (void * h, mha_wave_t * sIn, mha_wave_t ** sOut) inline static private
Referenced by load_io_lib().
void fw_t::stopped (int proc_err, int io_err) private
References b_exit_request, MHAParser::bool_t::data, exit_on_stop, fw_exiting, fw_running, fw_starting, fw_stopped, fw_stopping, fw_unprepared, io_error, proc_error, and state.
void fw_t::started () private
References fw_exiting, fw_running, fw_starting, fw_stopped, fw_stopping, fw_unprepared, and state.
Referenced by load_io_lib().
int fw_t::process (mha_wave_t * s_in, mha_wave_t ** s_out) private
References MHAParser::string_t::data, MHAParser::string_mon_t::data, errorlog, fatallog, fw_running, Getmsg, MHA_ErrorMsg, proc_error_string, proc_lib, PluginLoader::mhapluginloader_t::process(), and state.
void fw_t::exec_fw_command () private
References MHAParser::kw_t::data, fw_cmd, MHAParser::keyword_list_t::get_index(), prepare(), quit(), release(), MHAParser::keyword_list_t::set_index(), start(), and stop().
Referenced by fw_t().
void fw_t::load_proc_lib () private
References ac, MHAParser::string_t::data, MHAKernel::algo_comm_class_t::get_c_handle(), PluginLoader::mhapluginloader_t::has_parser(), MHAParser::parser_t::insert_item(), proc_lib, proc_name, and MHAParser::variable_t::setlock().
Referenced by fw_t().
void fw_t::load_io_lib () private
References MHAParser::string_t::data, MHAParser::int_t::data, MHAParser::float_t::data, MHAParser::parser_t::insert_item(), io_lib, io_name, fw_vars_t::lock_srate_fragsize(), fw_vars_t::pfragmentsize, prepare_vars, process(), fw_vars_t::psrate, MHAParser::variable_t::setlock(), started(), and stopped().
Referenced by fw_t().
void fw_t::fw_sleep_cmd () private
References MHAParser::int_t::data, fw_sleep, and mha_msleep.
Referenced by fw_t().
void fw_t::fw_until_cmd () private
References MHAParser::string_t::data, fw_until, mha_msleep, MHAParser::base_t::parse(), and value().
Referenced by fw_t().
void fw_t::get_input_signal_dimension () private
References cfin, cfout, mhaconfig_t::channels, MHAParser::int_t::data, MHAParser::float_t::data, mhaconfig_t::domain, mhaconfig_t::fragsize, MHA_WAVEFORM, fw_vars_t::pfragmentsize, fw_vars_t::pinchannels, prepare_vars, fw_vars_t::psrate, and mhaconfig_t::srate.
Referenced by prepare().
void fw_t::async_read () inline private
Referenced by fw_t().
void fw_t::async_poll_msg () private
Referenced by fw_t().
void fw_t::get_parserstate () private
Referenced by fw_t().
Member Data Documentation
fw_vars_t fw_t::prepare_vars private
Referenced by get_input_signal_dimension(), load_io_lib(), prepare(), and release().
MHAParser::int_mon_t fw_t::nchannels_out private
Referenced by fw_t(), prepare(), and release().
MHAParser::string_t fw_t::proc_name private
Referenced by fw_t(), and load_proc_lib().
MHAParser::string_t fw_t::io_name private
Referenced by fw_t(), and load_io_lib().
MHAParser::bool_t fw_t::exit_on_stop private
Referenced by stopped().
MHAParser::int_t fw_t::fw_sleep private
Referenced by fw_sleep_cmd(), and fw_t().
MHAParser::string_t fw_t::fw_until private
Referenced by fw_t(), and fw_until_cmd().
MHAParser::kw_t fw_t::fw_cmd private
Referenced by exec_fw_command(), and fw_t().
MHAParser::string_mon_t fw_t::parserstate private
Referenced by fw_t().
MHAParser::string_t fw_t::errorlog private
Referenced by fw_t(), and process().
MHAParser::string_t fw_t::fatallog private
Referenced by fw_t(), and process().
MHAParser::vstring_t fw_t::plugins private
Referenced by fw_t().
MHAParser::vstring_t fw_t::plugin_paths private
Referenced by fw_t().
MHAParser::bool_t fw_t::dump_mha private
Referenced by fw_t().
MHAParser::string_t fw_t::inst_name private
A variable for naming MHA instances.
Referenced by fw_t().
MHAKernel::algo_comm_class_t fw_t::ac private
Referenced by load_proc_lib().
PluginLoader::mhapluginloader_t* fw_t::proc_lib private
Referenced by load_proc_lib(), prepare(), process(), release(), and ~fw_t().
io_lib_t* fw_t::io_lib private
Referenced by load_io_lib(), prepare(), release(), start(), stop(), and ~fw_t().
mhaconfig_t fw_t::cfin private
Referenced by get_input_signal_dimension(), and prepare().
mhaconfig_t fw_t::cfout private
Referenced by get_input_signal_dimension(), and prepare().
state_t fw_t::state private
Referenced by prepare(), process(), quit(), release(), start(), started(), stop(), and stopped().
bool fw_t::b_exit_request private
Referenced by quit(), and stopped().
int fw_t::proc_error protected
Referenced by stopped().
int fw_t::io_error protected
Referenced by stopped().
MHAParser::string_mon_t fw_t::proc_error_string private
Referenced by fw_t(), and process().
MHAEvents::patchbay_t<fw_t> fw_t::patchbay private
Referenced by fw_t().
The documentation for this class was generated from the following files:
mhafw_lib.h
mhafw_lib.cpp