openMHA Manual: MHAEvents::patchbay_t< receiver_t > Class Template Reference
MHAEvents::patchbay_t< receiver_t > Class Template Reference
Patchbay which connects any event emitter with any member function of the parameter class.
#include <mha_events.h>
Public Member Functions
~patchbay_t ()
void connect (emitter_t *, receiver_t *, void(receiver_t::*)())
Connect a receiver member function void (receiver_t::*)() with an event emitter.
void connect (emitter_t *, receiver_t *, void(receiver_t::*)(const std::string &))
Connect a receiver member function void (receiver_t::*)(const std::string&) with an event emitter.
void connect (emitter_t *, receiver_t *, void(receiver_t::*)(const std::string &, unsigned int, unsigned int))
Private Attributes
std::list< connector_t< receiver_t > * > cons
Detailed Description
template<class receiver_t>
class MHAEvents::patchbay_t< receiver_t >
Patchbay which connects any event emitter with any member function of the parameter class.
The connections created by the connect() function are hold until the destructor is called. To avoid access to invalid function pointers, it is required to destruct the patchbay before the receiver, usually by declaring the patchbay as a member of the receiver.
The receiver can be any claas or structure; the event callback can be either a member function without arguments or with const std::string& argument.
Constructor & Destructor Documentation
template<class receiver_t > MHAEvents::patchbay_t< receiver_t >::~patchbay_t ()
Member Function Documentation
template<class receiver_t> void MHAEvents::patchbay_t< receiver_t >::connect (emitter_t * e, receiver_t * r, void(receiver_t::*)() rfun)
Connect a receiver member function void (receiver_t::*)() with an event emitter.
Create a connection.
The connection is removed when the patchbay is destructed.
Parameters
e Pointer to an event emitter
r Pointer to the receiver
rfun Pointer to a member function of the receiver class
Referenced by adm_if_t::adm_if_t(), calibrator_t::calibrator_t(), fw_t::fw_t(), io_parser_t::io_parser_t(), and windowselector_t::windowselector_t().
template<class receiver_t> void MHAEvents::patchbay_t< receiver_t >::connect (emitter_t * e, receiver_t * r, void(receiver_t::*)(const std::string &) rfun)
Connect a receiver member function void (receiver_t::*)(const std::string&) with an event emitter.
Create a connection.
The connection is removed when the patchbay is destructed.
Parameters
e Pointer to an event emitter
r Pointer to the receiver
rfun Pointer to a member function of the receiver class
template<class receiver_t> void MHAEvents::patchbay_t< receiver_t >::connect (emitter_t * e, receiver_t * r, void(receiver_t::*)(const std::string &, unsigned int, unsigned int) rfun)
Member Data Documentation
template<class receiver_t> std::list<connector_t<receiver_t>*> MHAEvents::patchbay_t< receiver_t >::cons private
The documentation for this class was generated from the following file:
mha_events.h