openMHA Manual: DynComp::dc_afterburn_rt_t Class Reference
DynComp::dc_afterburn_rt_t Class Reference
Real-time class for after burn effect.
#include <dc_afterburn.h>
Public Member Functions
dc_afterburn_rt_t (const std::vector< float > &cf, unsigned int channels, float srate, const dc_afterburn_vars_t &vars)
void burn (float &Gin, float Lin, unsigned int band, unsigned int channel)
gain modifier method (afterburn).
Private Attributes
std::vector< float > drain_inv
std::vector< float > conflux
std::vector< float > maxgain
std::vector< float > mpo_inv
std::vector< MHAFilter::o1flt_lowpass_t > lp
Detailed Description
Real-time class for after burn effect.
The constructor processes the parameters and creates pre-processed variables for efficient realtime processing.
Constructor & Destructor Documentation
DynComp::dc_afterburn_rt_t::dc_afterburn_rt_t (const std::vector< float > & cf, unsigned int channels, float srate, const dc_afterburn_vars_t & vars)
References channels(), DynComp::dc_afterburn_vars_t::conflux, MHAParser::float_t::data, MHAParser::vfloat_t::data, DynComp::dc_afterburn_vars_t::drain, DynComp::dc_afterburn_vars_t::f, MHASignal::for_each(), DynComp::interp1(), DynComp::dc_afterburn_vars_t::maxgain, MHA_assert_equal, DynComp::dc_afterburn_vars_t::mpo, mylogf(), and DynComp::dc_afterburn_vars_t::taugain.
Member Function Documentation
void DynComp::dc_afterburn_rt_t::burn (float & Gin, float Lin, unsigned int band, unsigned int channel) inline
gain modifier method (afterburn).
Parameters
Gin Linear gain.
Lin Input level (Pascal).
band Filter band number.
channel Channel number.
Output level for MPO is estimated by Gin * Lin.
References DynComp::dc_afterburn_vars_t::conflux, DynComp::dc_afterburn_vars_t::f, MHASignal::max(), DynComp::dc_afterburn_vars_t::maxgain, and MHASignal::min().
Member Data Documentation
std::vector<float> DynComp::dc_afterburn_rt_t::drain_inv private
std::vector<float> DynComp::dc_afterburn_rt_t::conflux private
std::vector<float> DynComp::dc_afterburn_rt_t::maxgain private
std::vector<float> DynComp::dc_afterburn_rt_t::mpo_inv private
std::vector<MHAFilter::o1flt_lowpass_t> DynComp::dc_afterburn_rt_t::lp private
The documentation for this class was generated from the following files:
dc_afterburn.h
dc_afterburn.cpp