openMHA Manual: adm_rtconfig_t Class Reference
adm_rtconfig_t Class Reference
Public Types
typedef ADM::ADM< mha_real_t > adm_t
Public Member Functions
adm_rtconfig_t (unsigned nchannels_in, unsigned nchannels_out, const std::vector< int > &front_channels, const std::vector< int > &rear_channels, const mha_real_t fs, const std::vector< mha_real_t > &distances, const int lp_order, const int decomb_order)
Construct new ADMs.
virtual ~adm_rtconfig_t ()
size_t num_adms () const
adm_t & adm (unsigned index)
Returns adm object number index.
int front_channel (unsigned index) const
Returns index of front channel for adm number index.
int rear_channel (unsigned index) const
Returns index of rear channel for adm number index.
Private Member Functions
void check_index (unsigned index) const throw (MHA_Error)
Index checking for all internal arrays.
Private Attributes
std::vector< int > front_channels
Indices of channels containing the front microphones' signal.
std::vector< int > rear_channels
Indices of channels containing the rear microphones' signal.
MHASignal::waveform_t * lp_coeffs
Low pass filter coefficients.
std::vector< MHASignal::waveform_t * > decomb_coeffs
Decomb-Filter coefficients.
std::vector< adm_t * > adms
ADMs.
Member Typedef Documentation
typedef ADM::ADM<mha_real_t> adm_rtconfig_t::adm_t
Constructor & Destructor Documentation
adm_rtconfig_t::adm_rtconfig_t (unsigned nchannels_in, unsigned nchannels_out, const std::vector< int > & front_channels, const std::vector< int > & rear_channels, const mha_real_t fs, const std::vector< mha_real_t > & distances, const int lp_order, const int decomb_order)
Construct new ADMs.
Used when configuration changes.
Parameters
nchannels_in Number of input channels
nchannels_out Number of output channels
front_channels Parser's front_channels setting.
rear_channels Parser's front_channels setting.
fs Sampling rate / Hz.
distances Distances between mics / meters.
lp_order Lowpass filter order for adaption.
decomb_order Filter order of FIR compensation filter (compensates for comb filter characteristic).
References adm_fir_decomb(), adm_fir_lp(), MHA_ErrorMsg, and num_adms().
Referenced by check_index().
adm_rtconfig_t::~adm_rtconfig_t () virtual
References lp_coeffs, and num_adms().
Referenced by check_index().
Member Function Documentation
void adm_rtconfig_t::check_index (unsigned index) const throw (MHA_Error) inline private
Index checking for all internal arrays.
References adm_rtconfig_t(), MHA_ErrorMsg, and ~adm_rtconfig_t().
Referenced by adm(), front_channel(), and rear_channel().
size_t adm_rtconfig_t::num_adms () const inline
Referenced by adm_rtconfig_t(), and ~adm_rtconfig_t().
adm_t& adm_rtconfig_t::adm (unsigned index) inline
Returns adm object number index.
References check_index().
Referenced by adm_if_t::process().
int adm_rtconfig_t::front_channel (unsigned index) const inline
Returns index of front channel for adm number index.
References check_index().
Referenced by adm_if_t::process().
int adm_rtconfig_t::rear_channel (unsigned index) const inline
Returns index of rear channel for adm number index.
References check_index().
Referenced by adm_if_t::process().
Member Data Documentation
std::vector<int> adm_rtconfig_t::front_channels private
Indices of channels containing the front microphones' signal.
std::vector<int> adm_rtconfig_t::rear_channels private
Indices of channels containing the rear microphones' signal.
MHASignal::waveform_t* adm_rtconfig_t::lp_coeffs private
Low pass filter coefficients.
Referenced by ~adm_rtconfig_t().
std::vector<MHASignal::waveform_t*> adm_rtconfig_t::decomb_coeffs private
Decomb-Filter coefficients.
std::vector<adm_t *> adm_rtconfig_t::adms private
ADMs.
The documentation for this class was generated from the following file:
adm.cpp