openMHA Manual: MHA_TCP::Async_Notify Class Reference
MHA_TCP::Async_Notify Class Reference
Portable Multiplexable cross-thread notification.
#include <mha_tcp.hh>
Public Member Functions
Async_Notify ()
virtual void reset ()
virtual void set ()
virtual ~Async_Notify ()
Public Member Functions inherited from MHA_TCP::Wakeup_Event
Wakeup_Event ()
virtual void observed_by (Event_Watcher *observer)
virtual void ignored_by (Event_Watcher *observer)
virtual ~Wakeup_Event ()
virtual OS_EVENT_TYPE get_os_event ()
virtual bool status ()
Private Attributes
int pipe [2]
Additional Inherited Members
Protected Attributes inherited from MHA_TCP::Wakeup_Event
OS_EVENT_TYPE os_event
bool os_event_valid
Detailed Description
Portable Multiplexable cross-thread notification.
Constructor & Destructor Documentation
Async_Notify::Async_Notify ()
References MHA_TCP::G_ERRNO(), MHA_TCP::OS_EVENT_TYPE::R, and MHA_TCP::STRERROR().
Async_Notify::~Async_Notify () virtual
Member Function Documentation
void Async_Notify::reset () virtual
Reimplemented from MHA_TCP::Wakeup_Event.
References MHA_TCP::G_ERRNO(), MHA_TCP::Wakeup_Event::reset(), and MHA_TCP::STRERROR().
Referenced by io_tcp_t::accept_loop(), and io_tcp_t::connection_loop().
void Async_Notify::set () virtual
References MHA_TCP::G_ERRNO(), MHA_ErrorMsg, and MHA_TCP::STRERROR().
Referenced by io_tcp_t::release(), MHA_TCP::Thread::run(), io_tcp_t::start(), and io_tcp_t::stop().
Member Data Documentation
int MHA_TCP::Async_Notify::pipe[2] private
The documentation for this class was generated from the following files:
mha_tcp.hh
mha_tcp.cpp