openMHA Manual: mha_fifo_lw_t< T > Class Template Reference
mha_fifo_lw_t< T > Class Template Reference
This FIFO uses locks to synchronize access.
#include <mha_fifo.h>
Public Member Functions
virtual void write (const T *data, unsigned count)
write specified ammount of data to the fifo.
virtual void read (T *buf, unsigned count)
read data from fifo.
mha_fifo_lw_t (unsigned max_fill_count)
Create FIFO with fixed buffer size.
virtual ~mha_fifo_lw_t ()
release synchronization object
virtual void set_error (unsigned index, MHA_Error *error)
Process waiting for more data or space should bail out, throwing this error.
Public Member Functions inherited from mha_fifo_t< T >
virtual unsigned get_fill_count () const
Read-only access to fill_count.
virtual unsigned get_available_space () const
Read-only access to available_space.
virtual unsigned get_max_fill_count () const
The capacity of this fifo.
mha_fifo_t (unsigned max_fill_count)
Create FIFO with fixed buffer size.
mha_fifo_t (unsigned max_fill_count, const T &t)
Create FIFO with fixed buffer size, where all (initially unused) copies of T are initialized as copies of t.
mha_fifo_t (const mha_fifo_t &src)
Copy constructor.
virtual ~mha_fifo_t ()
Destroy FIFO.
mha_fifo_t< T > & operator= (const mha_fifo_t< T > &)
Assignment operator.
Private Attributes
mha_fifo_thread_platform_t * sync
platform specific thread synchronization
MHA_Error * error [2]
If waiting for synchronization should be aborted then exception to be thrown by reader process (index 0) or writer process (index 1) has to be placed here.
Additional Inherited Members
Public Types inherited from mha_fifo_t< T >
typedef T value_type
The data type exchanged by this fifo.
Protected Member Functions inherited from mha_fifo_t< T >
void clear ()
Empty the fifo at once.
Detailed Description
template<class T>
class mha_fifo_lw_t< T >
This FIFO uses locks to synchronize access.
Reading and writing can block until the operation can be executed.
Constructor & Destructor Documentation
template<class T > mha_fifo_lw_t< T >::mha_fifo_lw_t (unsigned max_fill_count) explicit
Create FIFO with fixed buffer size.
References mha_fifo_lw_t< T >::error.
template<class T > mha_fifo_lw_t< T >::~mha_fifo_lw_t () virtual
release synchronization object
References mha_fifo_lw_t< T >::sync.
Member Function Documentation
template<class T > void mha_fifo_lw_t< T >::write (const T * data, unsigned count) virtual
write specified ammount of data to the fifo.
If there is not enough space, then wait for more space.
Parameters
data Pointer to source data.
count Number of instances to copy.
Exceptions
MHA_Error when detecting a deadlock situation.
Reimplemented from mha_fifo_t< T >.
References MHASignal::min(), and mha_fifo_t< T >::write().
template<class T > void mha_fifo_lw_t< T >::read (T * buf, unsigned count) virtual
read data from fifo.
If there is not enough data, then wait for more data.
Parameters
buf Pointer to the target buffer.
count Number of instances to copy.
Exceptions
MHA_Error when detecting a deadlock situation.
Reimplemented from mha_fifo_t< T >.
References MHASignal::min(), and mha_fifo_t< T >::read().
template<class T > void mha_fifo_lw_t< T >::set_error (unsigned index, MHA_Error * error) virtual
Process waiting for more data or space should bail out, throwing this error.
Parameters
index Use 0 for terminating reader, 1 for terminating writer.
error MHA_Error to be thrown
References mha_fifo_thread_platform_t::decrement(), mha_fifo_lw_t< T >::error, mha_fifo_thread_platform_t::increment(), and mha_fifo_lw_t< T >::sync.
Member Data Documentation
template<class T > mha_fifo_thread_platform_t* mha_fifo_lw_t< T >::sync private
platform specific thread synchronization
Referenced by mha_fifo_lw_t< T >::set_error(), and mha_fifo_lw_t< T >::~mha_fifo_lw_t().
template<class T > MHA_Error* mha_fifo_lw_t< T >::error[2] private
If waiting for synchronization should be aborted then exception to be thrown by reader process (index 0) or writer process (index 1) has to be placed here.
Referenced by mha_fifo_lw_t< T >::mha_fifo_lw_t(), and mha_fifo_lw_t< T >::set_error().
The documentation for this class was generated from the following files:
mha_fifo.h
mha_fifo.cpp