openMHA Manual: MHA_Error Class Reference
MHA_Error Class Reference
The MHA Toolbox library » Error handling in the MHA
Error reporting exception class.
#include <mha_error.hh>
Public Member Functions
MHA_Error (const char *file, int line, const char *fmt,...)
Create an instance of a MHA_Error.
MHA_Error (const MHA_Error &)
MHA_Error & operator= (const MHA_Error &)
~MHA_Error () throw ()
const char * get_msg () const
Return the error message without source position.
const char * get_longmsg () const
Return the error message with source position.
const char * what () const throw ()
overwrite std::execption::what()
Private Attributes
char * msg
char * longmsg
Detailed Description
Error reporting exception class.
This class is used for error handling in the MHA. It is used by the MHA kernel and by the MHA toolbox library. Please note that exceptions should not be used accross ANSI-C interfaces. It is necessary to catch exceptions within the library.
The MHA_Error class holds source file name, line number and an error message.
Constructor & Destructor Documentation
MHA_Error::MHA_Error (const char * s_file, int l, const char * fmt, ...)
Create an instance of a MHA_Error.
Parameters
s_file source file name (FILE)
l source line (LINE)
fmt format string for error message (as in printf)
References digits(), longmsg, mha_debug(), and msg.
MHA_Error::MHA_Error (const MHA_Error & p)
References longmsg, and msg.
MHA_Error::~MHA_Error () throw ()
References longmsg, and msg.
Member Function Documentation
MHA_Error & MHA_Error::operator= (const MHA_Error & p)
References longmsg, and msg.
const char* MHA_Error::get_msg () const inline
Return the error message without source position.
References msg.
Referenced by MHAKernel::algo_comm_class_t::get_var(), MHAKernel::algo_comm_class_t::get_var_float(), MHAKernel::algo_comm_class_t::get_var_int(), MHAKernel::algo_comm_class_t::insert_var(), MHAKernel::algo_comm_class_t::insert_var_float(), MHAKernel::algo_comm_class_t::insert_var_int(), MHAParser::parser_t::query_readfile(), MHAKernel::algo_comm_class_t::remove_ref(), and MHAKernel::algo_comm_class_t::remove_var().
const char* MHA_Error::get_longmsg () const inline
Return the error message with source position.
References longmsg.
const char* MHA_Error::what () const throw () inline
overwrite std::execption::what()
References Getmsg, and msg.
Referenced by main().
Member Data Documentation
char* MHA_Error::msg private
Referenced by get_msg(), MHA_Error(), operator=(), what(), and ~MHA_Error().
char* MHA_Error::longmsg private
Referenced by get_longmsg(), MHA_Error(), operator=(), and ~MHA_Error().
The documentation for this class was generated from the following files:
mha_error.hh
mha_error.cpp