openMHA Manual: io_tcp_t Class Reference
io_tcp_t Class Reference
The tcp sound io library.
Public Member Functions
io_tcp_t (int fragsize, float samplerate, IOProcessEvent_t proc_event, void *proc_handle, IOStartedEvent_t start_event, void *start_handle, IOStoppedEvent_t stop_event, void *stop_handle)
void prepare (int num_inchannels, int num_outchannels)
Allocate server socket and start thread waiting for sound data exchange.
void start ()
Call frameworks start callback if there is a sound data connection at the moment.
void stop ()
Close the current connection if there is one.
void release ()
Close the current connection and close the server socket.
virtual void accept_loop ()
IO thread executes this method.
virtual void connection_loop (MHA_TCP::Connection *c)
IO thread executes this method for each connection.
virtual void parse (const char *cmd, char *retval, unsigned int len)
Parser interface.
virtual ~io_tcp_t ()
Private Attributes
io_tcp_parser_t parser
io_tcp_sound_t sound
io_tcp_fwcb_t fwcb
MHA_TCP::Server * server
MHA_TCP::Thread * thread
MHA_TCP::Async_Notify notify_start
MHA_TCP::Async_Notify notify_stop
MHA_TCP::Async_Notify notify_release
Detailed Description
The tcp sound io library.
Constructor & Destructor Documentation
io_tcp_t::io_tcp_t (int fragsize, float samplerate, IOProcessEvent_t proc_event, void * proc_handle, IOStartedEvent_t start_event, void * start_handle, IOStoppedEvent_t stop_event, void * stop_handle)
Referenced by IOInit().
virtual io_tcp_t::~io_tcp_t () inline virtual
Member Function Documentation
void io_tcp_t::prepare (int num_inchannels, int num_outchannels)
Allocate server socket and start thread waiting for sound data exchange.
prepare opens the tcp server socket and starts the io thread that listens for audio data on the tcp socket after doing some sanity checks
References io_tcp_parser_t::debug(), io_tcp_parser_t::get_connected(), io_tcp_parser_t::get_local_address(), io_tcp_parser_t::get_local_port(), MHA_TCP::Server::get_port(), io_tcp_parser_t::get_server_port_open(), MHA_ErrorMsg, parser, io_tcp_sound_t::prepare(), server, io_tcp_parser_t::set_local_port(), io_tcp_parser_t::set_server_port_open(), sound, thread, and thread_startup_function().
Referenced by IOPrepare().
void io_tcp_t::start ()
Call frameworks start callback if there is a sound data connection at the moment.
References io_tcp_parser_t::get_server_port_open(), MHA_ErrorMsg, notify_start, parser, and MHA_TCP::Async_Notify::set().
Referenced by IOStart().
void io_tcp_t::stop ()
Close the current connection if there is one.
stop IO thread
References notify_stop, and MHA_TCP::Async_Notify::set().
Referenced by IOStop().
void io_tcp_t::release ()
Close the current connection and close the server socket.
Stop IO thread and close server socket.
References io_tcp_parser_t::debug(), notify_release, MHA_TCP::Event_Watcher::observe(), parser, io_tcp_sound_t::release(), MHA_TCP::Async_Notify::set(), sound, thread, MHA_TCP::Thread::thread_finish_event, and MHA_TCP::Event_Watcher::wait().
Referenced by IORelease().
void io_tcp_t::accept_loop () virtual
IO thread executes this method.
References connection_loop(), io_tcp_parser_t::debug(), MHA_TCP::Server::get_accept_event(), notify_release, notify_start, notify_stop, MHA_TCP::Event_Watcher::observe(), parser, MHA_TCP::Async_Notify::reset(), server, io_tcp_parser_t::set_server_port_open(), MHA_TCP::Server::try_accept(), and MHA_TCP::Event_Watcher::wait().
Referenced by thread_startup_function().
void io_tcp_t::connection_loop (MHA_TCP::Connection * c) virtual
IO thread executes this method for each connection.
Parameters
c pointer to connection. connection_loop deletes connection before exiting.
References MHA_TCP::Connection::buffered_incoming_bytes(), MHA_TCP::Connection::can_read_bytes(), io_tcp_sound_t::chunkbytes_in(), io_tcp_parser_t::debug(), MHA_TCP::Connection::eof(), fwcb, MHA_TCP::Connection::get_peer_address(), MHA_TCP::Connection::get_peer_port(), MHA_TCP::Connection::get_read_event(), MHA_TCP::Connection::get_write_event(), io_tcp_sound_t::header(), io_tcp_sound_t::hton(), MHA_TCP::Connection::needs_write(), notify_release, notify_start, notify_stop, io_tcp_sound_t::ntoh(), MHA_TCP::Event_Watcher::observe(), parser, io_tcp_fwcb_t::process(), MHA_TCP::Connection::read_bytes(), MHA_TCP::Async_Notify::reset(), io_tcp_parser_t::set_connected(), io_tcp_fwcb_t::set_errnos(), io_tcp_parser_t::set_new_peer(), sound, io_tcp_fwcb_t::start(), io_tcp_fwcb_t::stop(), MHA_TCP::Connection::try_write(), MHAParser::StrCnv::val2str(), and MHA_TCP::Event_Watcher::wait().
Referenced by accept_loop().
virtual void io_tcp_t::parse (const char * cmd, char * retval, unsigned int len) inline virtual
Parser interface.
Referenced by IOSetVar().
Member Data Documentation
io_tcp_parser_t io_tcp_t::parser private
Referenced by accept_loop(), connection_loop(), prepare(), release(), and start().
io_tcp_sound_t io_tcp_t::sound private
Referenced by connection_loop(), prepare(), and release().
io_tcp_fwcb_t io_tcp_t::fwcb private
Referenced by connection_loop().
MHA_TCP::Server* io_tcp_t::server private
Referenced by accept_loop(), and prepare().
MHA_TCP::Thread* io_tcp_t::thread private
Referenced by prepare(), and release().
MHA_TCP::Async_Notify io_tcp_t::notify_start private
Referenced by accept_loop(), connection_loop(), and start().
MHA_TCP::Async_Notify io_tcp_t::notify_stop private
Referenced by accept_loop(), connection_loop(), and stop().
MHA_TCP::Async_Notify io_tcp_t::notify_release private
Referenced by accept_loop(), connection_loop(), and release().
The documentation for this class was generated from the following file:
MHAIOTCP.cpp