openMHA Manual: mha_fifo_t< T > Class Template Reference
mha_fifo_t< T > Class Template Reference
A FIFO class for blocksize adaptation Synchronization: None.
#include <mha_fifo.h>
Public Types
typedef T value_type
The data type exchanged by this fifo.
Public Member Functions
virtual void write (const T *data, unsigned count)
write specified ammount of data to the fifo.
virtual void read (T *buf, unsigned count)
read data from fifo
virtual unsigned get_fill_count () const
Read-only access to fill_count.
virtual unsigned get_available_space () const
Read-only access to available_space.
virtual unsigned get_max_fill_count () const
The capacity of this fifo.
mha_fifo_t (unsigned max_fill_count)
Create FIFO with fixed buffer size.
mha_fifo_t (unsigned max_fill_count, const T &t)
Create FIFO with fixed buffer size, where all (initially unused) copies of T are initialized as copies of t.
mha_fifo_t (const mha_fifo_t &src)
Copy constructor.
virtual ~mha_fifo_t ()
Destroy FIFO.
mha_fifo_t< T > & operator= (const mha_fifo_t< T > &)
Assignment operator.
Protected Member Functions
void clear ()
Empty the fifo at once.
Private Attributes
const unsigned max_fill_count
The maximum fill count of this FIFO.
T * buf
The memory allocated to store the data.
T * write_ptr
points to location where to write next
const T * read_ptr
points to location where to read next
bool buf_uses_placement_new
wether buf was allocated using placement new or array new.
Detailed Description
template<class T>
class mha_fifo_t< T >
A FIFO class for blocksize adaptation Synchronization: None.
Use external synchronisation or synchronization in inheriting class.
Member Typedef Documentation
template<class T> typedef T mha_fifo_t< T >::value_type
The data type exchanged by this fifo.
Constructor & Destructor Documentation
template<class T > mha_fifo_t< T >::mha_fifo_t (unsigned max_fill_count) explicit
Create FIFO with fixed buffer size.
References mha_fifo_t< T >::buf, mha_fifo_t< T >::read_ptr, and mha_fifo_t< T >::write_ptr.
Referenced by mha_fifo_t< T >::get_max_fill_count().
template<class T > mha_fifo_t< T >::mha_fifo_t (unsigned max_fill_count, const T & t)
Create FIFO with fixed buffer size, where all (initially unused) copies of T are initialized as copies of t.
References mha_fifo_t< T >::buf, mha_fifo_t< T >::max_fill_count, mha_fifo_t< T >::read_ptr, and mha_fifo_t< T >::write_ptr.
template<class T > mha_fifo_t< T >::mha_fifo_t (const mha_fifo_t< T > & src)
Copy constructor.
References mha_fifo_t< T >::buf, mha_fifo_t< T >::max_fill_count, mha_fifo_t< T >::read_ptr, and mha_fifo_t< T >::write_ptr.
template<class T > mha_fifo_t< T >::~mha_fifo_t () virtual
Destroy FIFO.
References mha_fifo_t< T >::buf, mha_fifo_t< T >::buf_uses_placement_new, mha_fifo_t< T >::max_fill_count, mha_fifo_t< T >::read_ptr, and mha_fifo_t< T >::write_ptr.
Referenced by mha_fifo_t< T >::get_max_fill_count().
Member Function Documentation
template<class T > void mha_fifo_t< T >::write (const T * data, unsigned count) virtual
write specified ammount of data to the fifo.
Parameters
data Pointer to source data.
count Number of instances to copy
Exceptions
MHA_Error when there is not enough space available.
Reimplemented in mha_fifo_lw_t< T >, and mha_drifter_fifo_t< T >.
References mha_fifo_t< T >::buf, mha_fifo_t< T >::get_available_space(), mha_fifo_t< T >::max_fill_count, and mha_fifo_t< T >::write_ptr.
Referenced by mha_drifter_fifo_t< T >::write(), and mha_fifo_lw_t< T >::write().
template<class T > void mha_fifo_t< T >::read (T * buf, unsigned count) virtual
read data from fifo
Parameters
buf Pointer to the target buffer
count Number of instances to copy
Exceptions
MHA_Error when there is not enough data available.
Reimplemented in mha_fifo_lw_t< T >, and mha_drifter_fifo_t< T >.
References mha_fifo_t< T >::buf, mha_fifo_t< T >::get_fill_count(), mha_fifo_t< T >::max_fill_count, and mha_fifo_t< T >::read_ptr.
Referenced by mha_drifter_fifo_t< T >::read(), and mha_fifo_lw_t< T >::read().
template<class T > unsigned mha_fifo_t< T >::get_fill_count () const virtual
Read-only access to fill_count.
Reimplemented in mha_drifter_fifo_t< T >.
References mha_fifo_t< T >::max_fill_count, mha_fifo_t< T >::read_ptr, and mha_fifo_t< T >::write_ptr.
Referenced by mha_fifo_t< T >::get_available_space(), mha_drifter_fifo_t< T >::get_fill_count(), mha_fifo_t< T >::read(), and mha_drifter_fifo_t< T >::read().
template<class T > unsigned mha_fifo_t< T >::get_available_space () const virtual
Read-only access to available_space.
Reimplemented in mha_drifter_fifo_t< T >.
References mha_fifo_t< T >::get_fill_count(), and mha_fifo_t< T >::max_fill_count.
Referenced by mha_drifter_fifo_t< T >::get_available_space(), mha_fifo_t< T >::write(), and mha_drifter_fifo_t< T >::write().
template<class T> virtual unsigned mha_fifo_t< T >::get_max_fill_count () const inline virtual
The capacity of this fifo.
References mha_fifo_t< T >::max_fill_count, mha_fifo_t< T >::mha_fifo_t(), mha_fifo_t< T >::operator=(), and mha_fifo_t< T >::~mha_fifo_t().
template<class T > mha_fifo_t< T > & mha_fifo_t< T >::operator= (const mha_fifo_t< T > & src)
Assignment operator.
References mha_fifo_t< T >::buf, mha_fifo_t< T >::max_fill_count, mha_fifo_t< T >::read_ptr, and mha_fifo_t< T >::write_ptr.
Referenced by mha_fifo_t< T >::get_max_fill_count(), and mha_fifo_thread_platform_t::~mha_fifo_thread_platform_t().
template<class T> void mha_fifo_t< T >::clear () inline protected
Empty the fifo at once.
Should be called by the reader, or when the reader is inactive.
References mha_fifo_t< T >::write_ptr.
Referenced by mha_drifter_fifo_t< T >::starting().
Member Data Documentation
template<class T> const unsigned mha_fifo_t< T >::max_fill_count private
The maximum fill count of this FIFO.
Referenced by mha_fifo_t< T >::get_available_space(), mha_fifo_t< T >::get_fill_count(), mha_fifo_t< T >::get_max_fill_count(), mha_drifter_fifo_t< T >::get_min_fill_count(), mha_fifo_t< T >::mha_fifo_t(), mha_fifo_t< T >::operator=(), mha_fifo_t< T >::read(), mha_fifo_t< T >::write(), and mha_fifo_t< T >::~mha_fifo_t().
template<class T> T* mha_fifo_t< T >::buf private
The memory allocated to store the data.
max_fill_count + 1 locations are allocated: At least one location is always unused, because we have max_fill_count + 1 possible fillcounts [0:max_fill_count] that we need to distinguish.
Referenced by mha_fifo_t< T >::mha_fifo_t(), mha_fifo_t< T >::operator=(), mha_fifo_t< T >::read(), mha_fifo_t< T >::write(), and mha_fifo_t< T >::~mha_fifo_t().
template<class T> T* mha_fifo_t< T >::write_ptr private
points to location where to write next
Referenced by mha_fifo_t< T >::clear(), mha_fifo_t< T >::get_fill_count(), mha_fifo_t< T >::mha_fifo_t(), mha_fifo_t< T >::operator=(), mha_fifo_t< T >::write(), and mha_fifo_t< T >::~mha_fifo_t().
template<class T> const T* mha_fifo_t< T >::read_ptr private
points to location where to read next
Referenced by mha_fifo_t< T >::get_fill_count(), mha_fifo_t< T >::mha_fifo_t(), mha_fifo_t< T >::operator=(), mha_fifo_t< T >::read(), and mha_fifo_t< T >::~mha_fifo_t().
template<class T> bool mha_fifo_t< T >::buf_uses_placement_new private
wether buf was allocated using placement new or array new.
Referenced by mha_fifo_t< T >::~mha_fifo_t().
The documentation for this class was generated from the following file:
mha_fifo.h