openMHA Manual: dc::dc_t Class Reference
dc::dc_t Class Reference
Public Member Functions
dc_t (dc_vars_t vars, mha_real_t filter_rate, unsigned int nch, algo_comm_t ac, mha_domain_t domain, unsigned int fftlen, std::string algo)
mha_wave_t * process (mha_wave_t *)
mha_spec_t * process (mha_spec_t *, wb_inhib_cfg_t *wbinhib)
void explicit_insert ()
unsigned get_nbands () const
Number of frequency bands accessor.
const MHASignal::waveform_t & get_level_in_db () const
const MHASignal::waveform_t & get_level_in_db_adjusted () const
Private Attributes
std::vector< MHATableLookup::linear_table_t > gt
MHAFilter::o1flt_lowpass_t rmslevel
MHAFilter::o1flt_lowpass_t attack
MHAFilter::o1flt_maxtrack_t decay
bool powersum
bool bypass
unsigned int naudiochannels
unsigned int nbands
MHA_AC::waveform_t level_in_db
MHA_AC::waveform_t level_in_db_adjusted
MHA_AC::waveform_t inhib_gain
MHASignal::waveform_t max_level_difference
unsigned int k_nyquist
Additional Inherited Members
Private Member Functions inherited from dc::dc_vars_validator_t
dc_vars_validator_t (dc_vars_t &v, unsigned int s, mha_domain_t domain)
Constructor & Destructor Documentation
dc::dc_t::dc_t (dc_vars_t vars, mha_real_t filter_rate, unsigned int nch, algo_comm_t ac, mha_domain_t domain, unsigned int fftlen, std::string algo)
References MHAParser::vfloat_t::data, MHAParser::mfloat_t::data, gt, dc::dc_vars_t::gtdata, dc::dc_vars_t::gtmin, dc::dc_vars_t::gtstep, k_nyquist, dc::dc_vars_t::max_level_difference, max_level_difference, naudiochannels, nbands, and MHASignal::waveform_t::value().
Member Function Documentation
mha_wave_t * dc::dc_t::process (mha_wave_t * s)
References attack, mha_wave_t::buf, bypass, decay, explicit_insert(), gt, level_in_db, naudiochannels, nbands, mha_wave_t::num_channels, mha_wave_t::num_frames, powersum, rmslevel, and MHASignal::waveform_t::value().
mha_spec_t * dc::dc_t::process (mha_spec_t * s, wb_inhib_cfg_t * wbinhib)
References abs2(), attack, bypass, MHASignal::waveform_t::copy(), decay, dc::wb_inhib_cfg_t::dl_diff, dc::wb_inhib_cfg_t::dl_map_max, dc::wb_inhib_cfg_t::dl_map_min, dc::wb_inhib_cfg_t::g_scale, gt, inhib_gain, MHA_AC::waveform_t::insert(), k_nyquist, dc::wb_inhib_cfg_t::l_min, level_in_db, level_in_db_adjusted, MHASignal::max(), max_level_difference, MHASignal::min(), naudiochannels, nbands, mha_spec_t::num_channels, mha_spec_t::num_frames, powersum, value(), MHASignal::waveform_t::value(), and dc::wb_inhib_cfg_t::weights.
void dc::dc_t::explicit_insert ()
References inhib_gain, MHA_AC::waveform_t::insert(), level_in_db, and level_in_db_adjusted.
Referenced by process().
unsigned dc::dc_t::get_nbands () const inline
Number of frequency bands accessor.
const MHASignal::waveform_t& dc::dc_t::get_level_in_db () const inline
const MHASignal::waveform_t& dc::dc_t::get_level_in_db_adjusted () const inline
Member Data Documentation
std::vector<MHATableLookup::linear_table_t> dc::dc_t::gt private
Referenced by dc_t(), and process().
MHAFilter::o1flt_lowpass_t dc::dc_t::rmslevel private
Referenced by process().
MHAFilter::o1flt_lowpass_t dc::dc_t::attack private
Referenced by process().
MHAFilter::o1flt_maxtrack_t dc::dc_t::decay private
Referenced by process().
bool dc::dc_t::powersum private
Referenced by process().
bool dc::dc_t::bypass private
Referenced by process().
unsigned int dc::dc_t::naudiochannels private
Referenced by dc_t(), process(), and dc::dc_if_t::update_monitors().
unsigned int dc::dc_t::nbands private
Referenced by dc_t(), and process().
MHA_AC::waveform_t dc::dc_t::level_in_db private
Referenced by explicit_insert(), and process().
MHA_AC::waveform_t dc::dc_t::level_in_db_adjusted private
Referenced by explicit_insert(), and process().
MHA_AC::waveform_t dc::dc_t::inhib_gain private
Referenced by explicit_insert(), and process().
MHASignal::waveform_t dc::dc_t::max_level_difference private
Referenced by dc_t(), and process().
unsigned int dc::dc_t::k_nyquist private
Referenced by dc_t(), and process().
The documentation for this class was generated from the following file:
dc.cpp