openMHA Manual: mhachain::plugs_t Class Reference
mhachain::plugs_t Class Reference
#include <mha_generic_chain.h>
Public Member Functions
plugs_t (std::vector< std::string > algos, mhaconfig_t cfin, mhaconfig_t cfout, bool do_prepare, MHAParser::parser_t &p, algo_comm_t iac, std::string ichain, bool use_profiling)
~plugs_t ()
void prepare (mhaconfig_t &)
void release ()
void process (mha_wave_t *, mha_spec_t *, mha_wave_t **, mha_spec_t **)
bool prepared () const
Private Member Functions
void alloc_plugs (std::vector< std::string > algos)
void cleanup_plugs ()
void update_proc_load ()
Private Attributes
bool b_prepared
std::vector< PluginLoader::mhapluginloader_t * > algos
MHAParser::parser_t & parser
algo_comm_t ac
std::string chain
MHAParser::parser_t profiling
MHAParser::vstring_mon_t prof_algos
MHAParser::vfloat_mon_t prof_init
MHAParser::vfloat_mon_t prof_prepare
MHAParser::vfloat_mon_t prof_release
MHAParser::vfloat_mon_t prof_process
MHAParser::float_mon_t prof_process_tt
MHAParser::vfloat_mon_t prof_process_load
unsigned int proc_cnt
mhaconfig_t prof_cfg
MHAEvents::connector_t< mhachain::plugs_t > prof_load_con
MHAEvents::connector_t< mhachain::plugs_t > prof_tt_con
bool b_use_profiling
mha_platform_tictoc_t tictoc
Constructor & Destructor Documentation
mhachain::plugs_t::plugs_t (std::vector< std::string > algos, mhaconfig_t cfin, mhaconfig_t cfout, bool do_prepare, MHAParser::parser_t & p, algo_comm_t iac, std::string ichain, bool use_profiling)
References algos, alloc_plugs(), b_use_profiling, cleanup_plugs(), MHAParser::vstring_mon_t::data, MHAParser::vfloat_mon_t::data, MHAParser::parser_t::force_remove_item(), MHAParser::parser_t::insert_item(), mhaconfig_compare(), parser, prepare(), prof_algos, prof_init, prof_prepare, prof_process, prof_process_load, prof_process_tt, prof_release, profiling, and MHAParser::base_t::set_node_id().
mhachain::plugs_t::~plugs_t ()
References cleanup_plugs(), MHAParser::parser_t::force_remove_item(), parser, prepared(), and release().
Member Function Documentation
void mhachain::plugs_t::prepare (mhaconfig_t & tf)
References algos, b_prepared, b_use_profiling, MHAParser::vfloat_mon_t::data, mha_platform_tic(), mha_platform_toc(), proc_cnt, prof_cfg, prof_prepare, prof_process, and tictoc.
Referenced by plugs_t(), and mhachain::chain_base_t::prepare().
void mhachain::plugs_t::release ()
References algos, b_prepared, b_use_profiling, MHAParser::vfloat_mon_t::data, mha_platform_tic(), mha_platform_toc(), prof_release, and tictoc.
Referenced by mhachain::chain_base_t::release(), and ~plugs_t().
void mhachain::plugs_t::process (mha_wave_t * win, mha_spec_t * sin, mha_wave_t ** wout, mha_spec_t ** sout)
References algos, b_use_profiling, MHAParser::vfloat_mon_t::data, mha_platform_tic(), mha_platform_toc(), MHA_SPECTRUM, MHA_WAVEFORM, proc_cnt, prof_process, and tictoc.
bool mhachain::plugs_t::prepared () const inline
References alloc_plugs(), b_prepared, cleanup_plugs(), and update_proc_load().
Referenced by mhachain::chain_base_t::prepare(), mhachain::chain_base_t::release(), and ~plugs_t().
void mhachain::plugs_t::alloc_plugs (std::vector< std::string > algos) private
References ac, algos, b_use_profiling, MHAParser::vfloat_mon_t::data, MHAParser::parser_t::force_remove_item(), MHAParser::parser_t::insert_item(), MHA_ErrorMsg, mha_platform_tic(), mha_platform_toc(), parser, prof_init, and tictoc.
Referenced by plugs_t(), and prepared().
void mhachain::plugs_t::cleanup_plugs () private
References algos, parser, and MHAParser::parser_t::remove_item().
Referenced by plugs_t(), prepared(), and ~plugs_t().
void mhachain::plugs_t::update_proc_load () private
References MHAParser::vfloat_mon_t::data, MHAParser::float_mon_t::data, mhaconfig_t::fragsize, proc_cnt, prof_cfg, prof_process, prof_process_load, prof_process_tt, and mhaconfig_t::srate.
Referenced by prepared().
Member Data Documentation
bool mhachain::plugs_t::b_prepared private
Referenced by prepare(), prepared(), and release().
std::vector< PluginLoader::mhapluginloader_t* > mhachain::plugs_t::algos private
Referenced by alloc_plugs(), cleanup_plugs(), plugs_t(), prepare(), process(), and release().
MHAParser::parser_t& mhachain::plugs_t::parser private
Referenced by alloc_plugs(), cleanup_plugs(), plugs_t(), and ~plugs_t().
algo_comm_t mhachain::plugs_t::ac private
Referenced by alloc_plugs().
std::string mhachain::plugs_t::chain private
MHAParser::parser_t mhachain::plugs_t::profiling private
Referenced by plugs_t().
MHAParser::vstring_mon_t mhachain::plugs_t::prof_algos private
Referenced by plugs_t().
MHAParser::vfloat_mon_t mhachain::plugs_t::prof_init private
Referenced by alloc_plugs(), and plugs_t().
MHAParser::vfloat_mon_t mhachain::plugs_t::prof_prepare private
Referenced by plugs_t(), and prepare().
MHAParser::vfloat_mon_t mhachain::plugs_t::prof_release private
Referenced by plugs_t(), and release().
MHAParser::vfloat_mon_t mhachain::plugs_t::prof_process private
Referenced by plugs_t(), prepare(), process(), and update_proc_load().
MHAParser::float_mon_t mhachain::plugs_t::prof_process_tt private
Referenced by plugs_t(), and update_proc_load().
MHAParser::vfloat_mon_t mhachain::plugs_t::prof_process_load private
Referenced by plugs_t(), and update_proc_load().
unsigned int mhachain::plugs_t::proc_cnt private
Referenced by prepare(), process(), and update_proc_load().
mhaconfig_t mhachain::plugs_t::prof_cfg private
Referenced by prepare(), and update_proc_load().
MHAEvents::connector_t<mhachain::plugs_t> mhachain::plugs_t::prof_load_con private
MHAEvents::connector_t<mhachain::plugs_t> mhachain::plugs_t::prof_tt_con private
bool mhachain::plugs_t::b_use_profiling private
Referenced by alloc_plugs(), plugs_t(), prepare(), process(), and release().
mha_platform_tictoc_t mhachain::plugs_t::tictoc private
Referenced by alloc_plugs(), prepare(), process(), and release().
The documentation for this class was generated from the following files:
mha_generic_chain.h
mha_generic_chain.cpp