openMHA Manual: MHA_TCP::Wakeup_Event Class Reference
MHA_TCP::Wakeup_Event Class Reference
#include <mha_tcp.hh>
Public Member Functions
Wakeup_Event ()
virtual void observed_by (Event_Watcher *observer)
virtual void ignored_by (Event_Watcher *observer)
virtual ~Wakeup_Event ()
virtual OS_EVENT_TYPE get_os_event ()
virtual void reset ()
virtual bool status ()
Protected Attributes
OS_EVENT_TYPE os_event
bool os_event_valid
Private Attributes
std::set< class Event_Watcher * > observers
Detailed Description
A base class for asynchronous wakeup events.
Constructor & Destructor Documentation
Wakeup_Event::Wakeup_Event ()
Event Constructor. The new event has invalid state.
Wakeup_Event::~Wakeup_Event () virtual
Destructor deregisters from observers.
Member Function Documentation
void Wakeup_Event::observed_by (Event_Watcher * observer) virtual
Called by the Event_Watcher when this event is added to its list of observed events.
void Wakeup_Event::ignored_by (Event_Watcher * observer) virtual
Called by the Event_Watcher when this event is removed from its list of observed events.
OS_EVENT_TYPE Wakeup_Event::get_os_event () virtual
Get necessary information for the Event Watcher.
Reimplemented in MHA_TCP::Timeout_Event.
References MHA_ErrorMsg.
Referenced by MHA_TCP::Timeout_Event::get_os_event().
void Wakeup_Event::reset () virtual
For pure notification events, reset the "signalled" status
Reimplemented in MHA_TCP::Async_Notify.
References MHA_ErrorMsg.
Referenced by MHA_TCP::Async_Notify::reset().
bool Wakeup_Event::status () virtual
Query wether the event is in signalled state now.
References MHA_ErrorMsg, MHA_TCP::Event_Watcher::observe(), and MHA_TCP::Event_Watcher::wait().
Referenced by MHA_TCP::Connection::can_sysread(), and MHA_TCP::Connection::can_syswrite().
Member Data Documentation
std::set<class Event_Watcher *> MHA_TCP::Wakeup_Event::observers private
A list of all Event_Watcher instances that this Wakeup_Event is observed by (stored here for proper deregistering).
OS_EVENT_TYPE MHA_TCP::Wakeup_Event::os_event protected
bool MHA_TCP::Wakeup_Event::os_event_valid protected
The documentation for this class was generated from the following files:
mha_tcp.hh
mha_tcp.cpp