openMHA Manual: MHA_AC::acspace2matrix_t Class Reference
MHA_AC::acspace2matrix_t Class Reference
Communication between algorithms
Copy all or a subset of all numeric AC variables into an array of matrixes.
#include <mha_algo_comm.h>
Public Member Functions
acspace2matrix_t (algo_comm_t ac, const std::vector< std::string > &names)
Constructor.
acspace2matrix_t (const MHA_AC::acspace2matrix_t &src)
Constructor with initialization from an instance.
~acspace2matrix_t ()
MHA_AC::acspace2matrix_t & operator= (const MHA_AC::acspace2matrix_t &src)
Copy all contents (deep copy).
MHA_AC::ac2matrix_t & operator[] (unsigned int k)
Access operator.
const MHA_AC::ac2matrix_t & operator[] (unsigned int k) const
Constant access operator.
void update ()
Update function.
unsigned int size () const
Number of matrixes in AC space.
unsigned int frame () const
Actual frame number.
void insert (algo_comm_t ac)
Insert AC space copy into an AC space (other than source AC space)
Private Attributes
unsigned int len
MHA_AC::ac2matrix_t ** data
unsigned int frameno
Detailed Description
Copy all or a subset of all numeric AC variables into an array of matrixes.
Constructor & Destructor Documentation
MHA_AC::acspace2matrix_t::acspace2matrix_t (algo_comm_t ac, const std::vector< std::string > & names)
Constructor.
Scan all given AC variables and allocate corresponding matrixes.
Parameters
ac AC handle.
names Names of AC variables, or empty for all.
References data, algo_comm_t::get_entries, algo_comm_t::handle, len, mha_min_1(), and MHAParser::StrCnv::str2val().
MHA_AC::acspace2matrix_t::acspace2matrix_t (const MHA_AC::acspace2matrix_t & src)
Constructor with initialization from an instance.
Parameters
src Instance to be copied.
References data, len, and mha_min_1().
MHA_AC::acspace2matrix_t::~acspace2matrix_t ()
References data, and len.
Member Function Documentation
MHA_AC::acspace2matrix_t & MHA_AC::acspace2matrix_t::operator= (const MHA_AC::acspace2matrix_t & src)
Copy all contents (deep copy).
Parameters
src Array of matrixes to be copied.
References data, and len.
MHA_AC::ac2matrix_t& MHA_AC::acspace2matrix_t::operator[] (unsigned int k) inline
Access operator.
Parameters
k index into array; should not exceed size()-1.
Return values
Reference to matrix.
const MHA_AC::ac2matrix_t& MHA_AC::acspace2matrix_t::operator[] (unsigned int k) const inline
Constant access operator.
Parameters
k index into array; should not exceed size()-1.
Return values
Constant reference to matrix.
void MHA_AC::acspace2matrix_t::update () inline
Update function.
This function updates all matrixes from their corresponding AC variables. It can be called from the MHA Framework prepare function or in the processing callback.
References update().
Referenced by update().
unsigned int MHA_AC::acspace2matrix_t::size () const inline
Number of matrixes in AC space.
Referenced by insert().
unsigned int MHA_AC::acspace2matrix_t::frame () const inline
Actual frame number.
References MHA_AC::spectrum_t::insert().
void MHA_AC::acspace2matrix_t::insert (algo_comm_t ac)
Insert AC space copy into an AC space (other than source AC space)
Parameters
ac AC space handle to insert data
References size().
Member Data Documentation
unsigned int MHA_AC::acspace2matrix_t::len private
Referenced by acspace2matrix_t(), operator=(), and ~acspace2matrix_t().
MHA_AC::ac2matrix_t** MHA_AC::acspace2matrix_t::data private
Referenced by acspace2matrix_t(), operator=(), and ~acspace2matrix_t().
unsigned int MHA_AC::acspace2matrix_t::frameno private
The documentation for this class was generated from the following files:
mha_algo_comm.h
mha_algo_comm.cpp