openMHA Manual: MHAEvents::connector_t< receiver_t > Class Template Reference
MHAEvents::connector_t< receiver_t > Class Template Reference
#include <mha_events.h>
Public Member Functions
connector_t (emitter_t *, receiver_t *, void(receiver_t::*)())
connector_t (emitter_t *, receiver_t *, void(receiver_t::*)(const std::string &))
connector_t (emitter_t *, receiver_t *, void(receiver_t::*)(const std::string &, unsigned int, unsigned int))
~connector_t ()
Public Member Functions inherited from MHAEvents::connector_base_t
connector_base_t ()
virtual ~connector_base_t ()
void emitter_die ()
Private Member Functions
void emit_event ()
void emit_event (const std::string &)
void emit_event (const std::string &, unsigned int, unsigned int)
Private Attributes
emitter_t * emitter
receiver_t * receiver
void(receiver_t::* eventhandler)()
void(receiver_t::* eventhandler_s)(const std::string &)
void(receiver_t::* eventhandler_suu)(const std::string &, unsigned int, unsigned int)
Additional Inherited Members
Protected Attributes inherited from MHAEvents::connector_base_t
bool emitter_is_alive
Constructor & Destructor Documentation
template<class receiver_t> MHAEvents::connector_t< receiver_t >::connector_t (emitter_t * e, receiver_t * r, void(receiver_t::*)() rfun)
References MHAEvents::emitter_t::connect(), and MHAEvents::connector_t< receiver_t >::emitter.
template<class receiver_t> MHAEvents::connector_t< receiver_t >::connector_t (emitter_t * e, receiver_t * r, void(receiver_t::*)(const std::string &) rfun)
References MHAEvents::emitter_t::connect(), and MHAEvents::connector_t< receiver_t >::emitter.
template<class receiver_t> MHAEvents::connector_t< receiver_t >::connector_t (emitter_t * e, receiver_t * r, void(receiver_t::*)(const std::string &, unsigned int, unsigned int) rfun)
References MHAEvents::emitter_t::connect(), and MHAEvents::connector_t< receiver_t >::emitter.
template<class receiver_t > MHAEvents::connector_t< receiver_t >::~connector_t ()
References MHAEvents::emitter_t::disconnect(), MHAEvents::connector_t< receiver_t >::emitter, and MHAEvents::connector_base_t::emitter_is_alive.
Member Function Documentation
template<class receiver_t > void MHAEvents::connector_t< receiver_t >::emit_event () private virtual
Reimplemented from MHAEvents::connector_base_t.
References MHAEvents::connector_t< receiver_t >::eventhandler, and MHAEvents::connector_t< receiver_t >::receiver.
template<class receiver_t > void MHAEvents::connector_t< receiver_t >::emit_event (const std::string & arg) private virtual
Reimplemented from MHAEvents::connector_base_t.
References MHAEvents::connector_t< receiver_t >::eventhandler_s, and MHAEvents::connector_t< receiver_t >::receiver.
template<class receiver_t > void MHAEvents::connector_t< receiver_t >::emit_event (const std::string & arg, unsigned int arg2, unsigned int arg3) private virtual
Reimplemented from MHAEvents::connector_base_t.
References MHAEvents::connector_t< receiver_t >::eventhandler_suu, and MHAEvents::connector_t< receiver_t >::receiver.
Member Data Documentation
template<class receiver_t> emitter_t* MHAEvents::connector_t< receiver_t >::emitter private
Referenced by MHAEvents::connector_t< receiver_t >::connector_t(), and MHAEvents::connector_t< receiver_t >::~connector_t().
template<class receiver_t> receiver_t* MHAEvents::connector_t< receiver_t >::receiver private
Referenced by MHAEvents::connector_t< receiver_t >::emit_event().
template<class receiver_t> void(receiver_t::* MHAEvents::connector_t< receiver_t >::eventhandler) () private
Referenced by MHAEvents::connector_t< receiver_t >::emit_event().
template<class receiver_t> void(receiver_t::* MHAEvents::connector_t< receiver_t >::eventhandler_s) (const std::string &) private
Referenced by MHAEvents::connector_t< receiver_t >::emit_event().
template<class receiver_t> void(receiver_t::* MHAEvents::connector_t< receiver_t >::eventhandler_suu) (const std::string &, unsigned int, unsigned int) private
Referenced by MHAEvents::connector_t< receiver_t >::emit_event().
The documentation for this class was generated from the following file:
mha_events.h