openMHA Manual: MHA_AC::stat_t Class Reference
MHA_AC::stat_t Class Reference
#include <mha_algo_comm.h>
Public Member Functions
stat_t (algo_comm_t ac, const std::string &name, const unsigned int &frames, const unsigned int &channels, bool insert_now)
void update ()
void insert ()
Public Member Functions inherited from MHASignal::stat_t
stat_t (const unsigned int &frames, const unsigned int &channels)
void mean (mha_wave_t &m)
void mean_std (mha_wave_t &m, mha_wave_t &s)
void push (const mha_wave_t &)
void push (const mha_real_t &x, const unsigned int &k, const unsigned int &ch)
Private Attributes
MHA_AC::waveform_t mean
MHA_AC::waveform_t std
Constructor & Destructor Documentation
MHA_AC::stat_t::stat_t (algo_comm_t ac, const std::string & name, const unsigned int & frames, const unsigned int & channels, bool insert_now)
References insert().
Member Function Documentation
void MHA_AC::stat_t::update ()
References mean, and MHASignal::stat_t::mean_std().
void MHA_AC::stat_t::insert ()
References MHA_AC::waveform_t::insert(), and mean.
Referenced by stat_t().
Member Data Documentation
MHA_AC::waveform_t MHA_AC::stat_t::mean private
Referenced by insert(), and update().
MHA_AC::waveform_t MHA_AC::stat_t::std private
The documentation for this class was generated from the following files:
mha_algo_comm.h
mha_algo_comm.cpp