openMHA Manual: combc_if_t Class Reference
combc_if_t Class Reference
Public Member Functions
combc_if_t (const algo_comm_t &, const std::string &, const std::string &)
void prepare (mhaconfig_t &)
mha_wave_t * process (mha_wave_t *)
mha_spec_t * process (mha_spec_t *)
Public Member Functions inherited from MHAPlugin::plugin_t< combc_t >
plugin_t (const std::string &, const algo_comm_t &)
Constructor of plugin template.
virtual ~plugin_t ()
virtual void release ()
void prepare_ (mhaconfig_t &)
void release_ ()
bool is_prepared () const
Flag, if the prepare method is successfully called (or currently evaluated)
mhaconfig_t input_cfg () const
Current input channel configuration.
mhaconfig_t output_cfg () const
Current output channel configuration.
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from MHAPlugin::config_t< combc_t >
config_t ()
~config_t ()
Private Attributes
MHAParser::int_t outchannels
MHAParser::bool_t interleaved
MHAParser::string_t channel_gain_name
MHAParser::string_t element_gain_name
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Member Functions inherited from MHAPlugin::config_t< combc_t >
combc_t * poll_config ()
Receive the latest run time configuration.
combc_t * last_config ()
Receive the latest run time configuration.
void push_config (combc_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Protected Attributes inherited from MHAPlugin::plugin_t< combc_t >
mhaconfig_t tftype
Member for storage of plugin interface configuration.
algo_comm_t ac
AC handle of the chain.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Protected Attributes inherited from MHAPlugin::config_t< combc_t >
combc_t * cfg
Constructor & Destructor Documentation
combc_if_t::combc_if_t (const algo_comm_t & iac, const std::string & , const std::string &)
References channel_gain_name, element_gain_name, insert_member, interleaved, and outchannels.
Member Function Documentation
void combc_if_t::prepare (mhaconfig_t & chcfg) virtual
Implements MHAPlugin::plugin_t< combc_t >.
References MHAPlugin::plugin_t< combc_t >::ac, channel_gain_name, mhaconfig_t::channels, MHAParser::string_t::data, MHAParser::bool_t::data, MHAParser::int_t::data, element_gain_name, MHA_AC::get_var_waveform(), MHAPlugin::plugin_t< combc_t >::input_cfg(), interleaved, outchannels, MHAPlugin::config_t< combc_t >::push_config(), and std_vector_float().
mha_wave_t * combc_if_t::process (mha_wave_t * s)
References MHAPlugin::config_t< combc_t >::poll_config(), and combc_t::process().
mha_spec_t * combc_if_t::process (mha_spec_t * s)
References MHAPLUGIN_CALLBACKS, MHAPLUGIN_DOCUMENTATION, MHAPLUGIN_PROC_CALLBACK, MHAPlugin::config_t< combc_t >::poll_config(), and combc_t::process().
Member Data Documentation
MHAParser::int_t combc_if_t::outchannels private
Referenced by combc_if_t(), and prepare().
MHAParser::bool_t combc_if_t::interleaved private
Referenced by combc_if_t(), and prepare().
MHAParser::string_t combc_if_t::channel_gain_name private
Referenced by combc_if_t(), and prepare().
MHAParser::string_t combc_if_t::element_gain_name private
Referenced by combc_if_t(), and prepare().
The documentation for this class was generated from the following file:
combinechannels.cpp