openMHA Manual: io_tcp_sound_t Class Reference
io_tcp_sound_t Class Reference
Classes
union float_union
Public Member Functions
io_tcp_sound_t (int fragsize, float samplerate)
Initialize sound data handling.
virtual ~io_tcp_sound_t ()
Do-nothing destructor.
virtual void prepare (int num_inchannels, int num_outchannels)
Called during prepare, sets number of audio channels and allocates sound data storage.
virtual void release ()
Called during release.
virtual int chunkbytes_in () const
Number of bytes that constitute one input sound chunk.
virtual std::string header () const
Create the tcp sound header lines.
virtual mha_wave_t * ntoh (const std::string &data)
Copy data received from tcp into mha_wave_t structure.
virtual std::string hton (const mha_wave_t *s_out)
Copy sound data from the output sound structure to a string.
Static Private Member Functions
static void check_sound_data_type () throw (MHA_Error)
Check if mha_real_t is a usable 32-bit floating point type.
Private Attributes
int fragsize
Number of sound samples in each channel expected and returned from processing callback.
float samplerate
Sampling rate.
int num_inchannels
Number of input channels.
int num_outchannels
MHASignal::waveform_t * s_in
Storage for input signal.
Detailed Description
Sound data handling of io tcp library.
Constructor & Destructor Documentation
io_tcp_sound_t::io_tcp_sound_t (int fragsize, float samplerate)
Initialize sound data handling.
Checks sound data type by calling
See also
check_sound_data_type.
Parameters
fragsize Number of sound samples in each channel expected and returned from processing callback.
samplerate Number of samples per second in each channel.
References check_sound_data_type(), and fragsize.
virtual io_tcp_sound_t::~io_tcp_sound_t () inline virtual
Do-nothing destructor.
Member Function Documentation
void io_tcp_sound_t::check_sound_data_type () throw (MHA_Error) static private
Check if mha_real_t is a usable 32-bit floating point type.
Exceptions
MHA_Error if mha_real_t is not compatible to 32-bit float.
References io_tcp_sound_t::float_union::c, io_tcp_sound_t::float_union::f, io_tcp_sound_t::float_union::i, and MHA_ErrorMsg.
Referenced by io_tcp_sound_t().
void io_tcp_sound_t::prepare (int num_inchannels, int num_outchannels) virtual
Called during prepare, sets number of audio channels and allocates sound data storage.
Parameters
num_inchannels Number of input audio channels.
num_outchannels Number of output audio channels.
References fragsize, MHA_ErrorMsg, MHA_ErrorMsg2, num_inchannels, num_outchannels, and s_in.
Referenced by io_tcp_t::prepare().
void io_tcp_sound_t::release () virtual
Called during release.
Deletes sound data storage.
References num_inchannels, num_outchannels, and s_in.
Referenced by io_tcp_t::release().
int io_tcp_sound_t::chunkbytes_in () const virtual
Number of bytes that constitute one input sound chunk.
Returns
Number of bytes to read from TCP connection before invoking signal processing.
References fragsize, and num_inchannels.
Referenced by io_tcp_t::connection_loop(), and ntoh().
std::string io_tcp_sound_t::header () const virtual
Create the tcp sound header lines.
References fragsize, num_inchannels, num_outchannels, and samplerate.
Referenced by io_tcp_t::connection_loop().
mha_wave_t * io_tcp_sound_t::ntoh (const std::string & data) virtual
Copy data received from tcp into mha_wave_t structure.
Doing network-to-host byte order swapping in the process.
Parameters
data One chunk (
See also
chunkbytes_in) of sound data to process.
Returns
Pointer to the sound data storage.
References mha_wave_t::buf, chunkbytes_in(), fragsize, mha_wave_t::num_channels, mha_wave_t::num_frames, num_inchannels, s_in, and size().
Referenced by io_tcp_t::connection_loop().
std::string io_tcp_sound_t::hton (const mha_wave_t * s_out) virtual
Copy sound data from the output sound structure to a string.
Doing host-to-network byte order swapping while at it.
Parameters
s_out Pointer to the storage of the sound to put out.
Returns
The sound data in network byte order.
References mha_wave_t::buf, mha_wave_t::num_channels, mha_wave_t::num_frames, and size().
Referenced by io_tcp_t::connection_loop().
Member Data Documentation
int io_tcp_sound_t::fragsize private
Number of sound samples in each channel expected and returned from processing callback.
Referenced by chunkbytes_in(), header(), io_tcp_sound_t(), ntoh(), and prepare().
float io_tcp_sound_t::samplerate private
Sampling rate.
Number of samples per second in each channel.
Referenced by header().
int io_tcp_sound_t::num_inchannels private
Number of input channels.
Number of channels expected from and returned by signal processing callback.
Referenced by chunkbytes_in(), header(), ntoh(), prepare(), and release().
int io_tcp_sound_t::num_outchannels private
Referenced by header(), prepare(), and release().
MHASignal::waveform_t* io_tcp_sound_t::s_in private
Storage for input signal.
Referenced by ntoh(), prepare(), and release().
The documentation for this class was generated from the following file:
MHAIOTCP.cpp