openMHA Manual: fw_vars_t Class Reference
fw_vars_t Class Reference
#include <mhafw_lib.h>
Public Member Functions
fw_vars_t (MHAParser::parser_t &)
void lock_srate_fragsize ()
void lock_channels ()
void unlock_srate_fragsize ()
void unlock_channels ()
Public Attributes
MHAParser::int_t pinchannels
MHAParser::int_t pfragmentsize
MHAParser::float_t psrate
Constructor & Destructor Documentation
fw_vars_t::fw_vars_t (MHAParser::parser_t & p)
References MHAParser::parser_t::insert_item(), pfragmentsize, pinchannels, and psrate.
Member Function Documentation
void fw_vars_t::lock_srate_fragsize ()
Referenced by fw_t::load_io_lib().
void fw_vars_t::lock_channels ()
Referenced by fw_t::prepare().
void fw_vars_t::unlock_srate_fragsize ()
void fw_vars_t::unlock_channels ()
Referenced by fw_t::release().
Member Data Documentation
MHAParser::int_t fw_vars_t::pinchannels
Referenced by fw_vars_t(), and fw_t::get_input_signal_dimension().
MHAParser::int_t fw_vars_t::pfragmentsize
Referenced by fw_vars_t(), fw_t::get_input_signal_dimension(), and fw_t::load_io_lib().
MHAParser::float_t fw_vars_t::psrate
Referenced by fw_vars_t(), fw_t::get_input_signal_dimension(), and fw_t::load_io_lib().
The documentation for this class was generated from the following files:
mhafw_lib.h
mhafw_lib.cpp