openMHA Manual: coherence::cohflt_t Class Reference
coherence::cohflt_t Class Reference
Public Member Functions
cohflt_t (vars_t &v, const mhaconfig_t &icf, algo_comm_t iac, const std::string &name)
mha_spec_t * process (mha_spec_t *)
void insert ()
Private Attributes
unsigned int nbands
bool avg_ipd
mha_complex_t cg
float g
float c_scale
float c_min
MHASignal::waveform_t alpha
float limit
MHAFilter::o1flt_lowpass_t lp1r
MHAFilter::o1flt_lowpass_t lp1i
MHA_AC::spectrum_t coh_c
MHA_AC::waveform_t coh_rlp
MHASignal::waveform_t gain
MHASignal::delay_wave_t gain_delay
MHASignal::spectrum_t s_out
bool bInvert
MHAFilter::o1flt_lowpass_t lp1ltg
bool b_ltg
std::vector< float > staticgain
Private Attributes inherited from MHAOvlFilter::fspacing_t
std::vector< MHAOvlFilter::band_descriptor_t > bands
mha_real_t(* symmetry_scale)(mha_real_t)
Private Attributes inherited from mhaconfig_t
unsigned int channels
Number of audio channels.
unsigned int domain
Signal domain (MHA_WAVEFORM or MHA_SPECTRUM)
unsigned int fragsize
Fragment size of waveform data.
unsigned int wndlen
Window length of spectral data.
unsigned int fftlen
FFT length of spectral data.
mha_real_t srate
Sampling rate in Hz.
Additional Inherited Members
Private Member Functions inherited from MHAOvlFilter::fftfb_t
fftfb_t (MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
Constructor for a FFT-based overlapping filter bank.
~fftfb_t ()
void apply_gains (mha_spec_t *s_out, const mha_spec_t *s_in, const mha_wave_t *gains)
void get_fbpower (mha_wave_t *fbpow, const mha_spec_t *s_in)
void get_fbpower_db (mha_wave_t *fbpow, const mha_spec_t *s_in)
std::vector< mha_real_t > get_ltass_gain_db () const
unsigned int bin1 (unsigned int band) const
Return index of first non-zero filter shape window.
unsigned int bin2 (unsigned int band) const
Return index of first zero filter shape window above center frequency.
unsigned int get_fftlen () const
Return fft length.
mha_real_t w (unsigned int k, unsigned int b) const
Return filter shape window at index k in band b.
Private Member Functions inherited from MHAOvlFilter::fspacing_t
fspacing_t (const MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
std::vector< unsigned int > get_cf_fftbin () const
std::vector< mha_real_t > get_cf_hz () const
std::vector< mha_real_t > get_ef_hz () const
unsigned int nbands () const
Return number of bands in filter bank.
void fail_on_nonmonotonic_cf ()
void fail_on_unique_fftbins ()
Constructor & Destructor Documentation
coherence::cohflt_t::cohflt_t (vars_t & v, const mhaconfig_t & icf, algo_comm_t iac, const std::string & name)
References coherence::vars_t::alpha, alpha, c_min, c_scale, mhaconfig_t::channels, MHAParser::kw_t::data, MHAParser::vfloat_t::data, MHASignal::dupvec_chk(), MHAOvlFilter::fftfb_vars_t::f, MHAOvlFilter::fscale_t::get_f_hz(), MHAParser::keyword_list_t::get_index(), lp1i, lp1r, coherence::vars_t::mapping, MHAOvlFilter::fspacing_t::nbands(), MHAFilter::o1flt_lowpass_t::set_tau(), staticgain, coherence::vars_t::tau, and coherence::vars_t::tau_unit.
Member Function Documentation
mha_spec_t * coherence::cohflt_t::process (mha_spec_t * s)
References abs(), abs2(), channels(), CHECK_EXPR, CHECK_VAR, mhaconfig_t::fftlen, coherence::getcipd(), MHASignal::limit(), MHASignal::max(), mha_complex(), mha_spec_t::num_channels, mha_spec_t::num_frames, and value().
void coherence::cohflt_t::insert ()
Member Data Documentation
unsigned int coherence::cohflt_t::nbands private
bool coherence::cohflt_t::avg_ipd private
mha_complex_t coherence::cohflt_t::cg private
float coherence::cohflt_t::g private
float coherence::cohflt_t::c_scale private
Referenced by cohflt_t().
float coherence::cohflt_t::c_min private
Referenced by cohflt_t().
MHASignal::waveform_t coherence::cohflt_t::alpha private
Referenced by cohflt_t().
float coherence::cohflt_t::limit private
MHAFilter::o1flt_lowpass_t coherence::cohflt_t::lp1r private
Referenced by cohflt_t().
MHAFilter::o1flt_lowpass_t coherence::cohflt_t::lp1i private
Referenced by cohflt_t().
MHA_AC::spectrum_t coherence::cohflt_t::coh_c private
MHA_AC::waveform_t coherence::cohflt_t::coh_rlp private
MHASignal::waveform_t coherence::cohflt_t::gain private
MHASignal::delay_wave_t coherence::cohflt_t::gain_delay private
MHASignal::spectrum_t coherence::cohflt_t::s_out private
bool coherence::cohflt_t::bInvert private
MHAFilter::o1flt_lowpass_t coherence::cohflt_t::lp1ltg private
bool coherence::cohflt_t::b_ltg private
std::vector<float> coherence::cohflt_t::staticgain private
Referenced by cohflt_t().
The documentation for this class was generated from the following file:
coherence.cpp