openMHA Manual: dc::dc_if_t Class Reference
dc::dc_if_t Class Reference
Public Member Functions
dc_if_t (const algo_comm_t &ac_, const std::string &th_, const std::string &al_)
void prepare (mhaconfig_t &tf)
mha_wave_t * process (mha_wave_t *)
mha_spec_t * process (mha_spec_t *)
Public Member Functions inherited from MHAPlugin::plugin_t< dc_t >
plugin_t (const std::string &, const algo_comm_t &)
Constructor of plugin template.
virtual ~plugin_t ()
virtual void release ()
void prepare_ (mhaconfig_t &)
void release_ ()
bool is_prepared () const
Flag, if the prepare method is successfully called (or currently evaluated)
mhaconfig_t input_cfg () const
Current input channel configuration.
mhaconfig_t output_cfg () const
Current output channel configuration.
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from MHAPlugin::config_t< dc_t >
config_t ()
~config_t ()
Public Member Functions inherited from dc::dc_vars_t
dc_vars_t (MHAParser::parser_t &)
Private Member Functions
void update_monitors ()
Called from within the processing routines: updates the monitor variables.
void update ()
Called by MHA configuration change event mechanism: creates new runtime configuration.
Private Attributes
std::string algo
wideband_inhib_vars_t wbinhib
MHAEvents::patchbay_t< dc_if_t > patchbay
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Public Attributes inherited from dc::dc_vars_t
MHAParser::bool_t powersum
MHAParser::mfloat_t gtdata
MHAParser::vfloat_t gtmin
MHAParser::vfloat_t gtstep
MHAParser::vfloat_t taurmslevel
MHAParser::vfloat_t tauattack
MHAParser::vfloat_t taudecay
MHAParser::string_t filterbank
std::string cf_name
std::string ef_name
std::string bw_name
MHAParser::string_t chname
MHAParser::bool_t bypass
MHAParser::string_t clientid
MHAParser::string_t gainrule
MHAParser::string_t preset
MHAParser::int_mon_t modified
MHAParser::mfloat_t max_level_difference
MHAParser::vfloat_mon_t input_level
MHAParser::vfloat_mon_t filtered_level
MHAParser::vfloat_mon_t center_frequencies
MHAParser::vfloat_mon_t edge_frequencies
MHAParser::vfloat_mon_t band_weights
MHAParser::bool_t use_wbinhib
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Member Functions inherited from MHAPlugin::config_t< dc_t >
dc_t * poll_config ()
Receive the latest run time configuration.
dc_t * last_config ()
Receive the latest run time configuration.
void push_config (dc_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Protected Attributes inherited from MHAPlugin::plugin_t< dc_t >
mhaconfig_t tftype
Member for storage of plugin interface configuration.
algo_comm_t ac
AC handle of the chain.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Protected Attributes inherited from MHAPlugin::config_t< dc_t >
dc_t * cfg
Constructor & Destructor Documentation
dc::dc_if_t::dc_if_t (const algo_comm_t & ac_, const std::string & th_, const std::string & al_)
References insert_member, patchbay, update(), wbinhib, and MHAParser::base_t::writeaccess.
Member Function Documentation
void dc::dc_if_t::prepare (mhaconfig_t & tf) virtual
Implements MHAPlugin::plugin_t< dc_t >.
References dc::dc_vars_t::band_weights, dc::dc_vars_t::bw_name, dc::dc_vars_t::center_frequencies, dc::dc_vars_t::cf_name, MHAPlugin::config_t< dc_t >::cfg, mhaconfig_t::channels, MHAParser::string_t::data, MHAParser::vfloat_mon_t::data, dc::dc_vars_t::edge_frequencies, dc::dc_vars_t::ef_name, dc::dc_vars_t::filterbank, dc::dc_vars_t::filtered_level, dc::dc_vars_t::input_level, MHAPlugin::config_t< dc_t >::poll_config(), dc::wideband_inhib_vars_t::setchannels(), MHAPlugin::plugin_t< dc_t >::tftype, update(), update_monitors(), and wbinhib.
mha_wave_t * dc::dc_if_t::process (mha_wave_t * s_in)
References MHAPlugin::config_t< dc_t >::cfg, MHAPlugin::config_t< dc_t >::poll_config(), and update_monitors().
mha_spec_t * dc::dc_if_t::process (mha_spec_t * s_in)
References MHAPlugin::config_t< dc_t >::cfg, dc::wideband_inhib_vars_t::current(), MHAParser::bool_t::data, MHAPlugin::config_t< dc_t >::poll_config(), update_monitors(), dc::dc_vars_t::use_wbinhib, and wbinhib.
void dc::dc_if_t::update_monitors () private
Called from within the processing routines: updates the monitor variables.
References comm_var_t::data, comm_var_t::data_type, MHA_AC_MHAREAL, dc::dc_t::naudiochannels, and comm_var_t::num_entries.
Referenced by prepare(), and process().
void dc::dc_if_t::update () private
Called by MHA configuration change event mechanism: creates new runtime configuration.
References MHAPlugin::plugin_t< dc_t >::ac, algo, mhaconfig_t::channels, mhaconfig_t::domain, mhaconfig_t::fftlen, mhaconfig_t::fragsize, MHA_WAVEFORM, MHAPlugin::config_t< dc_t >::push_config(), mhaconfig_t::srate, and MHAPlugin::plugin_t< dc_t >::tftype.
Referenced by dc_if_t(), and prepare().
Member Data Documentation
std::string dc::dc_if_t::algo private
Referenced by update().
wideband_inhib_vars_t dc::dc_if_t::wbinhib private
Referenced by dc_if_t(), prepare(), and process().
MHAEvents::patchbay_t<dc_if_t> dc::dc_if_t::patchbay private
Referenced by dc_if_t().
The documentation for this class was generated from the following file:
dc.cpp