openMHA Manual: fftfilterbank::fftfb_interface_t Class Reference
fftfilterbank::fftfb_interface_t Class Reference
Public Member Functions
fftfb_interface_t (const algo_comm_t &ac, const std::string &th, const std::string &al)
void prepare (mhaconfig_t &)
Prepare all variables for processing.
void release ()
mha_spec_t * process (mha_spec_t *)
mha_wave_t * process (mha_wave_t *)
Public Member Functions inherited from MHAPlugin::plugin_t< fftfb_plug_t >
plugin_t (const std::string &, const algo_comm_t &)
Constructor of plugin template.
virtual ~plugin_t ()
void prepare_ (mhaconfig_t &)
void release_ ()
bool is_prepared () const
Flag, if the prepare method is successfully called (or currently evaluated)
mhaconfig_t input_cfg () const
Current input channel configuration.
mhaconfig_t output_cfg () const
Current output channel configuration.
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from MHAPlugin::config_t< fftfb_plug_t >
config_t ()
~config_t ()
Public Member Functions inherited from MHAOvlFilter::overlap_save_filterbank_t::vars_t
vars_t (MHAParser::parser_t &p)
Public Member Functions inherited from MHAOvlFilter::fftfb_vars_t
fftfb_vars_t (MHAParser::parser_t &p)
construct a set of MHA configuration language variables suitable for configuring the FFT-based overlapping filterbank.
Private Member Functions
void update_cfg ()
Private Attributes
MHAParser::bool_t return_imag
MHAEvents::patchbay_t< fftfb_interface_t > patchbay
MHA_AC::int_t nchannels
std::string algo
bool prepared
unsigned int nbands
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Public Attributes inherited from MHAOvlFilter::overlap_save_filterbank_t::vars_t
MHAParser::int_t fftlen
MHAParser::kw_t phasemodel
MHAParser::window_t irswnd
Public Attributes inherited from MHAOvlFilter::fftfb_vars_t
scale_var_t fscale
Frequency scale type (lin/bark/log/erb).
scale_var_t ovltype
Filter shape (rect/lin/hann).
MHAParser::float_t plateau
relative plateau width.
MHAParser::kw_t ftype
Flag to decide wether edge or center frequencies are used.
fscale_t f
Frequency.
MHAParser::bool_t normalize
Normalize sum of channels.
MHAParser::bool_t fail_on_nonmonotonic
Fail if frequency entries are non-monotonic (otherwise sort)
MHAParser::bool_t fail_on_unique_bins
Fail if center frequencies share the same FFT bin.
MHAParser::vfloat_mon_t cf
Final center frequencies in Hz.
MHAParser::vfloat_mon_t ef
Final edge frequencies in Hz.
MHAParser::vfloat_mon_t cLTASS
Bandwidth correction for LTASS noise (level of 0 dB RMS LTASS noise)
MHAParser::mfloat_mon_t shapes
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Member Functions inherited from MHAPlugin::config_t< fftfb_plug_t >
fftfb_plug_t * poll_config ()
Receive the latest run time configuration.
fftfb_plug_t * last_config ()
Receive the latest run time configuration.
void push_config (fftfb_plug_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Protected Attributes inherited from MHAPlugin::plugin_t< fftfb_plug_t >
mhaconfig_t tftype
Member for storage of plugin interface configuration.
algo_comm_t ac
AC handle of the chain.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Protected Attributes inherited from MHAPlugin::config_t< fftfb_plug_t >
fftfb_plug_t * cfg
Constructor & Destructor Documentation
fftfilterbank::fftfb_interface_t::fftfb_interface_t (const algo_comm_t & ac, const std::string & th, const std::string & al)
Default values are set and MHA configuration variables registered into the parser.
Parameters
ac algorithm communication handle
th chain name
al algorithm name
References insert_member, patchbay, return_imag, MHAParser::base_t::set_node_id(), update_cfg(), and MHAParser::base_t::writeaccess.
Member Function Documentation
void fftfilterbank::fftfb_interface_t::prepare (mhaconfig_t & tf) virtual
Prepare all variables for processing.
In this function, all variables are initialised and the filter shapes for each band are calculated. The filter shapes are defined as
beeing a symmetric window function in the interval and the transformation from the linear scale to the given frequency scale (see functions in FreqScaleFun). The function transforms the frequency range between the center frequencies and into the interval and , respectively. This function is realised by the function linscale().
Parameters
tf Channel configuration
Implements MHAPlugin::plugin_t< fftfb_plug_t >.
References MHAPlugin::plugin_t< fftfb_plug_t >::ac, algo, MHAPlugin::config_t< fftfb_plug_t >::cfg, mhaconfig_t::channels, MHA_AC::int_t::data, MHAParser::bool_t::data, MHAParser::int_t::data, mhaconfig_t::domain, mhaconfig_t::fftlen, MHAOvlFilter::overlap_save_filterbank_t::vars_t::fftlen, MHA_SPECTRUM, nbands, MHAOvlFilter::fspacing_t::nbands(), nchannels, MHAPlugin::config_t< fftfb_plug_t >::poll_config(), prepared, MHAPlugin::config_t< fftfb_plug_t >::push_config(), return_imag, MHAParser::variable_t::setlock(), and MHAPlugin::plugin_t< fftfb_plug_t >::tftype.
void fftfilterbank::fftfb_interface_t::release () virtual
Reimplemented from MHAPlugin::plugin_t< fftfb_plug_t >.
References MHAOvlFilter::overlap_save_filterbank_t::vars_t::fftlen, prepared, and MHAParser::variable_t::setlock().
mha_spec_t * fftfilterbank::fftfb_interface_t::process (mha_spec_t * s)
References MHAPlugin::config_t< fftfb_plug_t >::poll_config().
mha_wave_t * fftfilterbank::fftfb_interface_t::process (mha_wave_t * s)
References MHAPlugin::config_t< fftfb_plug_t >::poll_config().
void fftfilterbank::fftfb_interface_t::update_cfg () private
References MHAPlugin::plugin_t< fftfb_plug_t >::ac, algo, MHAParser::bool_t::data, nbands, MHAOvlFilter::fspacing_t::nbands(), prepared, MHAPlugin::config_t< fftfb_plug_t >::push_config(), return_imag, and MHAPlugin::plugin_t< fftfb_plug_t >::tftype.
Referenced by fftfb_interface_t().
Member Data Documentation
MHAParser::bool_t fftfilterbank::fftfb_interface_t::return_imag private
Referenced by fftfb_interface_t(), prepare(), and update_cfg().
MHAEvents::patchbay_t<fftfb_interface_t> fftfilterbank::fftfb_interface_t::patchbay private
Referenced by fftfb_interface_t().
MHA_AC::int_t fftfilterbank::fftfb_interface_t::nchannels private
Referenced by prepare().
std::string fftfilterbank::fftfb_interface_t::algo private
Referenced by prepare(), and update_cfg().
bool fftfilterbank::fftfb_interface_t::prepared private
Referenced by prepare(), release(), and update_cfg().
unsigned int fftfilterbank::fftfb_interface_t::nbands private
Referenced by prepare(), and update_cfg().
The documentation for this class was generated from the following file:
fftfilterbank.cpp