openMHA Manual: io_lib_t Class Reference
io_lib_t Class Reference
#include <mhafw_lib.h>
Public Member Functions
io_lib_t (int fragsize, float samplerate, IOProcessEvent_t proc_event, void *proc_handle, IOStartedEvent_t start_event, void *start_handle, IOStoppedEvent_t stop_event, void *stop_handle, std::string libname)
load and initialize MHA sound io module.
~io_lib_t ()
Deinitialize and unload this MHA sound io module.
void prepare (unsigned int inch, unsigned int outch)
Prepare the sound io module.
void start ()
Tell the sound io module to start sound processing.
void stop ()
void release ()
std::string lib_str_error (int err)
Public Member Functions inherited from MHAParser::c_ifc_parser_t
c_ifc_parser_t (const std::string &modulename_)
~c_ifc_parser_t ()
void set_parse_cb (c_parse_cmd_t, c_parse_err_t, void *)
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_dump (const std::string &)
virtual std::string query_entries (const std::string &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
virtual std::string query_type (const std::string &)
virtual std::string query_val (const std::string &)
virtual std::string query_readfile (const std::string &)
virtual std::string query_savefile (const std::string &)
virtual std::string query_savefile_compact (const std::string &)
virtual std::string query_savemons (const std::string &)
virtual std::string query_listids (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Protected Member Functions
void test_error ()
Protected Member Functions inherited from MHAParser::c_ifc_parser_t
std::string op_subparse (MHAParser::expression_t &)
std::string op_setval (MHAParser::expression_t &)
std::string op_query (MHAParser::expression_t &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes
int lib_err
dynamiclib_t lib_handle
void * lib_data
IOInit_t IOInit_cb
IOPrepare_t IOPrepare_cb
IOStart_t IOStart_cb
IOStop_t IOStop_cb
IORelease_t IORelease_cb
IOSetVar_t IOSetVar_cb
IOStrError_t IOStrError_cb
IODestroy_t IODestroy_cb
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Detailed Description
Class for loading MHA sound IO module.
Constructor & Destructor Documentation
io_lib_t::io_lib_t (int fragsize, float samplerate, IOProcessEvent_t proc_event, void * proc_handle, IOStartedEvent_t start_event, void * start_handle, IOStoppedEvent_t stop_event, void * stop_handle, std::string libname)
load and initialize MHA sound io module.
References IODestroy, IOInit, IOInit_cb, IOPrepare, IORelease, IOSetVar, IOSetVar_cb, IOStart, IOStop, IOStrError, IOStrError_cb, lib_data, lib_err, lib_handle, MHA_RESOLVE_CHECKED, MHAParser::c_ifc_parser_t::set_parse_cb(), and test_error().
io_lib_t::~io_lib_t ()
Deinitialize and unload this MHA sound io module.
References Getmsg, IODestroy_cb, and lib_data.
Member Function Documentation
void io_lib_t::prepare (unsigned int inch, unsigned int outch)
Prepare the sound io module.
After preparation, the sound io module may start the sound processing at any time (external trigger). When the sound processing is started, the sound io module will call the start_event callback.
Parameters
inch number of input channels
outch number of output channels
References IOPrepare_cb, lib_data, lib_err, and test_error().
Referenced by fw_t::exit_request(), and fw_t::prepare().
void io_lib_t::start ()
Tell the sound io module to start sound processing.
Some io modules need this, for others that wait for external events this method might do nothing.
References IOStart_cb, lib_data, lib_err, and test_error().
Referenced by fw_t::exit_request(), and fw_t::start().
void io_lib_t::stop ()
References IOStop_cb, lib_data, lib_err, and test_error().
Referenced by fw_t::exit_request(), and fw_t::stop().
void io_lib_t::release ()
References IORelease_cb, lib_data, lib_err, and test_error().
Referenced by fw_t::exit_request(), and fw_t::release().
std::string io_lib_t::lib_str_error (int err)
References IOStrError_cb, and lib_data.
void io_lib_t::test_error () protected
References IOStrError_cb, lib_data, and lib_err.
Referenced by io_lib_t(), prepare(), release(), start(), and stop().
Member Data Documentation
int io_lib_t::lib_err protected
Referenced by io_lib_t(), prepare(), release(), start(), stop(), and test_error().
dynamiclib_t io_lib_t::lib_handle protected
Referenced by io_lib_t().
void* io_lib_t::lib_data protected
Referenced by io_lib_t(), lib_str_error(), prepare(), release(), start(), stop(), test_error(), and ~io_lib_t().
IOInit_t io_lib_t::IOInit_cb protected
Referenced by io_lib_t().
IOPrepare_t io_lib_t::IOPrepare_cb protected
Referenced by prepare().
IOStart_t io_lib_t::IOStart_cb protected
Referenced by start().
IOStop_t io_lib_t::IOStop_cb protected
Referenced by stop().
IORelease_t io_lib_t::IORelease_cb protected
Referenced by release().
IOSetVar_t io_lib_t::IOSetVar_cb protected
Referenced by io_lib_t().
IOStrError_t io_lib_t::IOStrError_cb protected
Referenced by io_lib_t(), lib_str_error(), and test_error().
IODestroy_t io_lib_t::IODestroy_cb protected
Referenced by ~io_lib_t().
The documentation for this class was generated from the following files:
mhafw_lib.h
mhafw_lib.cpp