openMHA Manual: DynComp::gaintable_t Class Reference
DynComp::gaintable_t Class Reference
Gain table class.
#include <gaintable.h>
Public Member Functions
gaintable_t (const std::vector< mha_real_t > &LInput, const std::vector< mha_real_t > &FCenter, unsigned int channels)
Constructor.
~gaintable_t ()
void update (std::vector< std::vector< std::vector< mha_real_t > > > newGain)
Update gains from an external table.
mha_real_t get_gain (mha_real_t Lin, mha_real_t Fin, unsigned int channel)
Read Gain from gain table.
mha_real_t get_gain (mha_real_t Lin, unsigned int band, unsigned int channel)
Read Gain from gain table.
void get_gain (const mha_wave_t &Lin, mha_wave_t &Gain)
Read Gains from gain table.
unsigned int nbands () const
Return number of frequency bands.
unsigned int nchannels () const
Return number of audio channels.
std::vector< std::vector< mha_real_t > > get_iofun () const
Return current input-output function.
std::vector< mha_real_t > get_vL () const
std::vector< mha_real_t > get_vF () const
Private Attributes
unsigned int num_L
unsigned int num_F
unsigned int num_channels
std::vector< mha_real_t > vL
std::vector< mha_real_t > vF
std::vector< mha_real_t > vFlog
std::vector< std::vector< std::vector< mha_real_t > > > data
Detailed Description
Gain table class.
This gain table is intended to efficient table lookup, i.e, interpolation of levels, and optional interpolation of frequencies. Sample input levels and sample frequencies are given in the constructor. The gain entries can be updated with the update() member function via a gain prescription rule from an auditory profile.
Constructor & Destructor Documentation
gaintable_t::gaintable_t (const std::vector< mha_real_t > & LInput, const std::vector< mha_real_t > & FCenter, unsigned int channels)
Constructor.
Parameters
LInput Input level samples, in equivalent LTASS_combined dB SPL.
FCenter Frequency samples in Hz (e.g., center frequencies of filterbank).
channels Number of audio channels (typically 2).
References data, num_channels, num_F, and num_L.
gaintable_t::~gaintable_t ()
Member Function Documentation
void gaintable_t::update (std::vector< std::vector< std::vector< mha_real_t > > > newGain)
Update gains from an external table.
Parameters
newGain New gain table entries.
Dimension change is not allowed. The number of entries are checked.
References data, isempty(), num_channels, num_F, and size().
mha_real_t gaintable_t::get_gain (mha_real_t Lin, mha_real_t Fin, unsigned int channel)
Read Gain from gain table.
Parameters
Lin Input level
Fin Input frequency (no match required)
channel Audio channel
References data, DynComp::interp2(), vFlog, and vL.
Referenced by get_gain().
mha_real_t gaintable_t::get_gain (mha_real_t Lin, unsigned int band, unsigned int channel)
Read Gain from gain table.
Parameters
Lin Input level
band Input frequency band
channel Audio channel
References data, DynComp::interp1(), and vL.
void gaintable_t::get_gain (const mha_wave_t & Lin, mha_wave_t & Gain)
Read Gains from gain table.
Parameters
Lin Input levels.
Gain Output gain.
The number of channels in Lin and Gain must match the number of bands times number of channels in the gaintable.
References get_gain(), MHA_assert_equal, num_channels, mha_wave_t::num_channels, num_F, mha_wave_t::num_frames, and value().
unsigned int DynComp::gaintable_t::nbands () const inline
Return number of frequency bands.
References num_F.
unsigned int DynComp::gaintable_t::nchannels () const inline
Return number of audio channels.
References get_iofun(), and num_channels.
std::vector< std::vector< mha_real_t > > gaintable_t::get_iofun () const
Return current input-output function.
References data, num_channels, and num_F.
Referenced by nchannels().
std::vector<mha_real_t> DynComp::gaintable_t::get_vL () const inline
References vL.
std::vector<mha_real_t> DynComp::gaintable_t::get_vF () const inline
Member Data Documentation
unsigned int DynComp::gaintable_t::num_L private
Referenced by gaintable_t().
unsigned int DynComp::gaintable_t::num_F private
Referenced by gaintable_t(), get_gain(), get_iofun(), nbands(), and update().
unsigned int DynComp::gaintable_t::num_channels private
Referenced by gaintable_t(), get_gain(), get_iofun(), nchannels(), and update().
std::vector<mha_real_t> DynComp::gaintable_t::vL private
Referenced by get_gain(), and get_vL().
std::vector<mha_real_t> DynComp::gaintable_t::vF private
std::vector<mha_real_t> DynComp::gaintable_t::vFlog private
Referenced by get_gain().
std::vector<std::vector<std::vector<mha_real_t> > > DynComp::gaintable_t::data private
Referenced by gaintable_t(), get_gain(), get_iofun(), and update().
The documentation for this class was generated from the following files:
gaintable.h
gaintable.cpp