openMHA Manual: dynamiclib_t Class Reference
dynamiclib_t Class Reference
#include <mha_os.h>
Public Member Functions
dynamiclib_t (const std::string &)
void * resolve (const std::string &)
void * resolve_checked (const std::string &)
~dynamiclib_t ()
const std::string & getmodulename () const
const std::string & getname () const
Private Attributes
std::string fullname
std::string modulename
mha_libhandle_t h
Constructor & Destructor Documentation
dynamiclib_t::dynamiclib_t (const std::string & n)
References fullname, h, mha_lib_extension, mha_library_paths(), modulename, and resolve().
dynamiclib_t::~dynamiclib_t ()
References h.
Member Function Documentation
void * dynamiclib_t::resolve (const std::string & n)
References getmodulename(), and h.
Referenced by dynamiclib_t(), and resolve_checked().
void * dynamiclib_t::resolve_checked (const std::string & n)
References fullname, and resolve().
const std::string& dynamiclib_t::getmodulename () const inline
References modulename.
Referenced by resolve(), and PluginLoader::mhapluginloader_t::test_error().
const std::string& dynamiclib_t::getname () const inline
References fullname.
Referenced by PluginLoader::mhapluginloader_t::prepare(), and PluginLoader::mhapluginloader_t::test_version().
Member Data Documentation
std::string dynamiclib_t::fullname private
Referenced by dynamiclib_t(), getname(), and resolve_checked().
std::string dynamiclib_t::modulename private
Referenced by dynamiclib_t(), and getmodulename().
mha_libhandle_t dynamiclib_t::h private
Referenced by dynamiclib_t(), resolve(), and ~dynamiclib_t().
The documentation for this class was generated from the following files:
mha_os.h
mha_os.cpp