openMHA Manual: dc::wideband_inhib_vars_t Class Reference
dc::wideband_inhib_vars_t Class Reference
Public Member Functions
wideband_inhib_vars_t ()
void setchannels (unsigned int ch, unsigned int bnds)
wb_inhib_cfg_t * current ()
void update ()
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from MHAPlugin::config_t< wb_inhib_cfg_t >
config_t ()
~config_t ()
Public Attributes
MHAParser::vfloat_t weights
MHAParser::float_t dl_map_min
MHAParser::float_t dl_map_max
MHAParser::float_t l_min
MHAParser::mfloat_t g_scale
MHAEvents::patchbay_t< wideband_inhib_vars_t > patchbay
unsigned int channels
unsigned int bands
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Additional Inherited Members
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Member Functions inherited from MHAPlugin::config_t< wb_inhib_cfg_t >
wb_inhib_cfg_t * poll_config ()
Receive the latest run time configuration.
wb_inhib_cfg_t * last_config ()
Receive the latest run time configuration.
void push_config (wb_inhib_cfg_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Protected Attributes inherited from MHAPlugin::config_t< wb_inhib_cfg_t >
wb_inhib_cfg_t * cfg
Constructor & Destructor Documentation
dc::wideband_inhib_vars_t::wideband_inhib_vars_t ()
References dl_map_max, dl_map_min, g_scale, insert_member, l_min, patchbay, update(), weights, and MHAParser::base_t::writeaccess.
Member Function Documentation
void dc::wideband_inhib_vars_t::setchannels (unsigned int ch, unsigned int bnds) inline
References channels().
Referenced by dc::dc_if_t::prepare().
wb_inhib_cfg_t* dc::wideband_inhib_vars_t::current () inline
Referenced by dc::dc_if_t::process().
void dc::wideband_inhib_vars_t::update ()
References channels, and MHAPlugin::config_t< wb_inhib_cfg_t >::push_config().
Referenced by wideband_inhib_vars_t().
Member Data Documentation
MHAParser::vfloat_t dc::wideband_inhib_vars_t::weights
Referenced by wideband_inhib_vars_t().
MHAParser::float_t dc::wideband_inhib_vars_t::dl_map_min
Referenced by wideband_inhib_vars_t().
MHAParser::float_t dc::wideband_inhib_vars_t::dl_map_max
Referenced by wideband_inhib_vars_t().
MHAParser::float_t dc::wideband_inhib_vars_t::l_min
Referenced by wideband_inhib_vars_t().
MHAParser::mfloat_t dc::wideband_inhib_vars_t::g_scale
Referenced by wideband_inhib_vars_t().
MHAEvents::patchbay_t<wideband_inhib_vars_t> dc::wideband_inhib_vars_t::patchbay
Referenced by wideband_inhib_vars_t().
unsigned int dc::wideband_inhib_vars_t::channels
Referenced by update(), and dc::wb_inhib_cfg_t::wb_inhib_cfg_t().
unsigned int dc::wideband_inhib_vars_t::bands
Referenced by dc::wb_inhib_cfg_t::wb_inhib_cfg_t().
The documentation for this class was generated from the following file:
dc.cpp