openMHA Manual: combc_t Class Reference
combc_t Class Reference
Public Member Functions
combc_t (algo_comm_t ac, mhaconfig_t cfg_input, mhaconfig_t cfg_output, std::vector< float > channel_gains, const std::string &element_gain_name, bool interleaved)
mha_wave_t * process (mha_wave_t *s)
mha_spec_t * process (mha_spec_t *s)
Private Attributes
algo_comm_t ac_
bool interleaved_
unsigned int nbands
MHASignal::waveform_t w_out
MHASignal::spectrum_t s_out
std::vector< mha_real_t > channel_gains_
std::string element_gain_name_
Constructor & Destructor Documentation
combc_t::combc_t (algo_comm_t ac, mhaconfig_t cfg_input, mhaconfig_t cfg_output, std::vector< float > channel_gains, const std::string & element_gain_name, bool interleaved)
References channel_gains_, mhaconfig_t::channels, and nbands.
Member Function Documentation
mha_wave_t * combc_t::process (mha_wave_t * s)
References ac_, channel_gains_, clear(), element_gain_name_, MHA_AC::get_var_waveform(), interleaved_, nbands, mha_wave_t::num_channels, mha_wave_t::num_frames, value(), MHASignal::waveform_t::value(), and w_out.
Referenced by combc_if_t::process().
mha_spec_t * combc_t::process (mha_spec_t * s)
References channel_gains_, clear(), nbands, mha_spec_t::num_channels, mha_spec_t::num_frames, s_out, value(), and MHASignal::spectrum_t::value().
Member Data Documentation
algo_comm_t combc_t::ac_ private
Referenced by process().
bool combc_t::interleaved_ private
Referenced by process().
unsigned int combc_t::nbands private
Referenced by combc_t(), and process().
MHASignal::waveform_t combc_t::w_out private
Referenced by process().
MHASignal::spectrum_t combc_t::s_out private
Referenced by process().
std::vector<mha_real_t> combc_t::channel_gains_ private
Referenced by combc_t(), and process().
std::string combc_t::element_gain_name_ private
Referenced by process().
The documentation for this class was generated from the following file:
combinechannels.cpp