openMHA Manual: latex_doc_t Class Reference
latex_doc_t Class Reference
Public Member Functions
latex_doc_t (const std::string &plugname, const std::string &plugin_macro)
std::string get_latex_doc ()
std::string get_main_category ()
std::vector< std::string > get_categories ()
Private Member Functions
std::string strdom (mha_domain_t d)
std::string get_ac (MHAKernel::algo_comm_class_t &ac, std::string txt)
std::string parsername (std::string s)
std::string get_parser_var (MHAParser::base_t *p, std::string name)
std::string get_parser_tab (MHAParser::base_t *p, std::string prefix)
Private Attributes
std::string plugname
std::string latex_plugname
MHAKernel::algo_comm_class_t ac
PluginLoader::mhapluginloader_t loader
std::string plugin_macro
Constructor & Destructor Documentation
latex_doc_t::latex_doc_t (const std::string & plugname, const std::string & plugin_macro)
Member Function Documentation
std::string latex_doc_t::get_latex_doc ()
References conv2latex(), PluginLoader::mhapluginloader_t::get_categories(), PluginLoader::mhapluginloader_t::get_documentation(), get_parser_tab(), PluginLoader::mhapluginloader_t::has_parser(), PluginLoader::mhapluginloader_t::has_process(), latex_plugname, loader, MHA_DOMAIN_MAX, PluginLoader::mhapluginloader_t::parse(), plugin_macro, plugname, and strdom().
Referenced by create_latex_doc().
std::string latex_doc_t::get_main_category ()
References PluginLoader::mhapluginloader_t::get_categories(), and loader.
Referenced by create_latex_doc().
std::vector< std::string > latex_doc_t::get_categories ()
References PluginLoader::mhapluginloader_t::get_categories(), and loader.
std::string latex_doc_t::strdom (mha_domain_t d) private
References MHA_SPECTRUM, and MHA_WAVEFORM.
Referenced by get_latex_doc().
std::string latex_doc_t::get_ac (MHAKernel::algo_comm_class_t & ac, std::string txt) private
References MHAKernel::algo_comm_class_t::local_get_entries(), and MHAParser::StrCnv::str2val().
std::string latex_doc_t::parsername (std::string s) private
Referenced by get_parser_tab(), and get_parser_var().
std::string latex_doc_t::get_parser_var (MHAParser::base_t * p, std::string name) private
References conv2latex(), MHAParser::base_t::parse(), parsername(), and range().
Referenced by get_parser_tab().
std::string latex_doc_t::get_parser_tab (MHAParser::base_t * p, std::string prefix) private
References conv2latex(), get_parser_var(), MHAParser::base_t::parse(), parsername(), and MHAParser::StrCnv::str2val().
Referenced by get_latex_doc().
Member Data Documentation
std::string latex_doc_t::plugname private
Referenced by get_latex_doc().
std::string latex_doc_t::latex_plugname private
Referenced by get_latex_doc().
MHAKernel::algo_comm_class_t latex_doc_t::ac private
PluginLoader::mhapluginloader_t latex_doc_t::loader private
Referenced by get_categories(), get_latex_doc(), and get_main_category().
std::string latex_doc_t::plugin_macro private
Referenced by get_latex_doc(), and main().
The documentation for this class was generated from the following file:
generatemhaplugindoc.cpp