openMHA Manual: MHA_AC::spectrum_t Class Reference
MHA_AC::spectrum_t Class Reference
Communication between algorithms
Insert a MHASignal::spectrum_t class into the AC space.
#include <mha_algo_comm.h>
Public Member Functions
spectrum_t (algo_comm_t ac, std::string name, unsigned int bins, unsigned int channels, bool insert_now)
Create the AC variable.
~spectrum_t ()
void insert ()
Insert AC variable into AC space.
Public Member Functions inherited from MHASignal::spectrum_t
spectrum_t (const unsigned int &frames, const unsigned int &channels)
constructor of spectrum class
spectrum_t (const mha_spec_t &)
Copy constructor.
spectrum_t (const MHASignal::spectrum_t &)
Copy constructor.
spectrum_t (const std::vector< mha_complex_t > &)
mha_complex_t & operator() (unsigned int f, unsigned int ch)
Access to element.
mha_complex_t & operator[] (unsigned int k)
Access to a single element, direct index into data buffer.
mha_complex_t & value (unsigned int f, unsigned int ch)
Access to element.
void copy (const mha_spec_t &)
copy all elements from a spectrum
void copy_channel (const mha_spec_t &s, unsigned sch, unsigned dch)
Copy one channel of a given spectrum signal to a target channel.
void export_to (mha_spec_t &)
copy elements to spectrum structure
void scale (const unsigned int &, const unsigned int &, const unsigned int &, const mha_real_t &)
scale section [a,b) in channel "ch" by "val"
void scale_channel (const unsigned int &, const mha_real_t &)
scale all elements in one channel
Protected Attributes
algo_comm_t ac
std::string name
Additional Inherited Members
Public Attributes inherited from mha_spec_t
mha_complex_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Detailed Description
Insert a MHASignal::spectrum_t class into the AC space.
The variable is automatically removed on destruction.
Constructor & Destructor Documentation
MHA_AC::spectrum_t::spectrum_t (algo_comm_t ac, std::string name, unsigned int bins, unsigned int channels, bool insert_now)
Create the AC variable.
Parameters
ac AC handle
name Name of variable in AC space
bins Number of FFT bins in the waveform_t class
channels Number of audio channels in the waveform_t class
insert_now Insert implicitely in the constructor (true) or explicitely in the insert() function (false)
References insert().
MHA_AC::spectrum_t::~spectrum_t (void) virtual
Reimplemented from MHASignal::spectrum_t.
References ac, mha_spec_t::buf, algo_comm_t::handle, and algo_comm_t::remove_ref.
Member Function Documentation
void MHA_AC::spectrum_t::insert ()
Insert AC variable into AC space.
References comm_var_t::data, comm_var_t::data_type, MHA_AC_MHACOMPLEX, comm_var_t::num_entries, and comm_var_t::stride.
Referenced by MHA_AC::acspace2matrix_t::frame(), MHA_AC::ac2matrix_t::getusername(), spectrum_t(), and MHAMultiSrc::spectrum_t::update().
Member Data Documentation
algo_comm_t MHA_AC::spectrum_t::ac protected
Referenced by ~spectrum_t().
std::string MHA_AC::spectrum_t::name protected
Referenced by MHA_AC::ac2matrix_t::getname(), and MHAMultiSrc::spectrum_t::update().
The documentation for this class was generated from the following files:
mha_algo_comm.h
mha_algo_comm.cpp