openMHA Manual: calibrator_runtime_layer_t Class Reference
calibrator_runtime_layer_t Class Reference
Public Member Functions
calibrator_runtime_layer_t (bool is_input, const mhaconfig_t &tf, calibrator_variables_t &vars)
mha_real_t process (mha_wave_t **)
Static Private Member Functions
static unsigned int firfirlen (const std::vector< std::vector< float > > &)
static unsigned int firfir2fftlen (unsigned int, const std::vector< std::vector< float > > &)
Private Attributes
MHAFilter::fftfilter_t fir
MHASignal::quantizer_t quant
MHASignal::waveform_t gain
softclipper_t softclip
bool b_is_input
bool b_use_fir
bool b_use_clipping
MHASignal::loop_wavefragment_t speechnoise
MHASignal::loop_wavefragment_t::playback_mode_t pmode
Constructor & Destructor Documentation
calibrator_runtime_layer_t::calibrator_runtime_layer_t (bool is_input, const mhaconfig_t & tf, calibrator_variables_t & vars)
References b_is_input, b_use_fir, mhaconfig_t::channels, MHAParser::float_t::data, MHAParser::vfloat_t::data, MHAParser::mfloat_t::data, MHAParser::int_mon_t::data, MHAParser::float_mon_t::data, calibrator_variables_t::fir, fir, firfirlen(), calibrator_variables_t::fragsize, mhaconfig_t::fragsize, gain, calibrator_variables_t::num_channels, calibrator_variables_t::peaklevel, MHASignal::loop_wavefragment_t::set_level_db(), speechnoise, calibrator_variables_t::spnoise_level, calibrator_variables_t::srate, mhaconfig_t::srate, and MHAFilter::fftfilter_t::update_coeffs().
Member Function Documentation
mha_real_t calibrator_runtime_layer_t::process (mha_wave_t ** s)
References calibrator_variables_t::fir, and calibrator_variables_t::softclip.
Referenced by calibrator_t::release().
unsigned int calibrator_runtime_layer_t::firfirlen (const std::vector< std::vector< float > > & fir) static private
References calibrator_variables_t::fir, and size().
Referenced by calibrator_runtime_layer_t().
unsigned int calibrator_runtime_layer_t::firfir2fftlen (unsigned int fragsize, const std::vector< std::vector< float > > & fir) static private
References calibrator_variables_t::fir, calibrator_variables_t::fragsize, and MHASignal::max().
Member Data Documentation
MHAFilter::fftfilter_t calibrator_runtime_layer_t::fir private
Referenced by calibrator_runtime_layer_t().
MHASignal::quantizer_t calibrator_runtime_layer_t::quant private
MHASignal::waveform_t calibrator_runtime_layer_t::gain private
Referenced by calibrator_runtime_layer_t().
softclipper_t calibrator_runtime_layer_t::softclip private
bool calibrator_runtime_layer_t::b_is_input private
Referenced by calibrator_runtime_layer_t(), and calibrator_t::process().
bool calibrator_runtime_layer_t::b_use_fir private
Referenced by calibrator_runtime_layer_t().
bool calibrator_runtime_layer_t::b_use_clipping private
MHASignal::loop_wavefragment_t calibrator_runtime_layer_t::speechnoise private
Referenced by calibrator_runtime_layer_t().
MHASignal::loop_wavefragment_t::playback_mode_t calibrator_runtime_layer_t::pmode private
The documentation for this class was generated from the following file:
transducers.cpp