openMHA Manual: MHAFilter::partitioned_convolution_t Class Reference
MHAFilter::partitioned_convolution_t Class Reference
A filter class for partitioned convolution.
#include <mha_filter.hh>
Classes
struct index_t
Bookkeeping class.
Public Member Functions
partitioned_convolution_t (unsigned int fragsize, unsigned int nchannels_in, unsigned int nchannels_out, const transfer_matrix_t &transfer)
Create a new partitioned convolver.
~partitioned_convolution_t ()
Free fftw resource allocated in constructor.
mha_wave_t * process (const mha_wave_t *s_in)
processing
Public Attributes
unsigned int fragsize
Audio fragment size, always equal to partition size.
unsigned int nchannels_in
Number of audio input channels.
unsigned int nchannels_out
Number of audio output channels.
unsigned int output_partitions
The maximum number of partitions in any of the impulse responses.
unsigned int filter_partitions
The total number of non-zero impulse response partitions.
MHASignal::waveform_t input_signal_wave
Buffer for input signal.
unsigned int current_input_signal_buffer_half_index
A counter modulo 2.
MHASignal::spectrum_t input_signal_spec
Buffer for FFT transformed input signal.
MHASignal::spectrum_t frequency_response
Buffers for frequency response spectra of impulse response partitions.
std::vector< index_t > bookkeeping
Keeps track of input channels, output channels, impulse response partition, and delay.
std::vector< MHASignal::spectrum_t > output_signal_spec
Buffers for FFT transformed output signal.
unsigned int current_output_partition_index
A counter modulo output_partitions, indexing the "current" output partition.
MHASignal::waveform_t output_signal_wave
Buffer for the wave output signal.
mha_fft_t fft
The FFT transformer.
Detailed Description
A filter class for partitioned convolution.
Impulse responses are partitioned into sections of fragment size. Audio signal is convolved with every partition and delayed as needed. Convolution is done according to overlap-save. FFT length used is 2 times fragment size.
Constructor & Destructor Documentation
MHAFilter::partitioned_convolution_t::partitioned_convolution_t (unsigned int fragsize, unsigned int nchannels_in, unsigned int nchannels_out, const transfer_matrix_t & transfer)
Create a new partitioned convolver.
Parameters
fragsize Audio fragment size, equal to partition size.
nchannels_in Number of input audio channels.
nchannels_out Number of output audio channels.
transfer A sparse matrix of impulse responses.
index into transfer
ammount of delay, in blocks
index into frequency_response and partitions (channel index)
buffer for storing impulse response partitions
References bookkeeping, fft, filter_partitions, fragsize, frequency_response, isempty(), mha_fft_wave2spec(), nchannels_in, nchannels_out, MHAFilter::transfer_matrix_t::partitions(), and MHASignal::waveform_t::value().
Referenced by MHAFilter::transfer_function_t::transfer_function_t().
MHAFilter::partitioned_convolution_t::~partitioned_convolution_t ()
Free fftw resource allocated in constructor.
References fft, and mha_fft_free().
Member Function Documentation
mha_wave_t * MHAFilter::partitioned_convolution_t::process (const mha_wave_t * s_in)
processing
References bookkeeping, clear(), MHASignal::waveform_t::copy_from_at(), current_input_signal_buffer_half_index, current_output_partition_index, fft, filter_partitions, fragsize, frequency_response, input_signal_spec, input_signal_wave, MHA_ErrorMsg, mha_fft_spec2wave(), mha_fft_wave2spec(), nchannels_in, mha_wave_t::num_channels, mha_wave_t::num_frames, output_partitions, output_signal_spec, output_signal_wave, and MHASignal::spectrum_t::value().
Member Data Documentation
unsigned int MHAFilter::partitioned_convolution_t::fragsize
Audio fragment size, always equal to partition size.
Referenced by partitioned_convolution_t(), and process().
unsigned int MHAFilter::partitioned_convolution_t::nchannels_in
Number of audio input channels.
Referenced by partitioned_convolution_t(), and process().
unsigned int MHAFilter::partitioned_convolution_t::nchannels_out
Number of audio output channels.
Referenced by partitioned_convolution_t().
unsigned int MHAFilter::partitioned_convolution_t::output_partitions
The maximum number of partitions in any of the impulse responses.
Determines the size if the delay line.
Referenced by process().
unsigned int MHAFilter::partitioned_convolution_t::filter_partitions
The total number of non-zero impulse response partitions.
Referenced by partitioned_convolution_t(), and process().
MHASignal::waveform_t MHAFilter::partitioned_convolution_t::input_signal_wave
Buffer for input signal.
Has nchannels_in channels and fragsize*2 frames
Referenced by process().
unsigned int MHAFilter::partitioned_convolution_t::current_input_signal_buffer_half_index
A counter modulo 2.
Indicates the buffer half in input signal wave into which to copy the current input signal.
Referenced by process().
MHASignal::spectrum_t MHAFilter::partitioned_convolution_t::input_signal_spec
Buffer for FFT transformed input signal.
Has nchannels_in channels and fragsize+1 frames (fft bins).
Referenced by process().
MHASignal::spectrum_t MHAFilter::partitioned_convolution_t::frequency_response
Buffers for frequency response spectra of impulse response partitions.
Each "channel" contains another partition of some impulse response. The bookkeeping array is used to keep track what to do with these frequency responses. This container has filter_partitions channels and fragsize+1 frames (fft bins).
Referenced by partitioned_convolution_t(), and process().
std::vector<index_t> MHAFilter::partitioned_convolution_t::bookkeeping
Keeps track of input channels, output channels, impulse response partition, and delay.
The index into this array is the same as the "channel" index into the frequency_response array. Array has filter_partitions entries.
Referenced by partitioned_convolution_t(), and process().
std::vector<MHASignal::spectrum_t> MHAFilter::partitioned_convolution_t::output_signal_spec
Buffers for FFT transformed output signal.
For each array member, Number of channels is equal to nchannels_out, number of frames (fft bins) is equal to fragsize+1. Array size is equal to output_partitions.
Referenced by process().
unsigned int MHAFilter::partitioned_convolution_t::current_output_partition_index
A counter modulo output_partitions, indexing the "current" output partition.
Referenced by process().
MHASignal::waveform_t MHAFilter::partitioned_convolution_t::output_signal_wave
Buffer for the wave output signal.
Number of channels is equal to nchannels_out, number of frames is equal to fragsize
Referenced by process().
mha_fft_t MHAFilter::partitioned_convolution_t::fft
The FFT transformer.
Referenced by partitioned_convolution_t(), process(), and ~partitioned_convolution_t().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp