openMHA Manual: MHAFilter::gamma_flt_t Class Reference
MHAFilter::gamma_flt_t Class Reference
Class for gammatone filter.
#include <complex_filter.h>
Public Member Functions
gamma_flt_t (std::vector< mha_real_t > cf, std::vector< mha_real_t > bw, mha_real_t srate, unsigned int order)
Constructor.
~gamma_flt_t ()
void operator() (mha_wave_t &X, mha_spec_t &Y)
Filter method.
void operator() (mha_wave_t &X, mha_wave_t &Yre, mha_wave_t &Yim)
Filter method.
void operator() (mha_wave_t &Yre, mha_wave_t &Yim, unsigned int stage)
Filter method for specific stage.
void phase_correction (unsigned int desired_delay, unsigned int inchannels)
void set_weights (std::vector< mha_complex_t > new_B)
void set_weights (unsigned int stage, std::vector< mha_complex_t > new_B)
std::vector< mha_complex_t > get_weights () const
std::vector< mha_complex_t > get_weights (unsigned int stage) const
std::vector< mha_real_t > get_resynthesis_gain () const
void reset_state ()
const std::vector< mha_complex_t > & get_A ()
std::string inspect () const
Private Attributes
std::vector< mha_complex_t > A
std::vector< complex_bandpass_t > GF
MHASignal::delay_t * delay
std::vector< int > envelope_delay
std::vector< mha_real_t > resynthesis_gain
std::vector< mha_real_t > cf_
std::vector< mha_real_t > bw_
mha_real_t srate_
Detailed Description
Class for gammatone filter.
Constructor & Destructor Documentation
MHAFilter::gamma_flt_t::gamma_flt_t (std::vector< mha_real_t > cf, std::vector< mha_real_t > bw, mha_real_t srate, unsigned int order)
Constructor.
Parameters
cf Center frequency in Hz.
bw Bandwidth in Hz (same number of entries as in cf).
srate Sampling frequency in Hz.
order Filter order.
References MHA_assert.
MHAFilter::gamma_flt_t::~gamma_flt_t ()
References delay.
Member Function Documentation
void MHAFilter::gamma_flt_t::operator() (mha_wave_t & X, mha_spec_t & Y) inline
Filter method.
References MHAFilter::complex_bandpass_t::filter().
Referenced by phase_correction().
void MHAFilter::gamma_flt_t::operator() (mha_wave_t & X, mha_wave_t & Yre, mha_wave_t & Yim) inline
Filter method.
References MHAFilter::complex_bandpass_t::filter().
void MHAFilter::gamma_flt_t::operator() (mha_wave_t & Yre, mha_wave_t & Yim, unsigned int stage) inline
Filter method for specific stage.
References MHAFilter::complex_bandpass_t::set_weights().
void MHAFilter::gamma_flt_t::phase_correction (unsigned int desired_delay, unsigned int inchannels)
References abs(), bw_, cf_, delay, envelope_delay, get_weights(), GF, mha_complex(), normalize(), mha_wave_t::num_frames, mha_spec_t::num_frames, operator()(), reset_state(), resynthesis_gain, set_weights(), srate_, value(), and MHASignal::fft_t::wave2spec().
void MHAFilter::gamma_flt_t::set_weights (std::vector< mha_complex_t > new_B)
References GF.
Referenced by phase_correction().
void MHAFilter::gamma_flt_t::set_weights (unsigned int stage, std::vector< mha_complex_t > new_B)
References GF.
std::vector<mha_complex_t> MHAFilter::gamma_flt_t::get_weights () const inline
Referenced by phase_correction().
std::vector<mha_complex_t> MHAFilter::gamma_flt_t::get_weights (unsigned int stage) const inline
std::vector<mha_real_t> MHAFilter::gamma_flt_t::get_resynthesis_gain () const inline
void MHAFilter::gamma_flt_t::reset_state ()
References delay, envelope_delay, and GF.
Referenced by phase_correction().
const std::vector<mha_complex_t>& MHAFilter::gamma_flt_t::get_A () inline
std::string MHAFilter::gamma_flt_t::inspect () const inline
References MHAParser::StrCnv::val2str().
Member Data Documentation
std::vector<mha_complex_t> MHAFilter::gamma_flt_t::A private
std::vector<complex_bandpass_t> MHAFilter::gamma_flt_t::GF private
Referenced by phase_correction(), reset_state(), and set_weights().
MHASignal::delay_t* MHAFilter::gamma_flt_t::delay private
Referenced by phase_correction(), reset_state(), and ~gamma_flt_t().
std::vector<int> MHAFilter::gamma_flt_t::envelope_delay private
Referenced by phase_correction(), and reset_state().
std::vector<mha_real_t> MHAFilter::gamma_flt_t::resynthesis_gain private
Referenced by phase_correction().
std::vector<mha_real_t> MHAFilter::gamma_flt_t::cf_ private
Referenced by phase_correction().
std::vector<mha_real_t> MHAFilter::gamma_flt_t::bw_ private
Referenced by phase_correction().
mha_real_t MHAFilter::gamma_flt_t::srate_ private
Referenced by phase_correction().
The documentation for this class was generated from the following files:
complex_filter.h
complex_filter.cpp