openMHA Manual: MHAOvlFilter::fftfb_t Class Reference
MHAOvlFilter::fftfb_t Class Reference
FFT based overlapping filter bank.
#include <mha_fftfb.hh>
Public Member Functions
fftfb_t (MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
Constructor for a FFT-based overlapping filter bank.
~fftfb_t ()
void apply_gains (mha_spec_t *s_out, const mha_spec_t *s_in, const mha_wave_t *gains)
void get_fbpower (mha_wave_t *fbpow, const mha_spec_t *s_in)
void get_fbpower_db (mha_wave_t *fbpow, const mha_spec_t *s_in)
std::vector< mha_real_t > get_ltass_gain_db () const
unsigned int bin1 (unsigned int band) const
Return index of first non-zero filter shape window.
unsigned int bin2 (unsigned int band) const
Return index of first zero filter shape window above center frequency.
unsigned int get_fftlen () const
Return fft length.
mha_real_t w (unsigned int k, unsigned int b) const
Return filter shape window at index k in band b.
Public Member Functions inherited from MHAOvlFilter::fspacing_t
fspacing_t (const MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
std::vector< unsigned int > get_cf_fftbin () const
std::vector< mha_real_t > get_cf_hz () const
std::vector< mha_real_t > get_ef_hz () const
unsigned int nbands () const
Return number of bands in filter bank.
Private Attributes
unsigned int * vbin1
unsigned int * vbin2
mha_real_t(* shape)(mha_real_t)
unsigned int fftlen
mha_real_t samplingrate
Private Attributes inherited from mha_wave_t
mha_real_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Additional Inherited Members
Protected Member Functions inherited from MHAOvlFilter::fspacing_t
void fail_on_nonmonotonic_cf ()
void fail_on_unique_fftbins ()
Protected Attributes inherited from MHAOvlFilter::fspacing_t
std::vector< MHAOvlFilter::band_descriptor_t > bands
mha_real_t(* symmetry_scale)(mha_real_t)
Private Member Functions inherited from MHASignal::waveform_t
waveform_t (const unsigned int &frames, const unsigned int &channels)
constructor of waveform_t
waveform_t (const mhaconfig_t &cf)
Constructor to create a waveform from plugin configuration.
waveform_t (const mha_wave_t &src)
Copy contructor for mha_wave_t source.
waveform_t (const MHASignal::waveform_t &src)
Copy contructor.
waveform_t (const std::vector< mha_real_t > &src)
Copy contructor for std::vector<mha_real_t> source.
virtual ~waveform_t (void)
void operator= (const mha_real_t &v)
mha_real_t & operator[] (unsigned int k)
const mha_real_t & operator[] (unsigned int k) const
mha_real_t & value (unsigned int t, unsigned int ch)
Element accessor.
mha_real_t & operator() (unsigned int t, unsigned int ch)
Element accessor.
const mha_real_t & value (unsigned int t, unsigned int ch) const
Constant element accessor.
const mha_real_t & operator() (unsigned int t, unsigned int ch) const
Constant element accessor.
mha_real_t sum (const unsigned int &a, const unsigned int &b)
sum of all elements between [a,b) in all channels
mha_real_t sum (const unsigned int &a, const unsigned int &b, const unsigned int &ch)
sum of all elements between [a,b) in channel ch
mha_real_t sum ()
sum of all elements
mha_real_t sumsqr ()
sum of square of all elements
mha_real_t sum_channel (const unsigned int &)
return sum of all elements in one channel
void assign (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
set frame "k" in channel "ch" to value "val"
void assign (const mha_real_t &)
set all elements to value
void assign_frame (const unsigned int &k, const mha_real_t &val)
assign value "val" to frame k in all channels
void assign_channel (const unsigned int &c, const mha_real_t &val)
assign value "val" to channel ch in all frames
void copy (const std::vector< mha_real_t > &v)
void copy (const mha_wave_t &)
copy data from source into current waveform
void copy (const mha_wave_t *)
void copy_channel (const mha_wave_t &, unsigned int, unsigned int)
Copy one channel of a given waveform signal to a target channel.
void copy_from_at (unsigned int, unsigned int, const mha_wave_t &, unsigned int)
Copy part of the source signal into part of this waveform object.
void export_to (mha_wave_t &)
copy data into allocated mha_wave_t structure
void limit (const mha_real_t &min, const mha_real_t &max)
limit target to range [min,max]
void power (const waveform_t &)
transform waveform signal (in Pa) to squared signal (in W/m^2)
void powspec (const mha_spec_t &)
get the power spectrum (in W/m^2) from a complex spectrum
void scale (const unsigned int &a, const unsigned int &b, const unsigned int &ch, const mha_real_t &val)
scale section [a,b) in channel "ch" by "val"
void scale (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
scale one element
void scale_channel (const unsigned int &, const mha_real_t &)
scale one channel of target with a scalar
void scale_frame (const unsigned int &, const mha_real_t &)
unsigned int get_size () const
Detailed Description
FFT based overlapping filter bank.
Constructor & Destructor Documentation
MHAOvlFilter::fftfb_t::fftfb_t (MHAOvlFilter::fftfb_vars_t & par, unsigned int nfft, mha_real_t fs)
Constructor for a FFT-based overlapping filter bank.
Parameters
par Parameters for the FFT filterbank that can not be deduced from the signal dimensions are taken from this set of configuration variables.
nfft FFT length
fs Sampling rate / Hz
References MHAOvlFilter::fspacing_t::bands, MHAOvlFilter::fftfb_vars_t::cf, MHAOvlFilter::fftfb_vars_t::cLTASS, MHAParser::bool_t::data, MHAParser::float_t::data, MHAParser::vfloat_mon_t::data, MHAParser::mfloat_mon_t::data, MHAOvlFilter::fftfb_vars_t::ef, filtershapefun(), MHAOvlFilter::fspacing_t::get_cf_hz(), MHAOvlFilter::fspacing_t::get_ef_hz(), get_ltass_gain_db(), mha_min_1(), MHAOvlFilter::fspacing_t::nbands(), MHAOvlFilter::fftfb_vars_t::normalize, mha_wave_t::num_channels, mha_wave_t::num_frames, MHAOvlFilter::fftfb_vars_t::plateau, shape, MHAOvlFilter::fftfb_vars_t::shapes, MHASignal::waveform_t::sum(), MHAOvlFilter::fspacing_t::symmetry_scale, MHASignal::waveform_t::value(), vbin1, and vbin2.
MHAOvlFilter::fftfb_t::~fftfb_t ()
Member Function Documentation
void MHAOvlFilter::fftfb_t::apply_gains (mha_spec_t * s_out, const mha_spec_t * s_in, const mha_wave_t * gains)
References mha_complex_t::im, MHA_ErrorMsg, mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, mha_spec_t::num_frames, mha_complex_t::re, and value().
void MHAOvlFilter::fftfb_t::get_fbpower (mha_wave_t * fbpow, const mha_spec_t * s_in)
References abs2(), MHA_ErrorMsg, mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, mha_spec_t::num_frames, and value().
void MHAOvlFilter::fftfb_t::get_fbpower_db (mha_wave_t * fbpow, const mha_spec_t * s_in)
References mha_wave_t::buf, mha_wave_t::num_channels, and mha_wave_t::num_frames.
std::vector< float > MHAOvlFilter::fftfb_t::get_ltass_gain_db () const
References MHAOvlFilter::fftfb_vars_t::f, speechnoise_t::LTASS_combined, MHASignal::max(), mha_fft_free(), mha_fft_new(), mha_fft_wave2spec(), and MHASignal::rmslevel().
Referenced by MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t(), and fftfb_t().
unsigned int MHAOvlFilter::fftfb_t::bin1 (unsigned int band) const inline
Return index of first non-zero filter shape window.
Referenced by MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t(), and fftfilterbank::fftfb_plug_t::process().
unsigned int MHAOvlFilter::fftfb_t::bin2 (unsigned int band) const inline
Return index of first zero filter shape window above center frequency.
Referenced by MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t(), and fftfilterbank::fftfb_plug_t::process().
unsigned int MHAOvlFilter::fftfb_t::get_fftlen () const inline
Return fft length.
Referenced by MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t().
mha_real_t MHAOvlFilter::fftfb_t::w (unsigned int k, unsigned int b) const inline
Return filter shape window at index k in band b.
Parameters
k Frequency index
b Band index
References value().
Referenced by MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t(), MHAOvlFilter::overlap_save_filterbank_t::overlap_save_filterbank_t(), and fftfilterbank::fftfb_plug_t::process().
Member Data Documentation
unsigned int* MHAOvlFilter::fftfb_t::vbin1 private
Referenced by fftfb_t().
unsigned int* MHAOvlFilter::fftfb_t::vbin2 private
Referenced by fftfb_t().
mha_real_t(* MHAOvlFilter::fftfb_t::shape) (mha_real_t) private
Referenced by fftfb_t().
unsigned int MHAOvlFilter::fftfb_t::fftlen private
Referenced by MHAOvlFilter::overlap_save_filterbank_t::overlap_save_filterbank_t().
mha_real_t MHAOvlFilter::fftfb_t::samplingrate private
The documentation for this class was generated from the following files:
mha_fftfb.hh
mha_fftfb.cpp