openMHA Manual: MHAFilter::fftfilterbank_t Class Reference
MHAFilter::fftfilterbank_t Class Reference
FFT based FIR filterbank implementation.
#include <mha_filter.hh>
Public Member Functions
fftfilterbank_t (unsigned int fragsize, unsigned int inputchannels, unsigned int firchannels, unsigned int fftlen)
Constructor.
~fftfilterbank_t ()
void update_coeffs (const mha_wave_t *h)
Update the set of coefficients.
void filter (const mha_wave_t *s_in, mha_wave_t **s_out, const mha_wave_t *h)
Apply filter with changing coefficients to a waveform fragment.
void filter (const mha_wave_t *s_in, mha_wave_t **s_out)
Apply filter to waveform fragment, without changing the coefficients.
const mha_wave_t * get_irs () const
Return the current IRS.
Private Attributes
unsigned int fragsize
unsigned int inputchannels
unsigned int firchannels
unsigned int outputchannels
unsigned int fftlen
MHASignal::waveform_t hw
MHASignal::spectrum_t Hs
MHASignal::waveform_t xw
MHASignal::spectrum_t Xs
MHASignal::waveform_t yw
MHASignal::spectrum_t Ys
MHASignal::waveform_t yw_temp
MHASignal::waveform_t tail
mha_fft_t fft
Detailed Description
FFT based FIR filterbank implementation.
This class convolves n input channels with m filter coefficient sets and returns n*m output channels.
The maximal number of coefficients can be FFT length - fragsize + 1.
Constructor & Destructor Documentation
MHAFilter::fftfilterbank_t::fftfilterbank_t (unsigned int fragsize, unsigned int inputchannels, unsigned int firchannels, unsigned int fftlen)
Constructor.
Parameters
fragsize Number of frames expected in input signal (each cycle).
inputchannels Number of channels expected in input signal.
firchannels Number of channels expected in FIR filter coefficients (= number of bands).
fftlen FFT length of filter.
The number of output channels is inputchannels*firchannels.
References fft, fftlen, fragsize, and mha_fft_new().
MHAFilter::fftfilterbank_t::~fftfilterbank_t ()
References fft, and mha_fft_free().
Member Function Documentation
void MHAFilter::fftfilterbank_t::update_coeffs (const mha_wave_t * h)
Update the set of coefficients.
Parameters
h Coefficients structure
Note
The number of channels in h must match the number of channels given in the constructor, and the number of frames can not be more than fftlen-fragsize+1.
References clear(), MHASignal::waveform_t::copy_from_at(), fft, fftlen, fragsize, Hs, hw, mha_fft_wave2spec(), and mha_wave_t::num_frames.
Referenced by filter(), MHAOvlFilter::overlap_save_filterbank_analytic_t::overlap_save_filterbank_analytic_t(), and MHAOvlFilter::overlap_save_filterbank_t::overlap_save_filterbank_t().
void MHAFilter::fftfilterbank_t::filter (const mha_wave_t * s_in, mha_wave_t ** s_out, const mha_wave_t * h)
Apply filter with changing coefficients to a waveform fragment.
Parameters
s_in Input signal pointer.
Return values
s_out Pointer to output signal pointer, will be set to a valid signal
Parameters
h FIR coefficients
References update_coeffs().
Referenced by MHAOvlFilter::overlap_save_filterbank_analytic_t::filter_analytic(), and fftfilterbank::fftfb_plug_t::process().
void MHAFilter::fftfilterbank_t::filter (const mha_wave_t * s_in, mha_wave_t ** s_out)
Apply filter to waveform fragment, without changing the coefficients.
Parameters
s_in Input signal pointer.
Return values
s_out Pointer to output signal pointer, will be set to a valid signal
References clear(), MHASignal::waveform_t::copy_from_at(), fft, fftlen, firchannels, fragsize, Hs, inputchannels, MHASignal::max(), mha_fft_spec2wave(), mha_fft_wave2spec(), MHASignal::min(), mha_wave_t::num_frames, mha_spec_t::num_frames, outputchannels, tail, MHAFilter::transfer_function_t::transfer_function_t(), MHASignal::waveform_t::value(), Xs, xw, Ys, yw, and yw_temp.
const mha_wave_t* MHAFilter::fftfilterbank_t::get_irs () const inline
Return the current IRS.
Referenced by MHAOvlFilter::overlap_save_filterbank_analytic_t::overlap_save_filterbank_analytic_t().
Member Data Documentation
unsigned int MHAFilter::fftfilterbank_t::fragsize private
Referenced by fftfilterbank_t(), filter(), and update_coeffs().
unsigned int MHAFilter::fftfilterbank_t::inputchannels private
Referenced by filter().
unsigned int MHAFilter::fftfilterbank_t::firchannels private
Referenced by filter().
unsigned int MHAFilter::fftfilterbank_t::outputchannels private
Referenced by filter().
unsigned int MHAFilter::fftfilterbank_t::fftlen private
Referenced by fftfilterbank_t(), filter(), and update_coeffs().
MHASignal::waveform_t MHAFilter::fftfilterbank_t::hw private
Referenced by update_coeffs().
MHASignal::spectrum_t MHAFilter::fftfilterbank_t::Hs private
Referenced by filter(), and update_coeffs().
MHASignal::waveform_t MHAFilter::fftfilterbank_t::xw private
Referenced by filter().
MHASignal::spectrum_t MHAFilter::fftfilterbank_t::Xs private
Referenced by filter().
MHASignal::waveform_t MHAFilter::fftfilterbank_t::yw private
Referenced by filter().
MHASignal::spectrum_t MHAFilter::fftfilterbank_t::Ys private
Referenced by filter().
MHASignal::waveform_t MHAFilter::fftfilterbank_t::yw_temp private
Referenced by filter().
MHASignal::waveform_t MHAFilter::fftfilterbank_t::tail private
Referenced by filter().
mha_fft_t MHAFilter::fftfilterbank_t::fft private
Referenced by fftfilterbank_t(), filter(), update_coeffs(), and ~fftfilterbank_t().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp