openMHA Manual: MHAJack::client_t Class Reference
MHAJack::client_t Class Reference
Generic asynchronous JACK client.
#include <mhajack.h>
Public Member Functions
client_t (IOProcessEvent_t proc_event, void *proc_handle=NULL, IOStartedEvent_t start_event=NULL, void *start_handle=NULL, IOStoppedEvent_t stop_event=NULL, void *stop_handle=NULL, bool use_jack_transport=false)
void prepare (const std::string &client_name, const unsigned int &nchannels_in, const unsigned int &nchannels_out)
Allocate buffers, activate JACK client and install internal ports.
void prepare (const std::string &server_name, const std::string &client_name, const unsigned int &nchannels_in, const unsigned int &nchannels_out)
Allocate buffers, ports, and activates JACK client.
void release ()
Remove JACK client and deallocate internal ports and buffers.
void start (bool fail_on_async_jack_error=true)
void stop ()
void connect_input (const std::vector< std::string > &)
Connect the input ports when connection variable is accessed.
void connect_output (const std::vector< std::string > &)
Connect the output ports when connection variable is accessed.
unsigned int get_fragsize () const
float get_srate () const
unsigned long get_xruns ()
unsigned long get_xruns_reset ()
std::string str_error (int err)
void get_ports (std::vector< std::string > &, unsigned long jack_flags)
Get a list of Jack ports.
std::vector< std::string > get_my_input_ports ()
std::vector< std::string > get_my_output_ports ()
void set_input_portnames (const std::vector< std::string > &)
void set_output_portnames (const std::vector< std::string > &)
float get_cpu_load ()
void set_use_jack_transport (bool ut)
Protected Attributes
jack_client_t * jc
Private Member Functions
void prepare_impl (const char *server_name, const char *client_name, const unsigned int &nchannels_in, const unsigned int &nchannels_out)
void internal_start ()
void internal_stop ()
void stopped (int, int)
int jack_proc_cb (jack_nframes_t)
This is the main processing callback.
int jack_xrun_cb ()
Static Private Member Functions
static int jack_proc_cb (jack_nframes_t, void *)
static int jack_xrun_cb (void *)
Private Attributes
unsigned long num_xruns
unsigned int fragsize
float samplerate
unsigned int nchannels_in
unsigned int nchannels_out
IOProcessEvent_t proc_event
void * proc_handle
IOStartedEvent_t start_event
void * start_handle
IOStoppedEvent_t stop_event
void * stop_handle
MHASignal::waveform_t * s_in
mha_wave_t * s_out
MHAJack::port_t ** inch
MHAJack::port_t ** outch
unsigned int flags
bool b_prepared
bool use_jack_transport
jack_transport_state_t jstate_prev
std::vector< std::string > input_portnames
std::vector< std::string > output_portnames
bool fail_on_async_jackerror
Detailed Description
Generic asynchronous JACK client.
Constructor & Destructor Documentation
MHAJack::client_t::client_t (IOProcessEvent_t proc_event, void * proc_handle = NULL, IOStartedEvent_t start_event = NULL, void * start_handle = NULL, IOStoppedEvent_t stop_event = NULL, void * stop_handle = NULL, bool use_jack_transport = false)
Member Function Documentation
void MHAJack::client_t::prepare (const std::string & client_name, const unsigned int & nch_in, const unsigned int & nch_out)
Allocate buffers, activate JACK client and install internal ports.
Registers the jack client with the default jack server and activates it.
Parameters
client_name Name of this jack client
nch_in Input ports to register
nch_out Output ports to register
Referenced by MHAJack::client_noncont_t::io(), MHAJack::client_avg_t::io(), and MHAIOJack::io_jack_t::prepare().
void MHAJack::client_t::prepare (const std::string & server_name, const std::string & client_name, const unsigned int & nch_in, const unsigned int & nch_out)
Allocate buffers, ports, and activates JACK client.
Registers the jack client with specified jack server and activates it.
Parameters
server_name Name of the jack server to register with
client_name Name of this jack client
nch_in Input ports to register
nch_out Output ports to register
void MHAJack::client_t::release ()
Remove JACK client and deallocate internal ports and buffers.
References dummy_jack_proc_cb(), and MHAJack::port_t::jc.
Referenced by MHAJack::client_noncont_t::io(), MHAJack::client_avg_t::io(), and MHAIOJack::io_jack_t::release().
void MHAJack::client_t::start (bool fail_on_async_jack_error = true)
References b_prepared, fail_on_async_jackerror, internal_start(), jc, and use_jack_transport.
Referenced by MHAJack::client_noncont_t::io(), and MHAJack::client_avg_t::io().
void MHAJack::client_t::stop ()
References internal_stop(), jc, and use_jack_transport.
Referenced by MHAJack::client_noncont_t::io(), and MHAJack::client_avg_t::io().
void MHAJack::client_t::connect_input (const std::vector< std::string > & con)
Connect the input ports when connection variable is accessed.
References b_prepared, MHAJack::port_t::connect_to(), inch, MHA_ErrorMsg, and nchannels_in.
Referenced by MHAJack::client_noncont_t::io(), MHAJack::client_avg_t::io(), and MHAIOJack::io_jack_t::reconnect_inports().
void MHAJack::client_t::connect_output (const std::vector< std::string > & con)
Connect the output ports when connection variable is accessed.
References b_prepared, MHAJack::port_t::connect_to(), MHA_ErrorMsg, nchannels_out, and outch.
Referenced by MHAJack::client_noncont_t::io(), MHAJack::client_avg_t::io(), and MHAIOJack::io_jack_t::reconnect_outports().
unsigned int MHAJack::client_t::get_fragsize () const inline
Referenced by MHAJack::client_noncont_t::io(), MHAJack::client_avg_t::io(), MHAJack::io(), MHAIOJack::io_jack_t::prepare(), MHAJack::client_noncont_t::proc(), and MHAJack::client_avg_t::proc().
float MHAJack::client_t::get_srate () const inline
Referenced by MHAJack::client_noncont_t::io(), MHAJack::client_avg_t::io(), MHAJack::io(), and MHAIOJack::io_jack_t::prepare().
unsigned long MHAJack::client_t::get_xruns () inline
Referenced by MHAIOJack::io_jack_t::read_get_xruns().
unsigned long MHAJack::client_t::get_xruns_reset ()
References num_xruns.
std::string MHAJack::client_t::str_error (int err)
References IO_ERROR_JACK, IO_ERROR_MHAJACKLIB, and last_jack_err_msg.
void MHAJack::client_t::get_ports (std::vector< std::string > & res, unsigned long jack_flags)
Get a list of Jack ports.
Parameters
res Result string vector
jack_flags Jack port flags (JackPortInput etc.)
References jc.
Referenced by MHAIOJack::io_jack_t::get_all_input_ports(), MHAIOJack::io_jack_t::get_all_output_ports(), MHAIOJack::io_jack_t::get_physical_input_ports(), and MHAIOJack::io_jack_t::get_physical_output_ports().
std::vector< std::string > MHAJack::client_t::get_my_input_ports ()
References inch, and nchannels_in.
Referenced by MHAIOJack::io_jack_t::prepare().
std::vector< std::string > MHAJack::client_t::get_my_output_ports ()
References nchannels_out, and outch.
Referenced by MHAIOJack::io_jack_t::prepare().
void MHAJack::client_t::set_input_portnames (const std::vector< std::string > & names)
References input_portnames.
Referenced by MHAIOJack::io_jack_t::prepare().
void MHAJack::client_t::set_output_portnames (const std::vector< std::string > & names)
References output_portnames.
Referenced by MHAIOJack::io_jack_t::prepare().
float MHAJack::client_t::get_cpu_load ()
References jc.
Referenced by MHAIOJack::io_jack_t::read_get_cpu_load().
void MHAJack::client_t::set_use_jack_transport (bool ut) inline
void MHAJack::client_t::prepare_impl (const char * server_name, const char * client_name, const unsigned int & nch_in, const unsigned int & nch_out) private
Allocate buffers, activate JACK client and allocates jack ports Registers the jack client with the given server and activates it.
Parameters
server_name Name of the jack server to register with
client_name Name of this jack client
nch_in Input ports to register
nch_out Output ports to register
References MHAJack::port_t::input, jack_error_handler(), MHAJack::port_t::jc, last_jack_err, last_jack_err_msg, MHA_ErrorMsg, MHAJACK_STOPPED, and MHAJack::port_t::output.
void MHAJack::client_t::internal_start () private
References flags, MHAJACK_FW_STARTED, and MHAJACK_STARTING.
Referenced by jack_proc_cb(), and start().
void MHAJack::client_t::internal_stop () private
References flags, and MHAJACK_FW_STARTED.
Referenced by jack_proc_cb(), and stop().
void MHAJack::client_t::stopped (int proc_err, int io_err) private
References flags, MHAJACK_FW_STARTED, MHAJACK_STOPPED, stop_event, and stop_handle.
Referenced by jack_proc_cb().
int MHAJack::client_t::jack_proc_cb (jack_nframes_t n, void * h) static private
int MHAJack::client_t::jack_proc_cb (jack_nframes_t n) private
This is the main processing callback.
Here happens double buffering and downsampling.
References b_prepared, fail_on_async_jackerror, flags, Getmsg, inch, internal_start(), internal_stop(), IO_ERROR_MHAJACKLIB, jc, jstate_prev, last_jack_err, last_jack_err_msg, MAX_USER_ERR, MHAJACK_FW_STARTED, MHAJACK_STARTING, MHAJACK_STOPPED, nchannels_in, nchannels_out, mha_wave_t::num_channels, mha_wave_t::num_frames, outch, proc_event, proc_handle, s_in, s_out, start_event, start_handle, stopped(), and use_jack_transport.
int MHAJack::client_t::jack_xrun_cb (void * h) static private
int MHAJack::client_t::jack_xrun_cb () inline private
Member Data Documentation
unsigned long MHAJack::client_t::num_xruns private
Referenced by get_xruns_reset().
unsigned int MHAJack::client_t::fragsize private
float MHAJack::client_t::samplerate private
unsigned int MHAJack::client_t::nchannels_in private
Referenced by connect_input(), get_my_input_ports(), and jack_proc_cb().
unsigned int MHAJack::client_t::nchannels_out private
Referenced by connect_output(), get_my_output_ports(), and jack_proc_cb().
IOProcessEvent_t MHAJack::client_t::proc_event private
Referenced by jack_proc_cb().
void* MHAJack::client_t::proc_handle private
Referenced by jack_proc_cb().
IOStartedEvent_t MHAJack::client_t::start_event private
Referenced by jack_proc_cb().
void* MHAJack::client_t::start_handle private
Referenced by jack_proc_cb().
IOStoppedEvent_t MHAJack::client_t::stop_event private
Referenced by stopped().
void* MHAJack::client_t::stop_handle private
Referenced by stopped().
MHASignal::waveform_t* MHAJack::client_t::s_in private
Referenced by jack_proc_cb().
mha_wave_t* MHAJack::client_t::s_out private
Referenced by jack_proc_cb().
MHAJack::port_t** MHAJack::client_t::inch private
Referenced by connect_input(), get_my_input_ports(), and jack_proc_cb().
MHAJack::port_t** MHAJack::client_t::outch private
Referenced by connect_output(), get_my_output_ports(), and jack_proc_cb().
jack_client_t* MHAJack::client_t::jc protected
Referenced by get_cpu_load(), get_ports(), jack_proc_cb(), MHAIOJack::io_jack_t::read_get_scheduler(), start(), and stop().
unsigned int MHAJack::client_t::flags private
Referenced by internal_start(), internal_stop(), jack_proc_cb(), and stopped().
bool MHAJack::client_t::b_prepared private
Referenced by connect_input(), connect_output(), jack_proc_cb(), and start().
bool MHAJack::client_t::use_jack_transport private
Referenced by jack_proc_cb(), start(), and stop().
jack_transport_state_t MHAJack::client_t::jstate_prev private
Referenced by jack_proc_cb().
std::vector<std::string> MHAJack::client_t::input_portnames private
Referenced by set_input_portnames().
std::vector<std::string> MHAJack::client_t::output_portnames private
Referenced by set_output_portnames().
bool MHAJack::client_t::fail_on_async_jackerror private
Referenced by jack_proc_cb(), and start().
The documentation for this class was generated from the following files:
mhajack.h
mhajack.cpp