openMHA Manual: MHAFilter::fftfilter_t Class Reference
MHAFilter::fftfilter_t Class Reference
FFT based FIR filter implementation.
#include <mha_filter.hh>
Public Member Functions
fftfilter_t (unsigned int fragsize, unsigned int channels, unsigned int fftlen)
Constructor.
~fftfilter_t ()
void update_coeffs (const mha_wave_t *pwIRS)
Update the set of coefficients.
void filter (const mha_wave_t *pwIn, mha_wave_t **ppwOut, const mha_wave_t *pwIRS)
Apply filter with changing coefficients to a waveform fragment.
void filter (const mha_wave_t *pwIn, mha_wave_t **ppwOut)
Apply filter to waveform fragment, without changing the coefficients.
void filter (const mha_wave_t *pwIn, mha_wave_t **ppwOut, const mha_spec_t *psWeights)
Apply filter with changing coefficients to a waveform fragment.
Private Attributes
unsigned int fragsize
unsigned int channels
unsigned int fftlen
MHASignal::waveform_t wInput_fft
mha_wave_t wInput
MHASignal::waveform_t wOutput_fft
mha_wave_t wOutput
MHASignal::spectrum_t sInput
MHASignal::spectrum_t sWeights
MHASignal::waveform_t wIRS_fft
mha_fft_t fft
Detailed Description
FFT based FIR filter implementation.
The maximal number of coefficients can be FFT length - fragsize + 1.
Constructor & Destructor Documentation
MHAFilter::fftfilter_t::fftfilter_t (unsigned int fragsize, unsigned int channels, unsigned int fftlen)
Constructor.
Parameters
fragsize Number of frames expected in input signal (each cycle).
channels Number of channels expected in input signal.
fftlen FFT length of filter.
References fft, fftlen, fragsize, and mha_fft_new().
MHAFilter::fftfilter_t::~fftfilter_t ()
References fft, and mha_fft_free().
Member Function Documentation
void MHAFilter::fftfilter_t::update_coeffs (const mha_wave_t * pwIRS)
Update the set of coefficients.
Parameters
pwIRS Coefficients structure
Note
The number of channels in h must match the number of channels given in the constructor. The filter length is limited to fftlen-fragsize+1 (longer IRS will be shortened).
References assign(), clear(), fft, fftlen, fragsize, mha_fft_wave2spec(), MHASignal::min(), mha_wave_t::num_frames, range(), sWeights, and wIRS_fft.
Referenced by calibrator_runtime_layer_t::calibrator_runtime_layer_t(), filter(), and MHAFilter::resampling_filter_t::resampling_filter_t().
void MHAFilter::fftfilter_t::filter (const mha_wave_t * pwIn, mha_wave_t ** ppwOut, const mha_wave_t * pwIRS)
Apply filter with changing coefficients to a waveform fragment.
Parameters
pwIn Input signal pointer.
Return values
ppwOut Pointer to output signal pointer, will be set to a valid signal.
Parameters
pwIRS Pointer to FIR coefficients structure.
References sWeights, and update_coeffs().
Referenced by filter().
void MHAFilter::fftfilter_t::filter (const mha_wave_t * pwIn, mha_wave_t ** ppwOut)
Apply filter to waveform fragment, without changing the coefficients.
Parameters
pwIn Input signal pointer.
Return values
ppwOut Pointer to output signal pointer, will be set to a valid signal
References filter(), and sWeights.
void MHAFilter::fftfilter_t::filter (const mha_wave_t * pwIn, mha_wave_t ** ppwOut, const mha_spec_t * psWeights)
Apply filter with changing coefficients to a waveform fragment.
Parameters
pwIn Input signal pointer.
Return values
ppwOut Pointer to output signal pointer, will be set to a valid signal.
Parameters
psWeights Pointer to filter weights structure.
References assign(), fft, fragsize, mha_fft_spec2wave(), mha_fft_wave2spec(), sInput, timeshift(), wInput, wInput_fft, wOutput, and wOutput_fft.
Member Data Documentation
unsigned int MHAFilter::fftfilter_t::fragsize private
Referenced by fftfilter_t(), filter(), and update_coeffs().
unsigned int MHAFilter::fftfilter_t::channels private
unsigned int MHAFilter::fftfilter_t::fftlen private
Referenced by fftfilter_t(), and update_coeffs().
MHASignal::waveform_t MHAFilter::fftfilter_t::wInput_fft private
Referenced by filter().
mha_wave_t MHAFilter::fftfilter_t::wInput private
Referenced by filter().
MHASignal::waveform_t MHAFilter::fftfilter_t::wOutput_fft private
Referenced by filter().
mha_wave_t MHAFilter::fftfilter_t::wOutput private
Referenced by filter().
MHASignal::spectrum_t MHAFilter::fftfilter_t::sInput private
Referenced by filter().
MHASignal::spectrum_t MHAFilter::fftfilter_t::sWeights private
Referenced by filter(), and update_coeffs().
MHASignal::waveform_t MHAFilter::fftfilter_t::wIRS_fft private
Referenced by update_coeffs().
mha_fft_t MHAFilter::fftfilter_t::fft private
Referenced by fftfilter_t(), filter(), update_coeffs(), and ~fftfilter_t().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp