openMHA Manual: MHAFilter::complex_bandpass_t Class Reference
MHAFilter::complex_bandpass_t Class Reference
Complex bandpass filter.
#include <complex_filter.h>
Public Member Functions
complex_bandpass_t (std::vector< mha_complex_t > A, std::vector< mha_complex_t > B)
Constructor with filter coefficients (one per channel)
void set_state (mha_real_t val)
void set_state (std::vector< mha_real_t > val)
void set_state (mha_complex_t val)
void set_weights (std::vector< mha_complex_t > new_B)
Allow to modify the input weights at a later stage.
std::vector< mha_complex_t > get_weights () const
void filter (const mha_wave_t &X, mha_spec_t &Y)
Filter method for real value input.
void filter (const mha_wave_t &X, mha_wave_t &Yre, mha_wave_t &Yim)
Filter method for real value input.
void filter (const mha_spec_t &X, mha_spec_t &Y)
Filter method for complex value input.
void filter (const mha_wave_t &Xre, const mha_wave_t &Xim, mha_wave_t &Yre, mha_wave_t &Yim)
Filter method for complex value input.
std::string inspect () const
Static Public Member Functions
static std::vector< mha_complex_t > creator_A (std::vector< mha_real_t > cf, std::vector< mha_real_t > bw, mha_real_t srate, unsigned int order)
static std::vector< mha_complex_t > creator_B (std::vector< mha_complex_t > A, unsigned int order)
Private Attributes
std::vector< mha_complex_t > A_
std::vector< mha_complex_t > B_
std::vector< mha_complex_t > Yn
Detailed Description
Complex bandpass filter.
Constructor & Destructor Documentation
MHAFilter::complex_bandpass_t::complex_bandpass_t (std::vector< mha_complex_t > A, std::vector< mha_complex_t > B)
Constructor with filter coefficients (one per channel)
Parameters
A complex filter coefficients, one per band
B complex weights
Member Function Documentation
std::vector< mha_complex_t > MHAFilter::complex_bandpass_t::creator_A (std::vector< mha_real_t > cf, std::vector< mha_real_t > bw, mha_real_t srate, unsigned int order) static
References expi(), M_PI, and MHA_assert_equal.
std::vector< mha_complex_t > MHAFilter::complex_bandpass_t::creator_B (std::vector< mha_complex_t > A, unsigned int order) static
References abs(), and mha_complex().
void MHAFilter::complex_bandpass_t::set_state (mha_real_t val)
References mha_complex().
void MHAFilter::complex_bandpass_t::set_state (std::vector< mha_real_t > val)
References MHA_assert_equal, and mha_complex().
void MHAFilter::complex_bandpass_t::set_state (mha_complex_t val)
void MHAFilter::complex_bandpass_t::set_weights (std::vector< mha_complex_t > new_B)
Allow to modify the input weights at a later stage.
References B_, and MHA_assert_equal.
Referenced by MHAFilter::gamma_flt_t::operator()().
std::vector<mha_complex_t> MHAFilter::complex_bandpass_t::get_weights () const inline
References B_.
void MHAFilter::complex_bandpass_t::filter (const mha_wave_t & X, mha_spec_t & Y) inline
Filter method for real value input.
References A_, B_, MHA_assert_equal, mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, mha_spec_t::num_frames, value(), and Yn.
Referenced by MHAFilter::gamma_flt_t::operator()().
void MHAFilter::complex_bandpass_t::filter (const mha_wave_t & X, mha_wave_t & Yre, mha_wave_t & Yim) inline
Filter method for real value input.
References A_, B_, MHA_assert_equal, mha_wave_t::num_channels, mha_wave_t::num_frames, value(), and Yn.
void MHAFilter::complex_bandpass_t::filter (const mha_spec_t & X, mha_spec_t & Y) inline
Filter method for complex value input.
References A_, B_, MHA_assert_equal, mha_spec_t::num_channels, mha_spec_t::num_frames, value(), and Yn.
void MHAFilter::complex_bandpass_t::filter (const mha_wave_t & Xre, const mha_wave_t & Xim, mha_wave_t & Yre, mha_wave_t & Yim) inline
Filter method for complex value input.
References A_, B_, mha_complex_t::im, MHA_assert_equal, mha_wave_t::num_channels, mha_wave_t::num_frames, mha_complex_t::re, value(), and Yn.
std::string MHAFilter::complex_bandpass_t::inspect () const inline
References A_, B_, MHAParser::StrCnv::val2str(), and Yn.
Member Data Documentation
std::vector<mha_complex_t> MHAFilter::complex_bandpass_t::A_ private
Referenced by filter(), and inspect().
std::vector<mha_complex_t> MHAFilter::complex_bandpass_t::B_ private
Referenced by filter(), get_weights(), inspect(), and set_weights().
std::vector<mha_complex_t> MHAFilter::complex_bandpass_t::Yn private
Referenced by filter(), and inspect().
The documentation for this class was generated from the following files:
complex_filter.h
complex_filter.cpp