openMHA Manual: MHAFilter::polyphase_resampling_t Class Reference
MHAFilter::polyphase_resampling_t Class Reference
A class that does polyphase resampling.
#include <mha_filter.hh>
Public Member Functions
polyphase_resampling_t (unsigned n_up, unsigned n_down, mha_real_t nyquist_ratio, unsigned n_irs, unsigned n_ringbuffer, unsigned n_channels, unsigned n_prefill)
Initialize a polyphase resampler.
void write (mha_wave_t &signal)
Write signal to the ringbuffer.
void read (mha_wave_t &signal)
Read resampled signal.
unsigned readable_frames () const
Number of frames at target sampling rate that can be produced.
Private Attributes
unsigned upsampling_factor
Interpolation rate / source rate.
unsigned downsampling_factor
Interpolation rate / target rate.
unsigned now_index
points to "now" in the interpolated sampling rate
bool underflow
indicates if an underflow has occurred. Object cannot be used then.
MHAWindow::hanning_t impulse_response
contains the lowpass impulse response at interpolation rate
MHASignal::ringbuffer_t ringbuffer
storage of input signal
Detailed Description
A class that does polyphase resampling.
Constructor & Destructor Documentation
MHAFilter::polyphase_resampling_t::polyphase_resampling_t (unsigned n_up, unsigned n_down, mha_real_t nyquist_ratio, unsigned n_irs, unsigned n_ringbuffer, unsigned n_channels, unsigned n_prefill)
Initialize a polyphase resampler.
Parameters
n_up upsampling factor
n_down downsampling factor
nyquist_ratio low pass filter cutoff frequency relative to the nyquist frequency of the smaller of the two sampling rates. Example values: 0.8, 0.9
n_irs length of impulse response (in samples at interpolation rate)
n_ringbuffer length of ringbuffer, in samples at source sampling rate
n_channels audio channels count
n_prefill Prefill the ringbuffer with this many zero frames in samples at source sampling rate
References M_PI, MHASignal::max(), and MHAFilter::sinc().
Referenced by MHAFilter::resampling_factors().
Member Function Documentation
void MHAFilter::polyphase_resampling_t::write (mha_wave_t & signal)
Write signal to the ringbuffer.
Parameters
signal input signal in original sampling rate
Exceptions
MHA_Error Raises exception if there is not enough room or if the number of channels does not match.
Referenced by MHAFilter::blockprocessing_polyphase_resampling_t::blockprocessing_polyphase_resampling_t(), and MHAFilter::blockprocessing_polyphase_resampling_t::write().
void MHAFilter::polyphase_resampling_t::read (mha_wave_t & signal)
Read resampled signal.
Will perform the resampling and remove no longer needed samples from the input buffer.
Parameters
signal buffer to write the resampled signal to.
Exceptions
MHA_Error Raises exception if there is not enough input signal or if the number of channels is too high.
References assign(), MHAFilter::blockprocessing_polyphase_resampling_t::blockprocessing_polyphase_resampling_t(), mha_wave_t::num_channels, mha_wave_t::num_frames, and value().
Referenced by MHAFilter::blockprocessing_polyphase_resampling_t::read().
unsigned MHAFilter::polyphase_resampling_t::readable_frames () const inline
Number of frames at target sampling rate that can be produced.
Warning: This method only checks for enough future samples present, therefore, this number can be positive and a read operation can still fail if there are not enough past samples present to perform the filtering for the first output sample.
References MHASignal::ringbuffer_t::contained_frames().
Referenced by MHAFilter::blockprocessing_polyphase_resampling_t::can_read().
Member Data Documentation
unsigned MHAFilter::polyphase_resampling_t::upsampling_factor private
Interpolation rate / source rate.
unsigned MHAFilter::polyphase_resampling_t::downsampling_factor private
Interpolation rate / target rate.
unsigned MHAFilter::polyphase_resampling_t::now_index private
points to "now" in the interpolated sampling rate
bool MHAFilter::polyphase_resampling_t::underflow private
indicates if an underflow has occurred. Object cannot be used then.
MHAWindow::hanning_t MHAFilter::polyphase_resampling_t::impulse_response private
contains the lowpass impulse response at interpolation rate
MHASignal::ringbuffer_t MHAFilter::polyphase_resampling_t::ringbuffer private
storage of input signal
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp