openMHA Manual: MHAJack::client_noncont_t Class Reference
MHAJack::client_noncont_t Class Reference
Generic client for synchronous playback and recording of waveform fragments.
#include <mhajack.h>
Public Member Functions
client_noncont_t (const std::string &name, bool use_jack_transport=false)
void io (mha_wave_t *s_out, mha_wave_t *s_in, const std::vector< std::string > &p_out, const std::vector< std::string > &p_in, float *srate=NULL, unsigned int *fragsize=NULL)
Public Member Functions inherited from MHAJack::client_t
client_t (IOProcessEvent_t proc_event, void *proc_handle=NULL, IOStartedEvent_t start_event=NULL, void *start_handle=NULL, IOStoppedEvent_t stop_event=NULL, void *stop_handle=NULL, bool use_jack_transport=false)
void prepare (const std::string &client_name, const unsigned int &nchannels_in, const unsigned int &nchannels_out)
Allocate buffers, activate JACK client and install internal ports.
void prepare (const std::string &server_name, const std::string &client_name, const unsigned int &nchannels_in, const unsigned int &nchannels_out)
Allocate buffers, ports, and activates JACK client.
void release ()
Remove JACK client and deallocate internal ports and buffers.
void start (bool fail_on_async_jack_error=true)
void stop ()
void connect_input (const std::vector< std::string > &)
Connect the input ports when connection variable is accessed.
void connect_output (const std::vector< std::string > &)
Connect the output ports when connection variable is accessed.
unsigned int get_fragsize () const
float get_srate () const
unsigned long get_xruns ()
unsigned long get_xruns_reset ()
std::string str_error (int err)
void get_ports (std::vector< std::string > &, unsigned long jack_flags)
Get a list of Jack ports.
std::vector< std::string > get_my_input_ports ()
std::vector< std::string > get_my_output_ports ()
void set_input_portnames (const std::vector< std::string > &)
void set_output_portnames (const std::vector< std::string > &)
float get_cpu_load ()
void set_use_jack_transport (bool ut)
Private Member Functions
void proc (mha_wave_t *sIn, mha_wave_t **sOut)
void IOStoppedEvent ()
Static Private Member Functions
static int proc (void *handle, mha_wave_t *sIn, mha_wave_t **sOut)
static void IOStoppedEvent (void *handle, int proc_err, int io_err)
Private Attributes
bool b_stopped
unsigned int pos
mha_wave_t * sn_in
mha_wave_t * sn_out
std::string name
MHASignal::waveform_t * frag_out
Additional Inherited Members
Protected Attributes inherited from MHAJack::client_t
jack_client_t * jc
Detailed Description
Generic client for synchronous playback and recording of waveform fragments.
Constructor & Destructor Documentation
MHAJack::client_noncont_t::client_noncont_t (const std::string & name, bool use_jack_transport = false)
Member Function Documentation
void MHAJack::client_noncont_t::io (mha_wave_t * s_out, mha_wave_t * s_in, const std::vector< std::string > & p_out, const std::vector< std::string > & p_in, float * srate = NULL, unsigned int * fragsize = NULL)
References b_stopped, CHECK_VAR, MHAJack::client_t::connect_input(), MHAJack::client_t::connect_output(), frag_out, MHAJack::client_t::get_fragsize(), MHAJack::client_t::get_srate(), MHASignal::max(), name, mha_wave_t::num_channels, mha_wave_t::num_frames, pos, MHAJack::client_t::prepare(), MHAJack::client_t::release(), sn_in, sn_out, MHAJack::client_t::start(), and MHAJack::client_t::stop().
Referenced by MHAJack::io().
int MHAJack::client_noncont_t::proc (void * handle, mha_wave_t * sIn, mha_wave_t ** sOut) static private
void MHAJack::client_noncont_t::IOStoppedEvent (void * handle, int proc_err, int io_err) static private
References IOStoppedEvent().
void MHAJack::client_noncont_t::proc (mha_wave_t * sIn, mha_wave_t ** sOut) private
References b_stopped, CHECK_EXPR, frag_out, MHAJack::client_t::get_fragsize(), MHASignal::max(), MHASignal::min(), mha_wave_t::num_channels, mha_wave_t::num_frames, pos, sn_in, sn_out, and value().
void MHAJack::client_noncont_t::IOStoppedEvent () private
References b_stopped.
Referenced by IOStoppedEvent().
Member Data Documentation
bool MHAJack::client_noncont_t::b_stopped private
Referenced by io(), IOStoppedEvent(), and proc().
unsigned int MHAJack::client_noncont_t::pos private
Referenced by io(), and proc().
mha_wave_t* MHAJack::client_noncont_t::sn_in private
Referenced by io(), and proc().
mha_wave_t* MHAJack::client_noncont_t::sn_out private
Referenced by io(), and proc().
std::string MHAJack::client_noncont_t::name private
Referenced by io().
MHASignal::waveform_t* MHAJack::client_noncont_t::frag_out private
Referenced by io(), and proc().
The documentation for this class was generated from the following files:
mhajack.h
mhajack.cpp