openMHA Manual: MHAParser::monitor_t Class Reference
MHAParser::monitor_t Class Reference
Base class for monitors and variable nodes.
#include <mha_parser.hh>
Public Member Functions
monitor_t (const std::string &)
monitor_t (const monitor_t &)
std::string op_query (expression_t &)
std::string query_dump (const std::string &)
std::string query_perm (const std::string &)
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string op_subparse (expression_t &)
virtual std::string op_setval (expression_t &)
virtual std::string query_entries (const std::string &)
virtual std::string query_range (const std::string &)
virtual std::string query_type (const std::string &)
virtual std::string query_val (const std::string &)
virtual std::string query_readfile (const std::string &)
virtual std::string query_savefile (const std::string &)
virtual std::string query_savefile_compact (const std::string &)
virtual std::string query_savemons (const std::string &)
virtual std::string query_listids (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Detailed Description
Base class for monitors and variable nodes.
Constructor & Destructor Documentation
MHAParser::monitor_t::monitor_t (const std::string & h)
References MHAParser::base_t::activate_query(), MHAParser::base_t::query_perm(), and MHAParser::base_t::query_val().
MHAParser::monitor_t::monitor_t (const monitor_t & src)
References MHAParser::base_t::activate_query(), MHAParser::base_t::query_perm(), and MHAParser::base_t::query_val().
Member Function Documentation
std::string MHAParser::monitor_t::op_query (expression_t & x) virtual
Reimplemented from MHAParser::base_t.
References MHAParser::expression_t::lval, MHAParser::base_t::queries, and MHAParser::expression_t::rval.
std::string MHAParser::monitor_t::query_dump (const std::string & s) virtual
Reimplemented from MHAParser::base_t.
References MHAParser::commentate(), and MHAParser::base_t::parse().
std::string MHAParser::monitor_t::query_perm (const std::string & s) virtual
Reimplemented from MHAParser::base_t.
Reimplemented in MHAParser::variable_t.
The documentation for this class was generated from the following files:
mha_parser.hh
mha_parser.cpp