openMHA Manual: mhaserver_t Class Reference
mhaserver_t Class Reference
MHA Framework listening on TCP port for commands.
Public Member Functions
mhaserver_t (const std::string &ao, const std::string &af, const std::string &lf)
~mhaserver_t ()
virtual std::string received_group (const std::string &line)
A line of text was received from network client.
virtual void acceptor_started (int status)
Notification: "TCP port is open".
virtual void set_announce_port (unsigned short announce_port)
If set to nonzero, the spawning process has asked to be notified of the TCP port used by this process.
void logstring (const std::string &)
Log a message to log file.
int run (unsigned short port, const std::string &_interface)
Accept network connections and act on commands.
Public Member Functions inherited from fw_t
fw_t ()
~fw_t ()
bool exit_request () const
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Attributes
MHAParser::int_t port
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Private Attributes
MHA_TCP::Server * tcpserver
std::string ack_ok
std::string ack_fail
std::string logfile
unsigned short announce_port
MHAParser::int_mon_t pid_mon
Additional Inherited Members
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes inherited from fw_t
int proc_error
int io_error
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Detailed Description
MHA Framework listening on TCP port for commands.
Constructor & Destructor Documentation
mhaserver_t::mhaserver_t (const std::string & ao, const std::string & af, const std::string & lf)
Parameters
ao Acknowledgement string at end of successful command responses
af Achknoledgement string at end of failed command responses
lf File system path of file to use as log file. MHA appends.
References MHAParser::int_mon_t::data, MHAParser::parser_t::insert_item(), insert_member, logfile, logstring(), pid_mon, and port.
Referenced by mhamain().
mhaserver_t::~mhaserver_t ()
References logstring().
Member Function Documentation
std::string mhaserver_t::received_group (const std::string & line) virtual
A line of text was received from network client.
References ack_fail, ack_ok, logstring(), MHAParser::base_t::parse(), and MHAParser::StrCnv::val2str().
Referenced by run().
void mhaserver_t::acceptor_started (int status) virtual
Notification: "TCP port is open".
References announce_port, MHAParser::int_t::data, MHA_TCP::Server::get_port(), MHA_TCP::Connection::get_write_event(), logstring(), MHA_TCP::Connection::needs_write(), MHA_TCP::Event_Watcher::observe(), port, tcpserver, MHA_TCP::Connection::try_write(), MHAParser::StrCnv::val2str(), and MHA_TCP::Event_Watcher::wait().
Referenced by run().
void mhaserver_t::set_announce_port (unsigned short announce_port) virtual
If set to nonzero, the spawning process has asked to be notified of the TCP port used by this process.
References announce_port.
Referenced by mhamain().
void mhaserver_t::logstring (const std::string & s) inline
Log a message to log file.
References logfile.
Referenced by acceptor_started(), mhamain(), mhaserver_t(), received_group(), run(), and ~mhaserver_t().
int mhaserver_t::run (unsigned short port, const std::string & _interface)
Accept network connections and act on commands.
Calls acceptor_started() when the TCP port is opened. Calls received_group for every line received.
Returns
exit code that can be used as process exit code
References MHA_TCP::Server::accept(), acceptor_started(), MHA_TCP::Connection::eof(), fw_t::exit_request(), MHA_TCP::Connection::get_peer_address(), MHA_TCP::Connection::get_peer_port(), Getmsg, logstring(), MHA_TCP::Connection::read_line(), received_group(), tcpserver, MHAParser::StrCnv::val2str(), and MHA_TCP::Connection::write().
Referenced by mhamain().
Member Data Documentation
MHA_TCP::Server* mhaserver_t::tcpserver private
Referenced by acceptor_started(), and run().
std::string mhaserver_t::ack_ok private
Referenced by mhamain(), and received_group().
std::string mhaserver_t::ack_fail private
Referenced by mhamain(), and received_group().
std::string mhaserver_t::logfile private
Referenced by logstring(), mhamain(), and mhaserver_t().
unsigned short mhaserver_t::announce_port private
Referenced by acceptor_started(), mhamain(), and set_announce_port().
MHAParser::int_mon_t mhaserver_t::pid_mon private
Referenced by mhaserver_t().
MHAParser::int_t mhaserver_t::port
Referenced by acceptor_started(), mhamain(), and mhaserver_t().
The documentation for this class was generated from the following file:
mhamain.cpp