openMHA Manual: MHAOvlFilter::fscale_t Class Reference
MHAOvlFilter::fscale_t Class Reference
#include <mha_fftfb.hh>
Public Member Functions
fscale_t (MHAParser::parser_t &parent)
std::vector< mha_real_t > get_f_hz () const
Public Attributes
scale_var_t unit
MHAParser::vfloat_t f
MHAParser::vfloat_mon_t f_hz
Private Member Functions
void update_hz ()
Private Attributes
MHAEvents::connector_t< fscale_t > updater
Constructor & Destructor Documentation
MHAOvlFilter::fscale_t::fscale_t (MHAParser::parser_t & parent)
References MHAOvlFilter::scale_var_t::add_fun(), f, f_hz, MHAOvlFilter::FreqScaleFun::hz2bark_analytic(), MHAOvlFilter::FreqScaleFun::hz2erb(), MHAOvlFilter::FreqScaleFun::hz2erb_glasberg1990(), MHAOvlFilter::FreqScaleFun::hz2hz(), MHAOvlFilter::FreqScaleFun::hz2khz(), MHAOvlFilter::FreqScaleFun::hz2octave(), MHAOvlFilter::FreqScaleFun::hz2third_octave(), and unit.
Member Function Documentation
std::vector< mha_real_t > MHAOvlFilter::fscale_t::get_f_hz () const
References MHAParser::vfloat_t::data, f, unit, and MHAOvlFilter::scale_var_t::unit2hz().
Referenced by coherence::cohflt_t::cohflt_t(), MHAOvlFilter::fspacing_t::fspacing_t(), and update_hz().
void MHAOvlFilter::fscale_t::update_hz () private
References MHAParser::vfloat_mon_t::data, f_hz, and get_f_hz().
Member Data Documentation
scale_var_t MHAOvlFilter::fscale_t::unit
Referenced by fscale_t(), MHAOvlFilter::fscale_bw_t::get_bw_hz(), and get_f_hz().
MHAParser::vfloat_t MHAOvlFilter::fscale_t::f
Referenced by fscale_t(), MHAOvlFilter::fscale_bw_t::get_bw_hz(), and get_f_hz().
MHAParser::vfloat_mon_t MHAOvlFilter::fscale_t::f_hz
Referenced by fscale_t(), and update_hz().
MHAEvents::connector_t<fscale_t> MHAOvlFilter::fscale_t::updater private
The documentation for this class was generated from the following files:
mha_fftfb.hh
mha_fftfb.cpp