openMHA Manual: MHASignal::minphase_t Class Reference
MHASignal::minphase_t Class Reference
The MHA Toolbox library » Vector and matrix processing toolbox
Minimal phase function.
#include <mha_signal.hh>
Public Member Functions
minphase_t (unsigned int fftlen, unsigned int ch)
Constructor.
void operator() (mha_spec_t *s)
Transform input spectrum to a minimal-phase spectrum, discarding the original phase.
Private Attributes
MHASignal::waveform_t phase
Additional Inherited Members
Private Member Functions inherited from MHASignal::hilbert_t
hilbert_t (unsigned int len)
~hilbert_t ()
void operator() (const mha_wave_t *, mha_wave_t *)
Apply Hilbert transformation on a waveform segment.
Detailed Description
Minimal phase function.
The output spectrum is
with the input spectrum and the Hilbert transformation .
Constructor & Destructor Documentation
MHASignal::minphase_t::minphase_t (unsigned int fftlen, unsigned int ch)
Constructor.
Parameters
fftlen FFT length
ch Number of channels
Member Function Documentation
void MHASignal::minphase_t::operator() (mha_spec_t * s)
Transform input spectrum to a minimal-phase spectrum, discarding the original phase.
Parameters
s Spectrum to operate on.
References abs(), expi(), MHASignal::max(), MHA_ErrorMsg, mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, mha_spec_t::num_frames, MHASignal::hilbert_t::operator()(), phase, value(), and MHASignal::waveform_t::value().
Member Data Documentation
MHASignal::waveform_t MHASignal::minphase_t::phase private
Referenced by operator()().
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp