openMHA Manual: MHAFilter::thirdoctave_analyzer_t Class Reference
MHAFilter::thirdoctave_analyzer_t Class Reference
#include <complex_filter.h>
Public Member Functions
thirdoctave_analyzer_t (mhaconfig_t cfg)
mha_wave_t * process (mha_wave_t *)
unsigned int nbands ()
unsigned int nchannels ()
std::vector< mha_real_t > get_cf_hz ()
Static Public Member Functions
static std::vector< mha_real_t > cf_generator (mhaconfig_t cfg)
static std::vector< mha_real_t > bw_generator (mhaconfig_t cfg)
static std::vector< mha_real_t > dup (std::vector< mha_real_t >, mhaconfig_t cfg)
Private Attributes
mhaconfig_t cfg_
std::vector< mha_real_t > cf
MHAFilter::gamma_flt_t fb
MHASignal::waveform_t out_chunk
MHASignal::waveform_t out_chunk_im
Constructor & Destructor Documentation
MHAFilter::thirdoctave_analyzer_t::thirdoctave_analyzer_t (mhaconfig_t cfg)
Member Function Documentation
mha_wave_t * MHAFilter::thirdoctave_analyzer_t::process (mha_wave_t * sIn)
References MHASignal::waveform_t::copy_channel(), fb, nbands(), mha_wave_t::num_channels, out_chunk, and out_chunk_im.
unsigned int MHAFilter::thirdoctave_analyzer_t::nbands ()
References cf.
Referenced by process().
unsigned int MHAFilter::thirdoctave_analyzer_t::nchannels ()
References cfg_, and mhaconfig_t::channels.
std::vector< mha_real_t > MHAFilter::thirdoctave_analyzer_t::get_cf_hz ()
References cf.
std::vector< mha_real_t > MHAFilter::thirdoctave_analyzer_t::cf_generator (mhaconfig_t cfg) static
References cf, and mhaconfig_t::srate.
Referenced by bw_generator().
std::vector< mha_real_t > MHAFilter::thirdoctave_analyzer_t::bw_generator (mhaconfig_t cfg) static
References cf, and cf_generator().
std::vector< mha_real_t > MHAFilter::thirdoctave_analyzer_t::dup (std::vector< mha_real_t > vec, mhaconfig_t cfg) static
References mhaconfig_t::channels.
Member Data Documentation
mhaconfig_t MHAFilter::thirdoctave_analyzer_t::cfg_ private
Referenced by nchannels().
std::vector<mha_real_t> MHAFilter::thirdoctave_analyzer_t::cf private
Referenced by bw_generator(), cf_generator(), get_cf_hz(), and nbands().
MHAFilter::gamma_flt_t MHAFilter::thirdoctave_analyzer_t::fb private
Referenced by process().
MHASignal::waveform_t MHAFilter::thirdoctave_analyzer_t::out_chunk private
Referenced by process().
MHASignal::waveform_t MHAFilter::thirdoctave_analyzer_t::out_chunk_im private
Referenced by process().
The documentation for this class was generated from the following files:
complex_filter.h
complex_filter.cpp