openMHA Manual: MHAFilter::o1_ar_filter_t Class Reference
MHAFilter::o1_ar_filter_t Class Reference
First order attack-release lowpass filter.
#include <mha_filter.hh>
Public Member Functions
o1_ar_filter_t (unsigned int channels, mha_real_t fs=1.0f, std::vector< mha_real_t > tau_a=std::vector< float >(1, 0.0f), std::vector< mha_real_t > tau_r=std::vector< float >(1, 0.0f))
Constructor, setting all taus to zero.
void set_tau_attack (unsigned int ch, mha_real_t tau)
Set the attack time constant.
void set_tau_release (unsigned int ch, mha_real_t tau)
Set the release time constant.
mha_real_t operator() (unsigned int ch, mha_real_t x)
Apply filter to value x, using state channel ch.
void operator() (const mha_wave_t &in, mha_wave_t &out)
Apply filter to a mha_wave_t data.
Public Member Functions inherited from MHASignal::waveform_t
waveform_t (const unsigned int &frames, const unsigned int &channels)
constructor of waveform_t
waveform_t (const mhaconfig_t &cf)
Constructor to create a waveform from plugin configuration.
waveform_t (const mha_wave_t &src)
Copy contructor for mha_wave_t source.
waveform_t (const MHASignal::waveform_t &src)
Copy contructor.
waveform_t (const std::vector< mha_real_t > &src)
Copy contructor for std::vector<mha_real_t> source.
virtual ~waveform_t (void)
void operator= (const mha_real_t &v)
mha_real_t & operator[] (unsigned int k)
const mha_real_t & operator[] (unsigned int k) const
mha_real_t & value (unsigned int t, unsigned int ch)
Element accessor.
mha_real_t & operator() (unsigned int t, unsigned int ch)
Element accessor.
const mha_real_t & value (unsigned int t, unsigned int ch) const
Constant element accessor.
const mha_real_t & operator() (unsigned int t, unsigned int ch) const
Constant element accessor.
mha_real_t sum (const unsigned int &a, const unsigned int &b)
sum of all elements between [a,b) in all channels
mha_real_t sum (const unsigned int &a, const unsigned int &b, const unsigned int &ch)
sum of all elements between [a,b) in channel ch
mha_real_t sum ()
sum of all elements
mha_real_t sumsqr ()
sum of square of all elements
mha_real_t sum_channel (const unsigned int &)
return sum of all elements in one channel
void assign (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
set frame "k" in channel "ch" to value "val"
void assign (const mha_real_t &)
set all elements to value
void assign_frame (const unsigned int &k, const mha_real_t &val)
assign value "val" to frame k in all channels
void assign_channel (const unsigned int &c, const mha_real_t &val)
assign value "val" to channel ch in all frames
void copy (const std::vector< mha_real_t > &v)
void copy (const mha_wave_t &)
copy data from source into current waveform
void copy (const mha_wave_t *)
void copy_channel (const mha_wave_t &, unsigned int, unsigned int)
Copy one channel of a given waveform signal to a target channel.
void copy_from_at (unsigned int, unsigned int, const mha_wave_t &, unsigned int)
Copy part of the source signal into part of this waveform object.
void export_to (mha_wave_t &)
copy data into allocated mha_wave_t structure
void limit (const mha_real_t &min, const mha_real_t &max)
limit target to range [min,max]
void power (const waveform_t &)
transform waveform signal (in Pa) to squared signal (in W/m^2)
void powspec (const mha_spec_t &)
get the power spectrum (in W/m^2) from a complex spectrum
void scale (const unsigned int &a, const unsigned int &b, const unsigned int &ch, const mha_real_t &val)
scale section [a,b) in channel "ch" by "val"
void scale (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
scale one element
void scale_channel (const unsigned int &, const mha_real_t &)
scale one channel of target with a scalar
void scale_frame (const unsigned int &, const mha_real_t &)
unsigned int get_size () const
Protected Attributes
MHASignal::waveform_t c1_a
MHASignal::waveform_t c2_a
MHASignal::waveform_t c1_r
MHASignal::waveform_t c2_r
mha_real_t fs
Additional Inherited Members
Public Attributes inherited from mha_wave_t
mha_real_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Detailed Description
First order attack-release lowpass filter.
This filter is the base of first order lowpass filter, maximum tracker and minimum tracker.
Constructor & Destructor Documentation
MHAFilter::o1_ar_filter_t::o1_ar_filter_t (unsigned int channels, mha_real_t fs = 1.0f, std::vector< mha_real_t > tau_a = std::vector<float>(1,0.0f), std::vector< mha_real_t > tau_r = std::vector<float>(1,0.0f))
Constructor, setting all taus to zero.
The filter state can be accessed through the member functions of MHASignal::waveform_t.
Parameters
channels Number of independent filters
fs Sampling rate (optional, default = 1)
tau_a Attack time constants (optional, default = 0)
tau_r Release time constants (optional, default = 0)
References channels(), MHASignal::dupvec_chk(), fs, set_tau_attack(), and set_tau_release().
Member Function Documentation
void MHAFilter::o1_ar_filter_t::set_tau_attack (unsigned int ch, mha_real_t tau)
Set the attack time constant.
Parameters
ch Channel number
tau Time constant
References c1_a, c2_a, fs, mha_wave_t::num_channels, and MHAFilter::o1_lp_coeffs().
Referenced by o1_ar_filter_t(), MHAFilter::o1flt_lowpass_t::set_tau(), MHAFilter::o1flt_maxtrack_t::set_tau(), and MHAFilter::o1flt_mintrack_t::set_tau().
void MHAFilter::o1_ar_filter_t::set_tau_release (unsigned int ch, mha_real_t tau)
Set the release time constant.
Parameters
ch Channel number
tau Time constant
References c1_r, c2_r, fs, mha_wave_t::num_channels, and MHAFilter::o1_lp_coeffs().
Referenced by o1_ar_filter_t(), MHAFilter::o1flt_lowpass_t::set_tau(), MHAFilter::o1flt_maxtrack_t::set_tau(), and MHAFilter::o1flt_mintrack_t::set_tau().
mha_real_t MHAFilter::o1_ar_filter_t::operator() (unsigned int ch, mha_real_t x) inline
Apply filter to value x, using state channel ch.
Parameters
ch Cannel number
x Input value
Returns
Output value
References MHAFilter::make_friendly_number().
void MHAFilter::o1_ar_filter_t::operator() (const mha_wave_t & in, mha_wave_t & out) inline
Apply filter to a mha_wave_t data.
Parameters
in Input signal
out Output signal
The number of channels must match the number of filter bands.
References MHA_assert_equal, mha_wave_t::num_channels, mha_wave_t::num_frames, and value().
Member Data Documentation
MHASignal::waveform_t MHAFilter::o1_ar_filter_t::c1_a protected
Referenced by set_tau_attack().
MHASignal::waveform_t MHAFilter::o1_ar_filter_t::c2_a protected
Referenced by set_tau_attack().
MHASignal::waveform_t MHAFilter::o1_ar_filter_t::c1_r protected
Referenced by set_tau_release().
MHASignal::waveform_t MHAFilter::o1_ar_filter_t::c2_r protected
Referenced by set_tau_release().
mha_real_t MHAFilter::o1_ar_filter_t::fs protected
Referenced by o1_ar_filter_t(), set_tau_attack(), and set_tau_release().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp