openMHA Manual: MHAParser::keyword_list_t Class Reference
MHAParser::keyword_list_t Class Reference
Keyword list class.
#include <mha_parser.hh>
Public Types
typedef std::vector< std::string >::size_type size_t
Public Member Functions
void set_value (const std::string &)
Select a value from keyword list.
void set_entries (const std::string &)
Set keyword list entries.
const std::string & get_value () const
Return selected value.
const std::vector< std::string > & get_entries () const
Return keyword list.
const size_t & get_index () const
Return index of selected value.
void set_index (unsigned int)
void validate () const
Check if index of selected value is valid.
void add_entry (const std::string &en)
keyword_list_t ()
Constructor.
Private Attributes
size_t index
Index into list.
std::vector< std::string > entries
List of valid entries.
std::string empty_string
Detailed Description
Keyword list class.
The stucture keyword_list_t defines a keyword list (vector of strings) with an index into the list. Used as MHAParser::kw_t, it can be used to access a set of valid keywords through the parser (i.e. one of "pear apple banana").
Member Typedef Documentation
typedef std::vector<std::string>::size_type MHAParser::keyword_list_t::size_t
Constructor & Destructor Documentation
MHAParser::keyword_list_t::keyword_list_t ()
Constructor.
References entries.
Member Function Documentation
void MHAParser::keyword_list_t::set_value (const std::string & s)
Select a value from keyword list.
This function selects a value from the keyword list. The index is set to the last matching entry.
Parameters
s Value to be selected.
References MHAParser::StrCnv::val2str().
Referenced by MHAParser::StrCnv::str2val().
void MHAParser::keyword_list_t::set_entries (const std::string & s)
Set keyword list entries.
With this function, the keyword list can be set from a space separated string list.
Parameters
s Space separated entry list.
References MHAParser::StrCnv::str2val().
const std::string & MHAParser::keyword_list_t::get_value () const
Return selected value.
Referenced by MHAOvlFilter::fspacing_t::fspacing_t(), and MHAParser::StrCnv::val2str().
const std::vector< std::string > & MHAParser::keyword_list_t::get_entries () const
Return keyword list.
const MHAParser::keyword_list_t::size_t & MHAParser::keyword_list_t::get_index () const
Return index of selected value.
Referenced by coherence::cohflt_t::cohflt_t(), fw_t::exec_fw_command(), MHAOvlFilter::fspacing_t::fspacing_t(), MHAParser::window_t::get_type(), MHAParser::kw_t::op_setval(), and windowselector_t::update().
void MHAParser::keyword_list_t::set_index (unsigned int idx)
Referenced by MHAOvlFilter::scale_var_t::add_fun(), and fw_t::exec_fw_command().
void MHAParser::keyword_list_t::validate () const
Check if index of selected value is valid.
Referenced by MHAParser::kw_t::validate().
void MHAParser::keyword_list_t::add_entry (const std::string & en) inline
Referenced by io_file_t::io_file_t().
Member Data Documentation
size_t MHAParser::keyword_list_t::index private
Index into list.
std::vector<std::string> MHAParser::keyword_list_t::entries private
List of valid entries.
Referenced by keyword_list_t().
std::string MHAParser::keyword_list_t::empty_string private
The documentation for this class was generated from the following files:
mha_parser.hh
mha_parser.cpp