openMHA Manual: MHAOvlFilter::fftfb_ac_info_t Class Reference
MHAOvlFilter::fftfb_ac_info_t Class Reference
#include <mha_fftfb.hh>
Public Member Functions
fftfb_ac_info_t (const MHAOvlFilter::fftfb_t &fb, algo_comm_t ac, const std::string &prefix)
void insert ()
Private Attributes
MHA_AC::waveform_t cfv
vector of nominal center frequencies / Hz
MHA_AC::waveform_t efv
vector of edge frequencies / Hz
MHA_AC::waveform_t bwv
vector of band-weigths (sum of squared fft-bin-weigths)/num_frames
MHA_AC::waveform_t cLTASS
vector of LTASS correction
Constructor & Destructor Documentation
MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t (const MHAOvlFilter::fftfb_t & fb, algo_comm_t ac, const std::string & prefix)
References MHAOvlFilter::fftfb_t::bin1(), MHAOvlFilter::fftfb_t::bin2(), bwv, cfv, cLTASS, MHASignal::waveform_t::copy(), efv, MHAOvlFilter::fspacing_t::get_cf_hz(), MHAOvlFilter::fspacing_t::get_ef_hz(), MHAOvlFilter::fftfb_t::get_fftlen(), MHAOvlFilter::fftfb_t::get_ltass_gain_db(), MHAOvlFilter::fspacing_t::nbands(), and MHAOvlFilter::fftfb_t::w().
Member Function Documentation
void MHAOvlFilter::fftfb_ac_info_t::insert ()
References bwv, cfv, cLTASS, efv, and MHA_AC::waveform_t::insert().
Referenced by fftfilterbank::fftfb_plug_t::insert().
Member Data Documentation
MHA_AC::waveform_t MHAOvlFilter::fftfb_ac_info_t::cfv private
vector of nominal center frequencies / Hz
Referenced by fftfb_ac_info_t(), and insert().
MHA_AC::waveform_t MHAOvlFilter::fftfb_ac_info_t::efv private
vector of edge frequencies / Hz
Referenced by fftfb_ac_info_t(), and insert().
MHA_AC::waveform_t MHAOvlFilter::fftfb_ac_info_t::bwv private
vector of band-weigths (sum of squared fft-bin-weigths)/num_frames
Referenced by fftfb_ac_info_t(), and insert().
MHA_AC::waveform_t MHAOvlFilter::fftfb_ac_info_t::cLTASS private
vector of LTASS correction
Referenced by fftfb_ac_info_t(), and insert().
The documentation for this class was generated from the following files:
mha_fftfb.hh
mha_fftfb.cpp