openMHA Manual: MHAFilter::transfer_matrix_t Struct Reference
MHAFilter::transfer_matrix_t Struct Reference
A sparse matrix of transfer function partitionss.
#include <mha_filter.hh>
Public Member Functions
std::valarray< unsigned int > partitions (unsigned fragsize) const
Returns an array of the results of calling the partitions() method on every matrix member.
std::valarray< unsigned int > non_empty_partitions (unsigned int fragsize) const
Returns an array of the results of calling the non_empty_partitions() method on every matrix member.
Detailed Description
A sparse matrix of transfer function partitionss.
Each matrix element knows its position in the matrix, so they can be stored as a vector.
Member Function Documentation
std::valarray<unsigned int> MHAFilter::transfer_matrix_t::partitions (unsigned fragsize) const inline
Returns an array of the results of calling the partitions() method on every matrix member.
References size().
Referenced by MHAFilter::partitioned_convolution_t::partitioned_convolution_t().
std::valarray<unsigned int> MHAFilter::transfer_matrix_t::non_empty_partitions (unsigned int fragsize) const inline
Returns an array of the results of calling the non_empty_partitions() method on every matrix member.
References size().
The documentation for this struct was generated from the following file:
mha_filter.hh