openMHA Manual: MHAParser::range_var_t Class Reference
MHAParser::range_var_t Class Reference
Base class for all variables with a numeric value range.
#include <mha_parser.hh>
Public Member Functions
range_var_t (const std::string &, const std::string &="")
range_var_t (const range_var_t &)
std::string query_range (const std::string &)
void set_range (const std::string &r)
Change the valid range of a variable.
void validate (const int &)
void validate (const float &)
void validate (const mha_complex_t &)
void validate (const std::vector< int > &)
void validate (const std::vector< float > &)
void validate (const std::vector< mha_complex_t > &)
void validate (const std::vector< std::vector< float > > &)
void validate (const std::vector< std::vector< mha_complex_t > > &)
Public Member Functions inherited from MHAParser::variable_t
variable_t (const std::string &)
std::string op_setval (expression_t &)
std::string query_perm (const std::string &)
void setlock (const bool &)
Lock a variable against write access.
Public Member Functions inherited from MHAParser::monitor_t
monitor_t (const std::string &)
monitor_t (const monitor_t &)
std::string op_query (expression_t &)
std::string query_dump (const std::string &)
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string op_subparse (expression_t &)
virtual std::string query_entries (const std::string &)
virtual std::string query_type (const std::string &)
virtual std::string query_val (const std::string &)
virtual std::string query_readfile (const std::string &)
virtual std::string query_savefile (const std::string &)
virtual std::string query_savefile_compact (const std::string &)
virtual std::string query_savemons (const std::string &)
virtual std::string query_listids (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Protected Attributes
float low_limit
Lower limit of range.
float up_limit
Upper limit of range.
bool low_incl
Lower limit is included (or excluded) in range.
bool up_incl
Upper limit is included (or excluded) in range.
bool check_low
Check lower limit.
bool check_up
Check upper limit.
bool check_range
Range checking is active.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Detailed Description
Base class for all variables with a numeric value range.
Constructor & Destructor Documentation
MHAParser::range_var_t::range_var_t (const std::string & h, const std::string & r = "")
References MHAParser::base_t::activate_query(), MHAParser::base_t::query_range(), and set_range().
MHAParser::range_var_t::range_var_t (const range_var_t & src)
References MHAParser::base_t::activate_query(), and MHAParser::base_t::query_range().
Member Function Documentation
std::string MHAParser::range_var_t::query_range (const std::string & s) virtual
Reimplemented from MHAParser::base_t.
References check_low, check_range, check_up, low_incl, low_limit, up_incl, up_limit, and MHAParser::StrCnv::val2str().
Referenced by validate().
void MHAParser::range_var_t::set_range (const std::string & r)
Change the valid range of a variable.
Parameters
r New range of the variable (string representation)
References check_low, check_range, check_up, low_incl, low_limit, MHAParser::StrCnv::str2val(), up_incl, and up_limit.
Referenced by range_var_t().
void MHAParser::range_var_t::validate (const int & v)
References check_low, check_range, check_up, low_incl, low_limit, query_range(), up_incl, up_limit, and MHAParser::StrCnv::val2str().
Referenced by MHAParser::int_t::op_setval(), MHAParser::float_t::op_setval(), MHAParser::complex_t::op_setval(), MHAParser::vint_t::op_setval(), MHAParser::vfloat_t::op_setval(), MHAParser::vcomplex_t::op_setval(), MHAParser::mfloat_t::op_setval(), MHAParser::mcomplex_t::op_setval(), and validate().
void MHAParser::range_var_t::validate (const float & v)
References check_low, check_range, check_up, low_incl, low_limit, query_range(), up_incl, up_limit, and MHAParser::StrCnv::val2str().
void MHAParser::range_var_t::validate (const mha_complex_t & v)
References check_range, mha_complex_t::im, mha_complex_t::re, and validate().
void MHAParser::range_var_t::validate (const std::vector< int > & v)
References check_low, check_range, check_up, low_incl, low_limit, query_range(), up_incl, up_limit, and MHAParser::StrCnv::val2str().
void MHAParser::range_var_t::validate (const std::vector< float > & v)
References check_low, check_range, check_up, low_incl, low_limit, query_range(), up_incl, up_limit, and MHAParser::StrCnv::val2str().
void MHAParser::range_var_t::validate (const std::vector< mha_complex_t > & v)
References check_range, Getmsg, MHAParser::StrCnv::val2str(), and validate().
void MHAParser::range_var_t::validate (const std::vector< std::vector< float > > & v)
References check_low, check_range, check_up, low_incl, low_limit, query_range(), up_incl, up_limit, and MHAParser::StrCnv::val2str().
void MHAParser::range_var_t::validate (const std::vector< std::vector< mha_complex_t > > & v)
References check_range, Getmsg, MHAParser::StrCnv::val2str(), and validate().
Member Data Documentation
float MHAParser::range_var_t::low_limit protected
Lower limit of range.
Referenced by query_range(), set_range(), and validate().
float MHAParser::range_var_t::up_limit protected
Upper limit of range.
Referenced by query_range(), set_range(), and validate().
bool MHAParser::range_var_t::low_incl protected
Lower limit is included (or excluded) in range.
Referenced by query_range(), set_range(), and validate().
bool MHAParser::range_var_t::up_incl protected
Upper limit is included (or excluded) in range.
Referenced by query_range(), set_range(), and validate().
bool MHAParser::range_var_t::check_low protected
Check lower limit.
Referenced by query_range(), set_range(), and validate().
bool MHAParser::range_var_t::check_up protected
Check upper limit.
Referenced by query_range(), set_range(), and validate().
bool MHAParser::range_var_t::check_range protected
Range checking is active.
Referenced by query_range(), set_range(), and validate().
The documentation for this class was generated from the following files:
mha_parser.hh
mha_parser.cpp