openMHA Manual: MHAOvlFilter::overlap_save_filterbank_t Class Reference
MHAOvlFilter::overlap_save_filterbank_t Class Reference
A time-domain minimal phase filter bank with frequency shapes from MHAOvlFilter::fftfb_t.
#include <mha_fftfb.hh>
Classes
class vars_t
Public Member Functions
overlap_save_filterbank_t (MHAOvlFilter::overlap_save_filterbank_t::vars_t &fbpar, mhaconfig_t channelconfig_in)
mhaconfig_t get_channelconfig () const
Public Member Functions inherited from MHAOvlFilter::fftfb_t
fftfb_t (MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
Constructor for a FFT-based overlapping filter bank.
~fftfb_t ()
void apply_gains (mha_spec_t *s_out, const mha_spec_t *s_in, const mha_wave_t *gains)
void get_fbpower (mha_wave_t *fbpow, const mha_spec_t *s_in)
void get_fbpower_db (mha_wave_t *fbpow, const mha_spec_t *s_in)
std::vector< mha_real_t > get_ltass_gain_db () const
unsigned int bin1 (unsigned int band) const
Return index of first non-zero filter shape window.
unsigned int bin2 (unsigned int band) const
Return index of first zero filter shape window above center frequency.
unsigned int get_fftlen () const
Return fft length.
mha_real_t w (unsigned int k, unsigned int b) const
Return filter shape window at index k in band b.
Public Member Functions inherited from MHAOvlFilter::fspacing_t
fspacing_t (const MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
std::vector< unsigned int > get_cf_fftbin () const
std::vector< mha_real_t > get_cf_hz () const
std::vector< mha_real_t > get_ef_hz () const
unsigned int nbands () const
Return number of bands in filter bank.
Public Member Functions inherited from MHAFilter::fftfilterbank_t
fftfilterbank_t (unsigned int fragsize, unsigned int inputchannels, unsigned int firchannels, unsigned int fftlen)
Constructor.
~fftfilterbank_t ()
void update_coeffs (const mha_wave_t *h)
Update the set of coefficients.
void filter (const mha_wave_t *s_in, mha_wave_t **s_out, const mha_wave_t *h)
Apply filter with changing coefficients to a waveform fragment.
void filter (const mha_wave_t *s_in, mha_wave_t **s_out)
Apply filter to waveform fragment, without changing the coefficients.
const mha_wave_t * get_irs () const
Return the current IRS.
Private Attributes
mhaconfig_t channelconfig_out_
Additional Inherited Members
Protected Member Functions inherited from MHAOvlFilter::fspacing_t
void fail_on_nonmonotonic_cf ()
void fail_on_unique_fftbins ()
Protected Attributes inherited from MHAOvlFilter::fspacing_t
std::vector< MHAOvlFilter::band_descriptor_t > bands
mha_real_t(* symmetry_scale)(mha_real_t)
Detailed Description
A time-domain minimal phase filter bank with frequency shapes from MHAOvlFilter::fftfb_t.
Constructor & Destructor Documentation
MHAOvlFilter::overlap_save_filterbank_t::overlap_save_filterbank_t (MHAOvlFilter::overlap_save_filterbank_t::vars_t & fbpar, mhaconfig_t channelconfig_in)
References channelconfig_out_, mhaconfig_t::channels, MHAParser::int_t::data, MHAOvlFilter::fftfb_t::fftlen, MHAOvlFilter::overlap_save_filterbank_t::vars_t::fftlen, mhaconfig_t::fragsize, MHAParser::window_t::get_window(), MHAOvlFilter::overlap_save_filterbank_t::vars_t::irswnd, MHAParser::kw_t::isval(), mha_complex(), MHAOvlFilter::fspacing_t::nbands(), MHAOvlFilter::overlap_save_filterbank_t::vars_t::phasemodel, MHAFilter::spec2fir(), MHAFilter::fftfilterbank_t::update_coeffs(), and MHAOvlFilter::fftfb_t::w().
Member Function Documentation
mhaconfig_t MHAOvlFilter::overlap_save_filterbank_t::get_channelconfig () const inline
Member Data Documentation
mhaconfig_t MHAOvlFilter::overlap_save_filterbank_t::channelconfig_out_ private
Referenced by overlap_save_filterbank_t().
The documentation for this class was generated from the following files:
mha_fftfb.hh
mha_fftfb.cpp