openMHA Manual: MHAParser::variable_t Class Reference
MHAParser::variable_t Class Reference
Base class for variable nodes.
#include <mha_parser.hh>
Public Member Functions
variable_t (const std::string &)
std::string op_setval (expression_t &)
std::string query_perm (const std::string &)
void setlock (const bool &)
Lock a variable against write access.
Public Member Functions inherited from MHAParser::monitor_t
monitor_t (const std::string &)
monitor_t (const monitor_t &)
std::string op_query (expression_t &)
std::string query_dump (const std::string &)
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string op_subparse (expression_t &)
virtual std::string query_entries (const std::string &)
virtual std::string query_range (const std::string &)
virtual std::string query_type (const std::string &)
virtual std::string query_val (const std::string &)
virtual std::string query_readfile (const std::string &)
virtual std::string query_savefile (const std::string &)
virtual std::string query_savefile_compact (const std::string &)
virtual std::string query_savemons (const std::string &)
virtual std::string query_listids (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Private Attributes
bool locked
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Detailed Description
Base class for variable nodes.
Constructor & Destructor Documentation
MHAParser::variable_t::variable_t (const std::string & h)
Member Function Documentation
std::string MHAParser::variable_t::op_setval (expression_t & x) virtual
Reimplemented from MHAParser::base_t.
Reimplemented in MHAParser::mcomplex_t, MHAParser::mfloat_t, MHAParser::vcomplex_t, MHAParser::vfloat_t, MHAParser::vint_t, MHAParser::complex_t, MHAParser::float_t, MHAParser::int_t, MHAParser::bool_t, MHAParser::vstring_t, MHAParser::string_t, and MHAParser::kw_t.
References locked, and MHAParser::expression_t::lval.
Referenced by MHAParser::kw_t::op_setval(), MHAParser::string_t::op_setval(), MHAParser::vstring_t::op_setval(), MHAParser::bool_t::op_setval(), MHAParser::int_t::op_setval(), MHAParser::float_t::op_setval(), MHAParser::complex_t::op_setval(), MHAParser::vint_t::op_setval(), MHAParser::vfloat_t::op_setval(), MHAParser::vcomplex_t::op_setval(), MHAParser::mfloat_t::op_setval(), and MHAParser::mcomplex_t::op_setval().
std::string MHAParser::variable_t::query_perm (const std::string & s) virtual
Reimplemented from MHAParser::monitor_t.
References locked.
void MHAParser::variable_t::setlock (const bool & b)
Lock a variable against write access.
Parameters
b Lock state
References locked.
Referenced by fw_t::load_io_lib(), fw_t::load_proc_lib(), fftfilterbank::fftfb_interface_t::prepare(), MHAIOJack::io_jack_t::prepare(), MHAParser::mhapluginloader_t::prepare(), fftfilterbank::fftfb_interface_t::release(), MHAIOJack::io_jack_t::release(), and MHAParser::mhapluginloader_t::release().
Member Data Documentation
bool MHAParser::variable_t::locked private
Referenced by op_setval(), query_perm(), and setlock().
The documentation for this class was generated from the following files:
mha_parser.hh
mha_parser.cpp