openMHA Manual: MHASignal::loop_wavefragment_t Class Reference
MHASignal::loop_wavefragment_t Class Reference
Copy a fixed waveform fragment to a series of waveform fragments of other size.
#include <mha_signal.hh>
Public Types
enum level_mode_t { relative, peak, rms, rms_limit40 }
Switch for playback level mode.
enum playback_mode_t { add, replace, input, mute }
Switch for playback mode.
Public Member Functions
loop_wavefragment_t (const mha_wave_t &src, bool loop, level_mode_t level_mode, std::vector< int > channels, unsigned int startpos=0)
Constructor to create an instance of loop_wavefragment_t based on an existing waveform block.
std::vector< int > get_mapping (unsigned int channels)
void playback (mha_wave_t *s, playback_mode_t pmode, mha_wave_t *level_pa, const std::vector< int > &channels)
Add source waveform block to an output block.
void playback (mha_wave_t *s, playback_mode_t pmode, mha_wave_t *level_pa)
Add source waveform block to an output block.
void playback (mha_wave_t *s, playback_mode_t pmode)
Add source waveform block to an output block.
void set_level_lin (mha_real_t l)
void set_level_db (mha_real_t l)
void rewind ()
void locate_end ()
bool is_playback_active () const
Public Member Functions inherited from MHASignal::waveform_t
waveform_t (const unsigned int &frames, const unsigned int &channels)
constructor of waveform_t
waveform_t (const mhaconfig_t &cf)
Constructor to create a waveform from plugin configuration.
waveform_t (const mha_wave_t &src)
Copy contructor for mha_wave_t source.
waveform_t (const MHASignal::waveform_t &src)
Copy contructor.
waveform_t (const std::vector< mha_real_t > &src)
Copy contructor for std::vector<mha_real_t> source.
virtual ~waveform_t (void)
void operator= (const mha_real_t &v)
mha_real_t & operator[] (unsigned int k)
const mha_real_t & operator[] (unsigned int k) const
mha_real_t & value (unsigned int t, unsigned int ch)
Element accessor.
mha_real_t & operator() (unsigned int t, unsigned int ch)
Element accessor.
const mha_real_t & value (unsigned int t, unsigned int ch) const
Constant element accessor.
const mha_real_t & operator() (unsigned int t, unsigned int ch) const
Constant element accessor.
mha_real_t sum (const unsigned int &a, const unsigned int &b)
sum of all elements between [a,b) in all channels
mha_real_t sum (const unsigned int &a, const unsigned int &b, const unsigned int &ch)
sum of all elements between [a,b) in channel ch
mha_real_t sum ()
sum of all elements
mha_real_t sumsqr ()
sum of square of all elements
mha_real_t sum_channel (const unsigned int &)
return sum of all elements in one channel
void assign (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
set frame "k" in channel "ch" to value "val"
void assign (const mha_real_t &)
set all elements to value
void assign_frame (const unsigned int &k, const mha_real_t &val)
assign value "val" to frame k in all channels
void assign_channel (const unsigned int &c, const mha_real_t &val)
assign value "val" to channel ch in all frames
void copy (const std::vector< mha_real_t > &v)
void copy (const mha_wave_t &)
copy data from source into current waveform
void copy (const mha_wave_t *)
void copy_channel (const mha_wave_t &, unsigned int, unsigned int)
Copy one channel of a given waveform signal to a target channel.
void copy_from_at (unsigned int, unsigned int, const mha_wave_t &, unsigned int)
Copy part of the source signal into part of this waveform object.
void export_to (mha_wave_t &)
copy data into allocated mha_wave_t structure
void limit (const mha_real_t &min, const mha_real_t &max)
limit target to range [min,max]
void power (const waveform_t &)
transform waveform signal (in Pa) to squared signal (in W/m^2)
void powspec (const mha_spec_t &)
get the power spectrum (in W/m^2) from a complex spectrum
void scale (const unsigned int &a, const unsigned int &b, const unsigned int &ch, const mha_real_t &val)
scale section [a,b) in channel "ch" by "val"
void scale (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
scale one element
void scale_channel (const unsigned int &, const mha_real_t &)
scale one channel of target with a scalar
void scale_frame (const unsigned int &, const mha_real_t &)
unsigned int get_size () const
Private Attributes
std::vector< int > playback_channels
bool b_loop
unsigned int pos
MHASignal::waveform_t intern_level
Additional Inherited Members
Public Attributes inherited from mha_wave_t
mha_real_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Detailed Description
Copy a fixed waveform fragment to a series of waveform fragments of other size.
This class is designed to continously play back a waveform to an output stream, with variable output block size.
Member Enumeration Documentation
enum MHASignal::loop_wavefragment_t::level_mode_t
Switch for playback level mode.
Enumerator
relative
The nominal level is applied as a gain to the source signal.
peak
The nominal level is the peak level of source signal in Pascal.
rms
The nominal level is the RMS level of the source signal in Pascal.
rms_limit40
enum MHASignal::loop_wavefragment_t::playback_mode_t
Switch for playback mode.
Enumerator
add
Add source signal to output stream.
replace
Replace output stream by source signal.
input
Do nothing, keep output stream (source position is unchanged).
mute
Mute output stream (source position is unchanged).
Constructor & Destructor Documentation
MHASignal::loop_wavefragment_t::loop_wavefragment_t (const mha_wave_t & src, bool loop, level_mode_t level_mode, std::vector< int > channels, unsigned int startpos = 0)
Constructor to create an instance of loop_wavefragment_t based on an existing waveform block.
Parameters
src Waveform block to copy data from.
loop Flag whether the block should be looped or played once.
level_mode Configuration of playback level (see MHASignal::loop_wavefragment_t::level_mode_t for details)
channels Mapping of input to output channels.
startpos Starting position
References MHASignal::max(), MHASignal::maxabs(), peak, relative, rms, rms_limit40, size(), and MHASignal::waveform_t::sumsqr().
Member Function Documentation
std::vector< int > MHASignal::loop_wavefragment_t::get_mapping (unsigned int channels)
References mha_wave_t::num_channels, and playback_channels.
void MHASignal::loop_wavefragment_t::playback (mha_wave_t * s, playback_mode_t pmode, mha_wave_t * level_pa, const std::vector< int > & channels)
Add source waveform block to an output block.
Parameters
s Output block (streamed signal).
pmode Playback mode (add, replace, input, mute).
level_pa Linear output level/gain (depending on level_mode parameter in constructor); one value for each sample in output block.
channels Output channels
References b_loop, clear(), input, mute, mha_wave_t::num_channels, mha_wave_t::num_frames, pos, replace, and MHASignal::waveform_t::value().
Referenced by playback().
void MHASignal::loop_wavefragment_t::playback (mha_wave_t * s, playback_mode_t pmode, mha_wave_t * level_pa)
Add source waveform block to an output block.
Parameters
s Output block (streamed signal).
pmode Playback mode (add, replace, input, mute).
level_pa Linear output level/gain (depending on level_mode parameter in constructor); one value for each sample in output block.
References playback(), and playback_channels.
void MHASignal::loop_wavefragment_t::playback (mha_wave_t * s, playback_mode_t pmode)
Add source waveform block to an output block.
Parameters
s Output block (streamed signal).
pmode Playback mode (add, replace, input, mute).
References intern_level, and playback().
void MHASignal::loop_wavefragment_t::set_level_lin (mha_real_t l)
References intern_level.
Referenced by set_level_db().
void MHASignal::loop_wavefragment_t::set_level_db (mha_real_t l)
References set_level_lin().
Referenced by calibrator_runtime_layer_t::calibrator_runtime_layer_t().
void MHASignal::loop_wavefragment_t::rewind () inline
void MHASignal::loop_wavefragment_t::locate_end () inline
References mha_spec_t::num_frames.
bool MHASignal::loop_wavefragment_t::is_playback_active () const inline
References mha_spec_t::num_frames.
Member Data Documentation
std::vector<int> MHASignal::loop_wavefragment_t::playback_channels private
Referenced by get_mapping(), and playback().
bool MHASignal::loop_wavefragment_t::b_loop private
Referenced by playback().
unsigned int MHASignal::loop_wavefragment_t::pos private
Referenced by playback().
MHASignal::waveform_t MHASignal::loop_wavefragment_t::intern_level private
Referenced by playback(), and set_level_lin().
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp