openMHA Manual: MHAOvlFilter::fspacing_t Class Reference
MHAOvlFilter::fspacing_t Class Reference
Class for frequency spacing, used by filterbank shape generator class.
#include <mha_fftfb.hh>
Public Member Functions
fspacing_t (const MHAOvlFilter::fftfb_vars_t &par, unsigned int nfft, mha_real_t fs)
std::vector< unsigned int > get_cf_fftbin () const
std::vector< mha_real_t > get_cf_hz () const
std::vector< mha_real_t > get_ef_hz () const
unsigned int nbands () const
Return number of bands in filter bank.
Protected Member Functions
void fail_on_nonmonotonic_cf ()
void fail_on_unique_fftbins ()
Protected Attributes
std::vector< MHAOvlFilter::band_descriptor_t > bands
mha_real_t(* symmetry_scale)(mha_real_t)
Private Member Functions
void ef2bands (std::vector< mha_real_t > vef)
void cf2bands (std::vector< mha_real_t > vcf)
void equidist2bands (std::vector< mha_real_t > vcf)
Private Attributes
unsigned int nfft_
mha_real_t fs_
Detailed Description
Class for frequency spacing, used by filterbank shape generator class.
Constructor & Destructor Documentation
MHAOvlFilter::fspacing_t::fspacing_t (const MHAOvlFilter::fftfb_vars_t & par, unsigned int nfft, mha_real_t fs)
References cf2bands(), MHAParser::kw_t::data, MHAParser::bool_t::data, ef2bands(), MHAOvlFilter::fftfb_vars_t::f, MHAOvlFilter::fftfb_vars_t::fail_on_nonmonotonic, fail_on_nonmonotonic_cf(), MHAOvlFilter::fftfb_vars_t::fail_on_unique_bins, fail_on_unique_fftbins(), MHAOvlFilter::fftfb_vars_t::ftype, MHAOvlFilter::fscale_t::get_f_hz(), MHAParser::keyword_list_t::get_index(), MHAParser::keyword_list_t::get_value(), MHAParser::kw_t::isval(), and nbands().
Member Function Documentation
std::vector< unsigned int > MHAOvlFilter::fspacing_t::get_cf_fftbin () const
References fs_, get_cf_hz(), mha_round, and nfft_.
Referenced by fail_on_unique_fftbins().
std::vector< mha_real_t > MHAOvlFilter::fspacing_t::get_cf_hz () const
References bands, MHAOvlFilter::FreqScaleFun::inv_scale(), and symmetry_scale.
Referenced by fail_on_nonmonotonic_cf(), fail_on_unique_fftbins(), MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t(), MHAOvlFilter::fftfb_t::fftfb_t(), and get_cf_fftbin().
std::vector< mha_real_t > MHAOvlFilter::fspacing_t::get_ef_hz () const
References bands, MHAOvlFilter::FreqScaleFun::inv_scale(), nbands(), and symmetry_scale.
Referenced by MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t(), and MHAOvlFilter::fftfb_t::fftfb_t().
unsigned int MHAOvlFilter::fspacing_t::nbands () const inline
Return number of bands in filter bank.
Referenced by coherence::cohflt_t::cohflt_t(), MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t(), MHAOvlFilter::fftfb_t::fftfb_t(), fspacing_t(), get_ef_hz(), MHAOvlFilter::overlap_save_filterbank_analytic_t::overlap_save_filterbank_analytic_t(), MHAOvlFilter::overlap_save_filterbank_t::overlap_save_filterbank_t(), fftfilterbank::fftfb_interface_t::prepare(), fftfilterbank::fftfb_plug_t::process(), and fftfilterbank::fftfb_interface_t::update_cfg().
void MHAOvlFilter::fspacing_t::fail_on_nonmonotonic_cf () protected
References get_cf_hz().
Referenced by fspacing_t().
void MHAOvlFilter::fspacing_t::fail_on_unique_fftbins () protected
References get_cf_fftbin(), and get_cf_hz().
Referenced by fspacing_t().
void MHAOvlFilter::fspacing_t::ef2bands (std::vector< mha_real_t > vef) private
References bands, MHA_ErrorMsg, and symmetry_scale.
Referenced by fspacing_t().
void MHAOvlFilter::fspacing_t::cf2bands (std::vector< mha_real_t > vcf) private
References bands, MHASignal::max(), MHA_ErrorMsg, and symmetry_scale.
Referenced by fspacing_t().
void MHAOvlFilter::fspacing_t::equidist2bands (std::vector< mha_real_t > vcf) private
Member Data Documentation
std::vector<MHAOvlFilter::band_descriptor_t> MHAOvlFilter::fspacing_t::bands protected
Referenced by cf2bands(), ef2bands(), MHAOvlFilter::fftfb_t::fftfb_t(), get_cf_hz(), and get_ef_hz().
mha_real_t(* MHAOvlFilter::fspacing_t::symmetry_scale) (mha_real_t) protected
Referenced by cf2bands(), ef2bands(), MHAOvlFilter::fftfb_t::fftfb_t(), get_cf_hz(), and get_ef_hz().
unsigned int MHAOvlFilter::fspacing_t::nfft_ private
Referenced by get_cf_fftbin().
mha_real_t MHAOvlFilter::fspacing_t::fs_ private
Referenced by get_cf_fftbin().
The documentation for this class was generated from the following files:
mha_fftfb.hh
mha_fftfb.cpp