openMHA Manual: MHAMultiSrc::spectrum_t Class Reference
MHAMultiSrc::spectrum_t Class Reference
#include <mha_multisrc.h>
Public Member Functions
spectrum_t (algo_comm_t iac, std::string name, unsigned int frames, unsigned int channels)
mha_spec_t * update (mha_spec_t *s)
Update data of spectrum to hold actual input data.
Public Member Functions inherited from MHA_AC::spectrum_t
spectrum_t (algo_comm_t ac, std::string name, unsigned int bins, unsigned int channels, bool insert_now)
Create the AC variable.
~spectrum_t ()
void insert ()
Insert AC variable into AC space.
Public Member Functions inherited from MHASignal::spectrum_t
spectrum_t (const unsigned int &frames, const unsigned int &channels)
constructor of spectrum class
spectrum_t (const mha_spec_t &)
Copy constructor.
spectrum_t (const MHASignal::spectrum_t &)
Copy constructor.
spectrum_t (const std::vector< mha_complex_t > &)
mha_complex_t & operator() (unsigned int f, unsigned int ch)
Access to element.
mha_complex_t & operator[] (unsigned int k)
Access to a single element, direct index into data buffer.
mha_complex_t & value (unsigned int f, unsigned int ch)
Access to element.
void copy (const mha_spec_t &)
copy all elements from a spectrum
void copy_channel (const mha_spec_t &s, unsigned sch, unsigned dch)
Copy one channel of a given spectrum signal to a target channel.
void export_to (mha_spec_t &)
copy elements to spectrum structure
void scale (const unsigned int &, const unsigned int &, const unsigned int &, const mha_real_t &)
scale section [a,b) in channel "ch" by "val"
void scale_channel (const unsigned int &, const mha_real_t &)
scale all elements in one channel
Public Member Functions inherited from MHAMultiSrc::base_t
base_t (algo_comm_t iac)
void select_source (const std::vector< std::string > &src, int in_channels)
Change the selection of input sources.
Additional Inherited Members
Public Attributes inherited from mha_spec_t
mha_complex_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Protected Member Functions inherited from MHAPlugin::config_t< MHAMultiSrc::channels_t >
MHAMultiSrc::channels_t * poll_config ()
Receive the latest run time configuration.
MHAMultiSrc::channels_t * last_config ()
Receive the latest run time configuration.
void push_config (MHAMultiSrc::channels_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
config_t ()
~config_t ()
Protected Attributes inherited from MHA_AC::spectrum_t
algo_comm_t ac
std::string name
Protected Attributes inherited from MHAMultiSrc::base_t
algo_comm_t ac
Protected Attributes inherited from MHAPlugin::config_t< MHAMultiSrc::channels_t >
MHAMultiSrc::channels_t * cfg
Constructor & Destructor Documentation
MHAMultiSrc::spectrum_t::spectrum_t (algo_comm_t iac, std::string name, unsigned int frames, unsigned int channels)
Member Function Documentation
mha_spec_t * MHAMultiSrc::spectrum_t::update (mha_spec_t * s)
Update data of spectrum to hold actual input data.
Parameters
s Input signal chunk
Returns
Return pointer to spectrum structure
References MHAMultiSrc::base_t::ac, MHAPlugin::config_t< MHAMultiSrc::channels_t >::cfg, MHA_AC::get_var_spectrum(), MHA_AC::spectrum_t::insert(), MHA_AC::spectrum_t::name, mha_spec_t::num_channels, mha_spec_t::num_frames, MHAPlugin::config_t< MHAMultiSrc::channels_t >::poll_config(), and MHASignal::spectrum_t::value().
The documentation for this class was generated from the following files:
mha_multisrc.h
mha_multisrc.cpp