openMHA Manual: MHAFilter::transfer_function_t Struct Reference
MHAFilter::transfer_function_t Struct Reference
a structure containing a source channel number, a target channel number, and an impulse response.
#include <mha_filter.hh>
Public Member Functions
transfer_function_t ()
Default constructor for STL conformity.
transfer_function_t (unsigned int source_channel_index, unsigned int target_channel_index, const std::vector< float > &impulse_response)
Data constructor.
unsigned int partitions (unsigned int fragsize) const
for the given partition size, return the number of partitions of the impulse response.
unsigned int non_empty_partitions (unsigned int fragsize) const
for the given partition size, return the number of non-empty partitions of the impulse response.
bool isempty (unsigned int fragsize, unsigned int index) const
checks if the partition contains only zeros
Public Attributes
unsigned int source_channel_index
Source audio channel index for this transfer function.
unsigned int target_channel_index
Target audio channel index for this transfer function.
std::vector< float > impulse_response
Impulse response of transfer from source to target channel.
Detailed Description
a structure containing a source channel number, a target channel number, and an impulse response.
Constructor & Destructor Documentation
MHAFilter::transfer_function_t::transfer_function_t () inline
Default constructor for STL conformity.
Not used.
Referenced by MHAFilter::fftfilterbank_t::filter().
MHAFilter::transfer_function_t::transfer_function_t (unsigned int source_channel_index, unsigned int target_channel_index, const std::vector< float > & impulse_response)
Data constructor.
Parameters
source_channel_index Source audio channel index for this transfer function
target_channel_index Target audio channel index for this transfer function
impulse_response Impulse response of transfer from source to target channel
References MHAFilter::partitioned_convolution_t::partitioned_convolution_t().
Member Function Documentation
unsigned int MHAFilter::transfer_function_t::partitions (unsigned int fragsize) const inline
for the given partition size, return the number of partitions of the impulse response.
Parameters
fragsize partition size
Returns
number of partitions occupied by the impulse response
References MHA_ErrorMsg.
unsigned int MHAFilter::transfer_function_t::non_empty_partitions (unsigned int fragsize) const inline
for the given partition size, return the number of non-empty partitions of the impulse response.
Parameters
fragsize partition size
Returns
the number of non-empty partitions of the impulse response, i.e. partitions containing only zeros are not counted.
References isempty().
bool MHAFilter::transfer_function_t::isempty (unsigned int fragsize, unsigned int index) const inline
checks if the partition contains only zeros
Parameters
fragsize partition size
index partition index
Returns
true when this partition of the impulse response contains only zeros.
Member Data Documentation
unsigned int MHAFilter::transfer_function_t::source_channel_index
Source audio channel index for this transfer function.
unsigned int MHAFilter::transfer_function_t::target_channel_index
Target audio channel index for this transfer function.
std::vector<float> MHAFilter::transfer_function_t::impulse_response
Impulse response of transfer from source to target channel.
The documentation for this struct was generated from the following files:
mha_filter.hh
mha_filter.cpp