openMHA Manual: MHAParser::vcomplex_t Class Reference
MHAParser::vcomplex_t Class Reference
Vector variable with complex value.
#include <mha_parser.hh>
Public Member Functions
vcomplex_t (const std::string &, const std::string &, const std::string &="")
Public Member Functions inherited from MHAParser::range_var_t
range_var_t (const std::string &, const std::string &="")
range_var_t (const range_var_t &)
std::string query_range (const std::string &)
void set_range (const std::string &r)
Change the valid range of a variable.
void validate (const int &)
void validate (const float &)
void validate (const mha_complex_t &)
void validate (const std::vector< int > &)
void validate (const std::vector< float > &)
void validate (const std::vector< mha_complex_t > &)
void validate (const std::vector< std::vector< float > > &)
void validate (const std::vector< std::vector< mha_complex_t > > &)
Public Member Functions inherited from MHAParser::variable_t
variable_t (const std::string &)
std::string query_perm (const std::string &)
void setlock (const bool &)
Lock a variable against write access.
Public Member Functions inherited from MHAParser::monitor_t
monitor_t (const std::string &)
monitor_t (const monitor_t &)
std::string op_query (expression_t &)
std::string query_dump (const std::string &)
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string op_subparse (expression_t &)
virtual std::string query_entries (const std::string &)
virtual std::string query_readfile (const std::string &)
virtual std::string query_savefile (const std::string &)
virtual std::string query_savefile_compact (const std::string &)
virtual std::string query_savemons (const std::string &)
virtual std::string query_listids (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Attributes
std::vector< mha_complex_t > data
Data field.
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions
std::string op_setval (expression_t &)
std::string query_type (const std::string &)
std::string query_val (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Additional Inherited Members
Protected Attributes inherited from MHAParser::range_var_t
float low_limit
Lower limit of range.
float up_limit
Upper limit of range.
bool low_incl
Lower limit is included (or excluded) in range.
bool up_incl
Upper limit is included (or excluded) in range.
bool check_low
Check lower limit.
bool check_up
Check upper limit.
bool check_range
Range checking is active.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Detailed Description
Vector variable with complex value.
Constructor & Destructor Documentation
MHAParser::vcomplex_t::vcomplex_t (const std::string & h, const std::string & v, const std::string & rg = "")
References MHAParser::base_t::data_is_initialized, and MHAParser::base_t::parse().
Member Function Documentation
std::string MHAParser::vcomplex_t::op_setval (expression_t & x) protected virtual
Reimplemented from MHAParser::variable_t.
References data, MHAParser::base_t::data_is_initialized, MHAParser::variable_t::op_setval(), MHAParser::expression_t::rval, MHAParser::StrCnv::str2val(), MHAParser::range_var_t::validate(), MHAParser::base_t::valuechanged, and MHAParser::base_t::writeaccess.
std::string MHAParser::vcomplex_t::query_type (const std::string & s) protected virtual
Reimplemented from MHAParser::base_t.
std::string MHAParser::vcomplex_t::query_val (const std::string & s) protected virtual
Reimplemented from MHAParser::base_t.
References data, MHAParser::base_t::prereadaccess, MHAParser::base_t::readaccess, and MHAParser::StrCnv::val2str().
Member Data Documentation
std::vector<mha_complex_t> MHAParser::vcomplex_t::data
Data field.
Referenced by op_setval(), and query_val().
The documentation for this class was generated from the following files:
mha_parser.hh
mha_parser.cpp