openMHA Manual: MHAMultiSrc::waveform_t Class Reference
MHAMultiSrc::waveform_t Class Reference
#include <mha_multisrc.h>
Public Member Functions
waveform_t (algo_comm_t iac, std::string name, unsigned int frames, unsigned int channels)
mha_wave_t * update (mha_wave_t *s)
Update data of waveform to hold actual input data.
Public Member Functions inherited from MHA_AC::waveform_t
waveform_t (algo_comm_t ac, std::string name, unsigned int frames, unsigned int channels, bool insert_now)
Create the AC variable.
~waveform_t ()
void insert ()
Insert AC variable into AC space.
Public Member Functions inherited from MHASignal::waveform_t
waveform_t (const unsigned int &frames, const unsigned int &channels)
constructor of waveform_t
waveform_t (const mhaconfig_t &cf)
Constructor to create a waveform from plugin configuration.
waveform_t (const mha_wave_t &src)
Copy contructor for mha_wave_t source.
waveform_t (const MHASignal::waveform_t &src)
Copy contructor.
waveform_t (const std::vector< mha_real_t > &src)
Copy contructor for std::vector<mha_real_t> source.
void operator= (const mha_real_t &v)
mha_real_t & operator[] (unsigned int k)
const mha_real_t & operator[] (unsigned int k) const
mha_real_t & value (unsigned int t, unsigned int ch)
Element accessor.
mha_real_t & operator() (unsigned int t, unsigned int ch)
Element accessor.
const mha_real_t & value (unsigned int t, unsigned int ch) const
Constant element accessor.
const mha_real_t & operator() (unsigned int t, unsigned int ch) const
Constant element accessor.
mha_real_t sum (const unsigned int &a, const unsigned int &b)
sum of all elements between [a,b) in all channels
mha_real_t sum (const unsigned int &a, const unsigned int &b, const unsigned int &ch)
sum of all elements between [a,b) in channel ch
mha_real_t sum ()
sum of all elements
mha_real_t sumsqr ()
sum of square of all elements
mha_real_t sum_channel (const unsigned int &)
return sum of all elements in one channel
void assign (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
set frame "k" in channel "ch" to value "val"
void assign (const mha_real_t &)
set all elements to value
void assign_frame (const unsigned int &k, const mha_real_t &val)
assign value "val" to frame k in all channels
void assign_channel (const unsigned int &c, const mha_real_t &val)
assign value "val" to channel ch in all frames
void copy (const std::vector< mha_real_t > &v)
void copy (const mha_wave_t &)
copy data from source into current waveform
void copy (const mha_wave_t *)
void copy_channel (const mha_wave_t &, unsigned int, unsigned int)
Copy one channel of a given waveform signal to a target channel.
void copy_from_at (unsigned int, unsigned int, const mha_wave_t &, unsigned int)
Copy part of the source signal into part of this waveform object.
void export_to (mha_wave_t &)
copy data into allocated mha_wave_t structure
void limit (const mha_real_t &min, const mha_real_t &max)
limit target to range [min,max]
void power (const waveform_t &)
transform waveform signal (in Pa) to squared signal (in W/m^2)
void powspec (const mha_spec_t &)
get the power spectrum (in W/m^2) from a complex spectrum
void scale (const unsigned int &a, const unsigned int &b, const unsigned int &ch, const mha_real_t &val)
scale section [a,b) in channel "ch" by "val"
void scale (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
scale one element
void scale_channel (const unsigned int &, const mha_real_t &)
scale one channel of target with a scalar
void scale_frame (const unsigned int &, const mha_real_t &)
unsigned int get_size () const
Public Member Functions inherited from MHAMultiSrc::base_t
base_t (algo_comm_t iac)
void select_source (const std::vector< std::string > &src, int in_channels)
Change the selection of input sources.
Additional Inherited Members
Public Attributes inherited from mha_wave_t
mha_real_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Protected Member Functions inherited from MHAPlugin::config_t< MHAMultiSrc::channels_t >
MHAMultiSrc::channels_t * poll_config ()
Receive the latest run time configuration.
MHAMultiSrc::channels_t * last_config ()
Receive the latest run time configuration.
void push_config (MHAMultiSrc::channels_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
config_t ()
~config_t ()
Protected Attributes inherited from MHA_AC::waveform_t
algo_comm_t ac
std::string name
Protected Attributes inherited from MHAMultiSrc::base_t
algo_comm_t ac
Protected Attributes inherited from MHAPlugin::config_t< MHAMultiSrc::channels_t >
MHAMultiSrc::channels_t * cfg
Constructor & Destructor Documentation
MHAMultiSrc::waveform_t::waveform_t (algo_comm_t iac, std::string name, unsigned int frames, unsigned int channels)
Member Function Documentation
mha_wave_t * MHAMultiSrc::waveform_t::update (mha_wave_t * s)
Update data of waveform to hold actual input data.
Parameters
s Input signal chunk
Returns
Return pointer to waveform structure
References MHAMultiSrc::base_t::ac, MHAPlugin::config_t< MHAMultiSrc::channels_t >::cfg, MHA_AC::get_var_waveform(), MHA_AC::waveform_t::insert(), MHA_AC::waveform_t::name, mha_wave_t::num_channels, mha_wave_t::num_frames, MHAPlugin::config_t< MHAMultiSrc::channels_t >::poll_config(), and MHASignal::waveform_t::value().
The documentation for this class was generated from the following files:
mha_multisrc.h
mha_multisrc.cpp