openMHA Manual: MHAOvlFilter::fscale_bw_t Class Reference
MHAOvlFilter::fscale_bw_t Class Reference
#include <mha_fftfb.hh>
Public Member Functions
fscale_bw_t (MHAParser::parser_t &parent)
std::vector< mha_real_t > get_bw_hz () const
Public Member Functions inherited from MHAOvlFilter::fscale_t
fscale_t (MHAParser::parser_t &parent)
std::vector< mha_real_t > get_f_hz () const
Protected Attributes
MHAParser::vfloat_t bw
MHAParser::vfloat_mon_t bw_hz
Private Member Functions
void update_hz ()
Private Attributes
MHAEvents::connector_t< fscale_bw_t > updater
Additional Inherited Members
Public Attributes inherited from MHAOvlFilter::fscale_t
scale_var_t unit
MHAParser::vfloat_t f
MHAParser::vfloat_mon_t f_hz
Constructor & Destructor Documentation
MHAOvlFilter::fscale_bw_t::fscale_bw_t (MHAParser::parser_t & parent)
References bw, and bw_hz.
Member Function Documentation
std::vector< mha_real_t > MHAOvlFilter::fscale_bw_t::get_bw_hz () const
References bw, MHAParser::vfloat_t::data, MHAOvlFilter::fscale_t::f, MHAOvlFilter::fscale_t::unit, and MHAOvlFilter::scale_var_t::unit2hz().
Referenced by update_hz().
void MHAOvlFilter::fscale_bw_t::update_hz () private
References bw_hz, MHAParser::vfloat_mon_t::data, and get_bw_hz().
Member Data Documentation
MHAParser::vfloat_t MHAOvlFilter::fscale_bw_t::bw protected
Referenced by fscale_bw_t(), and get_bw_hz().
MHAParser::vfloat_mon_t MHAOvlFilter::fscale_bw_t::bw_hz protected
Referenced by fscale_bw_t(), and update_hz().
MHAEvents::connector_t<fscale_bw_t> MHAOvlFilter::fscale_bw_t::updater private
The documentation for this class was generated from the following files:
mha_fftfb.hh
mha_fftfb.cpp