openMHA Manual: MHAParser::parser_t Class Reference
MHAParser::parser_t Class Reference
Parser node class.
#include <mha_parser.hh>
Public Member Functions
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Protected Member Functions
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Private Attributes
entry_map_t entries
std::string id_string
identification string
std::string srcfile
unsigned int srcline
std::string last_errormsg
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Detailed Description
Parser node class.
A parser_t instance is a node in the configuration tree. A parser node can contain any number of other parser_t instances or configuration language variables. These items are inserted into a parser node using the parser_t::insert_item method.
Constructor & Destructor Documentation
MHAParser::parser_t::parser_t (const std::string & help_text = "")
Construct detached node to be used in the configuration tree.
Parameters
help_text A text describing this node. E.g. if this node lives at the root of some MHA plugin, then the help text should describe the functionality of the plugin.
References MHAParser::base_t::activate_query(), MHAParser::base_t::query_entries(), MHAParser::base_t::query_listids(), MHAParser::base_t::query_readfile(), MHAParser::base_t::query_savefile(), MHAParser::base_t::query_savefile_compact(), MHAParser::base_t::query_savemons(), and MHAParser::base_t::query_val().
MHAParser::parser_t::~parser_t ()
References entries.
Member Function Documentation
void MHAParser::parser_t::insert_item (const std::string & n, MHAParser::base_t * e)
Register a parser item into this sub-parser.
This function registers an item under a given name into this sub-parser and makes it accessible to the parser interface.
Parameters
n Name of the item in the configuration tree
e C++ pointer to the item instance. e can either point to a variable, to a monitor, or to another sub-parser.
References MHAParser::base_t::add_parent_on_insert(), and entries.
Referenced by MHAFilter::adapt_filter_t::adapt_filter_t(), adm_if_t::adm_if_t(), mhachain::plugs_t::alloc_plugs(), calibrator_variables_t::calibrator_variables_t(), dc::dc_vars_t::dc_vars_t(), AuditoryProfile::parser_t::fmap_t::fmap_t(), fw_t::fw_t(), fw_vars_t::fw_vars_t(), MHAFilter::iir_filter_t::iir_filter_t(), windowselector_t::insert_items(), io_file_t::io_file_t(), MHAIOJack::io_jack_t::io_jack_t(), io_parser_t::io_parser_t(), io_tcp_parser_t::io_tcp_parser_t(), fw_t::load_io_lib(), MHAParser::mhapluginloader_t::load_plug(), fw_t::load_proc_lib(), mhachain::mhachain_t::mhachain_t(), MHAParser::mhapluginloader_t::mhapluginloader_t(), mhaserver_t::mhaserver_t(), overlapadd::overlapadd_if_t::overlapadd_if_t(), mhachain::plugs_t::plugs_t(), softclipper_variables_t::softclipper_variables_t(), and MHAParser::window_t::window_t().
void MHAParser::parser_t::remove_item (const std::string & n)
Remove an item by name.
If the item does not exist, an error is being reported.
Parameters
n Name of parser item to be removed from list.
References entries.
Referenced by mhachain::plugs_t::cleanup_plugs(), and MHAParser::base_t::~base_t().
void MHAParser::parser_t::force_remove_item (const std::string & n)
Remove an item by name.
Non-existing items are ignored.
Parameters
n Name of parser item to be removed from list.
References entries.
Referenced by mhachain::plugs_t::alloc_plugs(), MHAParser::mhapluginloader_t::load_plug(), mhachain::plugs_t::plugs_t(), mhachain::chain_base_t::update(), and mhachain::plugs_t::~plugs_t().
void MHAParser::parser_t::remove_item (const base_t * addr)
Remove an item by address.
The item belonging to an address is being removed from the list of items.
Parameters
addr Address of parser item to be removed.
References entries.
std::string MHAParser::parser_t::op_subparse (expression_t & x) protected virtual
Reimplemented from MHAParser::base_t.
References entries, MHAParser::expression_t::lval, MHAParser::base_t::parse(), and MHAParser::expression_t::rval.
std::string MHAParser::parser_t::op_setval (expression_t & x) protected virtual
Reimplemented from MHAParser::base_t.
References entries, MHAParser::expression_t::lval, MHAParser::expression_t::op, MHAParser::base_t::parse(), MHAParser::expression_t::rval, MHAParser::StrCnv::str2val(), and MHAParser::base_t::writeaccess.
std::string MHAParser::parser_t::op_query (expression_t & x) protected virtual
Reimplemented from MHAParser::base_t.
References entries, MHAParser::expression_t::lval, MHA_ErrorMsg, MHAParser::expression_t::op, MHAParser::base_t::queries, and MHAParser::expression_t::rval.
std::string MHAParser::parser_t::query_type (const std::string & s) protected virtual
Reimplemented from MHAParser::base_t.
std::string MHAParser::parser_t::query_dump (const std::string & s) protected virtual
Reimplemented from MHAParser::base_t.
References MHAParser::all_dump().
std::string MHAParser::parser_t::query_entries (const std::string & s) protected virtual
Reimplemented from MHAParser::base_t.
References entries.
std::string MHAParser::parser_t::query_readfile (const std::string & fname) protected virtual
Reimplemented from MHAParser::base_t.
References MHA_Error::get_msg(), last_errormsg, MHAParser::base_t::parse(), srcfile, srcline, and MHAParser::trim().
std::string MHAParser::parser_t::query_savefile (const std::string & fname) protected virtual
Reimplemented from MHAParser::base_t.
References MHAParser::cfg_dump(), and id_string.
std::string MHAParser::parser_t::query_savefile_compact (const std::string & fname) protected virtual
Reimplemented from MHAParser::base_t.
References MHAParser::cfg_dump_short(), and id_string.
std::string MHAParser::parser_t::query_savemons (const std::string & fname) protected virtual
Reimplemented from MHAParser::base_t.
References id_string, and MHAParser::mon_dump().
std::string MHAParser::parser_t::query_val (const std::string & s) protected virtual
Reimplemented from MHAParser::base_t.
References MHAParser::cfg_dump_short(), MHAParser::base_t::prereadaccess, and MHAParser::base_t::readaccess.
std::string MHAParser::parser_t::query_listids (const std::string & s) protected virtual
Reimplemented from MHAParser::base_t.
References MHAParser::all_ids().
void MHAParser::parser_t::set_id_string (const std::string & s) protected
References id_string.
Member Data Documentation
entry_map_t MHAParser::parser_t::entries private
Referenced by MHAParser::all_dump(), MHAParser::all_ids(), MHAParser::cfg_dump(), MHAParser::cfg_dump_short(), force_remove_item(), insert_item(), MHAParser::mon_dump(), op_query(), op_setval(), op_subparse(), query_entries(), remove_item(), and ~parser_t().
std::string MHAParser::parser_t::id_string private
identification string
Referenced by query_savefile(), query_savefile_compact(), query_savemons(), and set_id_string().
std::string MHAParser::parser_t::srcfile private
Referenced by query_readfile().
unsigned int MHAParser::parser_t::srcline private
Referenced by query_readfile().
std::string MHAParser::parser_t::last_errormsg private
Referenced by query_readfile().
The documentation for this class was generated from the following files:
mha_parser.hh
mha_parser.cpp