openMHA Manual: MHAFilter::iir_ord1_real_t Class Reference
MHAFilter::iir_ord1_real_t Class Reference
First order recursive filter.
#include <mha_filter.hh>
Public Member Functions
iir_ord1_real_t (std::vector< mha_real_t > A, std::vector< mha_real_t > B)
Constructor with filter coefficients (one per channel)
iir_ord1_real_t (std::vector< mha_real_t > tau, mha_real_t srate)
Constructor for low pass filter (one time constant per channel)
void set_state (mha_real_t val)
void set_state (std::vector< mha_real_t > val)
void set_state (mha_complex_t val)
mha_real_t operator() (unsigned int ch, mha_real_t x)
Filter method for real value input, one element.
mha_complex_t operator() (unsigned int ch, mha_complex_t x)
Filter method for complex input, one element.
void operator() (const mha_wave_t &X, mha_wave_t &Y)
Filter method for real value input.
void operator() (const mha_spec_t &X, mha_spec_t &Y)
Filter method for complex value input.
void operator() (const mha_wave_t &Xre, const mha_wave_t &Xim, mha_wave_t &Yre, mha_wave_t &Yim)
Filter method for complex value input.
Private Attributes
std::vector< mha_real_t > A_
std::vector< mha_real_t > B_
std::vector< mha_complex_t > Yn
Detailed Description
First order recursive filter.
Constructor & Destructor Documentation
MHAFilter::iir_ord1_real_t::iir_ord1_real_t (std::vector< mha_real_t > A, std::vector< mha_real_t > B)
Constructor with filter coefficients (one per channel)
MHAFilter::iir_ord1_real_t::iir_ord1_real_t (std::vector< mha_real_t > tau, mha_real_t srate)
Constructor for low pass filter (one time constant per channel)
References A_, B_, and MHAFilter::o1_lp_coeffs().
Member Function Documentation
void MHAFilter::iir_ord1_real_t::set_state (mha_real_t val)
References mha_complex(), and Yn.
void MHAFilter::iir_ord1_real_t::set_state (std::vector< mha_real_t > val)
References MHA_assert_equal, mha_complex(), and Yn.
void MHAFilter::iir_ord1_real_t::set_state (mha_complex_t val)
References Yn.
mha_real_t MHAFilter::iir_ord1_real_t::operator() (unsigned int ch, mha_real_t x) inline
Filter method for real value input, one element.
mha_complex_t MHAFilter::iir_ord1_real_t::operator() (unsigned int ch, mha_complex_t x) inline
Filter method for complex input, one element.
References mha_complex_t::im, and mha_complex_t::re.
void MHAFilter::iir_ord1_real_t::operator() (const mha_wave_t & X, mha_wave_t & Y) inline
Filter method for real value input.
References MHA_assert_equal, mha_wave_t::num_channels, mha_wave_t::num_frames, and value().
void MHAFilter::iir_ord1_real_t::operator() (const mha_spec_t & X, mha_spec_t & Y) inline
Filter method for complex value input.
References MHA_assert_equal, mha_spec_t::num_channels, mha_spec_t::num_frames, and value().
void MHAFilter::iir_ord1_real_t::operator() (const mha_wave_t & Xre, const mha_wave_t & Xim, mha_wave_t & Yre, mha_wave_t & Yim) inline
Filter method for complex value input.
References MHA_assert_equal, mha_wave_t::num_channels, mha_wave_t::num_frames, and value().
Member Data Documentation
std::vector<mha_real_t> MHAFilter::iir_ord1_real_t::A_ private
Referenced by iir_ord1_real_t().
std::vector<mha_real_t> MHAFilter::iir_ord1_real_t::B_ private
Referenced by iir_ord1_real_t().
std::vector<mha_complex_t> MHAFilter::iir_ord1_real_t::Yn private
Referenced by set_state().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp