openMHA Manual: MHAFilter::iir_filter_t Class Reference
MHAFilter::iir_filter_t Class Reference
IIR filter class wrapper for integration into parser structure.
#include <mha_filter.hh>
Public Member Functions
iir_filter_t (std::string help="IIR filter structure", std::string def_A="[1]", std::string def_B="[1]", unsigned int channels=1)
Constructor of the IIR filter.
void filter (mha_wave_t *y, const mha_wave_t *x)
The filter processes the audio signal.
mha_real_t filter (mha_real_t x, unsigned int ch)
Filter a single audio sample.
void resize (unsigned int channels)
Change the number of channels after object creation.
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Private Member Functions
void update_filter ()
Private Member Functions inherited from MHAPlugin::config_t< iir_filter_state_t >
config_t ()
~config_t ()
iir_filter_state_t * poll_config ()
Receive the latest run time configuration.
iir_filter_state_t * last_config ()
Receive the latest run time configuration.
void push_config (iir_filter_state_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Private Attributes
MHAParser::vfloat_t A
MHAParser::vfloat_t B
MHAEvents::patchbay_t< iir_filter_t > connector
unsigned int nchannels
Private Attributes inherited from MHAPlugin::config_t< iir_filter_state_t >
iir_filter_state_t * cfg
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Detailed Description
IIR filter class wrapper for integration into parser structure.
This class implements an infinite impulse response filter. Since it inherits from MHAParser::parser_t, it can easily be integrated in the MHA configuration tree. It provides the configuration language variables "A" (vector of recursive filter coefficients) and "B" (vector of non-recursive filter coefficients).
The filter instance reacts to changes in filter coefficients through the MHA configuration language, and uses the updated coefficients in the next invocation of the filter method.
Update of the coefficients is thread-safe and non-blocking. Simply add this subparser to your parser items and use the "filter" member function. Filter states are reset to all 0 on update.
Constructor & Destructor Documentation
MHAFilter::iir_filter_t::iir_filter_t (std::string help = "IIR filter structure", std::string def_A = "[1]", std::string def_B = "[1]", unsigned int channels = 1)
Constructor of the IIR filter.
Initialises the sub-parser structure and the memory for holding the filter's state.
Parameters
help The help string for the parser that groups the configuration variables of this filter. Could be used to describe the purpose of this IIR filter.
def_A The initial value of the vector of the recursive filter coefficients, represented as string.
def_B The initial value of the vector of the non-recursive filter coefficients, represented as string.
channels The number of indipendent audio channels to process with this filter. Needed to allocate a state vector for each audio channel.
References A, B, connector, MHAParser::parser_t::insert_item(), update_filter(), and MHAParser::base_t::writeaccess.
Member Function Documentation
void MHAFilter::iir_filter_t::filter (mha_wave_t * y, const mha_wave_t * x)
The filter processes the audio signal.
All channels in the audio signal are processed using the same filter coefficients. Indipendent state is stored between calls for each audio channel.
Parameters
y Pointer to output signal holder. The output signal is stored here. Has to have the same signal dimensions as the input signal x. In-place processing (y and x pointing to the same signal holder) is possible.
x Pointer to input signal holder. Number of channels has to be the same as given to the constructor, or to the resize method.
References MHAPlugin::config_t< iir_filter_state_t >::cfg, MHAFilter::filter_t::filter(), and MHAPlugin::config_t< iir_filter_state_t >::poll_config().
mha_real_t MHAFilter::iir_filter_t::filter (mha_real_t x, unsigned int ch)
Filter a single audio sample.
Parameters
x The single audio sample
ch Zero-based channel index. Use and change the state of channel ch. ch has to be less than the number of channels given to the constructor or the resize method.
Returns
the filtered result sample.
References MHAPlugin::config_t< iir_filter_state_t >::cfg, MHAFilter::filter_t::filter(), and MHAPlugin::config_t< iir_filter_state_t >::poll_config().
void MHAFilter::iir_filter_t::resize (unsigned int channels)
Change the number of channels after object creation.
Parameters
channels The new number of channels. Old filter states are lost.
References channels(), nchannels, and update_filter().
void MHAFilter::iir_filter_t::update_filter () private
References A, B, MHAParser::vfloat_t::data, nchannels, and MHAPlugin::config_t< iir_filter_state_t >::push_config().
Referenced by iir_filter_t(), and resize().
Member Data Documentation
MHAParser::vfloat_t MHAFilter::iir_filter_t::A private
Referenced by iir_filter_t(), and update_filter().
MHAParser::vfloat_t MHAFilter::iir_filter_t::B private
Referenced by iir_filter_t(), and update_filter().
MHAEvents::patchbay_t<iir_filter_t> MHAFilter::iir_filter_t::connector private
Referenced by iir_filter_t().
unsigned int MHAFilter::iir_filter_t::nchannels private
Referenced by resize(), and update_filter().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp