openMHA Manual: MHAKernel::algo_comm_class_t Class Reference
MHAKernel::algo_comm_class_t Class Reference
#include <mha_algo_comm.hh>
Public Member Functions
algo_comm_class_t ()
virtual ~algo_comm_class_t ()
algo_comm_t get_c_handle ()
virtual void local_insert_var (const char *, comm_var_t)
virtual void local_remove_var (const char *)
virtual void local_remove_ref (void *)
virtual bool local_is_var (const char *)
virtual void local_get_var (const char *, comm_var_t *)
virtual std::string local_get_entries ()
virtual comm_var_map_t::size_type size () const
Static Public Member Functions
static int insert_var (void *, const char *, comm_var_t)
static int insert_var_int (void *, const char *, int *)
static int insert_var_float (void *, const char *, float *)
static int remove_var (void *, const char *)
static int remove_ref (void *, void *)
static int is_var (void *, const char *)
static int get_var (void *, const char *, comm_var_t *)
static int get_var_int (void *, const char *, int *)
static int get_var_float (void *, const char *, float *)
static int get_entries (void *, char *, unsigned int)
static const char * get_error (int)
Public Attributes
char * algo_comm_id_string
Private Attributes
algo_comm_t ac
int algo_comm_id_string_len
comm_var_map_t vars
Constructor & Destructor Documentation
MHAKernel::algo_comm_class_t::algo_comm_class_t ()
References ac, algo_comm_default, ALGO_COMM_ID_STR, algo_comm_id_string, algo_comm_id_string_len, algo_comm_t::handle, and vars.
MHAKernel::algo_comm_class_t::~algo_comm_class_t () virtual
References algo_comm_id_string, and algo_comm_id_string_len.
Member Function Documentation
algo_comm_t MHAKernel::algo_comm_class_t::get_c_handle ()
References ac.
Referenced by fw_t::load_proc_lib(), and main().
int MHAKernel::algo_comm_class_t::insert_var (void * handle, const char * name, comm_var_t var) static
References MHAKernel::algo_comm_safe_cast(), MHA_Error::get_msg(), last_error_str, and local_insert_var().
int MHAKernel::algo_comm_class_t::insert_var_int (void * handle, const char * name, int * ivar) static
References MHAKernel::algo_comm_safe_cast(), comm_var_t::data, comm_var_t::data_type, MHA_Error::get_msg(), last_error_str, local_insert_var(), MHA_AC_INT, comm_var_t::num_entries, and comm_var_t::stride.
int MHAKernel::algo_comm_class_t::insert_var_float (void * handle, const char * name, float * ivar) static
References MHAKernel::algo_comm_safe_cast(), comm_var_t::data, comm_var_t::data_type, MHA_Error::get_msg(), last_error_str, local_insert_var(), MHA_AC_FLOAT, comm_var_t::num_entries, and comm_var_t::stride.
int MHAKernel::algo_comm_class_t::remove_var (void * handle, const char * name) static
References MHAKernel::algo_comm_safe_cast(), MHA_Error::get_msg(), last_error_str, and local_remove_var().
int MHAKernel::algo_comm_class_t::remove_ref (void * handle, void * ref) static
References MHAKernel::algo_comm_safe_cast(), MHA_Error::get_msg(), last_error_str, and local_remove_ref().
int MHAKernel::algo_comm_class_t::is_var (void * handle, const char * name) static
References MHAKernel::algo_comm_safe_cast(), and local_is_var().
int MHAKernel::algo_comm_class_t::get_var (void * handle, const char * name, comm_var_t * var) static
References MHAKernel::algo_comm_safe_cast(), MHA_Error::get_msg(), last_error_str, and local_get_var().
int MHAKernel::algo_comm_class_t::get_var_int (void * handle, const char * name, int * ivar) static
References MHAKernel::algo_comm_safe_cast(), comm_var_t::data, comm_var_t::data_type, MHA_Error::get_msg(), last_error_str, local_get_var(), MHA_AC_INT, MHA_ErrorMsg, and comm_var_t::num_entries.
int MHAKernel::algo_comm_class_t::get_var_float (void * handle, const char * name, float * ivar) static
References MHAKernel::algo_comm_safe_cast(), comm_var_t::data, comm_var_t::data_type, MHA_Error::get_msg(), last_error_str, local_get_var(), MHA_AC_FLOAT, MHA_ErrorMsg, and comm_var_t::num_entries.
int MHAKernel::algo_comm_class_t::get_entries (void * handle, char * ret, unsigned int len) static
References MHAKernel::algo_comm_safe_cast(), and local_get_entries().
const char * MHAKernel::algo_comm_class_t::get_error (int e) static
References last_error_str.
void MHAKernel::algo_comm_class_t::local_insert_var (const char * name, comm_var_t var) virtual
References MHA_ErrorMsg, and vars.
Referenced by insert_var(), insert_var_float(), and insert_var_int().
void MHAKernel::algo_comm_class_t::local_remove_var (const char * name) virtual
References MHAKernel::comm_var_map_t::has_key(), MHA_ErrorMsg, and vars.
Referenced by remove_var().
void MHAKernel::algo_comm_class_t::local_remove_ref (void * addr) virtual
References vars.
Referenced by remove_ref().
bool MHAKernel::algo_comm_class_t::local_is_var (const char * name) virtual
References MHAKernel::comm_var_map_t::has_key(), and vars.
Referenced by is_var().
void MHAKernel::algo_comm_class_t::local_get_var (const char * name, comm_var_t * var) virtual
References MHAKernel::comm_var_map_t::has_key(), MHA_ErrorMsg, and vars.
Referenced by get_var(), get_var_float(), and get_var_int().
std::string MHAKernel::algo_comm_class_t::local_get_entries () virtual
References vars.
Referenced by latex_doc_t::get_ac(), get_entries(), and print_ac().
MHAKernel::comm_var_map_t::size_type MHAKernel::algo_comm_class_t::size () const virtual
References vars.
Member Data Documentation
char* MHAKernel::algo_comm_class_t::algo_comm_id_string
Referenced by algo_comm_class_t(), MHAKernel::algo_comm_safe_cast(), and ~algo_comm_class_t().
algo_comm_t MHAKernel::algo_comm_class_t::ac private
Referenced by algo_comm_class_t(), and get_c_handle().
int MHAKernel::algo_comm_class_t::algo_comm_id_string_len private
Referenced by algo_comm_class_t(), and ~algo_comm_class_t().
comm_var_map_t MHAKernel::algo_comm_class_t::vars private
Referenced by algo_comm_class_t(), local_get_entries(), local_get_var(), local_insert_var(), local_is_var(), local_remove_ref(), local_remove_var(), and size().
The documentation for this class was generated from the following files:
mha_algo_comm.hh
mha_algo_comm.cpp