openMHA Manual: MHAFilter::smoothspec_t Class Reference
MHAFilter::smoothspec_t Class Reference
Smooth spectral gains, create a windowed impulse response.
#include <mha_filter.hh>
Public Member Functions
smoothspec_t (unsigned int fftlen, unsigned int nchannels, const MHAWindow::base_t &window, bool minphase, bool linphase_asym=false)
Constructor.
void smoothspec (const mha_spec_t &s_in, mha_spec_t &s_out)
Create a smoothed spectrum.
void smoothspec (mha_spec_t &spec)
Create a smoothed spectrum (in place)
void spec2fir (const mha_spec_t &spec, mha_wave_t &fir)
Return FIR coefficients.
~smoothspec_t ()
Private Member Functions
void internal_fir (const mha_spec_t &)
Private Attributes
unsigned int fftlen
unsigned int nchannels
MHAWindow::base_t window
MHASignal::waveform_t tmp_wave
MHASignal::spectrum_t tmp_spec
MHASignal::minphase_t * minphase
bool _linphase_asym
mha_fft_t fft
Detailed Description
Smooth spectral gains, create a windowed impulse response.
Spectral gains are smoothed by multiplicating the impulse response with a window function.
If a minimal phase is used, then the original phase is discarded and replaced by the minimal phase function. In this case, the window is applied to the beginning of the inverse Fourier transform of the input spectrum, and the remaining signal set to zero. If the original phase is kept, the window is applied symmetrical arround zero, i.e. to the first and last samples of the inverse Fourier transform of the input spectrum. The spec2fir() function creates a causal impulse response by circular shifting the impulse response by half of the window length.
The signal dimensions of the arguments of smoothspec() must correspond to the FFT length and number of channels provided in the constructor. The function spec2fir() can fill signal structures with more than window length frames.
Constructor & Destructor Documentation
MHAFilter::smoothspec_t::smoothspec_t (unsigned int fftlen, unsigned int nchannels, const MHAWindow::base_t & window, bool minphase, bool linphase_asym = false)
Constructor.
Parameters
fftlen FFT length of input spectrum (fftlen/2+1 bins)
nchannels Number of channels in input spectrum
window Window used for smoothing
minphase Use minimal phase (true) or original phase (false)
linphase_asym Keep phase, but apply full window at beginning of IRS
References fftlen, minphase, nchannels, mha_wave_t::num_frames, and window.
MHAFilter::smoothspec_t::~smoothspec_t ()
References fft, mha_fft_free(), and minphase.
Member Function Documentation
void MHAFilter::smoothspec_t::smoothspec (const mha_spec_t & s_in, mha_spec_t & s_out)
Create a smoothed spectrum.
Parameters
s_in Input spectrum
Return values
s_out Output spectrum
References fft, internal_fir(), mha_fft_wave2spec(), and tmp_wave.
void MHAFilter::smoothspec_t::smoothspec (mha_spec_t & spec) inline
Create a smoothed spectrum (in place)
Parameters
spec Spectrum to be smoothed.
References smoothspec(), and MHAFilter::spec2fir().
Referenced by smoothspec().
void MHAFilter::smoothspec_t::spec2fir (const mha_spec_t & spec, mha_wave_t & fir)
Return FIR coefficients.
Parameters
spec Input spectrum
Return values
fir FIR coefficients, minimum length is window length
References clear(), fftlen, internal_fir(), minphase, nchannels, mha_wave_t::num_channels, mha_wave_t::num_frames, tmp_wave, value(), MHASignal::waveform_t::value(), and window.
Referenced by MHAFilter::spec2fir().
void MHAFilter::smoothspec_t::internal_fir (const mha_spec_t & s_in) private
References _linphase_asym, MHASignal::spectrum_t::copy(), fft, fftlen, mha_fft_spec2wave(), minphase, nchannels, mha_wave_t::num_frames, tmp_spec, tmp_wave, MHASignal::waveform_t::value(), and window.
Referenced by smoothspec(), and spec2fir().
Member Data Documentation
unsigned int MHAFilter::smoothspec_t::fftlen private
Referenced by internal_fir(), smoothspec_t(), and spec2fir().
unsigned int MHAFilter::smoothspec_t::nchannels private
Referenced by internal_fir(), smoothspec_t(), and spec2fir().
MHAWindow::base_t MHAFilter::smoothspec_t::window private
Referenced by internal_fir(), smoothspec_t(), and spec2fir().
MHASignal::waveform_t MHAFilter::smoothspec_t::tmp_wave private
Referenced by internal_fir(), smoothspec(), and spec2fir().
MHASignal::spectrum_t MHAFilter::smoothspec_t::tmp_spec private
Referenced by internal_fir().
MHASignal::minphase_t* MHAFilter::smoothspec_t::minphase private
Referenced by internal_fir(), smoothspec_t(), spec2fir(), and ~smoothspec_t().
bool MHAFilter::smoothspec_t::_linphase_asym private
Referenced by internal_fir().
mha_fft_t MHAFilter::smoothspec_t::fft private
Referenced by internal_fir(), smoothspec(), and ~smoothspec_t().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp