openMHA Manual: MHAFilter::blockprocessing_polyphase_resampling_t Class Reference
MHAFilter::blockprocessing_polyphase_resampling_t Class Reference
A class that does polyphase resampling and takes into account block processing.
#include <mha_filter.hh>
Public Member Functions
blockprocessing_polyphase_resampling_t (float source_srate, unsigned source_fragsize, float target_srate, unsigned target_fragsize, float nyquist_ratio, float irslen, unsigned nchannels, bool add_delay)
Contructs a polyphase resampling filter that can be used for blockprocessing with the given parameters.
virtual ~blockprocessing_polyphase_resampling_t ()
void write (mha_wave_t &signal)
Write signal to the ringbuffer.
void read (mha_wave_t &signal)
Read resampled signal.
bool can_read () const
Checks if the resampling ring buffer can produce another output signal block.
Private Attributes
polyphase_resampling_t * resampling
unsigned fragsize_in
unsigned fragsize_out
unsigned num_channels
Detailed Description
A class that does polyphase resampling and takes into account block processing.
Constructor & Destructor Documentation
MHAFilter::blockprocessing_polyphase_resampling_t::blockprocessing_polyphase_resampling_t (float source_srate, unsigned source_fragsize, float target_srate, unsigned target_fragsize, float nyquist_ratio, float irslen, unsigned nchannels, bool add_delay)
Contructs a polyphase resampling filter that can be used for blockprocessing with the given parameters.
Parameters
source_srate Source sampling rate / Hz
source_fragsize Fragment size of incoming audio blocks / frames at source_srate
target_srate Target sampling rate / Hz
target_fragsize Fragment size of produced audio blocks / frames at target_srate
nyquist_ratio Low pass filter cutoff frequency relative to the nyquist frequency of the smaller of the two sampling rates. Example values: 0.8, 0.9
irslen Impulse response length used for low pass filtering / s
nchannels Number of audio channels
add_delay To avoid underruns, a delay is generally necessary for round trip block size adaptations. It is only necessary to add this delay to one of the two resampling chains. Set this parameter to true for the first resampling object of a round trip pair. It will add the necessary delay, and calculate the size of the ring buffer appropriately, When set to false, only the ringbuffer size will be set sufficiently.
References MHAFilter::gcd(), MHASignal::max(), resampling, MHAFilter::resampling_factors(), MHAFilter::polyphase_resampling_t::write(), and write().
Referenced by MHAFilter::polyphase_resampling_t::read().
virtual MHAFilter::blockprocessing_polyphase_resampling_t::~blockprocessing_polyphase_resampling_t () inline virtual
Member Function Documentation
void MHAFilter::blockprocessing_polyphase_resampling_t::write (mha_wave_t & signal)
Write signal to the ringbuffer.
Parameters
signal input signal in original sampling rate
Exceptions
MHA_Error Raises exception if there is not enough room, if the number of channels does not match, or if the number of frames is not equal to the number specified in the constructor
References fragsize_in, mha_wave_t::num_frames, read(), resampling, and MHAFilter::polyphase_resampling_t::write().
Referenced by blockprocessing_polyphase_resampling_t().
void MHAFilter::blockprocessing_polyphase_resampling_t::read (mha_wave_t & signal)
Read resampled signal.
Will perform the resampling and remove no longer needed samples from the input buffer.
Parameters
signal buffer to write the resampled signal to.
Exceptions
MHA_Error Raises exception if there is not enough input signal, if the number of channels of frames does not match.
References fragsize_out, mha_wave_t::num_channels, num_channels, mha_wave_t::num_frames, MHAFilter::polyphase_resampling_t::read(), and resampling.
Referenced by write().
bool MHAFilter::blockprocessing_polyphase_resampling_t::can_read () const inline
Checks if the resampling ring buffer can produce another output signal block.
References MHAFilter::polyphase_resampling_t::readable_frames().
Member Data Documentation
polyphase_resampling_t* MHAFilter::blockprocessing_polyphase_resampling_t::resampling private
Referenced by blockprocessing_polyphase_resampling_t(), read(), and write().
unsigned MHAFilter::blockprocessing_polyphase_resampling_t::fragsize_in private
Referenced by write().
unsigned MHAFilter::blockprocessing_polyphase_resampling_t::fragsize_out private
Referenced by read().
unsigned MHAFilter::blockprocessing_polyphase_resampling_t::num_channels private
Referenced by read().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp