openMHA Manual: MHAFilter::resampling_filter_t Class Reference
MHAFilter::resampling_filter_t Class Reference
Hann shaped low pass filter for resampling.
#include <mha_filter.hh>
Public Member Functions
resampling_filter_t (unsigned int fftlen, unsigned int irslen, unsigned int channels, unsigned int Nup, unsigned int Ndown, double fCutOff)
Constructor.
Public Member Functions inherited from MHAFilter::fftfilter_t
fftfilter_t (unsigned int fragsize, unsigned int channels, unsigned int fftlen)
Constructor.
~fftfilter_t ()
void update_coeffs (const mha_wave_t *pwIRS)
Update the set of coefficients.
void filter (const mha_wave_t *pwIn, mha_wave_t **ppwOut, const mha_wave_t *pwIRS)
Apply filter with changing coefficients to a waveform fragment.
void filter (const mha_wave_t *pwIn, mha_wave_t **ppwOut)
Apply filter to waveform fragment, without changing the coefficients.
void filter (const mha_wave_t *pwIn, mha_wave_t **ppwOut, const mha_spec_t *psWeights)
Apply filter with changing coefficients to a waveform fragment.
Static Public Member Functions
static unsigned int fragsize_validator (unsigned int fftlen, unsigned int irslen)
Private Attributes
unsigned int fragsize
Detailed Description
Hann shaped low pass filter for resampling.
This class uses FFT filter at upsampled rate.
Constructor & Destructor Documentation
MHAFilter::resampling_filter_t::resampling_filter_t (unsigned int fftlen, unsigned int irslen, unsigned int channels, unsigned int Nup, unsigned int Ndown, double fCutOff)
Constructor.
Parameters
fftlen FFT length.
irslen Length of filter.
channels Number of channels to be filtered.
Nup Upsampling ratio.
Ndown Downsampling ratio.
fCutOff Cut off frequency (relative to lower Nyquist Frequency)
References MHASignal::copy_channel(), MHAOvlFilter::ShapeFun::hann(), M_PI, MHASignal::max(), mha_wave_t::num_channels, mha_wave_t::num_frames, MHAFilter::sinc(), MHASignal::waveform_t::sum(), MHAFilter::fftfilter_t::update_coeffs(), and MHASignal::waveform_t::value().
Member Function Documentation
unsigned int MHAFilter::resampling_filter_t::fragsize_validator (unsigned int fftlen, unsigned int irslen) static
Member Data Documentation
unsigned int MHAFilter::resampling_filter_t::fragsize private
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp