openMHA Manual: MHAFilter::adapt_filter_t Class Reference
MHAFilter::adapt_filter_t Class Reference
Adaptive filter.
#include <mha_filter.hh>
Public Member Functions
adapt_filter_t (std::string)
void filter (mha_wave_t y, mha_wave_t e, mha_wave_t x, mha_wave_t d)
void set_channelcnt (unsigned int)
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Private Member Functions
void update_mu ()
void update_ntaps ()
Private Member Functions inherited from MHAPlugin::config_t< adapt_filter_state_t >
config_t ()
~config_t ()
adapt_filter_state_t * poll_config ()
Receive the latest run time configuration.
adapt_filter_state_t * last_config ()
Receive the latest run time configuration.
void push_config (adapt_filter_state_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Private Member Functions inherited from MHAPlugin::config_t< adapt_filter_param_t >
config_t ()
~config_t ()
adapt_filter_param_t * poll_config ()
Receive the latest run time configuration.
adapt_filter_param_t * last_config ()
Receive the latest run time configuration.
void push_config (adapt_filter_param_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Private Attributes
MHAParser::float_t mu
MHAParser::int_t ntaps
MHAParser::bool_t err_in
MHAEvents::patchbay_t< adapt_filter_t > connector
unsigned int nchannels
Private Attributes inherited from MHAPlugin::config_t< adapt_filter_state_t >
adapt_filter_state_t * cfg
Private Attributes inherited from MHAPlugin::config_t< adapt_filter_param_t >
adapt_filter_param_t * cfg
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Detailed Description
Adaptive filter.
Constructor & Destructor Documentation
MHAFilter::adapt_filter_t::adapt_filter_t (std::string help)
References connector, err_in, MHAParser::parser_t::insert_item(), mu, ntaps, update_mu(), update_ntaps(), and MHAParser::base_t::writeaccess.
Member Function Documentation
void MHAFilter::adapt_filter_t::filter (mha_wave_t y, mha_wave_t e, mha_wave_t x, mha_wave_t d)
References err_in, mu, and MHAPlugin::config_t< runtime_cfg_t >::poll_config().
void MHAFilter::adapt_filter_t::set_channelcnt (unsigned int nch)
References nchannels, update_mu(), and update_ntaps().
void MHAFilter::adapt_filter_t::update_mu () private
References MHAParser::bool_t::data, MHAParser::float_t::data, err_in, mu, and MHAPlugin::config_t< runtime_cfg_t >::push_config().
Referenced by adapt_filter_t(), and set_channelcnt().
void MHAFilter::adapt_filter_t::update_ntaps () private
References MHAParser::int_t::data, nchannels, ntaps, and MHAPlugin::config_t< runtime_cfg_t >::push_config().
Referenced by adapt_filter_t(), and set_channelcnt().
Member Data Documentation
MHAParser::float_t MHAFilter::adapt_filter_t::mu private
Referenced by adapt_filter_t(), filter(), and update_mu().
MHAParser::int_t MHAFilter::adapt_filter_t::ntaps private
Referenced by adapt_filter_t(), and update_ntaps().
MHAParser::bool_t MHAFilter::adapt_filter_t::err_in private
Referenced by adapt_filter_t(), filter(), and update_mu().
MHAEvents::patchbay_t<adapt_filter_t> MHAFilter::adapt_filter_t::connector private
Referenced by adapt_filter_t().
unsigned int MHAFilter::adapt_filter_t::nchannels private
Referenced by set_channelcnt(), and update_ntaps().
The documentation for this class was generated from the following files:
mha_filter.hh
mha_filter.cpp