openMHA Manual: MHAParser::window_t Class Reference
MHAParser::window_t Class Reference
The MHA Toolbox library » Vector and matrix processing toolbox
MHA configuration interface for a window function generator.
#include <mha_windowparser.h>
Public Types
enum wtype_t {
wnd_rect =0, wnd_hann =1, wnd_hamming =2, wnd_blackman =3,
wnd_bartlett =4, wnd_user =5
}
Public Member Functions
window_t (const std::string &help="Window type configuration.")
Constructor to create parser class.
MHAWindow::base_t get_window (unsigned int len) const
Create a window instance, use default parameters.
MHAWindow::base_t get_window (unsigned int len, float xmin) const
Create a window instance.
MHAWindow::base_t get_window (unsigned int len, float xmin, float xmax) const
Create a window instance.
MHAWindow::base_t get_window (unsigned int len, float xmin, float xmax, bool minincluded) const
Create a window instance.
MHAWindow::base_t get_window (unsigned int len, float xmin, float xmax, bool minincluded, bool maxincluded) const
Create a window instance.
MHAParser::window_t::wtype_t get_type () const
Return currently selected window type.
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Private Attributes
MHAParser::kw_t wtype
MHAParser::vfloat_t user
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Detailed Description
MHA configuration interface for a window function generator.
This class implements a configuration interface (sub-parser) for window type selection and user-defined window type. It provides member functions to generate an instance of MHAWindow::base_t based on the values provided by the configuration interface.
The configuration interface is derived from MHAParser::parser_t and can thus be inserted into the configuration tree using the insert_item() method of the parent parser.
If one of the pre-defined window types is used, then the window is generated using the MHAWindow::fun_t class constructor; for the user-defined type the values from the "user" variable are copied.
Member Enumeration Documentation
enum MHAParser::window_t::wtype_t
Enumerator
wnd_rect
wnd_hann
wnd_hamming
wnd_blackman
wnd_bartlett
wnd_user
Constructor & Destructor Documentation
MHAParser::window_t::window_t (const std::string & help = "Window type configuration.")
Constructor to create parser class.
References MHAParser::parser_t::insert_item(), user, and wtype.
Member Function Documentation
MHAWindow::base_t MHAParser::window_t::get_window (unsigned int len) const
Create a window instance, use default parameters.
References MHAParser::vfloat_t::data, get_type(), user, wnd_funs, and wnd_user.
Referenced by MHAOvlFilter::overlap_save_filterbank_t::overlap_save_filterbank_t(), and overlapadd::overlapadd_t::overlapadd_t().
MHAWindow::base_t MHAParser::window_t::get_window (unsigned int len, float xmin) const
Create a window instance.
References MHAParser::vfloat_t::data, get_type(), user, wnd_funs, and wnd_user.
MHAWindow::base_t MHAParser::window_t::get_window (unsigned int len, float xmin, float xmax) const
Create a window instance.
References MHAParser::vfloat_t::data, get_type(), user, wnd_funs, and wnd_user.
MHAWindow::base_t MHAParser::window_t::get_window (unsigned int len, float xmin, float xmax, bool minincluded) const
Create a window instance.
References MHAParser::vfloat_t::data, get_type(), user, wnd_funs, and wnd_user.
MHAWindow::base_t MHAParser::window_t::get_window (unsigned int len, float xmin, float xmax, bool minincluded, bool maxincluded) const
Create a window instance.
References MHAParser::vfloat_t::data, get_type(), user, wnd_funs, and wnd_user.
MHAParser::window_t::wtype_t MHAParser::window_t::get_type () const
Return currently selected window type.
References MHAParser::kw_t::data, MHAParser::keyword_list_t::get_index(), and wtype.
Referenced by get_window(), and overlapadd::overlapadd_t::overlapadd_t().
Member Data Documentation
MHAParser::kw_t MHAParser::window_t::wtype private
Referenced by get_type(), and window_t().
MHAParser::vfloat_t MHAParser::window_t::user private
Referenced by get_window(), and window_t().
The documentation for this class was generated from the following files:
mha_windowparser.h
mha_windowparser.cpp