openMHA Manual: MHAParser::mhapluginloader_t Class Reference
MHAParser::mhapluginloader_t Class Reference
Class to create a plugin loader in a parser, including the load logic.
#include <mhapluginloader.h>
Public Member Functions
mhapluginloader_t (MHAParser::parser_t &parent, algo_comm_t ac, const std::string &plugname_name="plugin_name", const std::string &prefix="")
~mhapluginloader_t ()
void prepare (mhaconfig_t &cf)
void release ()
void process (mha_wave_t *sIn, mha_wave_t **sOut)
void process (mha_spec_t *sIn, mha_spec_t **sOut)
void process (mha_wave_t *sIn, mha_spec_t **sOut)
void process (mha_spec_t *sIn, mha_wave_t **sOut)
mhaconfig_t get_cfin () const
mhaconfig_t get_cfout () const
Protected Attributes
PluginLoader::mhapluginloader_t * plug
Private Member Functions
void load_plug ()
Private Attributes
MHAParser::parser_t & parent_
MHAParser::string_t plugname
std::string prefix_
MHAEvents::connector_t< mhapluginloader_t > connector
algo_comm_t ac_
std::string last_name
std::string plugname_name_
mhaconfig_t cf_in_
mhaconfig_t cf_out_
Static Private Attributes
static double bookkeeping
Detailed Description
Class to create a plugin loader in a parser, including the load logic.
Constructor & Destructor Documentation
MHAParser::mhapluginloader_t::mhapluginloader_t (MHAParser::parser_t & parent, algo_comm_t ac, const std::string & plugname_name = "plugin_name", const std::string & prefix = "")
References cf_in_, cf_out_, MHAParser::parser_t::insert_item(), parent_, and plugname.
MHAParser::mhapluginloader_t::~mhapluginloader_t ()
References plug.
Member Function Documentation
void MHAParser::mhapluginloader_t::prepare (mhaconfig_t & cf)
References cf_in_, cf_out_, plug, plugname, plugname_name_, PluginLoader::mhapluginloader_t::prepare(), and MHAParser::variable_t::setlock().
Referenced by overlapadd::overlapadd_if_t::prepare(), and bbcalib_interface_t::prepare().
void MHAParser::mhapluginloader_t::release ()
References cf_in_, cf_out_, plug, plugname, PluginLoader::mhapluginloader_t::release(), and MHAParser::variable_t::setlock().
Referenced by overlapadd::overlapadd_if_t::release(), and bbcalib_interface_t::release().
void MHAParser::mhapluginloader_t::process (mha_wave_t * sIn, mha_wave_t ** sOut) inline
Referenced by overlapadd::overlapadd_if_t::process(), and bbcalib_interface_t::process().
void MHAParser::mhapluginloader_t::process (mha_spec_t * sIn, mha_spec_t ** sOut) inline
void MHAParser::mhapluginloader_t::process (mha_wave_t * sIn, mha_spec_t ** sOut) inline
void MHAParser::mhapluginloader_t::process (mha_spec_t * sIn, mha_wave_t ** sOut) inline
mhaconfig_t MHAParser::mhapluginloader_t::get_cfin () const inline
mhaconfig_t MHAParser::mhapluginloader_t::get_cfout () const inline
void MHAParser::mhapluginloader_t::load_plug () private
References ac_, MHAParser::string_t::data, MHAParser::parser_t::force_remove_item(), PluginLoader::config_file_splitter_t::get_configname(), PluginLoader::mhapluginloader_t::has_parser(), MHAParser::parser_t::insert_item(), last_name, parent_, plug, plugname, and prefix_.
Member Data Documentation
PluginLoader::mhapluginloader_t* MHAParser::mhapluginloader_t::plug protected
Referenced by load_plug(), prepare(), release(), and ~mhapluginloader_t().
MHAParser::parser_t& MHAParser::mhapluginloader_t::parent_ private
Referenced by load_plug(), and mhapluginloader_t().
MHAParser::string_t MHAParser::mhapluginloader_t::plugname private
Referenced by load_plug(), mhapluginloader_t(), prepare(), and release().
std::string MHAParser::mhapluginloader_t::prefix_ private
Referenced by load_plug().
MHAEvents::connector_t<mhapluginloader_t> MHAParser::mhapluginloader_t::connector private
algo_comm_t MHAParser::mhapluginloader_t::ac_ private
Referenced by load_plug().
std::string MHAParser::mhapluginloader_t::last_name private
Referenced by load_plug().
std::string MHAParser::mhapluginloader_t::plugname_name_ private
Referenced by prepare().
mhaconfig_t MHAParser::mhapluginloader_t::cf_in_ private
Referenced by mhapluginloader_t(), prepare(), and release().
mhaconfig_t MHAParser::mhapluginloader_t::cf_out_ private
Referenced by mhapluginloader_t(), prepare(), and release().
double MHAParser::mhapluginloader_t::bookkeeping static private
The documentation for this class was generated from the following files:
mhapluginloader.h
mhapluginloader.cpp