openMHA Manual: MHAIOJack::io_jack_t Class Reference
MHAIOJack::io_jack_t Class Reference
Main class for JACK IO.
Public Member Functions
io_jack_t (unsigned int fragsize, float samplerate, IOProcessEvent_t proc_event, void *proc_handle, IOStartedEvent_t start_event, void *start_handle, IOStoppedEvent_t stop_event, void *stop_handle)
void prepare (int, int)
Allocate buffers, activate JACK client and install internal ports.
void release ()
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from MHAJack::client_t
client_t (IOProcessEvent_t proc_event, void *proc_handle=NULL, IOStartedEvent_t start_event=NULL, void *start_handle=NULL, IOStoppedEvent_t stop_event=NULL, void *stop_handle=NULL, bool use_jack_transport=false)
void prepare (const std::string &client_name, const unsigned int &nchannels_in, const unsigned int &nchannels_out)
Allocate buffers, activate JACK client and install internal ports.
void prepare (const std::string &server_name, const std::string &client_name, const unsigned int &nchannels_in, const unsigned int &nchannels_out)
Allocate buffers, ports, and activates JACK client.
void release ()
Remove JACK client and deallocate internal ports and buffers.
void start (bool fail_on_async_jack_error=true)
void stop ()
void connect_input (const std::vector< std::string > &)
Connect the input ports when connection variable is accessed.
void connect_output (const std::vector< std::string > &)
Connect the output ports when connection variable is accessed.
unsigned int get_fragsize () const
float get_srate () const
unsigned long get_xruns ()
unsigned long get_xruns_reset ()
std::string str_error (int err)
void get_ports (std::vector< std::string > &, unsigned long jack_flags)
Get a list of Jack ports.
std::vector< std::string > get_my_input_ports ()
std::vector< std::string > get_my_output_ports ()
void set_input_portnames (const std::vector< std::string > &)
void set_output_portnames (const std::vector< std::string > &)
float get_cpu_load ()
void set_use_jack_transport (bool ut)
Private Member Functions
void reconnect_inports ()
Connect the input ports when connection variable is accessed.
void reconnect_outports ()
Connect the output ports when connection variable is accessed.
void get_physical_input_ports ()
void get_physical_output_ports ()
void get_all_input_ports ()
void get_all_output_ports ()
void get_delays_in ()
void get_delays_out ()
void read_get_cpu_load ()
void read_get_xruns ()
void read_get_scheduler ()
Private Attributes
unsigned int fw_fragsize
float fw_samplerate
MHAParser::string_t servername
MHAParser::string_t clientname
MHAParser::vstring_t connections_in
MHAParser::vint_mon_t delays_in
MHAParser::vstring_t connections_out
MHAParser::vint_mon_t delays_out
MHAParser::vstring_t portnames_in
MHAParser::vstring_t portnames_out
MHAParser::vstring_mon_t ports_in_physical
MHAParser::vstring_mon_t ports_out_physical
MHAParser::vstring_mon_t ports_in_all
MHAParser::vstring_mon_t ports_out_all
MHAParser::parser_t ports_parser
MHAParser::float_mon_t state_cpuload
MHAParser::int_mon_t state_xruns
MHAParser::int_mon_t state_priority
MHAParser::string_mon_t state_scheduler
MHAParser::parser_t state_parser
MHAEvents::patchbay_t< io_jack_t > patchbay
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Protected Attributes inherited from MHAJack::client_t
jack_client_t * jc
Detailed Description
Main class for JACK IO.
This class registers a JACK client. JACK and framework states are managed by this class.
Constructor & Destructor Documentation
io_jack_t::io_jack_t (unsigned int fragsize, float samplerate, IOProcessEvent_t proc_event, void * proc_handle, IOStartedEvent_t start_event, void * start_handle, IOStoppedEvent_t stop_event, void * stop_handle)
References clientname, connections_in, connections_out, delays_in, delays_out, get_all_input_ports(), get_all_output_ports(), get_delays_in(), get_delays_out(), get_physical_input_ports(), get_physical_output_ports(), MHAParser::parser_t::insert_item(), insert_member, patchbay, portnames_in, portnames_out, ports_in_all, ports_in_physical, ports_out_all, ports_out_physical, ports_parser, MHAParser::base_t::prereadaccess, read_get_cpu_load(), read_get_scheduler(), read_get_xruns(), reconnect_inports(), reconnect_outports(), servername, MHAParser::base_t::set_node_id(), state_cpuload, state_parser, state_priority, state_scheduler, state_xruns, and MHAParser::base_t::writeaccess.
Referenced by IOInit().
Member Function Documentation
void io_jack_t::prepare (int nch_in, int nch_out)
Allocate buffers, activate JACK client and install internal ports.
References clientname, MHAParser::string_t::data, MHAParser::vstring_t::data, fw_fragsize, fw_samplerate, MHAJack::client_t::get_fragsize(), MHAJack::client_t::get_my_input_ports(), MHAJack::client_t::get_my_output_ports(), MHAJack::client_t::get_srate(), portnames_in, portnames_out, MHAJack::client_t::prepare(), reconnect_inports(), reconnect_outports(), release(), servername, MHAJack::client_t::set_input_portnames(), MHAJack::client_t::set_output_portnames(), and MHAParser::variable_t::setlock().
void io_jack_t::release ()
References clientname, portnames_in, portnames_out, MHAJack::client_t::release(), and MHAParser::variable_t::setlock().
Referenced by prepare().
void io_jack_t::reconnect_inports () private
Connect the input ports when connection variable is accessed.
References MHAJack::client_t::connect_input(), connections_in, and MHAParser::vstring_t::data.
Referenced by io_jack_t(), and prepare().
void io_jack_t::reconnect_outports () private
Connect the output ports when connection variable is accessed.
References MHAJack::client_t::connect_output(), connections_out, and MHAParser::vstring_t::data.
Referenced by io_jack_t(), and prepare().
void io_jack_t::get_physical_input_ports () private
References MHAParser::vstring_mon_t::data, MHAJack::client_t::get_ports(), and ports_in_physical.
Referenced by io_jack_t().
void io_jack_t::get_physical_output_ports () private
References MHAParser::vstring_mon_t::data, MHAJack::client_t::get_ports(), and ports_out_physical.
Referenced by io_jack_t().
void io_jack_t::get_all_input_ports () private
References MHAParser::vstring_mon_t::data, MHAJack::client_t::get_ports(), and ports_in_all.
Referenced by io_jack_t().
void io_jack_t::get_all_output_ports () private
References MHAParser::vstring_mon_t::data, MHAJack::client_t::get_ports(), and ports_out_all.
Referenced by io_jack_t().
void io_jack_t::get_delays_in () private
References connections_in, MHAParser::vstring_t::data, MHAParser::vint_mon_t::data, delays_in, and MHAJack::get_port_capture_latency_int().
Referenced by io_jack_t().
void io_jack_t::get_delays_out () private
References connections_out, MHAParser::vstring_t::data, MHAParser::vint_mon_t::data, delays_out, and MHAJack::get_port_playback_latency_int().
Referenced by io_jack_t().
void io_jack_t::read_get_cpu_load () private
References MHAParser::float_mon_t::data, MHAJack::client_t::get_cpu_load(), and state_cpuload.
Referenced by io_jack_t().
void io_jack_t::read_get_xruns () private
References MHAParser::int_mon_t::data, MHAJack::client_t::get_xruns(), and state_xruns.
Referenced by io_jack_t().
void io_jack_t::read_get_scheduler () private
References MHAParser::int_mon_t::data, MHAParser::string_mon_t::data, MHAJack::client_t::jc, state_priority, and state_scheduler.
Referenced by io_jack_t().
Member Data Documentation
unsigned int MHAIOJack::io_jack_t::fw_fragsize private
Referenced by prepare().
float MHAIOJack::io_jack_t::fw_samplerate private
Referenced by prepare().
MHAParser::string_t MHAIOJack::io_jack_t::servername private
Referenced by io_jack_t(), and prepare().
MHAParser::string_t MHAIOJack::io_jack_t::clientname private
Referenced by io_jack_t(), prepare(), and release().
MHAParser::vstring_t MHAIOJack::io_jack_t::connections_in private
Referenced by get_delays_in(), io_jack_t(), and reconnect_inports().
MHAParser::vint_mon_t MHAIOJack::io_jack_t::delays_in private
Referenced by get_delays_in(), and io_jack_t().
MHAParser::vstring_t MHAIOJack::io_jack_t::connections_out private
Referenced by get_delays_out(), io_jack_t(), and reconnect_outports().
MHAParser::vint_mon_t MHAIOJack::io_jack_t::delays_out private
Referenced by get_delays_out(), and io_jack_t().
MHAParser::vstring_t MHAIOJack::io_jack_t::portnames_in private
Referenced by io_jack_t(), prepare(), and release().
MHAParser::vstring_t MHAIOJack::io_jack_t::portnames_out private
Referenced by io_jack_t(), prepare(), and release().
MHAParser::vstring_mon_t MHAIOJack::io_jack_t::ports_in_physical private
Referenced by get_physical_input_ports(), and io_jack_t().
MHAParser::vstring_mon_t MHAIOJack::io_jack_t::ports_out_physical private
Referenced by get_physical_output_ports(), and io_jack_t().
MHAParser::vstring_mon_t MHAIOJack::io_jack_t::ports_in_all private
Referenced by get_all_input_ports(), and io_jack_t().
MHAParser::vstring_mon_t MHAIOJack::io_jack_t::ports_out_all private
Referenced by get_all_output_ports(), and io_jack_t().
MHAParser::parser_t MHAIOJack::io_jack_t::ports_parser private
Referenced by io_jack_t().
MHAParser::float_mon_t MHAIOJack::io_jack_t::state_cpuload private
Referenced by io_jack_t(), and read_get_cpu_load().
MHAParser::int_mon_t MHAIOJack::io_jack_t::state_xruns private
Referenced by io_jack_t(), and read_get_xruns().
MHAParser::int_mon_t MHAIOJack::io_jack_t::state_priority private
Referenced by io_jack_t(), and read_get_scheduler().
MHAParser::string_mon_t MHAIOJack::io_jack_t::state_scheduler private
Referenced by io_jack_t(), and read_get_scheduler().
MHAParser::parser_t MHAIOJack::io_jack_t::state_parser private
Referenced by io_jack_t().
MHAEvents::patchbay_t<io_jack_t> MHAIOJack::io_jack_t::patchbay private
Referenced by io_jack_t().
The documentation for this class was generated from the following file:
MHAIOJack.cpp