openMHA Manual: MHASignal::matrix_t Class Reference
MHASignal::matrix_t Class Reference
The MHA Toolbox library » Vector and matrix processing toolbox
n-dimensional matrix with real or complex floating point values.
#include <mha_signal.hh>
Public Member Functions
matrix_t (unsigned int nrows, unsigned int ncols, bool b_is_complex=true)
Create a two-dimensional matrix.
matrix_t (const mha_spec_t &spec)
Create a two-dimensional matrix from a spectrum, copy values.
matrix_t (const MHASignal::uint_vector_t &size, bool b_is_complex=true)
Create n-dimensional matrix, descriped by size argument.
matrix_t (const MHASignal::matrix_t &)
matrix_t (const uint8_t *buf, unsigned int len)
Construct from memory area.
~matrix_t ()
MHASignal::matrix_t & operator= (const MHASignal::matrix_t &)
MHASignal::matrix_t & operator= (const comm_var_t &v)
Fill matrix with data of an AC variable object.
comm_var_t get_comm_var ()
Return a AC communication variable pointing to the data of the current matrix.
unsigned int dimension () const
Return the dimension of the matrix.
unsigned int size (unsigned int k) const
Return the size of the matrix.
unsigned int get_nelements () const
Return total number of elements.
bool is_same_size (const MHASignal::matrix_t &)
Test if matrix has same size as other.
bool iscomplex () const
Return information about complexity.
mha_real_t & real (const MHASignal::uint_vector_t &index)
Access real part of an element in a n-dimensional matrix.
mha_real_t & imag (const MHASignal::uint_vector_t &index)
Access imaginary part of an element in a n-dimensional matrix.
mha_complex_t & operator() (const MHASignal::uint_vector_t &index)
Access complex value of an element in a n-dimensional matrix.
const mha_real_t & real (const MHASignal::uint_vector_t &index) const
Access real part of an element in a n-dimensional matrix.
const mha_real_t & imag (const MHASignal::uint_vector_t &index) const
Access imaginary part of an element in a n-dimensional matrix.
const mha_complex_t & operator() (const MHASignal::uint_vector_t &index) const
Access complex value of an element in a n-dimensional matrix.
mha_real_t & real (unsigned int row, unsigned int col)
Access real part of an element in a two-dimensional matrix.
mha_real_t & imag (unsigned int row, unsigned int col)
Access imaginary part of an element in a two-dimensional matrix.
mha_complex_t & operator() (unsigned int row, unsigned int col)
Access complex value of an element in a two-dimensional matrix.
const mha_real_t & real (unsigned int row, unsigned int col) const
Access real part of an element in a two-dimensional matrix.
const mha_real_t & imag (unsigned int row, unsigned int col) const
Access imaginary part of an element in a two-dimensional matrix.
const mha_complex_t & operator() (unsigned int row, unsigned int col) const
Access complex value of an element in a two-dimensional matrix.
unsigned int get_nreals () const
unsigned int get_index (unsigned int row, unsigned int col) const
unsigned int get_index (const MHASignal::uint_vector_t &index) const
unsigned int numbytes () const
Return number of bytes needed to store into memory.
unsigned int write (uint8_t *buf, unsigned int len) const
Copy to memory area.
const mha_real_t * get_rdata () const
Return pointer of real data.
const mha_complex_t * get_cdata () const
Return pointer of complex data.
Private Attributes
uint32_t complex_ofs
uint32_t nelements
union {
mha_real_t * rdata
mha_complex_t * cdata
};
Private Attributes inherited from MHASignal::uint_vector_t
uint32_t length
uint32_t * data
Additional Inherited Members
Private Member Functions inherited from MHASignal::uint_vector_t
uint_vector_t (unsigned int len)
Constructor, initializes all elements to zero.
uint_vector_t (const uint_vector_t &)
uint_vector_t (const uint8_t *buf, unsigned int len)
Construct from memory area.
~uint_vector_t ()
bool operator== (const uint_vector_t &) const
Check for equality.
uint_vector_t & operator= (const uint_vector_t &)
Assign from other uint_vector_t.
unsigned int get_length () const
Return the length of the vector.
const uint32_t & operator[] (unsigned int k) const
Read-only access to elements.
uint32_t & operator[] (unsigned int k)
Access to elements.
unsigned int numbytes () const
Return number of bytes needed to store into memory.
unsigned int write (uint8_t *buf, unsigned int len) const
Copy to memory area.
const uint32_t * getdata () const
Return pointer to the data field.
Detailed Description
n-dimensional matrix with real or complex floating point values.
Warning
The member functions imag() and operator() should only be called if the matrix is defined to hold complex values.
Constructor & Destructor Documentation
MHASignal::matrix_t::matrix_t (unsigned int nrows, unsigned int ncols, bool b_is_complex = true)
Create a two-dimensional matrix.
Parameters
nrows Number of rows
ncols Number of columns
b_is_complex Add space for complex values
References MHASignal::uint_vector_t::data, get_nelements(), get_nreals(), mha_min_1(), nelements, and rdata.
MHASignal::matrix_t::matrix_t (const mha_spec_t & spec)
Create a two-dimensional matrix from a spectrum, copy values.
Parameters
spec Source spectrum structure
References MHASignal::uint_vector_t::data, get_nelements(), get_nreals(), mha_min_1(), nelements, mha_spec_t::num_channels, mha_spec_t::num_frames, rdata, and value().
MHASignal::matrix_t::matrix_t (const MHASignal::uint_vector_t & size, bool b_is_complex = true)
Create n-dimensional matrix, descriped by size argument.
Parameters
size Size vector
b_is_complex Add space for complex values
References get_nreals(), and rdata.
MHASignal::matrix_t::matrix_t (const MHASignal::matrix_t & src)
References get_nreals(), and rdata.
MHASignal::matrix_t::matrix_t (const uint8_t * buf, unsigned int len)
Construct from memory area.
Warning
This constructor is not real time safe
References complex_ofs, get_nreals(), MHA_ID_MATRIX, mha_min_1(), nelements, MHASignal::uint_vector_t::numbytes(), and rdata.
MHASignal::matrix_t::~matrix_t ()
References rdata.
Member Function Documentation
matrix_t & MHASignal::matrix_t::operator= (const MHASignal::matrix_t & src)
References get_nreals(), is_same_size(), and rdata.
Referenced by MHA_AC::ac2matrix_t::update().
MHASignal::matrix_t & MHASignal::matrix_t::operator= (const comm_var_t & v)
Fill matrix with data of an AC variable object.
Parameters
v Source AC variable (comm_var_t)
Note
The type and dimension of the AC variable must match the type and dimension of the matrix.
References comm_var_t::data, comm_var_t::data_type, dimension(), iscomplex(), MHA_AC_DOUBLE, MHA_AC_FLOAT, MHA_AC_INT, MHA_AC_MHACOMPLEX, MHA_AC_MHAREAL, comm_var_t::num_entries, real(), size(), and comm_var_t::stride.
comm_var_t MHASignal::matrix_t::get_comm_var ()
Return a AC communication variable pointing to the data of the current matrix.
Returns
AC variable object (comm_var_t), valid for the life time of the matrix.
References cdata, comm_var_t::data, comm_var_t::data_type, dimension(), iscomplex(), MHA_AC_MHACOMPLEX, MHA_AC_MHAREAL, comm_var_t::num_entries, rdata, size(), and comm_var_t::stride.
Referenced by MHA_AC::ac2matrix_t::insert().
unsigned int MHASignal::matrix_t::dimension () const inline
Return the dimension of the matrix.
Returns
Dimension of the matrix
References MHASignal::uint_vector_t::get_length().
Referenced by get_comm_var(), and operator=().
unsigned int MHASignal::matrix_t::size (unsigned int k) const inline
Return the size of the matrix.
Parameters
k Dimension
Returns
Size of the matrix in dimension k
References MHASignal::uint_vector_t::operator[]().
Referenced by get_comm_var(), MHASignal::max(), MHASignal::min(), operator=(), and std_vector_float().
unsigned int MHASignal::matrix_t::get_nelements () const
Return total number of elements.
References MHASignal::uint_vector_t::data, and MHASignal::uint_vector_t::length.
Referenced by matrix_t().
bool MHASignal::matrix_t::is_same_size (const MHASignal::matrix_t & src)
Test if matrix has same size as other.
References iscomplex().
Referenced by operator=().
bool MHASignal::matrix_t::iscomplex () const inline
Return information about complexity.
Referenced by get_comm_var(), is_same_size(), and operator=().
mha_real_t& MHASignal::matrix_t::real (const MHASignal::uint_vector_t & index) inline
Access real part of an element in a n-dimensional matrix.
Parameters
index Index vector
Referenced by operator=().
mha_real_t& MHASignal::matrix_t::imag (const MHASignal::uint_vector_t & index) inline
Access imaginary part of an element in a n-dimensional matrix.
Parameters
index Index vector
mha_complex_t& MHASignal::matrix_t::operator() (const MHASignal::uint_vector_t & index) inline
Access complex value of an element in a n-dimensional matrix.
Parameters
index Index vector
const mha_real_t& MHASignal::matrix_t::real (const MHASignal::uint_vector_t & index) const inline
Access real part of an element in a n-dimensional matrix.
Parameters
index Index vector
const mha_real_t& MHASignal::matrix_t::imag (const MHASignal::uint_vector_t & index) const inline
Access imaginary part of an element in a n-dimensional matrix.
Parameters
index Index vector
const mha_complex_t& MHASignal::matrix_t::operator() (const MHASignal::uint_vector_t & index) const inline
Access complex value of an element in a n-dimensional matrix.
Parameters
index Index vector
mha_real_t& MHASignal::matrix_t::real (unsigned int row, unsigned int col) inline
Access real part of an element in a two-dimensional matrix.
Parameters
row Row number of element
col Column number of element
mha_real_t& MHASignal::matrix_t::imag (unsigned int row, unsigned int col) inline
Access imaginary part of an element in a two-dimensional matrix.
Parameters
row Row number of element
col Column number of element
mha_complex_t& MHASignal::matrix_t::operator() (unsigned int row, unsigned int col) inline
Access complex value of an element in a two-dimensional matrix.
Parameters
row Row number of element
col Column number of element
const mha_real_t& MHASignal::matrix_t::real (unsigned int row, unsigned int col) const inline
Access real part of an element in a two-dimensional matrix.
Parameters
row Row number of element
col Column number of element
const mha_real_t& MHASignal::matrix_t::imag (unsigned int row, unsigned int col) const inline
Access imaginary part of an element in a two-dimensional matrix.
Parameters
row Row number of element
col Column number of element
const mha_complex_t& MHASignal::matrix_t::operator() (unsigned int row, unsigned int col) const inline
Access complex value of an element in a two-dimensional matrix.
Parameters
row Row number of element
col Column number of element
unsigned int MHASignal::matrix_t::get_nreals () const inline
Referenced by matrix_t(), and operator=().
unsigned int MHASignal::matrix_t::get_index (unsigned int row, unsigned int col) const
References MHASignal::uint_vector_t::operator[]().
unsigned int MHASignal::matrix_t::get_index (const MHASignal::uint_vector_t & index) const
References MHASignal::uint_vector_t::get_length().
unsigned int MHASignal::matrix_t::numbytes () const
Return number of bytes needed to store into memory.
References MHA_ID_MATRIX, and MHASignal::uint_vector_t::numbytes().
unsigned int MHASignal::matrix_t::write (uint8_t * buf, unsigned int len) const
Copy to memory area.
References MHA_ID_MATRIX, MHASignal::uint_vector_t::numbytes(), and MHASignal::uint_vector_t::write().
const mha_real_t* MHASignal::matrix_t::get_rdata () const inline
Return pointer of real data.
const mha_complex_t* MHASignal::matrix_t::get_cdata () const inline
Return pointer of complex data.
Member Data Documentation
uint32_t MHASignal::matrix_t::complex_ofs private
Referenced by matrix_t().
uint32_t MHASignal::matrix_t::nelements private
Referenced by matrix_t().
mha_real_t* MHASignal::matrix_t::rdata
Referenced by get_comm_var(), matrix_t(), operator=(), and ~matrix_t().
mha_complex_t* MHASignal::matrix_t::cdata
Referenced by get_comm_var().
union { ... }
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp