openMHA Manual: MHAParser::base_t Class Reference
MHAParser::base_t Class Reference
Base class for all parser items.
#include <mha_parser.hh>
Classes
class replace_t
Public Member Functions
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string op_subparse (expression_t &)
virtual std::string op_setval (expression_t &)
virtual std::string op_query (expression_t &)
virtual std::string query_dump (const std::string &)
virtual std::string query_entries (const std::string &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
virtual std::string query_type (const std::string &)
virtual std::string query_val (const std::string &)
virtual std::string query_readfile (const std::string &)
virtual std::string query_savefile (const std::string &)
virtual std::string query_savefile_compact (const std::string &)
virtual std::string query_savemons (const std::string &)
virtual std::string query_listids (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Attributes
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes
query_map_t queries
bool data_is_initialized
Private Types
typedef std::vector< replace_t > repl_list_t
Private Member Functions
void add_replace_pair (const std::string &, const std::string &)
std::string oplist ()
Private Attributes
std::string help
std::string id_str
opact_map_t operators
repl_list_t repl_list
bool nested_lock
parser_t * parent
std::string thefullname
Detailed Description
Base class for all parser items.
The key method of the parser base class is the std::string parse(const std::string&) method. Parser proxy derivatives which overwrite any of the other parse() methods to be the key method must make sure that the original parse() method utilizes the new key method.
Member Typedef Documentation
typedef std::vector<replace_t> MHAParser::base_t::repl_list_t private
Constructor & Destructor Documentation
MHAParser::base_t::base_t (const std::string & h)
Constructor for base class of all parser nodes.
Parameters
h Help text describing this parser node. This help text is accessible to the configuration language through the "?help" query command.
References activate_query(), add_replace_pair(), MHAPLATFORM, op_query(), op_setval(), op_subparse(), operators, query_addsubst(), query_cmds(), query_dump(), query_help(), query_id(), query_subst(), query_type(), and query_version().
MHAParser::base_t::base_t (const base_t & src)
References activate_query(), add_replace_pair(), MHAPLATFORM, op_query(), op_setval(), op_subparse(), operators, query_addsubst(), query_cmds(), query_dump(), query_help(), query_id(), query_subst(), query_type(), and query_version().
MHAParser::base_t::~base_t () virtual
References parent, and MHAParser::parser_t::remove_item().
Member Function Documentation
std::string MHAParser::base_t::parse (const std::string & cs) virtual
Causes this node to process a command in the MHA configuration language.
Parameters
cs The command to parse
Returns
The response to the command, if successful
Exceptions
MHA_Error If the command cannot be executed successfully. The reason for failure is given in the message string of the exception.
Reimplemented in PluginLoader::mhapluginloader_t.
References MHAParser::envreplace(), MHA_ErrorMsg, nested_lock, MHAParser::expression_t::op, operators, oplist(), and repl_list.
Referenced by MHAParser::all_dump(), MHAParser::all_ids(), MHAParser::bool_t::bool_t(), MHAParser::cfg_dump(), MHAParser::cfg_dump_short(), MHAParser::complex_t::complex_t(), MHAParser::float_t::float_t(), fw_t::fw_until_cmd(), latex_doc_t::get_parser_tab(), latex_doc_t::get_parser_var(), MHAParser::int_t::int_t(), MHAParser::kw_t::kw_t(), MHAParser::mcomplex_t::mcomplex_t(), MHAParser::mfloat_t::mfloat_t(), mha_parse(), mhamain(), MHAParser::mon_dump(), MHAParser::parser_t::op_setval(), MHAParser::parser_t::op_subparse(), overlapadd::overlapadd_if_t::overlapadd_if_t(), PluginLoader::mhapluginloader_t::parse(), parse(), MHAParser::monitor_t::query_dump(), MHAParser::parser_t::query_readfile(), mhaserver_t::received_group(), MHAParser::vcomplex_t::vcomplex_t(), MHAParser::vfloat_t::vfloat_t(), MHAParser::vint_t::vint_t(), and MHAParser::vstring_t::vstring_t().
void MHAParser::base_t::parse (const char * cmd, char * retv, unsigned int len) virtual
This function parses a command and writes the parsing result into a C character array.
This base class implementation delegates to parse(const std::string &).
Parameters
cmd Command to be parsed
retv Buffer for the result
len Length of buffer
References parse().
void MHAParser::base_t::parse (const std::vector< std::string > & cs, std::vector< std::string > & retv) virtual
References parse().
std::string MHAParser::base_t::op_subparse (expression_t &) virtual
Reimplemented in MHAParser::c_ifc_parser_t, and MHAParser::parser_t.
Referenced by base_t().
std::string MHAParser::base_t::op_setval (expression_t &) virtual
Reimplemented in MHAParser::mcomplex_t, MHAParser::mfloat_t, MHAParser::vcomplex_t, MHAParser::vfloat_t, MHAParser::vint_t, MHAParser::complex_t, MHAParser::float_t, MHAParser::int_t, MHAParser::bool_t, MHAParser::vstring_t, MHAParser::string_t, MHAParser::kw_t, MHAParser::variable_t, MHAParser::c_ifc_parser_t, and MHAParser::parser_t.
Referenced by base_t().
std::string MHAParser::base_t::op_query (expression_t &) virtual
Reimplemented in MHAParser::monitor_t, MHAParser::c_ifc_parser_t, and MHAParser::parser_t.
Referenced by base_t().
std::string MHAParser::base_t::query_dump (const std::string & s) virtual
Reimplemented in MHAParser::monitor_t, and MHAParser::parser_t.
Referenced by base_t().
std::string MHAParser::base_t::query_entries (const std::string & s) virtual
Reimplemented in MHAParser::parser_t.
Referenced by MHAParser::parser_t::parser_t().
std::string MHAParser::base_t::query_perm (const std::string & s) virtual
Reimplemented in MHAParser::variable_t, and MHAParser::monitor_t.
Referenced by MHAParser::monitor_t::monitor_t().
std::string MHAParser::base_t::query_range (const std::string & s) virtual
Reimplemented in MHAParser::kw_t, and MHAParser::range_var_t.
Referenced by MHAParser::kw_t::kw_t(), and MHAParser::range_var_t::range_var_t().
std::string MHAParser::base_t::query_type (const std::string & s) virtual
Reimplemented in MHAParser::mcomplex_mon_t, MHAParser::vcomplex_mon_t, MHAParser::complex_mon_t, MHAParser::float_mon_t, MHAParser::mfloat_mon_t, MHAParser::vfloat_mon_t, MHAParser::vint_mon_t, MHAParser::vstring_mon_t, MHAParser::string_mon_t, MHAParser::bool_mon_t, MHAParser::int_mon_t, MHAParser::mcomplex_t, MHAParser::mfloat_t, MHAParser::vcomplex_t, MHAParser::vfloat_t, MHAParser::vint_t, MHAParser::complex_t, MHAParser::float_t, MHAParser::int_t, MHAParser::bool_t, MHAParser::vstring_t, MHAParser::string_t, MHAParser::kw_t, and MHAParser::parser_t.
Referenced by base_t().
std::string MHAParser::base_t::query_val (const std::string & s) virtual
Reimplemented in MHAParser::mcomplex_mon_t, MHAParser::vcomplex_mon_t, MHAParser::complex_mon_t, MHAParser::float_mon_t, MHAParser::mfloat_mon_t, MHAParser::vfloat_mon_t, MHAParser::vint_mon_t, MHAParser::vstring_mon_t, MHAParser::string_mon_t, MHAParser::bool_mon_t, MHAParser::int_mon_t, MHAParser::mcomplex_t, MHAParser::mfloat_t, MHAParser::vcomplex_t, MHAParser::vfloat_t, MHAParser::vint_t, MHAParser::complex_t, MHAParser::float_t, MHAParser::int_t, MHAParser::bool_t, MHAParser::vstring_t, MHAParser::string_t, MHAParser::kw_t, and MHAParser::parser_t.
Referenced by MHAParser::monitor_t::monitor_t(), and MHAParser::parser_t::parser_t().
std::string MHAParser::base_t::query_readfile (const std::string & s) virtual
Reimplemented in MHAParser::parser_t.
Referenced by MHAParser::parser_t::parser_t().
std::string MHAParser::base_t::query_savefile (const std::string & s) virtual
Reimplemented in MHAParser::parser_t.
Referenced by MHAParser::parser_t::parser_t().
std::string MHAParser::base_t::query_savefile_compact (const std::string & s) virtual
Reimplemented in MHAParser::parser_t.
Referenced by MHAParser::parser_t::parser_t().
std::string MHAParser::base_t::query_savemons (const std::string & s) virtual
Reimplemented in MHAParser::parser_t.
Referenced by MHAParser::parser_t::parser_t().
std::string MHAParser::base_t::query_listids (const std::string & s) virtual
Reimplemented in MHAParser::parser_t.
Referenced by MHAParser::parser_t::parser_t().
std::string MHAParser::base_t::query_version (const std::string &)
References MHA_VERSION_STRING.
Referenced by base_t().
std::string MHAParser::base_t::query_id (const std::string &)
References id_str.
Referenced by base_t().
std::string MHAParser::base_t::query_subst (const std::string & s)
References repl_list.
Referenced by base_t().
std::string MHAParser::base_t::query_addsubst (const std::string & s)
References add_replace_pair().
Referenced by base_t().
std::string MHAParser::base_t::query_help (const std::string & s)
References help.
Referenced by base_t().
std::string MHAParser::base_t::query_cmds (const std::string & s)
References queries.
Referenced by base_t().
void MHAParser::base_t::set_node_id (const std::string & s)
Set the identification string of this parser node.
The id can be queried from the configuration language using the ?id query command. Nodes can be found by id using the ?listid query command on a containing parser node.
Parameters
s The new identification string.
References id_str.
Referenced by bbcalib_interface_t::bbcalib_interface_t(), mhachain::chain_base_t::chain_base_t(), DynComp::dc_afterburn_vars_t::dc_afterburn_vars_t(), dc::dc_vars_t::dc_vars_t(), fftfilterbank::fftfb_interface_t::fftfb_interface_t(), MHAIOJack::io_jack_t::io_jack_t(), and mhachain::plugs_t::plugs_t().
void MHAParser::base_t::set_help (const std::string & s)
Set the help comment of a variable or parser.
Parameters
s New help comment.
References help.
void MHAParser::base_t::add_parent_on_insert (parser_t * p, std::string n)
References fullname(), parent, and thefullname.
Referenced by MHAParser::parser_t::insert_item().
void MHAParser::base_t::rm_parent_on_remove (parser_t *)
References parent, and thefullname.
const std::string & MHAParser::base_t::fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
References thefullname.
Referenced by add_parent_on_insert().
void MHAParser::base_t::activate_query (const std::string & n, query_t a) protected
References queries.
Referenced by base_t(), MHAParser::kw_t::kw_t(), MHAParser::monitor_t::monitor_t(), MHAParser::parser_t::parser_t(), and MHAParser::range_var_t::range_var_t().
void MHAParser::base_t::notify () protected
void MHAParser::base_t::add_replace_pair (const std::string & a, const std::string & b) private
References repl_list, and MHAParser::base_t::replace_t::replace_t().
Referenced by base_t(), and query_addsubst().
std::string MHAParser::base_t::oplist () private
References operators.
Referenced by parse().
Member Data Documentation
MHAEvents::emitter_t MHAParser::base_t::writeaccess
Event emitted on write access.
To connect a callback that is invoked on write access to this parser variable, use MHAEvents::patchbay_t<receiver_t> method connect(&writeaccess,&receiver_t::callback) where callback is a method that expects no parameters and returns void.
Referenced by MHAFilter::adapt_filter_t::adapt_filter_t(), adm_if_t::adm_if_t(), calibrator_t::calibrator_t(), mhachain::chain_base_t::chain_base_t(), coherence::cohflt_if_t::cohflt_if_t(), DynComp::dc_afterburn_t::dc_afterburn_t(), dc::dc_if_t::dc_if_t(), fftfilterbank::fftfb_interface_t::fftfb_interface_t(), AuditoryProfile::parser_t::fmap_t::fmap_t(), fw_t::fw_t(), MHAFilter::iir_filter_t::iir_filter_t(), MHAIOJack::io_jack_t::io_jack_t(), io_parser_t::io_parser_t(), MHAParser::parser_t::op_setval(), MHAParser::kw_t::op_setval(), MHAParser::string_t::op_setval(), MHAParser::vstring_t::op_setval(), MHAParser::bool_t::op_setval(), MHAParser::int_t::op_setval(), MHAParser::float_t::op_setval(), MHAParser::complex_t::op_setval(), MHAParser::vint_t::op_setval(), MHAParser::vfloat_t::op_setval(), MHAParser::vcomplex_t::op_setval(), MHAParser::mfloat_t::op_setval(), MHAParser::mcomplex_t::op_setval(), overlapadd::overlapadd_if_t::overlapadd_if_t(), dc::wideband_inhib_vars_t::wideband_inhib_vars_t(), and windowselector_t::windowselector_t().
MHAEvents::emitter_t MHAParser::base_t::valuechanged
Event emitted if the value has changed.
To connect a callback that is invoked when write access to this parser variable actually changes its value, use MHAEvents::patchbay_t<receiver_t> method connect(&valuechanged,&receiver_t::callback) where callback is a method that expects no parameters and returns void.
Referenced by MHAParser::kw_t::op_setval(), MHAParser::string_t::op_setval(), MHAParser::vstring_t::op_setval(), MHAParser::bool_t::op_setval(), MHAParser::int_t::op_setval(), MHAParser::float_t::op_setval(), MHAParser::complex_t::op_setval(), MHAParser::vint_t::op_setval(), MHAParser::vfloat_t::op_setval(), MHAParser::vcomplex_t::op_setval(), MHAParser::mfloat_t::op_setval(), and MHAParser::mcomplex_t::op_setval().
MHAEvents::emitter_t MHAParser::base_t::readaccess
Event emitted on read access.
To connect a callback that is invoked after the value of this variable has been read through the configuration interface, use MHAEvents::patchbay_t<receiver_t> method connect(&readaccess,&receiver_t::callback) where callback is a method that expects no parameters and returns void.
Referenced by fw_t::fw_t(), MHAParser::parser_t::query_val(), MHAParser::kw_t::query_val(), MHAParser::string_t::query_val(), MHAParser::vstring_t::query_val(), MHAParser::bool_t::query_val(), MHAParser::int_t::query_val(), MHAParser::float_t::query_val(), MHAParser::complex_t::query_val(), MHAParser::vint_t::query_val(), MHAParser::vfloat_t::query_val(), MHAParser::vcomplex_t::query_val(), MHAParser::mfloat_t::query_val(), MHAParser::mcomplex_t::query_val(), MHAParser::int_mon_t::query_val(), MHAParser::bool_mon_t::query_val(), MHAParser::string_mon_t::query_val(), MHAParser::vstring_mon_t::query_val(), MHAParser::vint_mon_t::query_val(), MHAParser::vfloat_mon_t::query_val(), MHAParser::mfloat_mon_t::query_val(), MHAParser::float_mon_t::query_val(), MHAParser::complex_mon_t::query_val(), MHAParser::vcomplex_mon_t::query_val(), and MHAParser::mcomplex_mon_t::query_val().
MHAEvents::emitter_t MHAParser::base_t::prereadaccess
Event emitted on read access, before the data field is accessed.
To connect a callback that is invoked when the value of this variable is about to be read through the configuration interface, so that the callback can influence the value that is reported, use MHAEvents::patchbay_t<receiver_t> method connect(&prereadaccess,&receiver_t::callback) where callback is a method that expects no parameters and returns void.
Referenced by calibrator_t::calibrator_t(), fw_t::fw_t(), MHAIOJack::io_jack_t::io_jack_t(), MHAParser::parser_t::query_val(), MHAParser::kw_t::query_val(), MHAParser::string_t::query_val(), MHAParser::vstring_t::query_val(), MHAParser::bool_t::query_val(), MHAParser::int_t::query_val(), MHAParser::float_t::query_val(), MHAParser::complex_t::query_val(), MHAParser::vint_t::query_val(), MHAParser::vfloat_t::query_val(), MHAParser::vcomplex_t::query_val(), MHAParser::mfloat_t::query_val(), MHAParser::mcomplex_t::query_val(), MHAParser::int_mon_t::query_val(), MHAParser::bool_mon_t::query_val(), MHAParser::string_mon_t::query_val(), MHAParser::vstring_mon_t::query_val(), MHAParser::vint_mon_t::query_val(), MHAParser::vfloat_mon_t::query_val(), MHAParser::mfloat_mon_t::query_val(), MHAParser::float_mon_t::query_val(), MHAParser::complex_mon_t::query_val(), MHAParser::vcomplex_mon_t::query_val(), and MHAParser::mcomplex_mon_t::query_val().
query_map_t MHAParser::base_t::queries protected
Referenced by activate_query(), MHAParser::parser_t::op_query(), MHAParser::monitor_t::op_query(), and query_cmds().
bool MHAParser::base_t::data_is_initialized protected
Referenced by MHAParser::bool_mon_t::bool_mon_t(), MHAParser::bool_t::bool_t(), MHAParser::complex_mon_t::complex_mon_t(), MHAParser::complex_t::complex_t(), MHAParser::float_mon_t::float_mon_t(), MHAParser::float_t::float_t(), MHAParser::int_mon_t::int_mon_t(), MHAParser::int_t::int_t(), MHAParser::kw_t::kw_t(), MHAParser::mcomplex_mon_t::mcomplex_mon_t(), MHAParser::mcomplex_t::mcomplex_t(), MHAParser::mfloat_mon_t::mfloat_mon_t(), MHAParser::mfloat_t::mfloat_t(), MHAParser::kw_t::op_setval(), MHAParser::string_t::op_setval(), MHAParser::vstring_t::op_setval(), MHAParser::bool_t::op_setval(), MHAParser::int_t::op_setval(), MHAParser::float_t::op_setval(), MHAParser::complex_t::op_setval(), MHAParser::vint_t::op_setval(), MHAParser::vfloat_t::op_setval(), MHAParser::vcomplex_t::op_setval(), MHAParser::mfloat_t::op_setval(), MHAParser::mcomplex_t::op_setval(), MHAParser::string_mon_t::string_mon_t(), MHAParser::string_t::string_t(), MHAParser::vcomplex_mon_t::vcomplex_mon_t(), MHAParser::vcomplex_t::vcomplex_t(), MHAParser::vfloat_mon_t::vfloat_mon_t(), MHAParser::vfloat_t::vfloat_t(), MHAParser::vint_mon_t::vint_mon_t(), MHAParser::vint_t::vint_t(), MHAParser::vstring_mon_t::vstring_mon_t(), and MHAParser::vstring_t::vstring_t().
std::string MHAParser::base_t::help private
Referenced by query_help(), and set_help().
std::string MHAParser::base_t::id_str private
Referenced by query_id(), and set_node_id().
opact_map_t MHAParser::base_t::operators private
Referenced by base_t(), oplist(), and parse().
repl_list_t MHAParser::base_t::repl_list private
Referenced by add_replace_pair(), parse(), and query_subst().
bool MHAParser::base_t::nested_lock private
Referenced by parse().
parser_t* MHAParser::base_t::parent private
Referenced by add_parent_on_insert(), rm_parent_on_remove(), and ~base_t().
std::string MHAParser::base_t::thefullname private
Referenced by add_parent_on_insert(), fullname(), and rm_parent_on_remove().
The documentation for this class was generated from the following files:
mha_parser.hh
mha_parser.cpp