openMHA Manual: adm.cpp File Reference
adm.cpp File Reference
#include "adm.hh"
#include "mha_signal.hh"
#include "mha_error.hh"
#include "mha_parser.hh"
#include "mha_plugin.hh"
#include "mha_events.h"
#include "mha_filter.hh"
#include <stdlib.h>
#include <math.h>
#include <string>
#include <cassert>
#include <cstdio>
Classes
class adm_rtconfig_t
class adm_if_t
Functions
MHASignal::waveform_t * adm_fir_lp (unsigned int fs, unsigned f_pass, unsigned int f_stop, unsigned int order)
MHASignal::waveform_t * adm_fir_decomb (unsigned int fs, float dist_m, unsigned int order)
Function Documentation
MHASignal::waveform_t* adm_fir_lp (unsigned int fs, unsigned f_pass, unsigned int f_stop, unsigned int order)
References MHAWindow::hamming(), M_PI, mha_complex(), mha_spec_t::num_frames, and MHAFilter::spec2fir().
Referenced by adm_rtconfig_t::adm_rtconfig_t(), and adm_if_t::prepare().
MHASignal::waveform_t* adm_fir_decomb (unsigned int fs, float dist_m, unsigned int order)
References ADM::C, MHAWindow::hamming(), M_PI, MHASignal::max(), mha_complex(), MHASignal::min(), mha_spec_t::num_frames, and MHAFilter::spec2fir().
Referenced by adm_rtconfig_t::adm_rtconfig_t(), and adm_if_t::prepare().