openMHA Manual: browsemhaplugins.cpp File Reference
browsemhaplugins.cpp File Reference
#include "mha_os.h"
#include "pluginbrowser.h"
#include "mha_algo_comm.hh"
#include <exception>
#include <dirent.h>
#include <fnmatch.h>
Macros
#define DEBUG(x) std::cerr << __FILE__ << ":" << __LINE__ << " " << #x<<"="<<x << std::endl
Functions
int main (int argc, char **argv)
Macro Definition Documentation
#define DEBUG (x) std::cerr << __FILE__ << ":" << __LINE__ << " " << #x<<"="<<x << std::endl
Function Documentation
int main (int argc, char ** argv)
References pluginbrowser_t::add_plugins(), pluginbrowser_t::clear_plugins(), pluginbrowser_t::get_paths(), pluginbrowser_t::get_plugins(), and pluginbrowser_t::scan_plugins().