openMHA Manual: MHASignal::waveform_t Class Reference
MHASignal::waveform_t Class Reference
The MHA Toolbox library » Vector and matrix processing toolbox
signal processing class for waveform data (based on mha_wave_t)
#include <mha_signal.hh>
Public Member Functions
waveform_t (const unsigned int &frames, const unsigned int &channels)
constructor of waveform_t
waveform_t (const mhaconfig_t &cf)
Constructor to create a waveform from plugin configuration.
waveform_t (const mha_wave_t &src)
Copy contructor for mha_wave_t source.
waveform_t (const MHASignal::waveform_t &src)
Copy contructor.
waveform_t (const std::vector< mha_real_t > &src)
Copy contructor for std::vector<mha_real_t> source.
virtual ~waveform_t (void)
void operator= (const mha_real_t &v)
mha_real_t & operator[] (unsigned int k)
const mha_real_t & operator[] (unsigned int k) const
mha_real_t & value (unsigned int t, unsigned int ch)
Element accessor.
mha_real_t & operator() (unsigned int t, unsigned int ch)
Element accessor.
const mha_real_t & value (unsigned int t, unsigned int ch) const
Constant element accessor.
const mha_real_t & operator() (unsigned int t, unsigned int ch) const
Constant element accessor.
mha_real_t sum (const unsigned int &a, const unsigned int &b)
sum of all elements between [a,b) in all channels
mha_real_t sum (const unsigned int &a, const unsigned int &b, const unsigned int &ch)
sum of all elements between [a,b) in channel ch
mha_real_t sum ()
sum of all elements
mha_real_t sumsqr ()
sum of square of all elements
mha_real_t sum_channel (const unsigned int &)
return sum of all elements in one channel
void assign (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
set frame "k" in channel "ch" to value "val"
void assign (const mha_real_t &)
set all elements to value
void assign_frame (const unsigned int &k, const mha_real_t &val)
assign value "val" to frame k in all channels
void assign_channel (const unsigned int &c, const mha_real_t &val)
assign value "val" to channel ch in all frames
void copy (const std::vector< mha_real_t > &v)
void copy (const mha_wave_t &)
copy data from source into current waveform
void copy (const mha_wave_t *)
void copy_channel (const mha_wave_t &, unsigned int, unsigned int)
Copy one channel of a given waveform signal to a target channel.
void copy_from_at (unsigned int, unsigned int, const mha_wave_t &, unsigned int)
Copy part of the source signal into part of this waveform object.
void export_to (mha_wave_t &)
copy data into allocated mha_wave_t structure
void limit (const mha_real_t &min, const mha_real_t &max)
limit target to range [min,max]
void power (const waveform_t &)
transform waveform signal (in Pa) to squared signal (in W/m^2)
void powspec (const mha_spec_t &)
get the power spectrum (in W/m^2) from a complex spectrum
void scale (const unsigned int &a, const unsigned int &b, const unsigned int &ch, const mha_real_t &val)
scale section [a,b) in channel "ch" by "val"
void scale (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
scale one element
void scale_channel (const unsigned int &, const mha_real_t &)
scale one channel of target with a scalar
void scale_frame (const unsigned int &, const mha_real_t &)
unsigned int get_size () const
Additional Inherited Members
Public Attributes inherited from mha_wave_t
mha_real_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Detailed Description
signal processing class for waveform data (based on mha_wave_t)
Constructor & Destructor Documentation
waveform_t::waveform_t (const unsigned int & frames, const unsigned int & channels)
constructor of waveform_t
Allocates buffer memory and initializes values to zero.
Parameters
frames number of frames in each channel
channels number of channels
References mha_wave_t::buf, mha_wave_t::channel_info, channels(), mha_wave_t::num_channels, and mha_wave_t::num_frames.
waveform_t::waveform_t (const mhaconfig_t & cf) explicit
Constructor to create a waveform from plugin configuration.
Parameters
cf Plugin configuration
References mha_wave_t::buf, mha_wave_t::channel_info, mhaconfig_t::channels, mhaconfig_t::fragsize, mha_wave_t::num_channels, and mha_wave_t::num_frames.
waveform_t::waveform_t (const mha_wave_t & src) explicit
Copy contructor for mha_wave_t source.
References mha_wave_t::buf, mha_wave_t::channel_info, copy(), mha_wave_t::num_channels, and mha_wave_t::num_frames.
waveform_t::waveform_t (const MHASignal::waveform_t & src)
Copy contructor.
References mha_wave_t::buf, mha_wave_t::channel_info, copy(), mha_wave_t::num_channels, and mha_wave_t::num_frames.
waveform_t::waveform_t (const std::vector< mha_real_t > & src)
Copy contructor for std::vector<mha_real_t> source.
A waveform structure with a single channel is created, the length is equal to the number of elements in the source vector.
References mha_wave_t::buf, mha_wave_t::channel_info, mha_wave_t::num_channels, and mha_wave_t::num_frames.
waveform_t::~waveform_t (void) virtual
Reimplemented in MHA_AC::waveform_t.
References mha_wave_t::buf, mha_wave_t::channel_info, Getmsg, and mha_debug().
Member Function Documentation
void MHASignal::waveform_t::operator= (const mha_real_t & v) inline
References assign().
mha_real_t& MHASignal::waveform_t::operator[] (unsigned int k) inline
References mha_spec_t::buf.
const mha_real_t& MHASignal::waveform_t::operator[] (unsigned int k) const inline
References mha_spec_t::buf.
mha_real_t& MHASignal::waveform_t::value (unsigned int t, unsigned int ch) inline
Element accessor.
Parameters
t Frame number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, and mha_spec_t::num_channels.
Referenced by MHASignal::copy_channel(), MHASignal::spectrum_t::copy_channel(), dc::dc_t::dc_t(), MHAOvlFilter::fftfb_t::fftfb_t(), MHAFilter::fftfilterbank_t::filter(), integrate(), MHAFilter::smoothspec_t::internal_fir(), MHASignal::minphase_t::operator()(), MHAWindow::base_t::operator()(), operator*=(), operator+=(), operator-=(), MHAFilter::partitioned_convolution_t::partitioned_convolution_t(), MHASignal::loop_wavefragment_t::playback(), combc_t::process(), dc::dc_t::process(), adm_if_t::process(), MHASignal::async_rmslevel_t::process(), io_parser_t::process_frame(), MHASignal::stat_t::push(), MHAWindow::base_t::ramp_begin(), MHAWindow::base_t::ramp_end(), MHAFilter::resampling_filter_t::resampling_filter_t(), MHAFilter::smoothspec_t::spec2fir(), MHAMultiSrc::waveform_t::update(), and MHASignal::ringbuffer_t::value().
mha_real_t& MHASignal::waveform_t::operator() (unsigned int t, unsigned int ch) inline
Element accessor.
Parameters
t Frame number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, and mha_spec_t::num_channels.
const mha_real_t& MHASignal::waveform_t::value (unsigned int t, unsigned int ch) const inline
Constant element accessor.
Parameters
t Frame number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, and mha_spec_t::num_channels.
const mha_real_t& MHASignal::waveform_t::operator() (unsigned int t, unsigned int ch) const inline
Constant element accessor.
Parameters
t Frame number
ch Channel number
Returns
Reference to element
References assign(), mha_spec_t::buf, MHASignal::spectrum_t::copy(), MHASignal::spectrum_t::copy_channel(), MHASignal::spectrum_t::export_to(), MHASignal::limit(), mha_spec_t::num_channels, MHASignal::spectrum_t::scale(), and MHASignal::spectrum_t::scale_channel().
mha_real_t waveform_t::sum (const unsigned int & a, const unsigned int & b)
sum of all elements between [a,b) in all channels
Parameters
a starting frame
b end frame (excluded)
Returns
sum
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by MHAFilter::resampling_filter_t::resampling_filter_t().
mha_real_t waveform_t::sum (const unsigned int & a, const unsigned int & b, const unsigned int & ch)
sum of all elements between [a,b) in channel ch
Parameters
a starting frame
b end frame (exluded)
ch channel number
Returns
sum
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
mha_real_t waveform_t::sum ()
sum of all elements
Returns
sum of all elements
References mha_wave_t::buf, and get_size().
Referenced by MHAOvlFilter::fftfb_t::fftfb_t().
mha_real_t waveform_t::sumsqr ()
sum of square of all elements
Returns
sum of square of all elements
References mha_wave_t::buf, and get_size().
Referenced by MHASignal::loop_wavefragment_t::loop_wavefragment_t(), and overlapadd::overlapadd_t::overlapadd_t().
mha_real_t waveform_t::sum_channel (const unsigned int & ch)
return sum of all elements in one channel
Parameters
ch channel number
Returns
sum
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
void waveform_t::assign (const unsigned int & k, const unsigned int & ch, const mha_real_t & val)
set frame "k" in channel "ch" to value "val"
Parameters
k frame number
ch channel number
val new value
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by MHAFilter::o1flt_lowpass_t::o1flt_lowpass_t(), MHAFilter::o1flt_maxtrack_t::o1flt_maxtrack_t(), and MHAFilter::o1flt_mintrack_t::o1flt_mintrack_t().
void waveform_t::assign (const mha_real_t & val)
set all elements to value
Parameters
val new value
References mha_wave_t::buf, and get_size().
void waveform_t::assign_frame (const unsigned int & k, const mha_real_t & val)
assign value "val" to frame k in all channels
Parameters
k frame number
val new value
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
void waveform_t::assign_channel (const unsigned int & ch, const mha_real_t & val)
assign value "val" to channel ch in all frames
Parameters
ch channel number
val new value
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
void waveform_t::copy (const std::vector< mha_real_t > & v)
References mha_wave_t::buf, MHASignal::min(), mha_wave_t::num_channels, mha_wave_t::num_frames, and size().
Referenced by MHAOvlFilter::fftfb_ac_info_t::fftfb_ac_info_t(), MHASignal::doublebuffer_t::outer_process(), fftfilterbank::fftfb_plug_t::process(), dc::dc_t::process(), MHASignal::delay_wave_t::process(), MHASignal::async_rmslevel_t::process(), MHASignal::spectrum_t::spectrum_t(), and waveform_t().
void waveform_t::copy (const mha_wave_t & src)
copy data from source into current waveform
Parameters
src input data (need to be same size as target)
References ASSERT_EQUAL_DIM_PTR, mha_wave_t::buf, mha_wave_t::channel_info, get_size(), and mha_wave_t::num_channels.
void waveform_t::copy (const mha_wave_t * src)
References ASSERT_EQUAL_DIM_PTR, mha_wave_t::buf, mha_wave_t::channel_info, get_size(), and mha_wave_t::num_channels.
void waveform_t::copy_channel (const mha_wave_t & src, unsigned int src_channel, unsigned int dest_channel)
Copy one channel of a given waveform signal to a target channel.
Parameters
src Input waveform signal
src_channel Channel in source signal
dest_channel Channel number in destination signal
References mha_wave_t::buf, mha_wave_t::channel_info, MHA_ErrorMsg, mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by MHAFilter::thirdoctave_analyzer_t::process(), MHASndFile::sf_wave_t::sf_wave_t(), and io_file_t::start().
void waveform_t::copy_from_at (unsigned int to_pos, unsigned int len, const mha_wave_t & src, unsigned int from_pos)
Copy part of the source signal into part of this waveform object.
Source and target have to have the same number of channels.
Parameters
to_pos Offset in target
len Number of frames copied
src Source
from_pos Offset in source
References mha_wave_t::buf, mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by MHAFilter::fftfilterbank_t::filter(), MHAFilter::partitioned_convolution_t::process(), and MHAFilter::fftfilterbank_t::update_coeffs().
void waveform_t::export_to (mha_wave_t & dest)
copy data into allocated mha_wave_t structure
Parameters
dest destination structure
References ASSERT_EQUAL_DIM_PTR, mha_wave_t::buf, mha_wave_t::channel_info, get_size(), and mha_wave_t::num_channels.
void waveform_t::limit (const mha_real_t & min, const mha_real_t & max)
limit target to range [min,max]
Parameters
min lower limit
max upper limit
References MHASignal::limit().
void waveform_t::power (const waveform_t & src)
transform waveform signal (in Pa) to squared signal (in W/m^2)
Parameters
src linear waveform signal (in Pa)
References mha_wave_t::buf, MHA_ErrorMsg, mha_wave_t::num_channels, and mha_wave_t::num_frames.
void waveform_t::powspec (const mha_spec_t & src)
get the power spectrum (in W/m^2) from a complex spectrum
Parameters
src complex spectrum (normalized to Pa)
References mha_wave_t::buf, mha_spec_t::buf, mha_complex_t::im, MHA_ErrorMsg, mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, mha_spec_t::num_frames, and mha_complex_t::re.
void waveform_t::scale (const unsigned int & a, const unsigned int & b, const unsigned int & ch, const mha_real_t & val)
scale section [a,b) in channel "ch" by "val"
Parameters
a starting frame
b end frame (excluded)
ch channel number
val scale factor
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
void waveform_t::scale (const unsigned int & k, const unsigned int & ch, const mha_real_t & val)
scale one element
Parameters
k frame number
ch channel number
val scale factor
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
void waveform_t::scale_channel (const unsigned int & ch, const mha_real_t & src)
scale one channel of target with a scalar
Parameters
ch channel number
src factor
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
void waveform_t::scale_frame (const unsigned int & frame, const mha_real_t & val)
References mha_wave_t::buf, CHECK_VAR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
unsigned int MHASignal::waveform_t::get_size () const inline
References MHASignal::limit(), MHASignal::spectrum_t::scale(), and size().
Referenced by assign(), copy(), export_to(), sum(), and sumsqr().
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp