openMHA Manual: MHASignal::schroeder_t Class Reference
MHASignal::schroeder_t Class Reference
Schroeder tone complex class.
#include <mha_signal.hh>
Public Types
enum sign_t { up, down }
Enumerator for sign of Schroeder tone complex sweep direction.
typedef float(* groupdelay_t) (float f, float fmin, float fmax)
Function type for group delay definition.
Public Member Functions
schroeder_t (unsigned int len, unsigned int channels=1, schroeder_t::sign_t sign=up, mha_real_t speed=1)
Constructor.
schroeder_t (unsigned int len, unsigned int channels=1, schroeder_t::groupdelay_t freqfun=MHASignal::schroeder_t::identity, float fmin=0, float fmax=1, float eps=1e-10)
Construct create Schroeder tone complex from a given frequency function.
Public Member Functions inherited from MHASignal::waveform_t
waveform_t (const unsigned int &frames, const unsigned int &channels)
constructor of waveform_t
waveform_t (const mhaconfig_t &cf)
Constructor to create a waveform from plugin configuration.
waveform_t (const mha_wave_t &src)
Copy contructor for mha_wave_t source.
waveform_t (const MHASignal::waveform_t &src)
Copy contructor.
waveform_t (const std::vector< mha_real_t > &src)
Copy contructor for std::vector<mha_real_t> source.
virtual ~waveform_t (void)
void operator= (const mha_real_t &v)
mha_real_t & operator[] (unsigned int k)
const mha_real_t & operator[] (unsigned int k) const
mha_real_t & value (unsigned int t, unsigned int ch)
Element accessor.
mha_real_t & operator() (unsigned int t, unsigned int ch)
Element accessor.
const mha_real_t & value (unsigned int t, unsigned int ch) const
Constant element accessor.
const mha_real_t & operator() (unsigned int t, unsigned int ch) const
Constant element accessor.
mha_real_t sum (const unsigned int &a, const unsigned int &b)
sum of all elements between [a,b) in all channels
mha_real_t sum (const unsigned int &a, const unsigned int &b, const unsigned int &ch)
sum of all elements between [a,b) in channel ch
mha_real_t sum ()
sum of all elements
mha_real_t sumsqr ()
sum of square of all elements
mha_real_t sum_channel (const unsigned int &)
return sum of all elements in one channel
void assign (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
set frame "k" in channel "ch" to value "val"
void assign (const mha_real_t &)
set all elements to value
void assign_frame (const unsigned int &k, const mha_real_t &val)
assign value "val" to frame k in all channels
void assign_channel (const unsigned int &c, const mha_real_t &val)
assign value "val" to channel ch in all frames
void copy (const std::vector< mha_real_t > &v)
void copy (const mha_wave_t &)
copy data from source into current waveform
void copy (const mha_wave_t *)
void copy_channel (const mha_wave_t &, unsigned int, unsigned int)
Copy one channel of a given waveform signal to a target channel.
void copy_from_at (unsigned int, unsigned int, const mha_wave_t &, unsigned int)
Copy part of the source signal into part of this waveform object.
void export_to (mha_wave_t &)
copy data into allocated mha_wave_t structure
void limit (const mha_real_t &min, const mha_real_t &max)
limit target to range [min,max]
void power (const waveform_t &)
transform waveform signal (in Pa) to squared signal (in W/m^2)
void powspec (const mha_spec_t &)
get the power spectrum (in W/m^2) from a complex spectrum
void scale (const unsigned int &a, const unsigned int &b, const unsigned int &ch, const mha_real_t &val)
scale section [a,b) in channel "ch" by "val"
void scale (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
scale one element
void scale_channel (const unsigned int &, const mha_real_t &)
scale one channel of target with a scalar
void scale_frame (const unsigned int &, const mha_real_t &)
unsigned int get_size () const
Static Public Member Functions
static float identity (float x, float, float)
static float log_up (float x, float fmin, float fmax)
static float log_down (float x, float fmin, float fmax)
Additional Inherited Members
Public Attributes inherited from mha_wave_t
mha_real_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Detailed Description
Schroeder tone complex class.
The Schroeder tone complex is a sweep defined in the sampled spectrum:
is the sampled frequency in Hz, is the sign of the sweep (-1 for up sweep, +1 for down sweep), is the sweep duration in samples, is the sampling rate in Hz and is the relative sweep speed.
Member Typedef Documentation
typedef float(* MHASignal::schroeder_t::groupdelay_t) (float f, float fmin, float fmax)
Function type for group delay definition.
Parameters
f Frequency relative to Nyquist frequency.
fmin Minimum frequency relative to Nyquist frequency.
fmax Maximum frequency relative to Nyquist frequency.
Member Enumeration Documentation
enum MHASignal::schroeder_t::sign_t
Enumerator for sign of Schroeder tone complex sweep direction.
Enumerator
up
Sweep from zero to Nyquist frequency ()
down
Sweep from Nyquist frequency to zero ()
Constructor & Destructor Documentation
MHASignal::schroeder_t::schroeder_t (unsigned int len, unsigned int channels = 1, schroeder_t::sign_t sign = up, mha_real_t speed = 1)
Constructor.
Parameters of the Schroeder tone complex are configured in the constructor.
Parameters
len Length of the Schroeder tone complex in samples
channels Number of channels
sign Sign of Schroeder sweep
speed Relative speed (curvature of phase function)
References down, expi(), M_PI, mha_fft_free(), mha_fft_new(), mha_fft_spec2wave(), mha_spec_t::num_channels, mha_spec_t::num_frames, and up.
MHASignal::schroeder_t::schroeder_t (unsigned int len, unsigned int channels = 1, schroeder_t::groupdelay_t freqfun = MHASignal::schroeder_t::identity, float fmin = 0, float fmax = 1, float eps = 1e-10)
Construct create Schroeder tone complex from a given frequency function.
The frequency function defines the sweep speed and sign (based on the group delay). It must be defined in the interval [0,1) and should return values in the interval [0,1].
Parameters
len Length of the Schroeder tone complex in samples.
channels Number of channels.
freqfun Frequency function .
fmin Start frequency (relative to Nyquist frequency).
fmax End frequency (relative to Nyquist frequency).
eps Stability constant for frequency ranges not covered by Schroeder tone complex.
References expi(), integrate(), M_PI, mha_fft_free(), mha_fft_new(), mha_fft_spec2wave(), MHASignal::min(), mha_spec_t::num_channels, mha_wave_t::num_frames, and mha_spec_t::num_frames.
Member Function Documentation
static float MHASignal::schroeder_t::identity (float x, float , float) inline static
Referenced by log_down().
static float MHASignal::schroeder_t::log_up (float x, float fmin, float fmax) inline static
static float MHASignal::schroeder_t::log_down (float x, float fmin, float fmax) inline static
References identity().
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp