openMHA Manual: MHASignal::spectrum_t Class Reference
MHASignal::spectrum_t Class Reference
The MHA Toolbox library » Vector and matrix processing toolbox
a signal processing class for spectral data (based on mha_spec_t)
#include <mha_signal.hh>
Public Member Functions
spectrum_t (const unsigned int &frames, const unsigned int &channels)
constructor of spectrum class
spectrum_t (const mha_spec_t &)
Copy constructor.
spectrum_t (const MHASignal::spectrum_t &)
Copy constructor.
spectrum_t (const std::vector< mha_complex_t > &)
virtual ~spectrum_t (void)
mha_complex_t & operator() (unsigned int f, unsigned int ch)
Access to element.
mha_complex_t & operator[] (unsigned int k)
Access to a single element, direct index into data buffer.
mha_complex_t & value (unsigned int f, unsigned int ch)
Access to element.
void copy (const mha_spec_t &)
copy all elements from a spectrum
void copy_channel (const mha_spec_t &s, unsigned sch, unsigned dch)
Copy one channel of a given spectrum signal to a target channel.
void export_to (mha_spec_t &)
copy elements to spectrum structure
void scale (const unsigned int &, const unsigned int &, const unsigned int &, const mha_real_t &)
scale section [a,b) in channel "ch" by "val"
void scale_channel (const unsigned int &, const mha_real_t &)
scale all elements in one channel
Additional Inherited Members
Public Attributes inherited from mha_spec_t
mha_complex_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Detailed Description
a signal processing class for spectral data (based on mha_spec_t)
Constructor & Destructor Documentation
spectrum_t::spectrum_t (const unsigned int & frames, const unsigned int & channels)
constructor of spectrum class
Allocates buffers and initializes memory to zeros.
Parameters
frames number of frames (fft bins) in one channel. Number of Frames is usually fftlen / 2 + 1
channels number of channels
References mha_wave_t::buf, mha_wave_t::channel_info, channels(), mha_wave_t::num_channels, and mha_wave_t::num_frames.
spectrum_t::spectrum_t (const mha_spec_t & src) explicit
Copy constructor.
References mha_wave_t::buf, mha_wave_t::channel_info, MHASignal::waveform_t::copy(), mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, and mha_spec_t::num_frames.
spectrum_t::spectrum_t (const MHASignal::spectrum_t & src)
Copy constructor.
References mha_wave_t::buf, mha_wave_t::channel_info, MHASignal::waveform_t::copy(), mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, and mha_spec_t::num_frames.
spectrum_t::spectrum_t (const std::vector< mha_complex_t > & src)
References mha_wave_t::buf, mha_wave_t::channel_info, mha_wave_t::num_channels, and mha_wave_t::num_frames.
spectrum_t::~spectrum_t (void) virtual
Reimplemented in MHA_AC::spectrum_t.
References mha_wave_t::buf, mha_wave_t::channel_info, Getmsg, and mha_debug().
Member Function Documentation
mha_complex_t& MHASignal::spectrum_t::operator() (unsigned int f, unsigned int ch) inline
Access to element.
Parameters
f Bin number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, and mha_spec_t::num_frames.
mha_complex_t& MHASignal::spectrum_t::operator[] (unsigned int k) inline
Access to a single element, direct index into data buffer.
Parameters
k Buffer index
Returns
Reference to element
References mha_spec_t::buf.
mha_complex_t& MHASignal::spectrum_t::value (unsigned int f, unsigned int ch) inline
Access to element.
Parameters
f Bin number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, copy(), copy_channel(), export_to(), mha_spec_t::num_frames, scale(), and scale_channel().
Referenced by speechnoise_t::creator(), combc_t::process(), MHAFilter::partitioned_convolution_t::process(), and MHAMultiSrc::spectrum_t::update().
void spectrum_t::copy (const mha_spec_t & src)
copy all elements from a spectrum
Parameters
src input spectrum
References ASSERT_EQUAL_DIM_PTR, mha_wave_t::buf, mha_spec_t::buf, mha_wave_t::channel_info, mha_spec_t::channel_info, mha_wave_t::num_channels, and size().
Referenced by MHAFilter::smoothspec_t::internal_fir(), MHASignal::waveform_t::operator()(), MHASignal::delay_spec_t::process(), and value().
void spectrum_t::copy_channel (const mha_spec_t & s, unsigned sch, unsigned dch)
Copy one channel of a given spectrum signal to a target channel.
Parameters
s Input spectrum signal
sch Channel index in source signal
dch Channel index in destination (this) signal
References mha_wave_t::channel_info, mha_spec_t::channel_info, MHA_ErrorMsg, mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, mha_spec_t::num_frames, and MHASignal::waveform_t::value().
Referenced by MHASignal::waveform_t::operator()(), and value().
void spectrum_t::export_to (mha_spec_t & dest)
copy elements to spectrum structure
Parameters
dest destination spectrum structure
References ASSERT_EQUAL_DIM_PTR, mha_wave_t::buf, mha_spec_t::buf, mha_wave_t::channel_info, mha_spec_t::channel_info, mha_wave_t::num_channels, and size().
Referenced by MHASignal::waveform_t::operator()(), and value().
void spectrum_t::scale (const unsigned int & a, const unsigned int & b, const unsigned int & ch, const mha_real_t & val)
scale section [a,b) in channel "ch" by "val"
Parameters
a starting frame
b end frame (excluded)
ch channel number
val scale factor
References mha_wave_t::buf, CHECK_EXPR, mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by MHASignal::waveform_t::get_size(), MHASignal::waveform_t::operator()(), and value().
void spectrum_t::scale_channel (const unsigned int & ch, const mha_real_t & src)
scale all elements in one channel
Parameters
ch channel number
src scale factor
References mha_wave_t::buf, and mha_wave_t::num_frames.
Referenced by MHASignal::waveform_t::operator()(), and value().
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp