openMHA Manual: gaintable.cpp File Reference
gaintable.cpp File Reference
#include "gaintable.h"
#include <math.h>
#include <numeric>
#include <iostream>
#include "mha_signal.hh"
Functions
std::vector< mha_real_t > convert_f2logf (const std::vector< mha_real_t > &vF)
bool isempty (const std::vector< std::vector< mha_real_t > > &arg)
Function Documentation
std::vector<mha_real_t> convert_f2logf (const std::vector< mha_real_t > & vF)
bool isempty (const std::vector< std::vector< mha_real_t > > & arg)
References size().
Referenced by MHAFilter::transfer_function_t::non_empty_partitions(), MHAFilter::partitioned_convolution_t::partitioned_convolution_t(), and DynComp::gaintable_t::update().