openMHA Manual: mha_os.h File Reference
mha_os.h File Reference
#include <list>
#include <stdint.h>
#include <stdlib.h>
#include <dlfcn.h>
#include <unistd.h>
#include <netinet/in.h>
#include <string>
Classes
class dynamiclib_t
Macros
#define mha_loadlib(x) dlopen(x,RTLD_NOW)
#define mha_freelib(x) dlclose(x)
#define mha_freelib_success(x) (x == 0)
#define mha_getlibfun(h, x) x ## _cb = (x ## _t)dlsym(h,#x)
#define mha_getlibfun_checked(h, x) x ## _cb = (x ## _t)dlsym(h,#x);if(! x ## _cb) throw MHA_Error(__FILE__,__LINE__,"Function " #x " is undefined.")
#define mha_loadlib_error(x) dlerror()
#define mha_lib_extension ".so"
#define mha_msleep(milliseconds) usleep((milliseconds)*1000)
#define FMTsz "%zu"
printf modifier to print integers of type size_t
#define MHA_RESOLVE(h, t) t ## _cb = (t ## _t)(h->resolve(#t))
#define MHA_RESOLVE_CHECKED(h, t) t ## _cb = (t ## _t)(h->resolve_checked(#t))
Typedefs
typedef void * mha_libhandle_t
Functions
std::string mha_getenv (std::string envvar)
std::list< std::string > mha_library_paths ()
std::list< std::string > list_dir (const std::string &path, const std::string &pattern)
void mha_hton (float *data, unsigned int len)
void mha_ntoh (float *data, unsigned int len)
void mha_hton (uint32_t *data, unsigned int len)
void mha_ntoh (uint32_t *data, unsigned int len)
void mha_hton (int32_t *data, unsigned int len)
void mha_ntoh (int32_t *data, unsigned int len)
Macro Definition Documentation
#define mha_loadlib (x) dlopen(x,RTLD_NOW)
#define mha_freelib (x) dlclose(x)
#define mha_freelib_success (x) (x == 0)
#define mha_getlibfun (h, x) x ## _cb = (x ## _t)dlsym(h,#x)
#define mha_getlibfun_checked (h, x) x ## _cb = (x ## _t)dlsym(h,#x);if(! x ## _cb) throw MHA_Error(__FILE__,__LINE__,"Function " #x " is undefined.")
#define mha_loadlib_error (x) dlerror()
#define mha_lib_extension ".so"
Referenced by dynamiclib_t::dynamiclib_t().
#define mha_msleep (milliseconds) usleep((milliseconds)*1000)
Referenced by fw_t::fw_sleep_cmd(), fw_t::fw_until_cmd(), and fw_t::stop().
#define FMTsz "%zu"
printf modifier to print integers of type size_t
#define MHA_RESOLVE (h, t) t ## _cb = (t ## _t)(h->resolve(#t))
Referenced by PluginLoader::mhapluginloader_t::resolve_and_init().
#define MHA_RESOLVE_CHECKED (h, t) t ## _cb = (t ## _t)(h->resolve_checked(#t))
Referenced by io_lib_t::io_lib_t(), and PluginLoader::mhapluginloader_t::resolve_and_init().
Typedef Documentation
typedef void* mha_libhandle_t
Function Documentation
std::string mha_getenv (std::string envvar)
Referenced by MHAParser::envreplace(), MHAParser::get_precision(), and mha_library_paths().
std::list<std::string> mha_library_paths ()
References mha_getenv().
Referenced by dynamiclib_t::dynamiclib_t(), and pluginbrowser_t::get_paths().
std::list<std::string> list_dir (const std::string & path, const std::string & pattern)
Referenced by pluginbrowser_t::add_plugins().
void mha_hton (float * data, unsigned int len) inline
void mha_ntoh (float * data, unsigned int len) inline
void mha_hton (uint32_t * data, unsigned int len) inline
void mha_ntoh (uint32_t * data, unsigned int len) inline
void mha_hton (int32_t * data, unsigned int len) inline
void mha_ntoh (int32_t * data, unsigned int len) inline