openMHA Manual: generatemhaplugindoc.cpp File Reference
generatemhaplugindoc.cpp File Reference
#include "mhapluginloader.h"
#include "mha_algo_comm.hh"
#include <exception>
#include <getopt.h>
#include <stdarg.h>
#include <fstream>
Classes
class latex_doc_t
Functions
std::string conv2latex (std::string s, bool iscolored=false)
void create_latex_doc (std::map< std::string, std::string > &doc, const std::string &plugname, const std::string &plugin_macro)
int main (int argc, char **argv)
Function Documentation
std::string conv2latex (std::string s, bool iscolored = false)
References MHAParser::strreplace().
Referenced by latex_doc_t::get_latex_doc(), latex_doc_t::get_parser_tab(), latex_doc_t::get_parser_var(), and main().
void create_latex_doc (std::map< std::string, std::string > & doc, const std::string & plugname, const std::string & plugin_macro)
References latex_doc_t::get_latex_doc(), and latex_doc_t::get_main_category().
Referenced by main().
int main (int argc, char ** argv)
References conv2latex(), create_latex_doc(), and latex_doc_t::plugin_macro.