openMHA Manual: overlapadd::overlapadd_if_t Class Reference
overlapadd::overlapadd_if_t Class Reference
Public Member Functions
overlapadd_if_t (const algo_comm_t &, const std::string &, const std::string &)
~overlapadd_if_t ()
void prepare (mhaconfig_t &)
void release ()
mha_wave_t * process (mha_wave_t *)
Public Member Functions inherited from MHAPlugin::plugin_t< overlapadd_t >
plugin_t (const std::string &, const algo_comm_t &)
Constructor of plugin template.
virtual ~plugin_t ()
void prepare_ (mhaconfig_t &)
void release_ ()
bool is_prepared () const
Flag, if the prepare method is successfully called (or currently evaluated)
mhaconfig_t input_cfg () const
Current input channel configuration.
mhaconfig_t output_cfg () const
Current output channel configuration.
Public Member Functions inherited from MHAParser::parser_t
parser_t (const std::string &help_text="")
Construct detached node to be used in the configuration tree.
~parser_t ()
void insert_item (const std::string &, base_t *)
Register a parser item into this sub-parser.
void remove_item (const std::string &)
Remove an item by name.
void force_remove_item (const std::string &)
Remove an item by name.
void remove_item (const base_t *)
Remove an item by address.
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual std::string parse (const std::string &)
Causes this node to process a command in the MHA configuration language.
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from MHAPlugin::config_t< overlapadd_t >
config_t ()
~config_t ()
Private Member Functions
void update ()
Private Attributes
MHAEvents::patchbay_t< overlapadd_if_t > patchbay
MHAParser::int_t nfft
FFT length to be used, zero-padding is FFT length-wndlength.
MHAParser::int_t nwnd
Window length to be used (overlap is 1-fragsize/wndlength)
MHAParser::float_t wndpos
Relative position of zero padding (0 end, 0.5 center, 1 start)
MHAParser::window_t window
MHAParser::float_t wndexp
MHAParser::window_t zerowindow
MHAParser::mhapluginloader_t plugloader
MHAParser::float_mon_t prescale
MHAParser::float_mon_t postscale
std::string algo
mhaconfig_t cf_in
mhaconfig_t cf_out
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Protected Member Functions inherited from MHAParser::parser_t
std::string op_subparse (expression_t &)
std::string op_setval (expression_t &)
std::string op_query (expression_t &)
std::string query_type (const std::string &)
std::string query_dump (const std::string &)
std::string query_entries (const std::string &)
std::string query_readfile (const std::string &)
std::string query_savefile (const std::string &)
std::string query_savefile_compact (const std::string &)
std::string query_savemons (const std::string &)
std::string query_val (const std::string &)
std::string query_listids (const std::string &)
void set_id_string (const std::string &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Member Functions inherited from MHAPlugin::config_t< overlapadd_t >
overlapadd_t * poll_config ()
Receive the latest run time configuration.
overlapadd_t * last_config ()
Receive the latest run time configuration.
void push_config (overlapadd_t *ncfg)
Push a new run time configuration into the configuration fifo.
void cleanup_unused_cfg ()
Protected Attributes inherited from MHAPlugin::plugin_t< overlapadd_t >
mhaconfig_t tftype
Member for storage of plugin interface configuration.
algo_comm_t ac
AC handle of the chain.
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Protected Attributes inherited from MHAPlugin::config_t< overlapadd_t >
overlapadd_t * cfg
Constructor & Destructor Documentation
overlapadd::overlapadd_if_t::overlapadd_if_t (const algo_comm_t & iac, const std::string & , const std::string & ialg)
References MHAParser::parser_t::insert_item(), insert_member, nfft, nwnd, MHAParser::base_t::parse(), patchbay, postscale, prescale, update(), window, wndexp, wndpos, MHAParser::base_t::writeaccess, and zerowindow.
overlapadd::overlapadd_if_t::~overlapadd_if_t ()
Member Function Documentation
void overlapadd::overlapadd_if_t::prepare (mhaconfig_t & t) virtual
Implements MHAPlugin::plugin_t< overlapadd_t >.
References cf_in, cf_out, MHAParser::int_t::data, mhaconfig_t::domain, mhaconfig_t::fftlen, mhaconfig_t::fragsize, MHA_ErrorMsg, MHA_SPECTRUM, MHA_WAVEFORM, nfft, nwnd, plugloader, MHAPlugin::config_t< overlapadd_t >::poll_config(), MHAParser::mhapluginloader_t::prepare(), MHAPlugin::plugin_t< overlapadd_t >::tftype, update(), and mhaconfig_t::wndlen.
void overlapadd::overlapadd_if_t::release () virtual
Reimplemented from MHAPlugin::plugin_t< overlapadd_t >.
References plugloader, and MHAParser::mhapluginloader_t::release().
mha_wave_t * overlapadd::overlapadd_if_t::process (mha_wave_t * wave_in)
References MHAPlugin::config_t< overlapadd_t >::cfg, MHAPLUGIN_CALLBACKS, MHAPLUGIN_DOCUMENTATION, plugloader, MHAPlugin::config_t< overlapadd_t >::poll_config(), and MHAParser::mhapluginloader_t::process().
void overlapadd::overlapadd_if_t::update () private
References cf_in, cf_out, mhaconfig_t::channels, MHAParser::float_t::data, MHAParser::float_mon_t::data, mhaconfig_t::fftlen, mhaconfig_t::fragsize, postscale, prescale, MHAPlugin::config_t< overlapadd_t >::push_config(), window, wndexp, mhaconfig_t::wndlen, wndpos, and zerowindow.
Referenced by overlapadd_if_t(), and prepare().
Member Data Documentation
MHAEvents::patchbay_t<overlapadd_if_t> overlapadd::overlapadd_if_t::patchbay private
Referenced by overlapadd_if_t().
MHAParser::int_t overlapadd::overlapadd_if_t::nfft private
FFT length to be used, zero-padding is FFT length-wndlength.
Referenced by overlapadd_if_t(), and prepare().
MHAParser::int_t overlapadd::overlapadd_if_t::nwnd private
Window length to be used (overlap is 1-fragsize/wndlength)
Referenced by overlapadd_if_t(), and prepare().
MHAParser::float_t overlapadd::overlapadd_if_t::wndpos private
Relative position of zero padding (0 end, 0.5 center, 1 start)
Referenced by overlapadd_if_t(), and update().
MHAParser::window_t overlapadd::overlapadd_if_t::window private
Referenced by overlapadd_if_t(), and update().
MHAParser::float_t overlapadd::overlapadd_if_t::wndexp private
Referenced by overlapadd_if_t(), and update().
MHAParser::window_t overlapadd::overlapadd_if_t::zerowindow private
Referenced by overlapadd_if_t(), and update().
MHAParser::mhapluginloader_t overlapadd::overlapadd_if_t::plugloader private
Referenced by prepare(), process(), and release().
MHAParser::float_mon_t overlapadd::overlapadd_if_t::prescale private
Referenced by overlapadd_if_t(), and update().
MHAParser::float_mon_t overlapadd::overlapadd_if_t::postscale private
Referenced by overlapadd_if_t(), and update().
std::string overlapadd::overlapadd_if_t::algo private
mhaconfig_t overlapadd::overlapadd_if_t::cf_in private
Referenced by prepare(), and update().
mhaconfig_t overlapadd::overlapadd_if_t::cf_out private
Referenced by prepare(), and update().
The documentation for this class was generated from the following file:
overlapadd.cpp