openMHA Manual: MHASignal::stat_t Class Reference
MHASignal::stat_t Class Reference
#include <mha_signal.hh>
Public Member Functions
stat_t (const unsigned int &frames, const unsigned int &channels)
void mean (mha_wave_t &m)
void mean_std (mha_wave_t &m, mha_wave_t &s)
void push (const mha_wave_t &)
void push (const mha_real_t &x, const unsigned int &k, const unsigned int &ch)
Private Attributes
MHASignal::waveform_t n
MHASignal::waveform_t sum
MHASignal::waveform_t sum2
Constructor & Destructor Documentation
MHASignal::stat_t::stat_t (const unsigned int & frames, const unsigned int & channels)
Member Function Documentation
void MHASignal::stat_t::mean (mha_wave_t & m)
References ASSERT_EQUAL_DIM, mha_wave_t::buf, MHASignal::max(), size(), and sum.
void MHASignal::stat_t::mean_std (mha_wave_t & m, mha_wave_t & s)
References ASSERT_EQUAL_DIM, mha_wave_t::buf, MHASignal::max(), size(), sum, and sum2.
Referenced by MHA_AC::stat_t::update().
void MHASignal::stat_t::push (const mha_wave_t & x)
References ASSERT_EQUAL_DIM, mha_wave_t::buf, size(), sum, and sum2.
void MHASignal::stat_t::push (const mha_real_t & x, const unsigned int & k, const unsigned int & ch)
References CHECK_EXPR, mha_wave_t::num_channels, mha_wave_t::num_frames, sum, sum2, and MHASignal::waveform_t::value().
Member Data Documentation
MHASignal::waveform_t MHASignal::stat_t::n private
MHASignal::waveform_t MHASignal::stat_t::sum private
Referenced by mean(), mean_std(), and push().
MHASignal::waveform_t MHASignal::stat_t::sum2 private
Referenced by mean_std(), and push().
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp