openMHA Manual: mha_parser.cpp File Reference
mha_parser.cpp File Reference
#include <stdio.h>
#include <sstream>
#include <ctype.h>
#include "mha_parser.hh"
#include "mha_error.hh"
#include "mha_defs.h"
#include "mha.h"
#include "mha_os.h"
#include <fstream>
#include "mha_signal.hh"
Namespaces
MHAParser
Name space for the MHA-Parser configuration language.
MHAParser::StrCnv
String converter namespace.
Macros
#define MHAPLATFORM "undefined-linux"
Functions
int MHAParser::get_precision ()
int MHAParser::StrCnv::num_brackets (const std::string &s)
Return number of brackets at beginning and end of string.
int MHAParser::StrCnv::bracket_balance (const std::string &s)
static std::ostream & write_float (std::ostream &o, const float &f)
static std::string parse_1_float (const std::string &s, mha_real_t &v)
static std::string parse_1_complex (const std::string &s, mha_complex_t &v)
Macro Definition Documentation
#define MHAPLATFORM "undefined-linux"
Referenced by MHAParser::base_t::base_t().
Function Documentation
static std::ostream& write_float (std::ostream & o, const float & f) inline static
Referenced by MHAParser::StrCnv::val2str().
static std::string parse_1_float (const std::string & s, mha_real_t & v) static
This internal function parses a floating point number from the beginning of a string.
Parameters
s The string to parse
v The float variable to fill with a value
Returns
The rest of the string.
Referenced by parse_1_complex().
static std::string parse_1_complex (const std::string & s, mha_complex_t & v) static
This internal function parses a complex number from the beginning of a string.
Parameters
s The string to parse
v The complex variable to fill with a value
Returns
The rest of the string.
References mha_complex_t::im, MHA_ErrorMsg, parse_1_float(), and mha_complex_t::re.
Referenced by MHAParser::StrCnv::str2val().