openMHA Manual: MHATableLookup::xy_table_t Class Reference
MHATableLookup::xy_table_t Class Reference
Class for interpolation with non-equidistant x values.
#include <mha_tablelookup.hh>
Public Member Functions
xy_table_t ()
mha_real_t lookup (mha_real_t x)
Return the y-value at the position of the nearest x value below input.
mha_real_t interp (mha_real_t x)
Linear interpolation function.
void add_entry (mha_real_t x, mha_real_t y)
Add a single x-y pair entry.
void add_entry (mha_real_t *pVX, mha_real_t *pVY, unsigned int len)
Add multiple entries at once.
void clear ()
Clear the table and transformation functions.
void set_xfun (float(*pXFun)(float))
Set transformation function for x values.
void set_yfun (float(*pYFun)(float))
Set transformation function for y values during insertion.
void set_xyfun (float(*pYFun)(float, float))
Set transformation function for y values during insertion, based on x and y values.
Public Member Functions inherited from MHATableLookup::table_t
table_t (void)
virtual ~table_t (void)
Private Attributes
std::map< mha_real_t, mha_real_t > mXY
float(* xfun)(float)
float(* yfun)(float)
float(* xyfun)(float, float)
Additional Inherited Members
Detailed Description
Class for interpolation with non-equidistant x values.
Linear interpolation of the x-y table is performed. A transformation of x and y-values is possible; if a transformation function is provided for the x-values, the same function is applied to the argument of xy_table_t::interp() and xy_table_t::lookup(). The transformation of y values is applied only during insertion into the table. Two functions for y-transformation can be provided: a simple transformation which depends only on the y values, or a transformation which takes both (non-transformed) x and y value as an argument. The two-argument transformation is applied before the one-argument transformation.
Constructor & Destructor Documentation
xy_table_t::xy_table_t ()
Member Function Documentation
mha_real_t xy_table_t::lookup (mha_real_t x) virtual
Return the y-value at the position of the nearest x value below input.
Parameters
x Input value
Returns
y value at nearest x value below input.
Implements MHATableLookup::table_t.
References MHA_ErrorMsg, mXY, and xfun.
mha_real_t xy_table_t::interp (mha_real_t x) virtual
Linear interpolation function.
Parameters
x x value
Returns
interpolated y value
Implements MHATableLookup::table_t.
References MHASignal::max(), MHA_ErrorMsg, MHASignal::min(), mXY, and xfun.
Referenced by speechnoise_t::creator(), and MHAOvlFilter::FreqScaleFun::hz2bark().
void xy_table_t::add_entry (mha_real_t x, mha_real_t y)
Add a single x-y pair entry.
Parameters
x x value
y corresponding y value
References mXY, xfun, xyfun, and yfun.
Referenced by add_entry(), MHAOvlFilter::barkscale::bark2hz_t::bark2hz_t(), speechnoise_t::creator(), and MHAOvlFilter::barkscale::hz2bark_t::hz2bark_t().
void xy_table_t::add_entry (mha_real_t * pVX, mha_real_t * pVY, unsigned int uLength)
Add multiple entries at once.
Parameters
pVX array of x values
pVY array of y values
uLength Length of x and y arrays
References add_entry().
void xy_table_t::clear (void) virtual
Clear the table and transformation functions.
Implements MHATableLookup::table_t.
References mXY, xfun, xyfun, and yfun.
void xy_table_t::set_xfun (float(*)(float) fun)
Set transformation function for x values.
Parameters
fun Transformation function.
References xfun.
Referenced by speechnoise_t::creator().
void xy_table_t::set_yfun (float(*)(float) fun)
Set transformation function for y values during insertion.
Parameters
fun Transformation function.
References yfun.
Referenced by speechnoise_t::creator().
void xy_table_t::set_xyfun (float(*)(float, float) fun)
Set transformation function for y values during insertion, based on x and y values.
Parameters
fun Transformation function.
References xyfun.
Referenced by speechnoise_t::creator().
Member Data Documentation
std::map<mha_real_t,mha_real_t> MHATableLookup::xy_table_t::mXY private
Referenced by add_entry(), clear(), interp(), and lookup().
float(* MHATableLookup::xy_table_t::xfun) (float) private
Referenced by add_entry(), clear(), interp(), lookup(), and set_xfun().
float(* MHATableLookup::xy_table_t::yfun) (float) private
Referenced by add_entry(), clear(), and set_yfun().
float(* MHATableLookup::xy_table_t::xyfun) (float, float) private
Referenced by add_entry(), clear(), and set_xyfun().
The documentation for this class was generated from the following files:
mha_tablelookup.hh
mha_tablelookup.cpp