openMHA Manual: MHAIOTCP.cpp File Reference
MHAIOTCP.cpp File Reference
#include "../../../frameworks/src/mha_tcp.cpp"
#include <cassert>
#include <cstdio>
#include "mha_io_ifc.h"
#include "mha_toolbox.h"
#include "mha_signal.hh"
Classes
class io_tcp_parser_t
class io_tcp_sound_t
union io_tcp_sound_t::float_union
class io_tcp_fwcb_t
class io_tcp_t
The tcp sound io library.
Macros
#define ERR_SUCCESS 0
#define ERR_IHANDLE -1
#define ERR_USER -1000
#define MAX_USER_ERR 0x2000
#define MHA_ErrorMsg2(x, y) MHA_Error(__FILE__,__LINE__,(x),(y))
#define MHA_ErrorMsg3(x, y, z) MHA_Error(__FILE__,__LINE__,(x),(y),(z))
#define MIN_TCP_PORT 0
#define MIN_TCP_PORT_STR "0"
#define MAX_TCP_PORT 65535
#define MAX_TCP_PORT_STR "65535"
#define IOInit MHA_DYNAMIC_IOInit
#define IOPrepare MHA_DYNAMIC_IOPrepare
#define IOStart MHA_DYNAMIC_IOStart
#define IOStop MHA_DYNAMIC_IOStop
#define IORelease MHA_DYNAMIC_IORelease
#define IOSetVar MHA_DYNAMIC_IOSetVar
#define IOStrError MHA_DYNAMIC_IOStrError
#define IODestroy MHA_DYNAMIC_IODestroy
#define dummy_interface_test MHA_DYNAMIC_dummy_interface_test
Functions
static int copy_error (MHA_Error &e)
static void * thread_startup_function (void *parameter)
int IOInit (int fragsize, float samplerate, IOProcessEvent_t proc_event, void *proc_handle, IOStartedEvent_t start_event, void *start_handle, IOStoppedEvent_t stop_event, void *stop_handle, void **handle)
int IOPrepare (void *handle, int num_inchannels, int num_outchannels)
int IOStart (void *handle)
int IOStop (void *handle)
int IORelease (void *handle)
int IOSetVar (void *handle, const char *cmd, char *retval, unsigned int len)
const char * IOStrError (void *handle, int err)
void IODestroy (void *handle)
void dummy_interface_test (void)
Variables
static char user_err_msg [MAX_USER_ERR]
Macro Definition Documentation
#define ERR_SUCCESS 0
Referenced by IOInit(), IOPrepare(), IORelease(), IOSetVar(), IOStart(), IOStop(), and IOStrError().
#define ERR_IHANDLE -1
Referenced by IOPrepare(), IORelease(), IOSetVar(), IOStart(), IOStop(), and IOStrError().
#define ERR_USER -1000
Referenced by copy_error(), and IOStrError().
#define MAX_USER_ERR 0x2000
Referenced by copy_error().
#define MHA_ErrorMsg2 (x, y) MHA_Error(__FILE__,__LINE__,(x),(y))
Referenced by io_tcp_parser_t::get_connected(), io_tcp_parser_t::get_local_port(), io_tcp_parser_t::get_server_port_open(), and io_tcp_sound_t::prepare().
#define MHA_ErrorMsg3 (x, y, z) MHA_Error(__FILE__,__LINE__,(x),(y),(z))
Referenced by io_tcp_parser_t::set_connected(), and io_tcp_parser_t::set_local_port().
#define MIN_TCP_PORT 0
Referenced by io_tcp_parser_t::get_local_port().
#define MIN_TCP_PORT_STR "0"
#define MAX_TCP_PORT 65535
Referenced by io_tcp_parser_t::get_local_port().
#define MAX_TCP_PORT_STR "65535"
#define IOInit MHA_DYNAMIC_IOInit
Referenced by dummy_interface_test().
#define IOPrepare MHA_DYNAMIC_IOPrepare
Referenced by dummy_interface_test().
#define IOStart MHA_DYNAMIC_IOStart
Referenced by dummy_interface_test().
#define IOStop MHA_DYNAMIC_IOStop
Referenced by dummy_interface_test().
#define IORelease MHA_DYNAMIC_IORelease
Referenced by dummy_interface_test().
#define IOSetVar MHA_DYNAMIC_IOSetVar
Referenced by dummy_interface_test().
#define IOStrError MHA_DYNAMIC_IOStrError
Referenced by dummy_interface_test().
#define IODestroy MHA_DYNAMIC_IODestroy
Referenced by dummy_interface_test().
#define dummy_interface_test MHA_DYNAMIC_dummy_interface_test
Function Documentation
static int copy_error (MHA_Error & e) static
References ERR_USER, Getmsg, MAX_USER_ERR, and user_err_msg.
Referenced by IOInit(), IOPrepare(), IORelease(), IOSetVar(), IOStart(), and IOStop().
static void* thread_startup_function (void * parameter) static
References io_tcp_t::accept_loop().
Referenced by io_tcp_t::prepare().
int IOInit (int fragsize, float samplerate, IOProcessEvent_t proc_event, void * proc_handle, IOStartedEvent_t start_event, void * start_handle, IOStoppedEvent_t stop_event, void * stop_handle, void ** handle)
References copy_error(), ERR_SUCCESS, and io_tcp_t::io_tcp_t().
int IOPrepare (void * handle, int num_inchannels, int num_outchannels)
References copy_error(), ERR_IHANDLE, ERR_SUCCESS, and io_tcp_t::prepare().
int IOStart (void * handle)
References copy_error(), ERR_IHANDLE, ERR_SUCCESS, and io_tcp_t::start().
int IOStop (void * handle)
References copy_error(), ERR_IHANDLE, ERR_SUCCESS, and io_tcp_t::stop().
int IORelease (void * handle)
References copy_error(), ERR_IHANDLE, ERR_SUCCESS, and io_tcp_t::release().
int IOSetVar (void * handle, const char * cmd, char * retval, unsigned int len)
References copy_error(), ERR_IHANDLE, ERR_SUCCESS, and io_tcp_t::parse().
const char* IOStrError (void * handle, int err)
References ERR_IHANDLE, ERR_SUCCESS, ERR_USER, and user_err_msg.
void IODestroy (void * handle)
void dummy_interface_test (void)
References IODestroy, IOInit, IOPrepare, IORelease, IOSetVar, IOStart, IOStop, IOStrError, MHA_CALLBACK_TEST, and MHA_CALLBACK_TEST_PREFIX.
Variable Documentation
char user_err_msg[MAX_USER_ERR] static
Referenced by copy_error(), and IOStrError().