openMHA Manual: mha_os.cpp File Reference
mha_os.cpp File Reference
#include "mha_os.h"
#include "mha_error.hh"
#include <iostream>
#include <dirent.h>
#include <fnmatch.h>
Functions
std::string mha_getenv (std::string envvar)
std::list< std::string > mha_library_paths ()
std::list< std::string > list_dir (const std::string &path, const std::string &pattern)
Function Documentation
std::string mha_getenv (std::string envvar)
Referenced by MHAParser::envreplace(), MHAParser::get_precision(), and mha_library_paths().
std::list<std::string> mha_library_paths ()
References mha_getenv().
Referenced by dynamiclib_t::dynamiclib_t(), and pluginbrowser_t::get_paths().
std::list<std::string> list_dir (const std::string & path, const std::string & pattern)
Referenced by pluginbrowser_t::add_plugins().