openMHA Manual: mha_ruby.cpp File Reference
mha_ruby.cpp File Reference
#include "mhafw_lib.h"
#include "ruby.h"
Typedefs
typedef VALUE(* rb_f_t) (...)
Functions
static void mha_free (void *mha)
static VALUE mha_alloc (VALUE klass)
static VALUE mha_exit_request (VALUE self)
static VALUE mha_parse (VALUE self, VALUE request)
void Init_mha_ruby ()
Typedef Documentation
typedef VALUE(* rb_f_t) (...)
Function Documentation
static void mha_free (void * mha) static
Referenced by mha_alloc().
static VALUE mha_alloc (VALUE klass) static
References mha_free().
Referenced by Init_mha_ruby().
static VALUE mha_exit_request (VALUE self) static
References fw_t::exit_request().
Referenced by Init_mha_ruby().
static VALUE mha_parse (VALUE self, VALUE request) static
References MHAParser::base_t::parse().
Referenced by Init_mha_ruby().
void Init_mha_ruby ()
References mha_alloc(), mha_exit_request(), and mha_parse().