openMHA Manual: MHASignal::ringbuffer_t Class Reference
MHASignal::ringbuffer_t Class Reference
A ringbuffer class for time domain audio signal, which makes no assumptions with respect to fragment size.
#include <mha_signal.hh>
Public Member Functions
ringbuffer_t (unsigned frames, unsigned channels, unsigned prefilled_frames)
Creates new ringbuffer.
unsigned contained_frames () const
number of currently contained frames
mha_real_t & value (unsigned frame, unsigned channel)
Access to value stored in ringbuffer.
void discard (unsigned frames)
Discards the oldest frames Makes room for new write, alters base frame index for value.
void write (mha_wave_t &signal)
Copies the contents of the signal into the ringbuffer if there is space.
Private Attributes
unsigned next_read_frame_index
identifies place with oldest frame in ringbuffer
unsigned next_write_frame_index
identifies place to store next frame in ringbuffer
Private Attributes inherited from mha_wave_t
mha_real_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Additional Inherited Members
Private Member Functions inherited from MHASignal::waveform_t
waveform_t (const unsigned int &frames, const unsigned int &channels)
constructor of waveform_t
waveform_t (const mhaconfig_t &cf)
Constructor to create a waveform from plugin configuration.
waveform_t (const mha_wave_t &src)
Copy contructor for mha_wave_t source.
waveform_t (const MHASignal::waveform_t &src)
Copy contructor.
waveform_t (const std::vector< mha_real_t > &src)
Copy contructor for std::vector<mha_real_t> source.
virtual ~waveform_t (void)
void operator= (const mha_real_t &v)
mha_real_t & operator[] (unsigned int k)
const mha_real_t & operator[] (unsigned int k) const
mha_real_t & value (unsigned int t, unsigned int ch)
Element accessor.
mha_real_t & operator() (unsigned int t, unsigned int ch)
Element accessor.
const mha_real_t & value (unsigned int t, unsigned int ch) const
Constant element accessor.
const mha_real_t & operator() (unsigned int t, unsigned int ch) const
Constant element accessor.
mha_real_t sum (const unsigned int &a, const unsigned int &b)
sum of all elements between [a,b) in all channels
mha_real_t sum (const unsigned int &a, const unsigned int &b, const unsigned int &ch)
sum of all elements between [a,b) in channel ch
mha_real_t sum ()
sum of all elements
mha_real_t sumsqr ()
sum of square of all elements
mha_real_t sum_channel (const unsigned int &)
return sum of all elements in one channel
void assign (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
set frame "k" in channel "ch" to value "val"
void assign (const mha_real_t &)
set all elements to value
void assign_frame (const unsigned int &k, const mha_real_t &val)
assign value "val" to frame k in all channels
void assign_channel (const unsigned int &c, const mha_real_t &val)
assign value "val" to channel ch in all frames
void copy (const std::vector< mha_real_t > &v)
void copy (const mha_wave_t &)
copy data from source into current waveform
void copy (const mha_wave_t *)
void copy_channel (const mha_wave_t &, unsigned int, unsigned int)
Copy one channel of a given waveform signal to a target channel.
void copy_from_at (unsigned int, unsigned int, const mha_wave_t &, unsigned int)
Copy part of the source signal into part of this waveform object.
void export_to (mha_wave_t &)
copy data into allocated mha_wave_t structure
void limit (const mha_real_t &min, const mha_real_t &max)
limit target to range [min,max]
void power (const waveform_t &)
transform waveform signal (in Pa) to squared signal (in W/m^2)
void powspec (const mha_spec_t &)
get the power spectrum (in W/m^2) from a complex spectrum
void scale (const unsigned int &a, const unsigned int &b, const unsigned int &ch, const mha_real_t &val)
scale section [a,b) in channel "ch" by "val"
void scale (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
scale one element
void scale_channel (const unsigned int &, const mha_real_t &)
scale one channel of target with a scalar
void scale_frame (const unsigned int &, const mha_real_t &)
unsigned int get_size () const
Detailed Description
A ringbuffer class for time domain audio signal, which makes no assumptions with respect to fragment size.
Constructor & Destructor Documentation
ringbuffer_t::ringbuffer_t (unsigned frames, unsigned channels, unsigned prefilled_frames)
Creates new ringbuffer.
Parameters
frames Size of ringbuffer. Maximum frames can be stored in ringbuffer.
channels Number of audio channels.
prefilled_frames Number of frames to be prefilled with zero values
Exceptions
MHA_Error if prefilled_frames > frames
Member Function Documentation
unsigned MHASignal::ringbuffer_t::contained_frames () const inline
number of currently contained frames
References mha_spec_t::num_frames.
Referenced by MHAFilter::polyphase_resampling_t::readable_frames().
mha_real_t& MHASignal::ringbuffer_t::value (unsigned frame, unsigned channel) inline
Access to value stored in ringbuffer.
Parameters
frame frame index, 0 corresponds to oldest frame stored.
channel audio channel
Returns
reference to contained sample value
Exceptions
MHA_Error if channel or frame out of bounds.
References mha_spec_t::num_channels, mha_spec_t::num_frames, and MHASignal::waveform_t::value().
void MHASignal::ringbuffer_t::discard (unsigned frames) inline
Discards the oldest frames Makes room for new write, alters base frame index for value.
Parameters
frames how many frames to discard.
Exceptions
MHA_Error if frames > contained_frames
References mha_spec_t::num_frames.
void MHASignal::ringbuffer_t::write (mha_wave_t & signal) inline
Copies the contents of the signal into the ringbuffer if there is space.
Parameters
signal New signal to be appended to the signal already present in the ringbuffer
Exceptions
MHA_Error if there is not enough space or if the channel count mismatches.
References MHASignal::min(), mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, and mha_spec_t::num_frames.
Member Data Documentation
unsigned MHASignal::ringbuffer_t::next_read_frame_index private
identifies place with oldest frame in ringbuffer
unsigned MHASignal::ringbuffer_t::next_write_frame_index private
identifies place to store next frame in ringbuffer
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp