openMHA Manual: mha_signal.cpp File Reference
mha_signal.cpp File Reference
#include "mha_signal.hh"
#include "mha_error.hh"
#include "mha_defs.h"
#include <limits>
#include <string.h>
#include <float.h>
#include "mha_signal_fft.h"
Classes
class MHASignal::hilbert_fftw_t
Namespaces
MHASignal
Namespace for audio signal handling and processing classes.
Macros
#define MHA_ID_UINT_VECTOR "MHASignal::uint_vector_t"
#define MHA_ID_MATRIX "MHASignal::matrix_t"
#define ASSERT_EQUAL_DIM(a, b)
#define ASSERT_EQUAL_DIM_PTR(a, b)
Functions
void set_minabs (mha_spec_t &self, const mha_real_t &m)
mha_wave_t & operator+= (mha_wave_t &self, const mha_real_t &v)
Addition operator.
mha_wave_t & operator*= (mha_wave_t &self, const mha_real_t &v)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &self, const mha_real_t &v)
Element-wise multiplication operator.
mha_wave_t & operator*= (mha_wave_t &self, const mha_wave_t &v)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &self, const mha_wave_t &v)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &self, const mha_spec_t &v)
Element-wise multiplication operator.
mha_spec_t & safe_div (mha_spec_t &self, const mha_spec_t &v, mha_real_t eps)
mha_spec_t & operator/= (mha_spec_t &self, const mha_spec_t &v)
Element-wise division operator.
mha_wave_t & operator/= (mha_wave_t &self, const mha_wave_t &v)
Element-wise division operator.
mha_spec_t & operator+= (mha_spec_t &self, const mha_spec_t &v)
Addition operator.
mha_spec_t & operator+= (mha_spec_t &self, const mha_real_t &v)
Addition operator.
mha_wave_t & operator+= (mha_wave_t &self, const mha_wave_t &v)
Addition operator.
mha_wave_t & operator-= (mha_wave_t &self, const mha_wave_t &v)
Subtraction operator.
mha_spec_t & operator-= (mha_spec_t &self, const mha_spec_t &v)
Subtraction operator.
mha_fft_t mha_fft_new (unsigned int n)
Create a new instance of an FFT object.
void mha_fft_free (mha_fft_t h)
Remove an FFT object.
void mha_fft_wave2spec (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out)
Perform an FFT on each channel of input waveform signal.
void mha_fft_wave2spec (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out, bool swap)
Tranform waveform segment into spectrum.
void mha_fft_spec2wave (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out)
Perform an inverse FFT on each channel of input spectrum.
void mha_fft_spec2wave (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out, unsigned int offset)
Perform an inverse FFT on each channel of input spectrum.
void mha_fft_forward (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (forward).
void mha_fft_backward (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (backward).
void mha_fft_forward_scale (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (forward).
void mha_fft_backward_scale (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (backward).
void mha_fft_wave2spec_scale (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out)
Tranform waveform segment into spectrum.
void mha_fft_spec2wave_scale (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out)
Tranform spectrum into waveform segment.
std::vector< float > std_vector_float (const mha_wave_t &w)
Converts a mha_wave_t structure into a std::vector<float> (interleaved order).
std::vector< std::vector< float > > std_vector_vector_float (const mha_wave_t &w)
Converts a mha_wave_t structure into a std::vector< std::vector<float> > (outer vector represents channels).
std::vector< std::vector< mha_complex_t > > std_vector_vector_complex (const mha_spec_t &w)
Converts a mha_spec_t structure into a std::vector< std::vector<mha_complex_t> > (outer vector represents channels).
static mha_real_t intensity (const mha_spec_t &s, unsigned int channel, unsigned int fftlen, mha_real_t *sqfreq_response=0)
void integrate (mha_wave_t &s)
Numeric integration of a signal vector (real values)
void integrate (mha_spec_t &s)
Numeric integration of a signal vector (complex values)
mha_wave_t & operator^= (mha_wave_t &self, const mha_real_t &arg)
Exponent operator.
mha_wave_t range (mha_wave_t s, unsigned int k0, unsigned int len)
Return a time interval from a waveform chunk.
mha_spec_t channels (mha_spec_t s, unsigned int ch_start, unsigned int nch)
Return a channel interval from a spectrum.
void assign (mha_wave_t self, const mha_wave_t &val)
Set all values of waveform 'self' to 'val'.
void assign (mha_spec_t self, const mha_spec_t &val)
Set all values of spectrum 'self' to 'val'.
void timeshift (mha_wave_t &self, int shift)
Time shift of waveform chunk.
Macro Definition Documentation
#define MHA_ID_UINT_VECTOR "MHASignal::uint_vector_t"
Referenced by MHASignal::uint_vector_t::numbytes(), MHASignal::uint_vector_t::uint_vector_t(), and MHASignal::uint_vector_t::write().
#define MHA_ID_MATRIX "MHASignal::matrix_t"
Referenced by MHASignal::matrix_t::matrix_t(), MHASignal::matrix_t::numbytes(), and MHASignal::matrix_t::write().
#define ASSERT_EQUAL_DIM (a, b)
Referenced by MHASignal::stat_t::mean(), MHASignal::stat_t::mean_std(), operator*=(), operator+=(), operator-=(), and MHASignal::stat_t::push().
#define ASSERT_EQUAL_DIM_PTR (a, b)
Referenced by MHASignal::spectrum_t::copy(), MHASignal::waveform_t::copy(), MHASignal::spectrum_t::export_to(), and MHASignal::waveform_t::export_to().
Function Documentation
void set_minabs (mha_spec_t & self, const mha_real_t & m)
References abs(), angle(), mha_wave_t::buf, expi(), and size().
Referenced by value().
mha_spec_t& safe_div (mha_spec_t & self, const mha_spec_t & v, mha_real_t eps)
In-Place division with lower limit on divisor.
References mha_wave_t::buf, mha_spec_t::buf, safe_div(), and size().
Referenced by operator/=(), safe_div(), and value().
static mha_real_t intensity (const mha_spec_t & s, unsigned int channel, unsigned int fftlen, mha_real_t * sqfreq_response = 0) static
References abs2(), mha_spec_t::num_frames, and value().
Referenced by MHASignal::colored_intensity(), and MHASignal::rmslevel().