openMHA Manual: mha_profiling.h File Reference
mha_profiling.h File Reference
#include <sys/time.h>
Classes
struct mha_tictoc_t
Typedefs
typedef mha_tictoc_t mha_platform_tictoc_t
Functions
void mha_platform_tic (mha_platform_tictoc_t *t)
float mha_platform_toc (mha_platform_tictoc_t *t)
Typedef Documentation
typedef mha_tictoc_t mha_platform_tictoc_t
Function Documentation
void mha_platform_tic (mha_platform_tictoc_t * t)
References mha_tic(), and mha_tictoc_t::tv1.
Referenced by mhachain::plugs_t::alloc_plugs(), mhachain::plugs_t::prepare(), mhachain::plugs_t::process(), and mhachain::plugs_t::release().
float mha_platform_toc (mha_platform_tictoc_t * t)
References mha_toc(), mha_tictoc_t::t, mha_tictoc_t::tv1, and mha_tictoc_t::tv2.
Referenced by mhachain::plugs_t::alloc_plugs(), mhachain::plugs_t::prepare(), mhachain::plugs_t::process(), and mhachain::plugs_t::release().