openMHA Manual: mha_profiling.c File Reference
mha_profiling.c File Reference
#include "mha_profiling.h"
#include <string.h>
Functions
void mha_tic (mha_tictoc_t *t)
void mha_platform_tic (mha_platform_tictoc_t *t)
float mha_toc (mha_tictoc_t *t)
float mha_platform_toc (mha_platform_tictoc_t *t)
Function Documentation
void mha_tic (mha_tictoc_t * t)
References mha_tictoc_t::tv1, and mha_tictoc_t::tz.
Referenced by mha_platform_tic().
void mha_platform_tic (mha_platform_tictoc_t * t)
References mha_tic(), and mha_tictoc_t::tv1.
Referenced by mhachain::plugs_t::alloc_plugs(), mhachain::plugs_t::prepare(), mhachain::plugs_t::process(), and mhachain::plugs_t::release().
float mha_toc (mha_tictoc_t * t)
References mha_tictoc_t::t, mha_tictoc_t::tv1, mha_tictoc_t::tv2, and mha_tictoc_t::tz.
Referenced by mha_platform_toc().
float mha_platform_toc (mha_platform_tictoc_t * t)
References mha_toc(), mha_tictoc_t::t, mha_tictoc_t::tv1, and mha_tictoc_t::tv2.
Referenced by mhachain::plugs_t::alloc_plugs(), mhachain::plugs_t::prepare(), mhachain::plugs_t::process(), and mhachain::plugs_t::release().