openMHA Manual: mha_tcp.cpp File Reference
mha_tcp.cpp File Reference
#include <string.h>
#include <sstream>
#include "mha_tcp.hh"
#include <sys/select.h>
#include <sys/socket.h>
#include <unistd.h>
#include <sys/time.h>
#include <netdb.h>
#include <fcntl.h>
#include <stdarg.h>
#include <errno.h>
#include <algorithm>
#include <vector>
Namespaces
MHA_TCP
Macros
#define INVALID_SOCKET (-1)
#define SOCKET_ERROR (-1)
#define closesocket(fd) (close((fd)))
#define ASYNC_CONNECT_STARTED EINPROGRESS
Typedefs
typedef int SOCKET
Functions
std::string MHA_TCP::STRERROR (int err)
std::string MHA_TCP::HSTRERROR (int err)
int MHA_TCP::N_ERRNO ()
int MHA_TCP::H_ERRNO ()
int MHA_TCP::G_ERRNO ()
static sockaddr_in host_port_to_sock_addr (const std::string &host, unsigned short port)
static SOCKET tcp_connect_to (const std::string &host, unsigned short port)
static SOCKET tcp_connect_to_with_timeout (const std::string &host, unsigned short port, Timeout_Watcher &timeout_watcher)
static void * thread_start_func (void *thread)
Macro Definition Documentation
#define INVALID_SOCKET (-1)
Referenced by MHA_TCP::Connection::Connection(), MHA_TCP::Server::initialize(), tcp_connect_to(), tcp_connect_to_with_timeout(), MHA_TCP::Server::try_accept(), MHA_TCP::Connection::~Connection(), and MHA_TCP::Server::~Server().
#define SOCKET_ERROR (-1)
Referenced by MHA_TCP::Connection::Connection(), MHA_TCP::Server::initialize(), MHA_TCP::Sockaccept_Event::Sockaccept_Event(), MHA_TCP::Sockread_Event::Sockread_Event(), MHA_TCP::Connection::sysread(), MHA_TCP::Connection::syswrite(), tcp_connect_to(), and tcp_connect_to_with_timeout().
#define closesocket (fd) (close((fd)))
Referenced by MHA_TCP::Server::initialize(), tcp_connect_to(), tcp_connect_to_with_timeout(), MHA_TCP::Connection::~Connection(), and MHA_TCP::Server::~Server().
#define ASYNC_CONNECT_STARTED EINPROGRESS
Referenced by tcp_connect_to_with_timeout().
Typedef Documentation
typedef int SOCKET
Function Documentation
static sockaddr_in host_port_to_sock_addr (const std::string & host, unsigned short port) static
References MHA_TCP::H_ERRNO(), and MHA_TCP::HSTRERROR().
Referenced by MHA_TCP::Server::initialize(), tcp_connect_to(), and tcp_connect_to_with_timeout().
static SOCKET tcp_connect_to (const std::string & host, unsigned short port) static
References closesocket, host_port_to_sock_addr(), INVALID_SOCKET, MHA_TCP::N_ERRNO(), SOCKET_ERROR, and MHA_TCP::STRERROR().
static SOCKET tcp_connect_to_with_timeout (const std::string & host, unsigned short port, Timeout_Watcher & timeout_watcher) static
References ASYNC_CONNECT_STARTED, closesocket, host_port_to_sock_addr(), INVALID_SOCKET, MHA_TCP::N_ERRNO(), MHA_TCP::Event_Watcher::observe(), SOCKET_ERROR, MHA_TCP::STRERROR(), and MHA_TCP::Event_Watcher::wait().
static void* thread_start_func (void * thread) static
Referenced by MHA_TCP::Thread::Thread().