openMHA Manual: mha_signal.hh File Reference
mha_signal.hh File Reference
The MHA Toolbox library
Header file for audio signal handling and processing classes.
#include "mha.h"
#include "mha_error.hh"
#include <limits>
#include <string>
#include <cmath>
#include <iostream>
#include <sstream>
#include <complex>
#include <cstring>
#include "mha_os.h"
#include <vector>
#include <numeric>
#include <algorithm>
#include "mha_parser.hh"
Classes
class MHASignal::spectrum_t
a signal processing class for spectral data (based on mha_spec_t)
class MHASignal::waveform_t
signal processing class for waveform data (based on mha_wave_t)
class MHASignal::doublebuffer_t
Double-buffering class.
class MHASignal::ringbuffer_t
A ringbuffer class for time domain audio signal, which makes no assumptions with respect to fragment size.
class MHASignal::hilbert_t
Hilbert transformation of a waveform segment.
class MHASignal::minphase_t
Minimal phase function.
class MHAWindow::base_t
Common base for window types.
class MHAWindow::fun_t
Generic window based on a generator function.
class MHAWindow::rect_t
Rectangular window.
class MHAWindow::bartlett_t
Bartlett window.
class MHAWindow::hanning_t
von-Hann window
class MHAWindow::hamming_t
Hamming window.
class MHAWindow::blackman_t
Blackman window.
class MHAWindow::user_t
User defined window.
class MHASignal::stat_t
class MHASignal::delay_wave_t
Delayline containing wave fragments.
class MHASignal::delay_spec_t
class MHASignal::async_rmslevel_t
Class for asynchronous level metering.
class MHASignal::uint_vector_t
Vector of unsigned values, used for size and index description of n-dimensional matrixes.
class MHASignal::matrix_t
n-dimensional matrix with real or complex floating point values.
class MHASignal::schroeder_t
Schroeder tone complex class.
class MHASignal::quantizer_t
Simple simulation of fixpoint quantization.
class MHASignal::loop_wavefragment_t
Copy a fixed waveform fragment to a series of waveform fragments of other size.
class MHASignal::delay_t
Class to realize a simple delay of waveform streams.
class MHASignal::subsample_delay_t
implements subsample delay in spectral domain.
Namespaces
MHASignal
Namespace for audio signal handling and processing classes.
MHAWindow
Collection of Window types.
Macros
#define M_PI 3.14159265358979323846
#define mha_round(x) (int)((float)x+0.5)
Functions
void MHASignal::for_each (mha_wave_t *s, mha_real_t(*fun)(mha_real_t))
Apply a function to each element of a mha_wave_t.
mha_real_t MHASignal::lin2db (mha_real_t x)
Conversion from linear scale to dB (no SPL reference)
mha_real_t MHASignal::db2lin (mha_real_t x)
Conversion from dB scale to linear (no SPL reference)
mha_real_t MHASignal::pa2dbspl (mha_real_t x)
Conversion from linear Pascal scale to dB SPL.
mha_real_t MHASignal::pa22dbspl (mha_real_t x, mha_real_t eps=1e-20f)
Conversion from squared Pascal scale to dB SPL.
mha_real_t MHASignal::dbspl2pa (mha_real_t x)
Conversion from dB SPL to linear Pascal scale.
mha_real_t MHASignal::smp2sec (mha_real_t n, mha_real_t srate)
conversion from samples to seconds
mha_real_t MHASignal::sec2smp (mha_real_t sec, mha_real_t srate)
conversion from seconds to samples
mha_real_t MHASignal::bin2freq (mha_real_t bin, unsigned fftlen, mha_real_t srate)
conversion from fft bin index to frequency
mha_real_t MHASignal::freq2bin (mha_real_t freq, unsigned fftlen, mha_real_t srate)
conversion from frequency to fft bin index
mha_real_t MHASignal::smp2rad (mha_real_t samples, unsigned bin, unsigned fftlen)
conversion from delay in samples to phase shift
mha_real_t MHASignal::rad2smp (mha_real_t phase_shift, unsigned bin, unsigned fftlen)
conversion from phase shift to delay in samples
template<class elem_type >
std::vector< elem_type > MHASignal::dupvec (std::vector< elem_type > vec, unsigned n)
Duplicate last vector element to match desired size.
template<class elem_type >
std::vector< elem_type > MHASignal::dupvec_chk (std::vector< elem_type > vec, unsigned n)
Duplicate last vector element to match desired size, check for dimension.
bool equal_dim (const mha_wave_t &a, const mha_wave_t &b)
Test for equal dimension of waveform structures.
bool equal_dim (const mha_wave_t &a, const mhaconfig_t &b)
Test for match of waveform dimension with mhaconfig structure.
bool equal_dim (const mha_spec_t &a, const mha_spec_t &b)
Test for equal dimension of spectrum structures.
bool equal_dim (const mha_spec_t &a, const mhaconfig_t &b)
Test for match of spectrum dimension with mhaconfig structure.
bool equal_dim (const mha_wave_t &a, const mha_spec_t &b)
Test for equal dimension of waveform/spectrum structures.
bool equal_dim (const mha_spec_t &a, const mha_wave_t &b)
Test for equal dimension of waveform/spectrum structures.
void integrate (mha_wave_t &s)
Numeric integration of a signal vector (real values)
void integrate (mha_spec_t &s)
Numeric integration of a signal vector (complex values)
unsigned int mha_min_1 (unsigned int a)
unsigned int size (const mha_wave_t &s)
Return size of a waveform structure.
unsigned int size (const mha_spec_t &s)
Return size of a spectrum structure.
unsigned int size (const mha_wave_t *s)
Return size of a waveform structure.
unsigned int size (const mha_spec_t *s)
Return size of a spectrum structure.
void clear (mha_wave_t &s)
Set all values of waveform to zero.
void clear (mha_wave_t *s)
Set all values of waveform to zero.
void clear (mha_spec_t &s)
Set all values of spectrum to zero.
void clear (mha_spec_t *s)
Set all values of spectrum to zero.
void assign (mha_wave_t self, mha_real_t val)
Set all values of waveform 'self' to 'val'.
void assign (mha_wave_t self, const mha_wave_t &val)
Set all values of waveform 'self' to 'val'.
void assign (mha_spec_t self, const mha_spec_t &val)
Set all values of spectrum 'self' to 'val'.
void timeshift (mha_wave_t &self, int shift)
Time shift of waveform chunk.
mha_wave_t range (mha_wave_t s, unsigned int k0, unsigned int len)
Return a time interval from a waveform chunk.
mha_spec_t channels (mha_spec_t s, unsigned int ch_start, unsigned int nch)
Return a channel interval from a spectrum.
mha_real_t & value (mha_wave_t *s, unsigned int fr, unsigned int ch)
Access an element of a waveform structure.
const mha_real_t & value (const mha_wave_t *s, unsigned int fr, unsigned int ch)
Constant access to an element of a waveform structure.
mha_real_t & value (mha_wave_t *s, unsigned int k)
mha_complex_t & value (mha_spec_t *s, unsigned int k)
mha_complex_t & value (mha_spec_t *s, unsigned int fr, unsigned int ch)
Access to an element of a spectrum.
const mha_complex_t & value (const mha_spec_t *s, unsigned int fr, unsigned int ch)
Constant access to an element of a spectrum.
mha_real_t & value (mha_wave_t &s, unsigned int fr, unsigned int ch)
Access to an element of a waveform structure.
const mha_real_t & value (const mha_wave_t &s, unsigned int fr, unsigned int ch)
Constant access to an element of a waveform structure.
mha_complex_t & value (mha_spec_t &s, unsigned int fr, unsigned int ch)
Access to an element of a spectrum.
const mha_complex_t & value (const mha_spec_t &s, unsigned int fr, unsigned int ch)
Constant access to an element of a spectrum.
std::vector< float > std_vector_float (const mha_wave_t &)
Converts a mha_wave_t structure into a std::vector<float> (interleaved order).
std::vector< std::vector< float > > std_vector_vector_float (const mha_wave_t &)
Converts a mha_wave_t structure into a std::vector< std::vector<float> > (outer vector represents channels).
std::vector< std::vector< mha_complex_t > > std_vector_vector_complex (const mha_spec_t &)
Converts a mha_spec_t structure into a std::vector< std::vector<mha_complex_t> > (outer vector represents channels).
mha_wave_t & operator+= (mha_wave_t &, const mha_real_t &)
Addition operator.
mha_wave_t & operator+= (mha_wave_t &, const mha_wave_t &)
Addition operator.
mha_wave_t & operator-= (mha_wave_t &, const mha_wave_t &)
Subtraction operator.
mha_spec_t & operator-= (mha_spec_t &, const mha_spec_t &)
Subtraction operator.
mha_wave_t & operator*= (mha_wave_t &, const mha_real_t &)
Element-wise multiplication operator.
mha_wave_t & operator*= (mha_wave_t &, const mha_wave_t &)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &, const mha_real_t &)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &, const mha_wave_t &)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &, const mha_spec_t &)
Element-wise multiplication operator.
mha_spec_t & operator/= (mha_spec_t &, const mha_spec_t &)
Element-wise division operator.
mha_wave_t & operator/= (mha_wave_t &, const mha_wave_t &)
Element-wise division operator.
mha_spec_t & operator+= (mha_spec_t &, const mha_spec_t &)
Addition operator.
mha_spec_t & operator+= (mha_spec_t &, const mha_real_t &)
Addition operator.
void set_minabs (mha_spec_t &, const mha_real_t &)
mha_spec_t & safe_div (mha_spec_t &self, const mha_spec_t &v, mha_real_t eps)
mha_wave_t & operator^= (mha_wave_t &self, const mha_real_t &arg)
Exponent operator.
void MHASignal::copy_channel (mha_spec_t &self, const mha_spec_t &src, unsigned sch, unsigned dch)
Copy one channel of a source signal.
void MHASignal::copy_channel (mha_wave_t &self, const mha_wave_t &src, unsigned src_channel, unsigned dest_channel)
Copy one channel of a source signal.
mha_real_t MHASignal::rmslevel (const mha_spec_t &s, unsigned int channel, unsigned int fftlen)
Return RMS level of a spectrum channel.
mha_real_t MHASignal::colored_intensity (const mha_spec_t &s, unsigned int channel, unsigned int fftlen, mha_real_t sqfreq_response[])
Colored spectrum intensity.
mha_real_t MHASignal::maxabs (const mha_spec_t &s, unsigned int channel)
Find maximal absolute value.
mha_real_t MHASignal::rmslevel (const mha_wave_t &s, unsigned int channel)
Return RMS level of a waveform channel.
mha_real_t MHASignal::maxabs (const mha_wave_t &s, unsigned int channel)
Find maximal absolute value.
mha_real_t MHASignal::maxabs (const mha_wave_t &s)
Find maximal absolute value.
mha_real_t MHASignal::max (const mha_wave_t &s)
Find maximal value.
mha_real_t MHASignal::min (const mha_wave_t &s)
Find minimal value.
mha_real_t MHASignal::sumsqr_channel (const mha_wave_t &s, unsigned int channel)
Calculate sum of squared values in one channel.
mha_real_t MHASignal::sumsqr_frame (const mha_wave_t &s, unsigned int frame)
Calculate sum over all channels of squared values.
void MHASignal::scale (mha_spec_t *dest, const mha_wave_t *src)
void MHASignal::limit (mha_wave_t &s, const mha_real_t &min, const mha_real_t &max)
Limit the singal in the waveform buffer to the range [min, max].
mha_complex_t & set (mha_complex_t &self, mha_real_t real, mha_real_t imag=0)
Assign real and imaginary parts to a mha_complex_t variable.
mha_complex_t mha_complex (mha_real_t real, mha_real_t imag=0)
Create a new mha_complex_t with specified real and imaginary parts.
mha_complex_t & set (mha_complex_t &self, const std::complex< mha_real_t > &stdcomplex)
Assign a mha_complex_t variable from a std::complex.
std::complex< mha_real_t > stdcomplex (const mha_complex_t &self)
Create a std::complex from mha_complex_t.
mha_complex_t & expi (mha_complex_t &self, mha_real_t angle)
replaces the value of the given mha_complex_t with exp(i*b).
double angle (const mha_complex_t &self)
Computes the angle of a complex number in the complex plane.
mha_complex_t & operator+= (mha_complex_t &self, const mha_complex_t &other)
Addition of two complex numbers, overwriting the first.
mha_complex_t operator+ (const mha_complex_t &self, const mha_complex_t &other)
Addition of two complex numbers, result is a temporary object.
mha_complex_t & operator+= (mha_complex_t &self, mha_real_t other_real)
Addition of a complex and a real number, overwriting the complex.
mha_complex_t operator+ (const mha_complex_t &self, mha_real_t other_real)
Addition of a complex and a real number, result is a temporary object.
mha_complex_t & operator-= (mha_complex_t &self, const mha_complex_t &other)
Subtraction of two complex numbers, overwriting the first.
mha_complex_t operator- (const mha_complex_t &self, const mha_complex_t &other)
Subtraction of two complex numbers, result is a temporary object.
mha_complex_t & operator-= (mha_complex_t &self, mha_real_t other_real)
Subtraction of a complex and a real number, overwriting the complex.
mha_complex_t operator- (const mha_complex_t &self, mha_real_t other_real)
Subtraction of a complex and a real number, result is a temporary object.
mha_complex_t & operator*= (mha_complex_t &self, const mha_complex_t &other)
Multiplication of two complex numbers, overwriting the first.
mha_complex_t operator* (const mha_complex_t &self, const mha_complex_t &other)
Multiplication of two complex numbers, result is a temporary object.
mha_complex_t & operator*= (mha_complex_t &self, mha_real_t other_real)
Multiplication of a complex and a real number, overwriting the complex.
mha_complex_t & expi (mha_complex_t &self, mha_real_t angle, mha_real_t factor)
replaces (!) the value of the given mha_complex_t with a * exp(i*b)
mha_complex_t operator* (const mha_complex_t &self, mha_real_t other_real)
Multiplication of a complex and a real number, result is a temporary object.
mha_real_t abs2 (const mha_complex_t &self)
Compute the square of the absolute value of a complex value.
mha_real_t abs (const mha_complex_t &self)
Compute the absolute value of a complex value.
mha_complex_t & operator/= (mha_complex_t &self, mha_real_t other_real)
Division of a complex and a real number, overwriting the complex.
mha_complex_t operator/ (const mha_complex_t &self, mha_real_t other_real)
Division of a complex and a real number, result is a temporary object.
mha_complex_t & safe_div (mha_complex_t &self, const mha_complex_t &other, mha_real_t eps, mha_real_t eps2)
mha_complex_t & operator/= (mha_complex_t &self, const mha_complex_t &other)
Division of two complex numbers, overwriting the first.
mha_complex_t operator/ (const mha_complex_t &self, const mha_complex_t &other)
Division of two complex numbers, result is a temporary object.
mha_complex_t operator- (const mha_complex_t &self)
Unary minus on a complex results in a negative temporary object.
bool operator== (const mha_complex_t &x, const mha_complex_t &y)
Compare two complex numbers for equality.
bool operator!= (const mha_complex_t &x, const mha_complex_t &y)
Compare two complex numbers for inequality.
void conjugate (mha_complex_t &self)
Replace (!) the value of this mha_complex_t with its conjugate.
void conjugate (mha_spec_t &self)
Replace (!) the value of this mha_spec_t with its conjugate.
mha_complex_t _conjugate (const mha_complex_t &self)
Compute the cojugate of this complex value.
void reciprocal (mha_complex_t &self)
Replace the value of this complex with its reciprocal.
mha_complex_t _reciprocal (const mha_complex_t &self)
compute the reciprocal of this complex value.
void normalize (mha_complex_t &self)
Divide a complex by its absolute value, thereby normalizing it (projecting onto the unit circle).
void normalize (mha_complex_t &self, mha_real_t margin)
Divide a complex by its absolute value, thereby normalizing it (projecting onto the unit circle), with a safety margin.
bool almost (const mha_complex_t &self, const mha_complex_t &other, mha_real_t times_epsilon=1e2)
Compare two complex numbers for equality except for a small relative error.
bool operator< (const mha_complex_t &x, const mha_complex_t &y)
Compares the absolute values of two complex numbers.
std::ostream & operator<< (std::ostream &o, const mha_complex_t &c)
std::istream & operator>> (std::istream &i, mha_complex_t &c)
mha_fft_t mha_fft_new (unsigned int n)
Create a new FFT handle.
void mha_fft_free (mha_fft_t h)
Destroy an FFT handle.
void mha_fft_wave2spec (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out)
Tranform waveform segment into spectrum.
void mha_fft_wave2spec (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out, bool swaps)
Tranform waveform segment into spectrum.
void mha_fft_spec2wave (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out)
Tranform spectrum into waveform segment.
void mha_fft_spec2wave (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out, unsigned int offset)
Tranform spectrum into waveform segment.
void mha_fft_forward (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (forward).
void mha_fft_backward (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (backward).
void mha_fft_forward_scale (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (forward).
void mha_fft_backward_scale (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (backward).
void mha_fft_wave2spec_scale (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out)
Tranform waveform segment into spectrum.
void mha_fft_spec2wave_scale (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out)
Tranform spectrum into waveform segment.
float MHAWindow::rect (float)
Rectangular window function.
float MHAWindow::bartlett (float)
Bartlett window function.
float MHAWindow::hanning (float)
Hanning window function.
float MHAWindow::hamming (float)
Hamming window function.
float MHAWindow::blackman (float)
Blackman window function.
template<class elem_type >
elem_type MHASignal::kth_smallest (elem_type array[], unsigned n, unsigned k)
Fast search for the kth smallest element of an array.
template<class elem_type >
elem_type MHASignal::median (elem_type array[], unsigned n)
Fast median search.
template<class elem_type >
elem_type MHASignal::mean (const std::vector< elem_type > &data, elem_type start_val)
Calculate average of elements in a vector.
template<class elem_type >
std::vector< elem_type > MHASignal::quantile (std::vector< elem_type > data, const std::vector< elem_type > &p)
Calculate quantile of elements in a vector.
void MHASignal::saveas_mat4 (const mha_spec_t &data, const std::string &varname, FILE *fh)
Save a MHA spectrum as a variable in a Matlab4 file.
void MHASignal::saveas_mat4 (const mha_wave_t &data, const std::string &varname, FILE *fh)
Save a MHA waveform as a variable in a Matlab4 file.
void MHASignal::saveas_mat4 (const std::vector< mha_real_t > &data, const std::string &varname, FILE *fh)
Save a float vector as a variable in a Matlab4 file.
void MHASignal::copy_permuted (mha_wave_t *dest, const mha_wave_t *src)
Copy contents of a waveform to a permuted waveform.
Variables
unsigned long int MHASignal::signal_counter = 0
Signal counter to produce signal ID strings.
Detailed Description
Header file for audio signal handling and processing classes.
The classes for waveform, spectrum and filterbank signals defined in this file are "intelligent" versions of the basic waveform, spectrum and filterbank structures used in the C function calls.
Macro Definition Documentation
#define M_PI 3.14159265358979323846
Referenced by MHASignal::rad2smp(), and MHASignal::smp2rad().
#define mha_round (x) (int)((float)x+0.5)
Referenced by MHAOvlFilter::fspacing_t::get_cf_fftbin().
Function Documentation
unsigned int mha_min_1 (unsigned int a) inline
Referenced by MHA_AC::acspace2matrix_t::acspace2matrix_t(), MHAOvlFilter::fftfb_t::fftfb_t(), MHAWindow::fun_t::fun_t(), MHASignal::matrix_t::matrix_t(), and MHASignal::uint_vector_t::uint_vector_t().
mha_real_t& value (mha_wave_t * s, unsigned int k) inline
References mha_wave_t::buf.
mha_complex_t& value (mha_spec_t * s, unsigned int k) inline
References mha_spec_t::buf.
void set_minabs (mha_spec_t & , const mha_real_t &)
References abs(), angle(), mha_wave_t::buf, expi(), and size().
Referenced by value().
mha_spec_t& safe_div (mha_spec_t & self, const mha_spec_t & v, mha_real_t eps)
In-Place division with lower limit on divisor.
References mha_wave_t::buf, mha_spec_t::buf, safe_div(), and size().
Referenced by operator/=(), safe_div(), and value().
std::ostream& operator<< (std::ostream & o, const mha_complex_t & c) inline
ostream operator for mha_complex_t
References mha_complex_t::im, and mha_complex_t::re.
std::istream& operator>> (std::istream & i, mha_complex_t & c) inline
preliminary istream operator for mha_complex_t without error checking
References mha_complex_t::im, mha_fft_backward(), mha_fft_backward_scale(), mha_fft_forward(), mha_fft_forward_scale(), mha_fft_free(), mha_fft_new(), mha_fft_spec2wave(), mha_fft_spec2wave_scale(), mha_fft_wave2spec(), mha_fft_wave2spec_scale(), and mha_complex_t::re.