openMHA Manual: MHASignal::subsample_delay_t Class Reference
MHASignal::subsample_delay_t Class Reference
implements subsample delay in spectral domain.
#include <mha_signal.hh>
Public Member Functions
subsample_delay_t (const std::vector< float > &subsample_delay, unsigned fftlen)
Constructor computes complex phase factors to apply to achieve subsample delay.
void process (mha_spec_t *s)
Apply the phase_gains to s to achieve the subsample delay.
void process (mha_spec_t *s, unsigned idx)
Apply the pase gains to channel idx in s to achieve the subsample delay in channel idx.
Public Attributes
spectrum_t phase_gains
The complex factors to apply to achieve the necessary phase shift.
Private Attributes
unsigned last_complex_bin
index of the last complex fft bin for the used fft length.
Detailed Description
implements subsample delay in spectral domain.
When transformed back to the time domain, the signal is delayed by the configured fraction of a sample. This operation must not be used in a smoothgains bracket.
Constructor & Destructor Documentation
MHASignal::subsample_delay_t::subsample_delay_t (const std::vector< float > & subsample_delay, unsigned fftlen)
Constructor computes complex phase factors to apply to achieve subsample delay.
Parameters
subsample_delay The subsample delay to apply. -0.5 <= subsample_delay <= 0.5
fftlen FFT length
Exceptions
MHA_Error if the parameters are out of range
References expi(), last_complex_bin, M_PI, mha_spec_t::num_channels, mha_spec_t::num_frames, and phase_gains.
Member Function Documentation
void MHASignal::subsample_delay_t::process (mha_spec_t * s)
Apply the phase_gains to s to achieve the subsample delay.
References last_complex_bin, MHA_assert_equal, mha_spec_t::num_channels, phase_gains, and value().
void MHASignal::subsample_delay_t::process (mha_spec_t * s, unsigned idx)
Apply the pase gains to channel idx in s to achieve the subsample delay in channel idx.
Parameters
s signal
idx channel index, 0-based
Exceptions
MHA_Error if idx >= s->num_channels
References last_complex_bin, mha_spec_t::num_channels, phase_gains, and value().
Member Data Documentation
spectrum_t MHASignal::subsample_delay_t::phase_gains
The complex factors to apply to achieve the necessary phase shift.
Referenced by process(), and subsample_delay_t().
unsigned MHASignal::subsample_delay_t::last_complex_bin private
index of the last complex fft bin for the used fft length.
Referenced by process(), and subsample_delay_t().
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp