openMHA Manual: analysemhaplugin.cpp File Reference
analysemhaplugin.cpp File Reference
#include "mhapluginloader.h"
#include "mha_algo_comm.hh"
#include <exception>
Functions
std::string strdom (mha_domain_t d)
void print_ac (MHAKernel::algo_comm_class_t &ac, std::string txt)
int main (int argc, char **argv)
Function Documentation
std::string strdom (mha_domain_t d)
References MHA_SPECTRUM, and MHA_WAVEFORM.
Referenced by main().
void print_ac (MHAKernel::algo_comm_class_t & ac, std::string txt)
References MHAKernel::algo_comm_class_t::local_get_entries(), and MHAParser::StrCnv::str2val().
Referenced by main().
int main (int argc, char ** argv)
References mhaconfig_t::channels, mhaconfig_t::domain, mhaconfig_t::fftlen, mhaconfig_t::fragsize, MHAKernel::algo_comm_class_t::get_c_handle(), MHA_DOMAIN_MAX, MHA_SPECTRUM, MHA_WAVEFORM, PluginLoader::mhapluginloader_t::parse(), print_ac(), mhaconfig_t::srate, strdom(), MHAParser::StrCnv::val2str(), MHA_Error::what(), and mhaconfig_t::wndlen.