openMHA Manual: MHASignal::uint_vector_t Class Reference
MHASignal::uint_vector_t Class Reference
The MHA Toolbox library » Vector and matrix processing toolbox
Vector of unsigned values, used for size and index description of n-dimensional matrixes.
#include <mha_signal.hh>
Public Member Functions
uint_vector_t (unsigned int len)
Constructor, initializes all elements to zero.
uint_vector_t (const uint_vector_t &)
uint_vector_t (const uint8_t *buf, unsigned int len)
Construct from memory area.
~uint_vector_t ()
bool operator== (const uint_vector_t &) const
Check for equality.
uint_vector_t & operator= (const uint_vector_t &)
Assign from other uint_vector_t.
unsigned int get_length () const
Return the length of the vector.
const uint32_t & operator[] (unsigned int k) const
Read-only access to elements.
uint32_t & operator[] (unsigned int k)
Access to elements.
unsigned int numbytes () const
Return number of bytes needed to store into memory.
unsigned int write (uint8_t *buf, unsigned int len) const
Copy to memory area.
const uint32_t * getdata () const
Return pointer to the data field.
Protected Attributes
uint32_t length
uint32_t * data
Detailed Description
Vector of unsigned values, used for size and index description of n-dimensional matrixes.
Constructor & Destructor Documentation
MHASignal::uint_vector_t::uint_vector_t (unsigned int len)
Constructor, initializes all elements to zero.
Parameters
len Length of vector.
References data, and length.
MHASignal::uint_vector_t::uint_vector_t (const uint_vector_t & src)
References data, and length.
MHASignal::uint_vector_t::uint_vector_t (const uint8_t * buf, unsigned int len)
Construct from memory area.
Warning
This constructor is not real time safe
References data, length, MHA_ID_UINT_VECTOR, and mha_min_1().
MHASignal::uint_vector_t::~uint_vector_t ()
References data.
Member Function Documentation
bool MHASignal::uint_vector_t::operator== (const uint_vector_t & src) const
Check for equality.
References data, get_length(), and length.
uint_vector_t & MHASignal::uint_vector_t::operator= (const uint_vector_t & src)
Assign from other uint_vector_t.
Warning
This assignment will fail if the lengths mismatch.
References data, get_length(), and length.
unsigned int MHASignal::uint_vector_t::get_length () const inline
Return the length of the vector.
Referenced by MHASignal::matrix_t::dimension(), MHASignal::matrix_t::get_index(), operator=(), and operator==().
const uint32_t& MHASignal::uint_vector_t::operator[] (unsigned int k) const inline
Read-only access to elements.
Referenced by MHASignal::matrix_t::get_index(), and MHASignal::matrix_t::size().
uint32_t& MHASignal::uint_vector_t::operator[] (unsigned int k) inline
Access to elements.
unsigned int MHASignal::uint_vector_t::numbytes () const
Return number of bytes needed to store into memory.
References length, and MHA_ID_UINT_VECTOR.
Referenced by MHASignal::matrix_t::matrix_t(), MHASignal::matrix_t::numbytes(), write(), and MHASignal::matrix_t::write().
unsigned int MHASignal::uint_vector_t::write (uint8_t * buf, unsigned int len) const
Copy to memory area.
References data, length, MHA_ID_UINT_VECTOR, and numbytes().
Referenced by MHASignal::matrix_t::write().
const uint32_t* MHASignal::uint_vector_t::getdata () const inline
Return pointer to the data field.
Member Data Documentation
uint32_t MHASignal::uint_vector_t::length protected
Referenced by MHASignal::matrix_t::get_nelements(), numbytes(), operator=(), operator==(), uint_vector_t(), and write().
uint32_t* MHASignal::uint_vector_t::data protected
Referenced by MHASignal::matrix_t::get_nelements(), MHASignal::matrix_t::matrix_t(), operator=(), operator==(), uint_vector_t(), write(), and ~uint_vector_t().
The documentation for this class was generated from the following files:
mha_signal.hh
mha_signal.cpp