openMHA Manual: overlapadd::overlapadd_t Class Reference
overlapadd::overlapadd_t Class Reference
Public Member Functions
overlapadd_t (mhaconfig_t spar_in, mhaconfig_t spar_out, float wexp, float wndpos, const MHAParser::window_t &window, const MHAParser::window_t &zerowindow, float &prescale_fac, float &postscale_fac)
~overlapadd_t ()
mha_spec_t * ola1 (mha_wave_t *)
mha_wave_t * ola2 (mha_spec_t *)
Private Attributes
mha_fft_t fft
MHAWindow::base_t prewnd
MHAWindow::base_t postwnd
MHASignal::waveform_t wave_in1
MHASignal::waveform_t wave_out1
MHASignal::spectrum_t spec_in
MHASignal::waveform_t calc_out
MHASignal::waveform_t out_buf
MHASignal::waveform_t write_buf
unsigned int n_zero
unsigned int n_pad1
unsigned int n_pad2
Constructor & Destructor Documentation
overlapadd::overlapadd_t::overlapadd_t (mhaconfig_t spar_in, mhaconfig_t spar_out, float wexp, float wndpos, const MHAParser::window_t & window, const MHAParser::window_t & zerowindow, float & prescale_fac, float & postscale_fac)
References mhaconfig_t::fftlen, mhaconfig_t::fragsize, MHAParser::window_t::get_type(), MHAParser::window_t::get_window(), n_pad1, n_pad2, postwnd, prewnd, MHAWindow::base_t::ramp_begin(), MHAWindow::base_t::ramp_end(), MHASignal::waveform_t::sumsqr(), MHAParser::window_t::wnd_bartlett, MHAParser::window_t::wnd_blackman, MHAParser::window_t::wnd_hamming, MHAParser::window_t::wnd_hann, MHAParser::window_t::wnd_rect, MHAParser::window_t::wnd_user, and mhaconfig_t::wndlen.
overlapadd::overlapadd_t::~overlapadd_t ()
References fft, and mha_fft_free().
Member Function Documentation
mha_spec_t * overlapadd::overlapadd_t::ola1 (mha_wave_t * s)
References assign(), fft, mha_fft_wave2spec(), n_pad1, n_pad2, mha_wave_t::num_frames, prewnd, range(), spec_in, timeshift(), wave_in1, and wave_out1.
mha_wave_t * overlapadd::overlapadd_t::ola2 (mha_spec_t * s)
References assign(), calc_out, fft, mha_fft_spec2wave(), mha_wave_t::num_frames, out_buf, postwnd, range(), timeshift(), and write_buf.
Member Data Documentation
mha_fft_t overlapadd::overlapadd_t::fft private
Referenced by ola1(), ola2(), and ~overlapadd_t().
MHAWindow::base_t overlapadd::overlapadd_t::prewnd private
Referenced by ola1(), and overlapadd_t().
MHAWindow::base_t overlapadd::overlapadd_t::postwnd private
Referenced by ola2(), and overlapadd_t().
MHASignal::waveform_t overlapadd::overlapadd_t::wave_in1 private
Referenced by ola1().
MHASignal::waveform_t overlapadd::overlapadd_t::wave_out1 private
Referenced by ola1().
MHASignal::spectrum_t overlapadd::overlapadd_t::spec_in private
Referenced by ola1().
MHASignal::waveform_t overlapadd::overlapadd_t::calc_out private
Referenced by ola2().
MHASignal::waveform_t overlapadd::overlapadd_t::out_buf private
Referenced by ola2().
MHASignal::waveform_t overlapadd::overlapadd_t::write_buf private
Referenced by ola2().
unsigned int overlapadd::overlapadd_t::n_zero private
unsigned int overlapadd::overlapadd_t::n_pad1 private
Referenced by ola1(), and overlapadd_t().
unsigned int overlapadd::overlapadd_t::n_pad2 private
Referenced by ola1(), and overlapadd_t().
The documentation for this class was generated from the following file:
overlapadd.cpp