openMHA Manual: PluginLoader::config_file_splitter_t Class Reference
PluginLoader::config_file_splitter_t Class Reference
#include <mhapluginloader.h>
Public Member Functions
config_file_splitter_t (const std::string &name)
const std::string & get_configname () const
const std::string & get_libname () const
const std::string & get_origname () const
const std::string & get_configfile () const
Private Attributes
std::string libname
std::string configname
std::string origname
std::string configfile
Constructor & Destructor Documentation
PluginLoader::config_file_splitter_t::config_file_splitter_t (const std::string & name)
References configfile, configname, libname, MHAParser::expression_t::lval, MHA_ErrorMsg, and MHAParser::expression_t::rval.
Member Function Documentation
const std::string& PluginLoader::config_file_splitter_t::get_configname () const inline
References configname.
Referenced by MHAParser::mhapluginloader_t::load_plug(), PluginLoader::mhapluginloader_t::resolve_and_init(), and PluginLoader::mhapluginloader_t::test_error().
const std::string& PluginLoader::config_file_splitter_t::get_libname () const inline
References libname.
const std::string& PluginLoader::config_file_splitter_t::get_origname () const inline
References origname.
const std::string& PluginLoader::config_file_splitter_t::get_configfile () const inline
Referenced by PluginLoader::mhapluginloader_t::resolve_and_init().
Member Data Documentation
std::string PluginLoader::config_file_splitter_t::libname private
Referenced by config_file_splitter_t(), get_libname(), and PluginLoader::mhapluginloader_t::parse().
std::string PluginLoader::config_file_splitter_t::configname private
Referenced by config_file_splitter_t(), and get_configname().
std::string PluginLoader::config_file_splitter_t::origname private
Referenced by get_origname().
std::string PluginLoader::config_file_splitter_t::configfile private
Referenced by config_file_splitter_t().
The documentation for this class was generated from the following files:
mhapluginloader.h
mhapluginloader.cpp