openMHA Manual: pluginbrowser_t Class Reference
pluginbrowser_t Class Reference
#include <pluginbrowser.h>
Public Member Functions
pluginbrowser_t ()
void get_paths ()
plugindescription_t scan_plugin (const std::string &name)
void add_plugins ()
void clear_plugins ()
void scan_plugins ()
void add_plugin (const std::string &name)
std::list< plugindescription_t > get_plugins () const
Private Attributes
std::string plugin_extension
std::list< std::string > library_paths
std::list< plugindescription_t > plugins
std::map< std::string, pluginloader_t * > p
Constructor & Destructor Documentation
pluginbrowser_t::pluginbrowser_t ()
Member Function Documentation
void pluginbrowser_t::get_paths ()
References mha_library_paths().
Referenced by main().
plugindescription_t pluginbrowser_t::scan_plugin (const std::string & name)
References plugindescription_t::categories, plugindescription_t::documentation, plugindescription_t::fullname, PluginLoader::mhapluginloader_t::get_categories(), PluginLoader::mhapluginloader_t::get_documentation(), PluginLoader::mhapluginloader_t::getfullname(), PluginLoader::mhapluginloader_t::has_parser(), PluginLoader::mhapluginloader_t::has_process(), MHA_SPECTRUM, MHA_WAVEFORM, plugindescription_t::name, PluginLoader::mhapluginloader_t::parse(), plugindescription_t::queries, plugindescription_t::query_cmds, plugindescription_t::spec2spec, plugindescription_t::spec2wave, MHAParser::StrCnv::str2val(), plugindescription_t::wave2spec, and plugindescription_t::wave2wave.
void pluginbrowser_t::add_plugins ()
References list_dir().
Referenced by main().
void pluginbrowser_t::clear_plugins ()
Referenced by main().
void pluginbrowser_t::scan_plugins ()
Referenced by main().
void pluginbrowser_t::add_plugin (const std::string & name)
References pluginloader_t::pluginloader_t().
std::list<plugindescription_t> pluginbrowser_t::get_plugins () const inline
Referenced by main().
Member Data Documentation
std::string pluginbrowser_t::plugin_extension private
std::list<std::string> pluginbrowser_t::library_paths private
std::list<plugindescription_t> pluginbrowser_t::plugins private
std::map<std::string,pluginloader_t*> pluginbrowser_t::p private
The documentation for this class was generated from the following files:
pluginbrowser.h
pluginbrowser.cpp