openMHA Manual: speechnoise_t Class Reference
speechnoise_t Class Reference
#include <speechnoise.h>
Public Types
enum noise_type_t {
mha, olnoise, LTASS_combined, LTASS_female,
LTASS_male, white, pink, brown,
TEN_SPL, TEN_SPL_250_8k, TEN_SPL_50_16k, sin125,
sin250, sin500, sin1k, sin2k,
sin4k, sin8k
}
Public Member Functions
speechnoise_t (float duration, float srate, unsigned int channels, speechnoise_t::noise_type_t noise_type=speechnoise_t::mha)
speechnoise_t (unsigned int length_samples, float srate, unsigned int channels, speechnoise_t::noise_type_t noise_type=speechnoise_t::mha)
Public Member Functions inherited from MHASignal::waveform_t
waveform_t (const unsigned int &frames, const unsigned int &channels)
constructor of waveform_t
waveform_t (const mhaconfig_t &cf)
Constructor to create a waveform from plugin configuration.
waveform_t (const mha_wave_t &src)
Copy contructor for mha_wave_t source.
waveform_t (const MHASignal::waveform_t &src)
Copy contructor.
waveform_t (const std::vector< mha_real_t > &src)
Copy contructor for std::vector<mha_real_t> source.
virtual ~waveform_t (void)
void operator= (const mha_real_t &v)
mha_real_t & operator[] (unsigned int k)
const mha_real_t & operator[] (unsigned int k) const
mha_real_t & value (unsigned int t, unsigned int ch)
Element accessor.
mha_real_t & operator() (unsigned int t, unsigned int ch)
Element accessor.
const mha_real_t & value (unsigned int t, unsigned int ch) const
Constant element accessor.
const mha_real_t & operator() (unsigned int t, unsigned int ch) const
Constant element accessor.
mha_real_t sum (const unsigned int &a, const unsigned int &b)
sum of all elements between [a,b) in all channels
mha_real_t sum (const unsigned int &a, const unsigned int &b, const unsigned int &ch)
sum of all elements between [a,b) in channel ch
mha_real_t sum ()
sum of all elements
mha_real_t sumsqr ()
sum of square of all elements
mha_real_t sum_channel (const unsigned int &)
return sum of all elements in one channel
void assign (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
set frame "k" in channel "ch" to value "val"
void assign (const mha_real_t &)
set all elements to value
void assign_frame (const unsigned int &k, const mha_real_t &val)
assign value "val" to frame k in all channels
void assign_channel (const unsigned int &c, const mha_real_t &val)
assign value "val" to channel ch in all frames
void copy (const std::vector< mha_real_t > &v)
void copy (const mha_wave_t &)
copy data from source into current waveform
void copy (const mha_wave_t *)
void copy_channel (const mha_wave_t &, unsigned int, unsigned int)
Copy one channel of a given waveform signal to a target channel.
void copy_from_at (unsigned int, unsigned int, const mha_wave_t &, unsigned int)
Copy part of the source signal into part of this waveform object.
void export_to (mha_wave_t &)
copy data into allocated mha_wave_t structure
void limit (const mha_real_t &min, const mha_real_t &max)
limit target to range [min,max]
void power (const waveform_t &)
transform waveform signal (in Pa) to squared signal (in W/m^2)
void powspec (const mha_spec_t &)
get the power spectrum (in W/m^2) from a complex spectrum
void scale (const unsigned int &a, const unsigned int &b, const unsigned int &ch, const mha_real_t &val)
scale section [a,b) in channel "ch" by "val"
void scale (const unsigned int &k, const unsigned int &ch, const mha_real_t &val)
scale one element
void scale_channel (const unsigned int &, const mha_real_t &)
scale one channel of target with a scalar
void scale_frame (const unsigned int &, const mha_real_t &)
unsigned int get_size () const
Private Member Functions
void creator (speechnoise_t::noise_type_t noise_type, float srate)
Additional Inherited Members
Public Attributes inherited from mha_wave_t
mha_real_t * buf
signal buffer
unsigned int num_channels
number of channels
unsigned int num_frames
number of frames in each channel
mha_channel_info_t * channel_info
detailed channel description
Member Enumeration Documentation
enum speechnoise_t::noise_type_t
Enumerator
mha
olnoise
LTASS_combined
LTASS_female
LTASS_male
white
pink
brown
TEN_SPL
TEN_SPL_250_8k
TEN_SPL_50_16k
sin125
sin250
sin500
sin1k
sin2k
sin4k
sin8k
Constructor & Destructor Documentation
speechnoise_t::speechnoise_t (float duration, float srate, unsigned int channels, speechnoise_t::noise_type_t noise_type = speechnoise_t::mha)
References creator().
speechnoise_t::speechnoise_t (unsigned int length_samples, float srate, unsigned int channels, speechnoise_t::noise_type_t noise_type = speechnoise_t::mha)
References creator().
Member Function Documentation
void speechnoise_t::creator (speechnoise_t::noise_type_t noise_type, float srate) private
References MHATableLookup::xy_table_t::add_entry(), bandw_correction(), brown, MHASignal::db2lin(), erb_hz_f_hz(), expi(), fhz2bandno(), MHATableLookup::xy_table_t::interp(), LTASS_combined, LTASS_female, LTASS_male, M_PI, mha, mha_complex(), mha_fft_free(), mha_fft_new(), mha_fft_spec2wave(), mha_wave_t::num_channels, NUM_ENTR_LTASS, NUM_ENTR_MHAORIG, NUM_ENTR_OLNOISE, mha_wave_t::num_frames, mha_spec_t::num_frames, olnoise, pink, MHATableLookup::xy_table_t::set_xfun(), MHATableLookup::xy_table_t::set_xyfun(), MHATableLookup::xy_table_t::set_yfun(), sin125, sin1k, sin250, sin2k, sin4k, sin500, sin8k, TEN_SPL, TEN_SPL_250_8k, TEN_SPL_50_16k, MHASignal::spectrum_t::value(), vLTASS_combined_lev, vLTASS_female_lev, vLTASS_freq, vLTASS_male_lev, vMHAOrigFreq, vMHAOrigSpec, vOlnoiseFreq, vOlnoiseLev, and white.
Referenced by speechnoise_t().
The documentation for this class was generated from the following files:
speechnoise.h
speechnoise.cpp