openMHA Manual: PluginLoader::mhapluginloader_t Class Reference
PluginLoader::mhapluginloader_t Class Reference
#include <mhapluginloader.h>
Public Member Functions
std::string parse (const std::string &str)
mhapluginloader_t (algo_comm_t iac, const std::string &libname, bool check_version=true)
Loads and initializes mha plugin and establishes interface.
~mhapluginloader_t () throw ()
bool has_process (mha_domain_t in, mha_domain_t out) const
bool has_parser () const
mha_domain_t input_domain () const
mha_domain_t output_domain () const
void prepare (mhaconfig_t &)
void release ()
void process (mha_wave_t *, mha_wave_t **)
void process (mha_spec_t *, mha_spec_t **)
void process (mha_wave_t *, mha_spec_t **)
void process (mha_spec_t *, mha_wave_t **)
std::string getfullname () const
std::string get_documentation () const
std::vector< std::string > get_categories () const
bool is_prepared () const
Public Member Functions inherited from PluginLoader::config_file_splitter_t
config_file_splitter_t (const std::string &name)
const std::string & get_configname () const
const std::string & get_libname () const
const std::string & get_origname () const
const std::string & get_configfile () const
Public Member Functions inherited from MHAParser::c_ifc_parser_t
c_ifc_parser_t (const std::string &modulename_)
~c_ifc_parser_t ()
void set_parse_cb (c_parse_cmd_t, c_parse_err_t, void *)
Public Member Functions inherited from MHAParser::base_t
base_t (const std::string &)
Constructor for base class of all parser nodes.
base_t (const base_t &)
virtual ~base_t ()
virtual void parse (const char *, char *, unsigned int)
This function parses a command and writes the parsing result into a C character array.
virtual void parse (const std::vector< std::string > &, std::vector< std::string > &)
virtual std::string query_dump (const std::string &)
virtual std::string query_entries (const std::string &)
virtual std::string query_perm (const std::string &)
virtual std::string query_range (const std::string &)
virtual std::string query_type (const std::string &)
virtual std::string query_val (const std::string &)
virtual std::string query_readfile (const std::string &)
virtual std::string query_savefile (const std::string &)
virtual std::string query_savefile_compact (const std::string &)
virtual std::string query_savemons (const std::string &)
virtual std::string query_listids (const std::string &)
std::string query_version (const std::string &)
std::string query_id (const std::string &)
std::string query_subst (const std::string &)
std::string query_addsubst (const std::string &)
std::string query_help (const std::string &)
std::string query_cmds (const std::string &)
void set_node_id (const std::string &)
Set the identification string of this parser node.
void set_help (const std::string &)
Set the help comment of a variable or parser.
void add_parent_on_insert (parser_t *, std::string)
void rm_parent_on_remove (parser_t *)
const std::string & fullname () const
Return the full dot-separated path name of this parser node in the MHA configuration tree.
Public Member Functions inherited from PluginLoader::fourway_processor_t
virtual ~fourway_processor_t ()
Classes with virtual methods need virtual destructor.
Protected Member Functions
void test_error ()
void test_version ()
void mha_test_struct_size (unsigned int s)
void resolve_and_init ()
Protected Member Functions inherited from MHAParser::c_ifc_parser_t
std::string op_subparse (MHAParser::expression_t &)
std::string op_setval (MHAParser::expression_t &)
std::string op_query (MHAParser::expression_t &)
Protected Member Functions inherited from MHAParser::base_t
void activate_query (const std::string &, query_t)
void notify ()
Protected Attributes
int lib_err
algo_comm_t ac
dynamiclib_t lib_handle
void * lib_data
MHAGetVersion_t MHAGetVersion_cb
MHAInit_t MHAInit_cb
MHADestroy_t MHADestroy_cb
MHAPrepare_t MHAPrepare_cb
MHARelease_t MHARelease_cb
MHAProc_wave2wave_t MHAProc_wave2wave_cb
MHAProc_spec2spec_t MHAProc_spec2spec_cb
MHAProc_wave2spec_t MHAProc_wave2spec_cb
MHAProc_spec2wave_t MHAProc_spec2wave_cb
MHASet_t MHASet_cb
MHAStrError_t MHAStrError_cb
mhaconfig_t cf_input
mhaconfig_t cf_output
std::string plugin_documentation
std::vector< std::string > plugin_categories
bool b_check_version
bool b_is_prepared
Protected Attributes inherited from MHAParser::base_t
query_map_t queries
bool data_is_initialized
Additional Inherited Members
Public Attributes inherited from MHAParser::base_t
MHAEvents::emitter_t writeaccess
Event emitted on write access.
MHAEvents::emitter_t valuechanged
Event emitted if the value has changed.
MHAEvents::emitter_t readaccess
Event emitted on read access.
MHAEvents::emitter_t prereadaccess
Event emitted on read access, before the data field is accessed.
Constructor & Destructor Documentation
PluginLoader::mhapluginloader_t::mhapluginloader_t (algo_comm_t iac, const std::string & libname, bool check_version = true)
Loads and initializes mha plugin and establishes interface.
Parameters
iac AC space (algorithm communication variables)
libname Either file name of MHA plugin without platform-specific extension (i.e. "identity" for "identity.so" or "identity.dll") to be found on the MHA_LIBRARY_PATH (which is an environment variable). Or the same file name without extension followed by a colon ":" followed by the "configuration name" of the MHA plugin, which may be used to differentiate between multiple identical MHA plugins or to give the plugin a self-documenting name that fits its purpose. The library name - configuration name expression can be followed by a "<" followed by a configuration file name, which will be read after initialization of the plugin.
Example: "overlapadd:agc<compression.cfg" will load the plugin "overlapadd.so" or "overlapadd.dll", insert it as the configuration node "agc", and reads the configuration file "compression.cfg" into that node.
Parameters
check_version Pluginloader will not check that the plugin was built using a known compatible MHA version if this flag is set to false. Disabling version check is discouraged.
References resolve_and_init().
PluginLoader::mhapluginloader_t::~mhapluginloader_t () throw ()
References lib_data, and MHADestroy_cb.
Member Function Documentation
std::string PluginLoader::mhapluginloader_t::parse (const std::string & str) inline virtual
Implements PluginLoader::fourway_processor_t.
References PluginLoader::config_file_splitter_t::libname, and MHAParser::base_t::parse().
Referenced by latex_doc_t::get_latex_doc(), main(), resolve_and_init(), and pluginbrowser_t::scan_plugin().
bool PluginLoader::mhapluginloader_t::has_process (mha_domain_t in, mha_domain_t out) const
References MHA_SPECTRUM, MHA_WAVEFORM, MHAProc_spec2spec_cb, MHAProc_spec2wave_cb, MHAProc_wave2spec_cb, and MHAProc_wave2wave_cb.
Referenced by latex_doc_t::get_latex_doc(), prepare(), and pluginbrowser_t::scan_plugin().
bool PluginLoader::mhapluginloader_t::has_parser () const
References MHASet_cb.
Referenced by latex_doc_t::get_latex_doc(), MHAParser::mhapluginloader_t::load_plug(), fw_t::load_proc_lib(), and pluginbrowser_t::scan_plugin().
mha_domain_t PluginLoader::mhapluginloader_t::input_domain () const
References cf_input, and mhaconfig_t::domain.
mha_domain_t PluginLoader::mhapluginloader_t::output_domain () const
References cf_output, and mhaconfig_t::domain.
void PluginLoader::mhapluginloader_t::prepare (mhaconfig_t & tf) virtual
Implements PluginLoader::fourway_processor_t.
References b_is_prepared, cf_input, cf_output, mhaconfig_t::domain, dynamiclib_t::getname(), has_process(), lib_data, lib_err, lib_handle, MHAPrepare_cb, MHARelease_cb, PluginLoader::mhastrdomain(), and test_error().
Referenced by fw_t::prepare(), and MHAParser::mhapluginloader_t::prepare().
void PluginLoader::mhapluginloader_t::release () virtual
Implements PluginLoader::fourway_processor_t.
References b_is_prepared, lib_data, lib_err, MHARelease_cb, and test_error().
Referenced by fw_t::prepare(), fw_t::release(), and MHAParser::mhapluginloader_t::release().
void PluginLoader::mhapluginloader_t::process (mha_wave_t * s_in, mha_wave_t ** s_out) virtual
Implements PluginLoader::fourway_processor_t.
References lib_data, lib_err, MHA_ErrorMsg, MHAProc_wave2wave_cb, and test_error().
Referenced by fw_t::process().
void PluginLoader::mhapluginloader_t::process (mha_spec_t * s_in, mha_spec_t ** s_out) virtual
Implements PluginLoader::fourway_processor_t.
References lib_data, lib_err, MHA_ErrorMsg, MHAProc_spec2spec_cb, and test_error().
void PluginLoader::mhapluginloader_t::process (mha_wave_t * s_in, mha_spec_t ** s_out) virtual
Implements PluginLoader::fourway_processor_t.
References lib_data, lib_err, MHA_ErrorMsg, MHAProc_wave2spec_cb, and test_error().
void PluginLoader::mhapluginloader_t::process (mha_spec_t * s_in, mha_wave_t ** s_out) virtual
Implements PluginLoader::fourway_processor_t.
References lib_data, lib_err, MHA_ErrorMsg, MHAProc_spec2wave_cb, and test_error().
std::string PluginLoader::mhapluginloader_t::getfullname () const inline
Referenced by pluginbrowser_t::scan_plugin().
std::string PluginLoader::mhapluginloader_t::get_documentation () const inline
Referenced by latex_doc_t::get_latex_doc(), and pluginbrowser_t::scan_plugin().
std::vector<std::string> PluginLoader::mhapluginloader_t::get_categories () const inline
Referenced by latex_doc_t::get_categories(), latex_doc_t::get_latex_doc(), latex_doc_t::get_main_category(), and pluginbrowser_t::scan_plugin().
bool PluginLoader::mhapluginloader_t::is_prepared () const inline
void PluginLoader::mhapluginloader_t::test_error () protected
References PluginLoader::config_file_splitter_t::get_configname(), dynamiclib_t::getmodulename(), lib_data, lib_err, lib_handle, MHAStrError_cb, and MHAParser::c_ifc_parser_t::modulename.
Referenced by prepare(), process(), release(), and resolve_and_init().
void PluginLoader::mhapluginloader_t::test_version () protected
References dynamiclib_t::getname(), lib_handle, mha_test_struct_size(), MHA_VERSION_MAJOR, MHA_VERSION_MINOR, MHA_VERSION_RELEASE, and MHAGetVersion_cb.
Referenced by resolve_and_init().
void PluginLoader::mhapluginloader_t::mha_test_struct_size (unsigned int s) protected
Referenced by test_version().
void PluginLoader::mhapluginloader_t::resolve_and_init () protected
References ac, b_check_version, PluginLoader::config_file_splitter_t::get_configfile(), PluginLoader::config_file_splitter_t::get_configname(), lib_data, lib_err, lib_handle, MHA_RESOLVE, MHA_RESOLVE_CHECKED, MHAInit_cb, MHASet_cb, MHAStrError_cb, parse(), plugin_categories, plugin_documentation, MHAParser::c_ifc_parser_t::set_parse_cb(), MHAParser::StrCnv::str2val(), test_error(), and test_version().
Referenced by mhapluginloader_t().
Member Data Documentation
int PluginLoader::mhapluginloader_t::lib_err protected
Referenced by prepare(), process(), release(), resolve_and_init(), and test_error().
algo_comm_t PluginLoader::mhapluginloader_t::ac protected
Referenced by resolve_and_init().
dynamiclib_t PluginLoader::mhapluginloader_t::lib_handle protected
Referenced by prepare(), resolve_and_init(), test_error(), and test_version().
void* PluginLoader::mhapluginloader_t::lib_data protected
Referenced by prepare(), process(), release(), resolve_and_init(), test_error(), and ~mhapluginloader_t().
MHAGetVersion_t PluginLoader::mhapluginloader_t::MHAGetVersion_cb protected
Referenced by test_version().
MHAInit_t PluginLoader::mhapluginloader_t::MHAInit_cb protected
Referenced by resolve_and_init().
MHADestroy_t PluginLoader::mhapluginloader_t::MHADestroy_cb protected
Referenced by ~mhapluginloader_t().
MHAPrepare_t PluginLoader::mhapluginloader_t::MHAPrepare_cb protected
Referenced by prepare().
MHARelease_t PluginLoader::mhapluginloader_t::MHARelease_cb protected
Referenced by prepare(), and release().
MHAProc_wave2wave_t PluginLoader::mhapluginloader_t::MHAProc_wave2wave_cb protected
Referenced by has_process(), and process().
MHAProc_spec2spec_t PluginLoader::mhapluginloader_t::MHAProc_spec2spec_cb protected
Referenced by has_process(), and process().
MHAProc_wave2spec_t PluginLoader::mhapluginloader_t::MHAProc_wave2spec_cb protected
Referenced by has_process(), and process().
MHAProc_spec2wave_t PluginLoader::mhapluginloader_t::MHAProc_spec2wave_cb protected
Referenced by has_process(), and process().
MHASet_t PluginLoader::mhapluginloader_t::MHASet_cb protected
Referenced by has_parser(), and resolve_and_init().
MHAStrError_t PluginLoader::mhapluginloader_t::MHAStrError_cb protected
Referenced by resolve_and_init(), and test_error().
mhaconfig_t PluginLoader::mhapluginloader_t::cf_input protected
Referenced by input_domain(), and prepare().
mhaconfig_t PluginLoader::mhapluginloader_t::cf_output protected
Referenced by output_domain(), and prepare().
std::string PluginLoader::mhapluginloader_t::plugin_documentation protected
Referenced by resolve_and_init().
std::vector<std::string> PluginLoader::mhapluginloader_t::plugin_categories protected
Referenced by resolve_and_init().
bool PluginLoader::mhapluginloader_t::b_check_version protected
Referenced by resolve_and_init().
bool PluginLoader::mhapluginloader_t::b_is_prepared protected
Referenced by prepare(), and release().
The documentation for this class was generated from the following files:
mhapluginloader.h
mhapluginloader.cpp