openMHA Manual: mhajack.cpp File Reference
mhajack.cpp File Reference
#include <stdio.h>
#include "mhajack.h"
#include "mha_error.hh"
#include "mha_signal.hh"
#include <math.h>
#include "mha_defs.h"
#include <unistd.h>
Functions
static void jack_error_handler (const char *msg)
static int dummy_jack_proc_cb (jack_nframes_t, void *)
void make_friendly_number (jack_default_audio_sample_t &x)
Variables
char last_jack_err_msg [MAX_USER_ERR] = ""
int last_jack_err = 0
Function Documentation
static void jack_error_handler (const char * msg) static
References IO_ERROR_JACK, last_jack_err, last_jack_err_msg, and MAX_USER_ERR.
Referenced by MHAJack::client_t::prepare_impl().
static int dummy_jack_proc_cb (jack_nframes_t , void *) static
Referenced by MHAJack::client_t::release().
void make_friendly_number (jack_default_audio_sample_t & x) inline
References MHASignal::max(), and MHASignal::min().
Referenced by MHAJack::port_t::read().
Variable Documentation
char last_jack_err_msg[MAX_USER_ERR] = ""
Referenced by IOStrError(), jack_error_handler(), MHAJack::client_t::jack_proc_cb(), MHAJack::client_t::prepare_impl(), and MHAJack::client_t::str_error().
int last_jack_err = 0
Referenced by jack_error_handler(), MHAJack::client_t::jack_proc_cb(), and MHAJack::client_t::prepare_impl().