openMHA Manual: mha.cpp File Reference
mha.cpp File Reference
Functions
int mhamain (int argc, char *argv[])
int main (int argc, char *argv[])
Function Documentation
int mhamain (int argc, char * argv[])
References mhaserver_t::ack_fail, mhaserver_t::ack_ok, mhaserver_t::announce_port, create_lock(), MHAParser::int_t::data, fw_t::exit_request(), GREETING_TEXT, HELP_TEXT, LICENSE_AGREEMENT, mhaserver_t::logfile, mhaserver_t::logstring(), mhaserver_t::mhaserver_t(), MHAParser::base_t::parse(), mhaserver_t::port, remove_lock(), mhaserver_t::run(), and mhaserver_t::set_announce_port().
Referenced by main().
int main (int argc, char * argv[])
References mhamain().