openMHA Manual: windowselector_t Class Reference
windowselector_t Class Reference
#include <windowselector.h>
Public Member Functions
windowselector_t (const std::string &default_type)
~windowselector_t ()
void set_length (unsigned int len)
const MHAWindow::base_t & current ()
void insert_items (MHAParser::parser_t *p)
Public Attributes
MHAEvents::emitter_t updated
Private Member Functions
void update ()
void update_parser ()
Private Attributes
MHAWindow::base_t * wnd
MHAParser::kw_t wndtype
MHAParser::float_t wndexp
MHAParser::vfloat_t userwnd
MHAEvents::patchbay_t< windowselector_t > patchbay
unsigned int length
Constructor & Destructor Documentation
windowselector_t::windowselector_t (const std::string & default_type)
References MHAEvents::patchbay_t< receiver_t >::connect(), patchbay, update(), update_parser(), userwnd, wndexp, wndtype, and MHAParser::base_t::writeaccess.
windowselector_t::~windowselector_t ()
References wnd.
Member Function Documentation
void windowselector_t::set_length (unsigned int len)
References length, and update().
const MHAWindow::base_t & windowselector_t::current ()
References wnd.
void windowselector_t::insert_items (MHAParser::parser_t * p)
References MHAParser::parser_t::insert_item(), userwnd, wndexp, and wndtype.
void windowselector_t::update () private
References MHAParser::kw_t::data, MHAParser::float_t::data, MHAParser::vfloat_t::data, MHAParser::keyword_list_t::get_index(), length, MHA_ErrorMsg, userwnd, wnd, wndexp, and wndtype.
Referenced by set_length(), update_parser(), and windowselector_t().
void windowselector_t::update_parser () private
References update(), and updated.
Referenced by windowselector_t().
Member Data Documentation
MHAEvents::emitter_t windowselector_t::updated
Referenced by update_parser().
MHAWindow::base_t* windowselector_t::wnd private
Referenced by current(), update(), and ~windowselector_t().
MHAParser::kw_t windowselector_t::wndtype private
Referenced by insert_items(), update(), and windowselector_t().
MHAParser::float_t windowselector_t::wndexp private
Referenced by insert_items(), update(), and windowselector_t().
MHAParser::vfloat_t windowselector_t::userwnd private
Referenced by insert_items(), update(), and windowselector_t().
MHAEvents::patchbay_t<windowselector_t> windowselector_t::patchbay private
Referenced by windowselector_t().
unsigned int windowselector_t::length private
Referenced by set_length(), and update().
The documentation for this class was generated from the following files:
windowselector.h
windowselector.cpp