openMHA Manual: MHAParser Namespace Reference
MHAParser Namespace Reference
The MHA Toolbox library
Name space for the MHA-Parser configuration language.
Namespaces
StrCnv
String converter namespace.
Classes
class base_t
Base class for all parser items.
class bool_mon_t
Monitor with string value.
class bool_t
Variable with a boolean value ("yes"/"no")
class c_ifc_parser_t
class commit_t
Parser variable with event-emission functionality.
class complex_mon_t
Monitor with complex value.
class complex_t
Variable with complex value.
class entry_t
class expression_t
class float_mon_t
Monitor with float value.
class float_t
Variable with float value.
class int_mon_t
Monitor variable with int value.
class int_t
Variable with integer value.
class keyword_list_t
Keyword list class.
class kw_t
Variable with keyword list value.
class mcomplex_mon_t
Matrix of complex numbers monitor.
class mcomplex_t
Matrix variable with complex value.
class mfloat_mon_t
Matrix of floats monitor.
class mfloat_t
Matrix variable with float value.
class mhaconfig_mon_t
class mhapluginloader_t
Class to create a plugin loader in a parser, including the load logic.
class monitor_t
Base class for monitors and variable nodes.
class parser_t
Parser node class.
class range_var_t
Base class for all variables with a numeric value range.
class string_mon_t
Monitor with string value.
class string_t
Variable with a string value.
class variable_t
Base class for variable nodes.
class vcomplex_mon_t
Monitor with vector of complex values.
class vcomplex_t
Vector variable with complex value.
class vfloat_mon_t
Vector of floats monitor.
class vfloat_t
Vector variable with float value.
class vint_mon_t
Vector of ints monitor.
class vint_t
Variable with vector<int> value.
class vstring_mon_t
Vector of monitors with string value.
class vstring_t
Vector variable with string values.
class window_t
MHA configuration interface for a window function generator.
Typedefs
typedef std::string(base_t::* opact_t) (expression_t &)
typedef std::string(base_t::* query_t) (const std::string &)
typedef std::map< std::string, opact_t > opact_map_t
typedef std::map< std::string, query_t > query_map_t
typedef std::list< entry_t > entry_map_t
typedef int(* c_parse_cmd_t) (void *, const char *, char *, unsigned int)
typedef const char *(* c_parse_err_t) (void *, int)
Functions
int get_precision ()
std::string commentate (const std::string &s)
void trim (std::string &s)
std::string cfg_dump (base_t *, const std::string &)
std::string cfg_dump_short (base_t *, const std::string &)
std::string all_dump (base_t *, const std::string &)
std::string mon_dump (base_t *, const std::string &)
std::string all_ids (base_t *, const std::string &, const std::string &="")
void strreplace (std::string &, const std::string &, const std::string &)
string replace function
void envreplace (std::string &s)
Detailed Description
Name space for the MHA-Parser configuration language.
This namespace contains all classes which are needed for the implementation of the MHA configuration language. For details on the script language itself please see section The MHA configuration language.
List of valid MHAParser items
Sub-parser: parser_t
Variables:
Numeric variables: int_t, vint_t, float_t, vfloat_t, mfloat_t
Other variables: string_t, vstring_t, kw_t, bool_t
Monitors:
Numeric monitors: int_mon_t, vint_mon_t, float_mon_t, vfloat_mon_t
mfloat_mon_t
mcomplex_mon_t
Other monitors: bool_mon_t, string_mon_t, vstring_mon_t
Members can be inserted into the configuration namespace by using MHAParser::insert_item() or the insert_member() macro.
Typedef Documentation
typedef std::string(base_t::* MHAParser::opact_t) (expression_t &)
typedef std::string(base_t::* MHAParser::query_t) (const std::string &)
typedef std::map<std::string,opact_t> MHAParser::opact_map_t
typedef std::map<std::string,query_t> MHAParser::query_map_t
typedef std::list<entry_t> MHAParser::entry_map_t
typedef int(* MHAParser::c_parse_cmd_t) (void *, const char *, char *, unsigned int)
typedef const char*(* MHAParser::c_parse_err_t) (void *, int)
Function Documentation
int MHAParser::get_precision ()
References mha_getenv().
Referenced by MHAParser::StrCnv::val2str().
std::string MHAParser::commentate (const std::string & s)
Referenced by all_dump(), cfg_dump(), mon_dump(), and MHAParser::monitor_t::query_dump().
void MHAParser::trim (std::string & s)
Referenced by MHAParser::expression_t::expression_t(), MHAParser::StrCnv::num_brackets(), MHAParser::parser_t::query_readfile(), and MHAParser::StrCnv::str2val().
std::string MHAParser::cfg_dump (base_t * p, const std::string & pref)
References commentate(), MHAParser::parser_t::entries, MHAParser::base_t::parse(), and MHAParser::StrCnv::str2val().
Referenced by MHAParser::parser_t::query_savefile().
std::string MHAParser::cfg_dump_short (base_t * p, const std::string & pref)
References MHAParser::parser_t::entries, MHAParser::base_t::parse(), and MHAParser::StrCnv::str2val().
Referenced by MHAParser::parser_t::query_savefile_compact(), and MHAParser::parser_t::query_val().
std::string MHAParser::all_dump (base_t * p, const std::string & pref)
References commentate(), MHAParser::parser_t::entries, MHAParser::base_t::parse(), and MHAParser::StrCnv::str2val().
Referenced by MHAParser::parser_t::query_dump().
std::string MHAParser::mon_dump (base_t * p, const std::string & pref)
References commentate(), MHAParser::parser_t::entries, MHAParser::base_t::parse(), and MHAParser::StrCnv::str2val().
Referenced by MHAParser::parser_t::query_savemons().
std::string MHAParser::all_ids (base_t * p, const std::string & pref, const std::string & id = "")
References MHAParser::parser_t::entries, MHAParser::base_t::parse(), size(), and MHAParser::StrCnv::str2val().
Referenced by MHAParser::parser_t::query_listids().
void MHAParser::strreplace (std::string & s, const std::string & arg, const std::string & rep)
string replace function
Parameters
s target string
arg search pattern
rep replace pattern
Referenced by conv2latex(), io_file_t::io_file_t(), io_file_t::prepare(), and MHAParser::base_t::replace_t::replace().
void MHAParser::envreplace (std::string & s)
References mha_getenv().
Referenced by MHAParser::base_t::parse().