openMHA Manual: MHAJack Namespace Reference
MHAJack Namespace Reference
Classes
class client_avg_t
Generic JACK client for averaging a system response across time.
class client_noncont_t
Generic client for synchronous playback and recording of waveform fragments.
class client_t
Generic asynchronous JACK client.
class port_t
Class for one channel/port.
Functions
void io (mha_wave_t *s_out, mha_wave_t *s_in, const std::string &name, const std::vector< std::string > &p_out, const std::vector< std::string > &p_in, float *srate=NULL, unsigned int *fragsize=NULL, bool use_jack_transport=false)
Functional form of generic client for synchronous playback and recording of waveform fragments.
std::vector< unsigned int > get_port_capture_latency (const std::vector< std::string > &ports)
Return the JACK port latency of ports.
std::vector< int > get_port_capture_latency_int (const std::vector< std::string > &ports)
Return the JACK port latency of ports.
std::vector< unsigned int > get_port_playback_latency (const std::vector< std::string > &ports)
Return the JACK port latency of ports.
std::vector< int > get_port_playback_latency_int (const std::vector< std::string > &ports)
Function Documentation
void MHAJack::io (mha_wave_t * s_out, mha_wave_t * s_in, const std::string & name, const std::vector< std::string > & p_out, const std::vector< std::string > & p_in, float * srate = NULL, unsigned int * fragsize = NULL, bool use_jack_transport = false)
Functional form of generic client for synchronous playback and recording of waveform fragments.
References CHECK_VAR, MHAJack::client_t::get_fragsize(), MHAJack::client_t::get_srate(), and MHAJack::client_noncont_t::io().
std::vector< unsigned int > MHAJack::get_port_capture_latency (const std::vector< std::string > & ports)
Return the JACK port latency of ports.
Parameters
ports Ports to be tested
Returns
Latency vector (one entry for each port)
Referenced by get_port_capture_latency_int().
std::vector< int > MHAJack::get_port_capture_latency_int (const std::vector< std::string > & ports)
Return the JACK port latency of ports.
Parameters
ports Ports to be tested
Returns
Latency vector (one entry for each port)
References get_port_capture_latency().
Referenced by MHAIOJack::io_jack_t::get_delays_in().
std::vector< unsigned int > MHAJack::get_port_playback_latency (const std::vector< std::string > & ports)
Return the JACK port latency of ports.
Parameters
ports Ports to be tested
Returns
Latency vector (one entry for each port)
Referenced by get_port_playback_latency_int().
std::vector< int > MHAJack::get_port_playback_latency_int (const std::vector< std::string > & ports)
References get_port_playback_latency().
Referenced by MHAIOJack::io_jack_t::get_delays_out().