openMHA Manual: DynComp Namespace Reference
DynComp Namespace Reference
dynamic compression related classes and functions
Classes
class dc_afterburn_rt_t
Real-time class for after burn effect.
class dc_afterburn_t
Afterburn class, to be defined as a member of compressors.
class dc_afterburn_vars_t
Variables for dc_afterburn_t class.
class gaintable_t
Gain table class.
Functions
mha_real_t interp1 (const std::vector< mha_real_t > &vX, const std::vector< mha_real_t > &vY, mha_real_t X)
One-dimensional linear interpolation.
mha_real_t interp2 (const std::vector< mha_real_t > &vX, const std::vector< mha_real_t > &vY, const std::vector< std::vector< mha_real_t > > &mZ, mha_real_t X, mha_real_t Y)
Linear interpolation in a two-dimensional field.
Detailed Description
dynamic compression related classes and functions
Function Documentation
mha_real_t DynComp::interp1 (const std::vector< mha_real_t > & vX, const std::vector< mha_real_t > & vY, mha_real_t X)
One-dimensional linear interpolation.
Parameters
vX Vector with input samples.
vY Vector with values at input samples.
X Input value to be interpolated.
Return values
Interpolated value Y(X) at position X.
References MHA_ErrorMsg.
Referenced by DynComp::dc_afterburn_rt_t::dc_afterburn_rt_t(), DynComp::gaintable_t::get_gain(), and interp2().
mha_real_t DynComp::interp2 (const std::vector< mha_real_t > & vX, const std::vector< mha_real_t > & vY, const std::vector< std::vector< mha_real_t > > & mZ, mha_real_t X, mha_real_t Y)
Linear interpolation in a two-dimensional field.
Parameters
vX Vector with input samples, first dimension.
vY Vector with input samples, second dimension.
mZ Field with values at input samples.
X First dimension of input value to be interpolated.
Y Second dimension of input value to be interpolated.
Return values
Interpolated value Z(X,Y) at position X,Y.
References interp1(), MHA_ErrorMsg, and size().
Referenced by DynComp::gaintable_t::get_gain().