openMHA Manual: MHAWindow Namespace Reference
MHAWindow Namespace Reference
The MHA Toolbox library » Vector and matrix processing toolbox
Collection of Window types.
Classes
class bartlett_t
Bartlett window.
class base_t
Common base for window types.
class blackman_t
Blackman window.
class fun_t
Generic window based on a generator function.
class hamming_t
Hamming window.
class hanning_t
von-Hann window
class rect_t
Rectangular window.
class user_t
User defined window.
Functions
float rect (float)
Rectangular window function.
float bartlett (float)
Bartlett window function.
float hanning (float)
Hanning window function.
float hamming (float)
Hamming window function.
float blackman (float)
Blackman window function.
Detailed Description
Collection of Window types.
Function Documentation
float MHAWindow::rect (float x)
Rectangular window function.
float MHAWindow::bartlett (float x)
Bartlett window function.
float MHAWindow::hanning (float x)
Hanning window function.
References M_PI.
float MHAWindow::hamming (float x)
Hamming window function.
References M_PI.
Referenced by adm_fir_decomb(), and adm_fir_lp().
float MHAWindow::blackman (float x)
Blackman window function.
References M_PI, and MHASignal::max().