openMHA Manual: Fast Fourier Transform functions
Fast Fourier Transform functions
The MHA Toolbox library
Typedefs
typedef void * mha_fft_t
Handle for an FFT object.
Functions
mha_fft_t mha_fft_new (unsigned int n)
Create a new FFT handle.
void mha_fft_free (mha_fft_t h)
Destroy an FFT handle.
void mha_fft_wave2spec (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out)
Tranform waveform segment into spectrum.
void mha_fft_wave2spec (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out, bool swaps)
Tranform waveform segment into spectrum.
void mha_fft_spec2wave (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out)
Tranform spectrum into waveform segment.
void mha_fft_spec2wave (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out, unsigned int offset)
Tranform spectrum into waveform segment.
void mha_fft_forward (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (forward).
void mha_fft_backward (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (backward).
void mha_fft_forward_scale (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (forward).
void mha_fft_backward_scale (mha_fft_t h, mha_spec_t *sIn, mha_spec_t *sOut)
Complex to complex FFT (backward).
void mha_fft_wave2spec_scale (mha_fft_t h, const mha_wave_t *in, mha_spec_t *out)
Tranform waveform segment into spectrum.
void mha_fft_spec2wave_scale (mha_fft_t h, const mha_spec_t *in, mha_wave_t *out)
Tranform spectrum into waveform segment.
Detailed Description
Typedef Documentation
typedef void* mha_fft_t
Handle for an FFT object.
This FFT object is used by the functions mha_fft_wave2spec and mha_fft_spec2wave. The FFT back-end is the FFTW library. The back-end is completely hidden, including external header files or linking external libraries is not required.
Function Documentation
mha_fft_t mha_fft_new (unsigned int n)
Create a new FFT handle.
Parameters
n FFT length.
Create a new FFT handle.
Parameters
n FFT length
Return values
FFT object
Referenced by speechnoise_t::creator(), MHAFilter::fftfilter_t::fftfilter_t(), MHAFilter::fftfilterbank_t::fftfilterbank_t(), MHAOvlFilter::fftfb_t::get_ltass_gain_db(), operator>>(), and MHASignal::schroeder_t::schroeder_t().
void mha_fft_free (mha_fft_t h)
Destroy an FFT handle.
Parameters
h Handle to be destroyed.
Destroy an FFT handle.
Parameters
h FFT object to be removed
Referenced by speechnoise_t::creator(), MHAOvlFilter::fftfb_t::get_ltass_gain_db(), operator>>(), MHASignal::schroeder_t::schroeder_t(), MHAFilter::fftfilter_t::~fftfilter_t(), MHAFilter::fftfilterbank_t::~fftfilterbank_t(), overlapadd::overlapadd_t::~overlapadd_t(), MHAFilter::partitioned_convolution_t::~partitioned_convolution_t(), and MHAFilter::smoothspec_t::~smoothspec_t().
void mha_fft_wave2spec (mha_fft_t h, const mha_wave_t * in, mha_spec_t * out)
Tranform waveform segment into spectrum.
Parameters
h FFT handle.
in Input waveform segment.
out Output spectrum.
Tranform waveform segment into spectrum.
Parameters
h FFT object handle
in pointer to input waveform signal
out pointer to output spectrum signal (has to be allocated)
Referenced by MHAFilter::fftfilter_t::filter(), MHAFilter::fftfilterbank_t::filter(), MHAOvlFilter::fftfb_t::get_ltass_gain_db(), overlapadd::overlapadd_t::ola1(), operator>>(), MHAFilter::partitioned_convolution_t::partitioned_convolution_t(), MHAFilter::partitioned_convolution_t::process(), MHAFilter::smoothspec_t::smoothspec(), MHAFilter::fftfilter_t::update_coeffs(), and MHAFilter::fftfilterbank_t::update_coeffs().
void mha_fft_wave2spec (mha_fft_t h, const mha_wave_t * in, mha_spec_t * out, bool swaps)
Tranform waveform segment into spectrum.
Like normal wave2spec, but swaps wave buffer halves before transforming if the swaps parameter is true.
Warning: These MHA FFTs adopt a nonstandard scaling scheme in which the forward transform scales by 1/N and the backward does not scale. We would recommend using the '_scale' methods instead.
Parameters
h FFT handle.
in Input waveform segment.
out Output spectrum.
swaps Function swaps the first and second half of the waveform buffer before the FFT transform when this parameter is set to true.
void mha_fft_spec2wave (mha_fft_t h, const mha_spec_t * in, mha_wave_t * out)
Tranform spectrum into waveform segment.
Warning: These MHA FFTs adopt a nonstandard scaling scheme in which the forward transform scales by 1/N and the backward does not scale. We would recommend using the '_scale' methods instead.
Parameters
h FFT handle.
in Input spectrum.
out Output waveform segment.
Tranform spectrum into waveform segment.
Parameters
h FFT object handle
in pointer to input spectrum
out pointer to output waveform signal (has to be allocated)
Referenced by speechnoise_t::creator(), MHAFilter::fftfilter_t::filter(), MHAFilter::fftfilterbank_t::filter(), MHAFilter::smoothspec_t::internal_fir(), overlapadd::overlapadd_t::ola2(), operator>>(), MHAFilter::partitioned_convolution_t::process(), and MHASignal::schroeder_t::schroeder_t().
void mha_fft_spec2wave (mha_fft_t h, const mha_spec_t * in, mha_wave_t * out, unsigned int offset)
Tranform spectrum into waveform segment.
out may have fewer number of frames than needed for a complete iFFT. Only as many frames are written into out as fit, starting with offset offset of the complete iFFT.
Warning: These MHA FFTs adopt a nonstandard scaling scheme in which the forward transform scales by 1/N and the backward does not scale. We would recommend using the '_scale' methods instead.
Parameters
h FFT handle.
in Input spectrum.
out Output waveform segment.
offset Offset into iFFT wave buffer
Tranform spectrum into waveform segment.
Only part of the iFFT is tranferred into the out buffer.
Out may have fewer number of freames than needed for a complete iFFT. Only as many frames are written into out as fit, starting with offset offset of the complete iFFT.
Parameters
h FFT object handle
in pointer to input spectrum
out pointer to output waveform signal (has to be allocated)
offset Offset into complete iFFT buffer.
void mha_fft_forward (mha_fft_t h, mha_spec_t * sIn, mha_spec_t * sOut)
Complex to complex FFT (forward).
sIn and sOut need to have nfft bins (please note that mha_spec_t typically has nfft/2+1 bins for half-complex representation).
Warning: These MHA FFTs adopt a nonstandard scaling scheme in which the forward transform scales by 1/N and the backward does not scale. We would recommend using the '_scale' methods instead.
Parameters
h FFT handle.
sIn Input spectrum.
sOut Output spectrum.
Referenced by operator>>().
void mha_fft_backward (mha_fft_t h, mha_spec_t * sIn, mha_spec_t * sOut)
Complex to complex FFT (backward).
sIn and sOut need to have nfft bins (please note that mha_spec_t typically has nfft/2+1 bins for half-complex representation).
Warning: These MHA FFTs adopt a nonstandard scaling scheme in which the forward transform scales by 1/N and the backward does not scale. We would recommend using the '_scale' methods instead.
Parameters
h FFT handle.
sIn Input spectrum.
sOut Output spectrum.
Referenced by operator>>().
void mha_fft_forward_scale (mha_fft_t h, mha_spec_t * sIn, mha_spec_t * sOut)
Complex to complex FFT (forward).
sIn and sOut need to have nfft bins (please note that mha_spec_t typically has nfft/2+1 bins for half-complex representation).
The _scale methods use standard DFT scaling: There is no scaling in the forward transformation, and 1/N scaling for the backward.
Parameters
h FFT handle.
sIn Input spectrum.
sOut Output spectrum.
Referenced by operator>>().
void mha_fft_backward_scale (mha_fft_t h, mha_spec_t * sIn, mha_spec_t * sOut)
Complex to complex FFT (backward).
sIn and sOut need to have nfft bins (please note that mha_spec_t typically has nfft/2+1 bins for half-complex representation).
The _scale methods use standard DFT scaling: There is no scaling in the forward transformation, and 1/N scaling for the backward.
Parameters
h FFT handle.
sIn Input spectrum.
sOut Output spectrum.
Referenced by operator>>().
void mha_fft_wave2spec_scale (mha_fft_t h, const mha_wave_t * in, mha_spec_t * out)
Tranform waveform segment into spectrum.
The _scale methods use standard DFT scaling: There is no scaling in the forward transformation, and 1/N scaling for the backward.
Parameters
h FFT handle.
in Input waveform segment.
out Output spectrum.
Referenced by operator>>().
void mha_fft_spec2wave_scale (mha_fft_t h, const mha_spec_t * in, mha_wave_t * out)
Tranform spectrum into waveform segment.
The _scale methods use standard DFT scaling: There is no scaling in the forward transformation, and 1/N scaling for the backward.
Parameters
h FFT handle.
in Input spectrum.
out Output waveform segment.
Referenced by operator>>().