openMHA Manual: MHAKernel Namespace Reference
MHAKernel Namespace Reference
Classes
class algo_comm_class_t
class comm_var_map_t
Functions
algo_comm_class_t * algo_comm_safe_cast (void *)
Function Documentation
MHAKernel::algo_comm_class_t * MHAKernel::algo_comm_safe_cast (void * h)
References ALGO_COMM_ID_STR, and MHAKernel::algo_comm_class_t::algo_comm_id_string.
Referenced by MHAKernel::algo_comm_class_t::get_entries(), MHAKernel::algo_comm_class_t::get_var(), MHAKernel::algo_comm_class_t::get_var_float(), MHAKernel::algo_comm_class_t::get_var_int(), MHAKernel::algo_comm_class_t::insert_var(), MHAKernel::algo_comm_class_t::insert_var_float(), MHAKernel::algo_comm_class_t::insert_var_int(), MHAKernel::algo_comm_class_t::is_var(), MHAKernel::algo_comm_class_t::remove_ref(), and MHAKernel::algo_comm_class_t::remove_var().