openMHA Manual: Communication between algorithms
Communication between algorithms
Algorithms within one chain can share variables for communication with other algorithms.
Files
file mha_algo_comm.h
Header file for Algorithm Communication.
Namespaces
MHA_AC
Functions and classes for Algorithm Communication (AC) support.
Classes
class MHA_AC::spectrum_t
Insert a MHASignal::spectrum_t class into the AC space.
class MHA_AC::waveform_t
Insert a MHASignal::waveform_t class into the AC space.
class MHA_AC::int_t
Insert a integer variable into the AC space.
class MHA_AC::float_t
Insert a float point variable into the AC space.
class MHA_AC::double_t
Insert a double precision floating point variable into the AC space.
class MHA_AC::ac2matrix_t
Copy AC variable to a matrix.
class MHA_AC::acspace2matrix_t
Copy all or a subset of all numeric AC variables into an array of matrixes.
struct algo_comm_t
A reference handle for algorithm communication variables.
struct comm_var_t
Algorithm communication variable structure.
Functions
mha_spec_t MHA_AC::get_var_spectrum (algo_comm_t ac, const std::string &name)
Convert an AC variable into a spectrum.
mha_wave_t MHA_AC::get_var_waveform (algo_comm_t ac, const std::string &name)
Convert an AC variable into a waveform.
int MHA_AC::get_var_int (algo_comm_t ac, const std::string &name)
Return value of an integer scalar AC variable.
float MHA_AC::get_var_float (algo_comm_t ac, const std::string &name)
Return value of an floating point scalar AC variable.
std::vector< float > MHA_AC::get_var_vfloat (algo_comm_t ac, const std::string &name)
Return value of an floating point vector AC variable as standard vector of floats.
Detailed Description
Algorithms within one chain can share variables for communication with other algorithms.
This mechanism allows interaction between algorithms (i.e. separation of noise estimation and noise reduction algorithms, combination of dynamic compression and noise estimation). Through a set of simple C functions, algorithms can propagate variables of any type, even C++ classes, to other algorithms.
An algorithm communication handle (algo_comm_t) is passed at initialisation time to the constructor of each plugin class constructor. This handle contains a reference handle, algo_comm_t::handle, and a number of function pointers, algo_comm_t::insert_var etc.. An algorithm communication variable is an object of type comm_var_t.
For AC variables of numeric types, MHA Plugins for conversion into parsable monitor variables, acmon, and storage into Matlab or text files, acsave, are available.
Function Documentation
mha_spec_t MHA_AC::get_var_spectrum (algo_comm_t ac, const std::string & name)
Convert an AC variable into a spectrum.
This function reads an AC variable and tries to convert it into a valid spectrum. The Spectrum variable is granted to be valid only for one call of the processing function.
Parameters
ac AC handle
name Name of the variable
Returns
Spectrum structure
References comm_var_t::data, comm_var_t::data_type, algo_comm_t::get_error, algo_comm_t::get_var, algo_comm_t::handle, MHA_AC_MHACOMPLEX, comm_var_t::num_entries, and comm_var_t::stride.
Referenced by MHAMultiSrc::spectrum_t::update().
mha_wave_t MHA_AC::get_var_waveform (algo_comm_t ac, const std::string & name)
Convert an AC variable into a waveform.
This function reads an AC variable and tries to convert it into a valid waveform. The waveform variable is granted to be valid only for one call of the processing function.
Parameters
ac AC handle
name Name of the variable
Returns
waveform structure
References comm_var_t::data, comm_var_t::data_type, algo_comm_t::get_error, algo_comm_t::get_var, algo_comm_t::handle, MHA_AC_FLOAT, MHA_AC_MHAREAL, comm_var_t::num_entries, and comm_var_t::stride.
Referenced by combc_if_t::prepare(), combc_t::process(), and MHAMultiSrc::waveform_t::update().
int MHA_AC::get_var_int (algo_comm_t ac, const std::string & name)
Return value of an integer scalar AC variable.
Parameters
ac AC handle
name Name of the variable
Returns
Variable value
References comm_var_t::data, comm_var_t::data_type, algo_comm_t::get_error, algo_comm_t::get_var, algo_comm_t::handle, MHA_AC_INT, and comm_var_t::num_entries.
Referenced by dc::get_audiochannels().
float MHA_AC::get_var_float (algo_comm_t ac, const std::string & name)
Return value of an floating point scalar AC variable.
Parameters
ac AC handle
name Name of the variable
Returns
Variable value
References comm_var_t::data, comm_var_t::data_type, algo_comm_t::get_error, algo_comm_t::get_var, algo_comm_t::handle, MHA_AC_DOUBLE, MHA_AC_FLOAT, MHA_AC_INT, MHA_AC_MHAREAL, and comm_var_t::num_entries.
std::vector< float > MHA_AC::get_var_vfloat (algo_comm_t ac, const std::string & name)
Return value of an floating point vector AC variable as standard vector of floats.
Parameters
ac AC handle
name Name of the variable
Returns
Variable value
References comm_var_t::data, comm_var_t::data_type, algo_comm_t::get_error, algo_comm_t::get_var, algo_comm_t::handle, MHA_AC_MHAREAL, and comm_var_t::num_entries.