openMHA Manual: Vector and matrix processing toolbox
Vector and matrix processing toolbox
The MHA Toolbox library
The vector and matrix processing toolbox consists of a number of classes defined in the namespace MHASignal, and many functions and operators for use with the structures mha_wave_t and mha_spec_t.
Namespaces
MHASignal
Namespace for audio signal handling and processing classes.
MHAWindow
Collection of Window types.
Classes
struct mha_wave_t
Waveform signal structure.
struct mha_spec_t
Spectrum signal structure.
struct mha_audio_descriptor_t
Description of an audio fragment (planned as a replacement of mhaconfig_t).
struct mha_audio_t
An audio fragment in the MHA (planned as a replacement of mha_wave_t and mha_spec_t).
class MHASignal::spectrum_t
a signal processing class for spectral data (based on mha_spec_t)
class MHASignal::waveform_t
signal processing class for waveform data (based on mha_wave_t)
class MHASignal::doublebuffer_t
Double-buffering class.
class MHASignal::hilbert_t
Hilbert transformation of a waveform segment.
class MHASignal::minphase_t
Minimal phase function.
class MHASignal::uint_vector_t
Vector of unsigned values, used for size and index description of n-dimensional matrixes.
class MHASignal::matrix_t
n-dimensional matrix with real or complex floating point values.
class MHAParser::window_t
MHA configuration interface for a window function generator.
class MHASignal::delay_wave_t
Delayline containing wave fragments.
class MHASignal::async_rmslevel_t
Class for asynchronous level metering.
Typedefs
typedef float mha_real_t
MHA type for real numbers.
Functions
mha_wave_t range (mha_wave_t s, unsigned int k0, unsigned int len)
Return a time interval from a waveform chunk.
mha_spec_t channels (mha_spec_t s, unsigned int ch_start, unsigned int nch)
Return a channel interval from a spectrum.
void MHASignal::for_each (mha_wave_t *s, mha_real_t(*fun)(mha_real_t))
Apply a function to each element of a mha_wave_t.
mha_real_t MHASignal::lin2db (mha_real_t x)
Conversion from linear scale to dB (no SPL reference)
mha_real_t MHASignal::db2lin (mha_real_t x)
Conversion from dB scale to linear (no SPL reference)
mha_real_t MHASignal::pa2dbspl (mha_real_t x)
Conversion from linear Pascal scale to dB SPL.
mha_real_t MHASignal::pa22dbspl (mha_real_t x, mha_real_t eps=1e-20f)
Conversion from squared Pascal scale to dB SPL.
mha_real_t MHASignal::dbspl2pa (mha_real_t x)
Conversion from dB SPL to linear Pascal scale.
mha_real_t MHASignal::smp2sec (mha_real_t n, mha_real_t srate)
conversion from samples to seconds
mha_real_t MHASignal::sec2smp (mha_real_t sec, mha_real_t srate)
conversion from seconds to samples
mha_real_t MHASignal::bin2freq (mha_real_t bin, unsigned fftlen, mha_real_t srate)
conversion from fft bin index to frequency
mha_real_t MHASignal::freq2bin (mha_real_t freq, unsigned fftlen, mha_real_t srate)
conversion from frequency to fft bin index
mha_real_t MHASignal::smp2rad (mha_real_t samples, unsigned bin, unsigned fftlen)
conversion from delay in samples to phase shift
mha_real_t MHASignal::rad2smp (mha_real_t phase_shift, unsigned bin, unsigned fftlen)
conversion from phase shift to delay in samples
template<class elem_type >
std::vector< elem_type > MHASignal::dupvec (std::vector< elem_type > vec, unsigned n)
Duplicate last vector element to match desired size.
template<class elem_type >
std::vector< elem_type > MHASignal::dupvec_chk (std::vector< elem_type > vec, unsigned n)
Duplicate last vector element to match desired size, check for dimension.
bool equal_dim (const mha_wave_t &a, const mha_wave_t &b)
Test for equal dimension of waveform structures.
bool equal_dim (const mha_wave_t &a, const mhaconfig_t &b)
Test for match of waveform dimension with mhaconfig structure.
bool equal_dim (const mha_spec_t &a, const mha_spec_t &b)
Test for equal dimension of spectrum structures.
bool equal_dim (const mha_spec_t &a, const mhaconfig_t &b)
Test for match of spectrum dimension with mhaconfig structure.
bool equal_dim (const mha_wave_t &a, const mha_spec_t &b)
Test for equal dimension of waveform/spectrum structures.
bool equal_dim (const mha_spec_t &a, const mha_wave_t &b)
Test for equal dimension of waveform/spectrum structures.
void integrate (mha_wave_t &s)
Numeric integration of a signal vector (real values)
void integrate (mha_spec_t &s)
Numeric integration of a signal vector (complex values)
unsigned int size (const mha_wave_t &s)
Return size of a waveform structure.
unsigned int size (const mha_spec_t &s)
Return size of a spectrum structure.
unsigned int size (const mha_wave_t *s)
Return size of a waveform structure.
unsigned int size (const mha_spec_t *s)
Return size of a spectrum structure.
void clear (mha_wave_t &s)
Set all values of waveform to zero.
void clear (mha_wave_t *s)
Set all values of waveform to zero.
void clear (mha_spec_t &s)
Set all values of spectrum to zero.
void clear (mha_spec_t *s)
Set all values of spectrum to zero.
void assign (mha_wave_t self, mha_real_t val)
Set all values of waveform 'self' to 'val'.
void assign (mha_wave_t self, const mha_wave_t &val)
Set all values of waveform 'self' to 'val'.
void assign (mha_spec_t self, const mha_spec_t &val)
Set all values of spectrum 'self' to 'val'.
void timeshift (mha_wave_t &self, int shift)
Time shift of waveform chunk.
mha_real_t & value (mha_wave_t *s, unsigned int fr, unsigned int ch)
Access an element of a waveform structure.
const mha_real_t & value (const mha_wave_t *s, unsigned int fr, unsigned int ch)
Constant access to an element of a waveform structure.
mha_complex_t & value (mha_spec_t *s, unsigned int fr, unsigned int ch)
Access to an element of a spectrum.
const mha_complex_t & value (const mha_spec_t *s, unsigned int fr, unsigned int ch)
Constant access to an element of a spectrum.
mha_real_t & value (mha_wave_t &s, unsigned int fr, unsigned int ch)
Access to an element of a waveform structure.
const mha_real_t & value (const mha_wave_t &s, unsigned int fr, unsigned int ch)
Constant access to an element of a waveform structure.
mha_complex_t & value (mha_spec_t &s, unsigned int fr, unsigned int ch)
Access to an element of a spectrum.
const mha_complex_t & value (const mha_spec_t &s, unsigned int fr, unsigned int ch)
Constant access to an element of a spectrum.
std::vector< float > std_vector_float (const mha_wave_t &)
Converts a mha_wave_t structure into a std::vector<float> (interleaved order).
std::vector< std::vector< float > > std_vector_vector_float (const mha_wave_t &)
Converts a mha_wave_t structure into a std::vector< std::vector<float> > (outer vector represents channels).
std::vector< std::vector< mha_complex_t > > std_vector_vector_complex (const mha_spec_t &)
Converts a mha_spec_t structure into a std::vector< std::vector<mha_complex_t> > (outer vector represents channels).
mha_wave_t & operator+= (mha_wave_t &, const mha_real_t &)
Addition operator.
mha_wave_t & operator+= (mha_wave_t &, const mha_wave_t &)
Addition operator.
mha_wave_t & operator-= (mha_wave_t &, const mha_wave_t &)
Subtraction operator.
mha_spec_t & operator-= (mha_spec_t &, const mha_spec_t &)
Subtraction operator.
mha_wave_t & operator*= (mha_wave_t &, const mha_real_t &)
Element-wise multiplication operator.
mha_wave_t & operator*= (mha_wave_t &, const mha_wave_t &)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &, const mha_real_t &)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &, const mha_wave_t &)
Element-wise multiplication operator.
mha_spec_t & operator*= (mha_spec_t &, const mha_spec_t &)
Element-wise multiplication operator.
mha_spec_t & operator/= (mha_spec_t &, const mha_spec_t &)
Element-wise division operator.
mha_wave_t & operator/= (mha_wave_t &, const mha_wave_t &)
Element-wise division operator.
mha_spec_t & operator+= (mha_spec_t &, const mha_spec_t &)
Addition operator.
mha_spec_t & operator+= (mha_spec_t &, const mha_real_t &)
Addition operator.
mha_wave_t & operator^= (mha_wave_t &self, const mha_real_t &arg)
Exponent operator.
void MHASignal::copy_channel (mha_spec_t &self, const mha_spec_t &src, unsigned sch, unsigned dch)
Copy one channel of a source signal.
void MHASignal::copy_channel (mha_wave_t &self, const mha_wave_t &src, unsigned src_channel, unsigned dest_channel)
Copy one channel of a source signal.
mha_real_t MHASignal::rmslevel (const mha_spec_t &s, unsigned int channel, unsigned int fftlen)
Return RMS level of a spectrum channel.
mha_real_t MHASignal::colored_intensity (const mha_spec_t &s, unsigned int channel, unsigned int fftlen, mha_real_t sqfreq_response[])
Colored spectrum intensity.
mha_real_t MHASignal::maxabs (const mha_spec_t &s, unsigned int channel)
Find maximal absolute value.
mha_real_t MHASignal::rmslevel (const mha_wave_t &s, unsigned int channel)
Return RMS level of a waveform channel.
mha_real_t MHASignal::maxabs (const mha_wave_t &s, unsigned int channel)
Find maximal absolute value.
mha_real_t MHASignal::maxabs (const mha_wave_t &s)
Find maximal absolute value.
mha_real_t MHASignal::max (const mha_wave_t &s)
Find maximal value.
mha_real_t MHASignal::min (const mha_wave_t &s)
Find minimal value.
mha_real_t MHASignal::sumsqr_channel (const mha_wave_t &s, unsigned int channel)
Calculate sum of squared values in one channel.
mha_real_t MHASignal::sumsqr_frame (const mha_wave_t &s, unsigned int frame)
Calculate sum over all channels of squared values.
void conjugate (mha_spec_t &self)
Replace (!) the value of this mha_spec_t with its conjugate.
Detailed Description
The vector and matrix processing toolbox consists of a number of classes defined in the namespace MHASignal, and many functions and operators for use with the structures mha_wave_t and mha_spec_t.
Typedef Documentation
typedef float mha_real_t
MHA type for real numbers.
This type is expected to be allways the C-type 'float' (IEEE 754 single).
Function Documentation
mha_wave_t range (mha_wave_t s, unsigned int k0, unsigned int len)
Return a time interval from a waveform chunk.
A waveform chunk containing a time intervall of a larger waveform chunk is returned. The number of channels remains constant. The data of the output waveform structure points to the data of the input structure, i.e., write access to the output waveform chunk modifies the corresponding entries in the input chunk.
Parameters
s Waveform structure
k0 Index of first value in output
len Number of frames in output
Returns
Waveform structure representing the sub-interval.
References mha_wave_t::buf, mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by assign(), latex_doc_t::get_parser_var(), overlapadd::overlapadd_t::ola1(), overlapadd::overlapadd_t::ola2(), MHAOvlFilter::overlap_save_filterbank_analytic_t::overlap_save_filterbank_analytic_t(), MHASignal::async_rmslevel_t::peaklevel(), MHASignal::async_rmslevel_t::process(), MHASignal::async_rmslevel_t::rmslevel(), timeshift(), and MHAFilter::fftfilter_t::update_coeffs().
mha_spec_t channels (mha_spec_t s, unsigned int ch_start, unsigned int nch)
Return a channel interval from a spectrum.
Parameters
s Input spectrum
ch_start Index of first channel in output
nch Number of channels in output
Returns
Spectrum structure representing the sub-interval.
References mha_spec_t::buf, mha_spec_t::num_channels, and mha_spec_t::num_frames.
Referenced by assign(), DynComp::dc_afterburn_rt_t::dc_afterburn_rt_t(), MHAFilter::o1_ar_filter_t::o1_ar_filter_t(), coherence::cohflt_t::process(), MHAFilter::iir_filter_t::resize(), DynComp::dc_afterburn_t::set_fb_pars(), dc::wideband_inhib_vars_t::setchannels(), MHASndFile::sf_t::sf_t(), MHASndFile::sf_wave_t::sf_wave_t(), MHASignal::spectrum_t::spectrum_t(), validator_channels(), and MHASignal::waveform_t::waveform_t().
void MHASignal::for_each (mha_wave_t * s, mha_real_t(*)(mha_real_t) fun) inline
Apply a function to each element of a mha_wave_t.
Parameters
s Pointer to a mha_wave_t structure
fun Function to be applied (one argument)
References mha_wave_t::buf, mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by DynComp::dc_afterburn_rt_t::dc_afterburn_rt_t().
mha_real_t MHASignal::lin2db (mha_real_t x) inline
Conversion from linear scale to dB (no SPL reference)
Parameters
x Linear input.
mha_real_t MHASignal::db2lin (mha_real_t x) inline
Conversion from dB scale to linear (no SPL reference)
Parameters
x dB input.
Referenced by speechnoise_t::creator(), and MHASignal::dbspl2pa().
mha_real_t MHASignal::pa2dbspl (mha_real_t x) inline
Conversion from linear Pascal scale to dB SPL.
Parameters
x Linear input.
References MHASignal::max().
mha_real_t MHASignal::pa22dbspl (mha_real_t x, mha_real_t eps = 1e-20f) inline
Conversion from squared Pascal scale to dB SPL.
Parameters
x squared pascal input
eps minimum squared-pascal value
References MHASignal::max().
mha_real_t MHASignal::dbspl2pa (mha_real_t x) inline
Conversion from dB SPL to linear Pascal scale.
Parameters
x Linear input.
References MHASignal::db2lin().
mha_real_t MHASignal::smp2sec (mha_real_t n, mha_real_t srate) inline
conversion from samples to seconds
Parameters
n number of samples
srate sampling rate / Hz
mha_real_t MHASignal::sec2smp (mha_real_t sec, mha_real_t srate) inline
conversion from seconds to samples
Parameters
sec time in seconds
srate sampling rate / Hz
Returns
number of samples, generally has non-zero fractional part
mha_real_t MHASignal::bin2freq (mha_real_t bin, unsigned fftlen, mha_real_t srate) inline
conversion from fft bin index to frequency
Parameters
bin index of fft bin, index 0 has dc
fftlen FFT length
srate sampling frequency / Hz
Returns
frequency of fft bin / Hz
mha_real_t MHASignal::freq2bin (mha_real_t freq, unsigned fftlen, mha_real_t srate) inline
conversion from frequency to fft bin index
Parameters
freq frequency / Hz
fftlen FFT length
srate sampling frequency / Hz
Returns
0-based index of fft bin, generally has non-zero fractional part
mha_real_t MHASignal::smp2rad (mha_real_t samples, unsigned bin, unsigned fftlen) inline
conversion from delay in samples to phase shift
Compute phase shift that needs to be applied to fft spectrum to achieve the desired delay.
Parameters
samples delay in samples. Positive delay: shift current signal to future.
bin index of fft bin, index 0 has dc (index 0 and nyqvist bin cannot be delayed)
fftlen FFT length
Returns
The phase shift in radiant that needs to be applied to fft bin to achieve the desired delay. A positive delay requires a negative phase shift. If required phase shift is >pi or <-pi, then the desired delay cannot be applied in the fft domain with given parameters. Required phase shifts close to pi should not be used. If bin is 0 or nyqvist, returns 0 phase shift.
References M_PI.
mha_real_t MHASignal::rad2smp (mha_real_t phase_shift, unsigned bin, unsigned fftlen) inline
conversion from phase shift to delay in samples
Compute delay in samples that is achieved by a phase shift.
Parameters
phase_shift phase shift in radiant
bin index of fft bin, index 0 has dc (index 0 and nyqvist bin cannot be delayed)
fftlen FFT length
Returns
The delay in samples achieved by applying the phase shift. A negative phase shift causes a positive delay: shifts current signal to future.
References M_PI.
template<class elem_type > std::vector<elem_type> MHASignal::dupvec (std::vector< elem_type > vec, unsigned n)
Duplicate last vector element to match desired size.
Parameters
vec Input vector.
n Target number of elements.
Return values
Resized vector.
template<class elem_type > std::vector<elem_type> MHASignal::dupvec_chk (std::vector< elem_type > vec, unsigned n)
Duplicate last vector element to match desired size, check for dimension.
The input dimension can be either 1 or the target length.
Parameters
vec Input vector.
n Target number of elements.
Return values
Resized vector.
Referenced by coherence::cohflt_t::cohflt_t(), and MHAFilter::o1_ar_filter_t::o1_ar_filter_t().
bool equal_dim (const mha_wave_t & a, const mha_wave_t & b) inline
Test for equal dimension of waveform structures.
References mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by assign().
bool equal_dim (const mha_wave_t & a, const mhaconfig_t & b) inline
Test for match of waveform dimension with mhaconfig structure.
References mhaconfig_t::channels, mhaconfig_t::fragsize, mha_wave_t::num_channels, and mha_wave_t::num_frames.
bool equal_dim (const mha_spec_t & a, const mha_spec_t & b) inline
Test for equal dimension of spectrum structures.
References mha_spec_t::num_channels, and mha_spec_t::num_frames.
bool equal_dim (const mha_spec_t & a, const mhaconfig_t & b) inline
Test for match of spectrum dimension with mhaconfig structure.
References mhaconfig_t::channels, mhaconfig_t::fftlen, mha_spec_t::num_channels, and mha_spec_t::num_frames.
bool equal_dim (const mha_wave_t & a, const mha_spec_t & b) inline
Test for equal dimension of waveform/spectrum structures.
Warning
Waveform structures mha_wave_t use interleaved data order, while spectrum structures mha_spec_t use non-interleaved.
References mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, and mha_spec_t::num_frames.
bool equal_dim (const mha_spec_t & a, const mha_wave_t & b) inline
Test for equal dimension of waveform/spectrum structures.
Warning
Waveform structures mha_wave_t use interleaved data order, while spectrum structures mha_spec_t use non-interleaved.
References integrate(), mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, and mha_spec_t::num_frames.
void integrate (mha_wave_t & s)
Numeric integration of a signal vector (real values)
Parameters
s Input signal vector
References mha_wave_t::num_channels, mha_wave_t::num_frames, and MHASignal::waveform_t::value().
Referenced by equal_dim(), and MHASignal::schroeder_t::schroeder_t().
void integrate (mha_spec_t & s)
Numeric integration of a signal vector (complex values)
Parameters
s Input signal vector
References mha_spec_t::num_channels, mha_spec_t::num_frames, and MHASignal::waveform_t::value().
unsigned int size (const mha_wave_t & s) inline
Return size of a waveform structure.
References mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by MHAParser::all_ids(), assign(), clear(), conjugate(), MHASignal::spectrum_t::copy(), MHASignal::waveform_t::copy(), MHASignal::copy_permuted(), MHASignal::spectrum_t::export_to(), calibrator_runtime_layer_t::firfirlen(), MHASignal::waveform_t::get_size(), io_tcp_sound_t::hton(), DynComp::interp2(), AuditoryProfile::fmap_t::isempty(), isempty(), MHASignal::loop_wavefragment_t::loop_wavefragment_t(), MHASignal::stat_t::mean(), MHASignal::stat_t::mean_std(), MHAFilter::transfer_matrix_t::non_empty_partitions(), io_tcp_sound_t::ntoh(), operator*=(), operator+=(), operator/=(), operator^=(), MHAFilter::transfer_matrix_t::partitions(), MHASignal::stat_t::push(), safe_div(), MHASignal::saveas_mat4(), set_minabs(), MHAParser::StrCnv::str2val(), DynComp::gaintable_t::update(), and dc::wb_inhib_cfg_t::wb_inhib_cfg_t().
unsigned int size (const mha_spec_t & s) inline
Return size of a spectrum structure.
References mha_spec_t::num_channels, and mha_spec_t::num_frames.
unsigned int size (const mha_wave_t * s) inline
Return size of a waveform structure.
References mha_wave_t::num_channels, and mha_wave_t::num_frames.
unsigned int size (const mha_spec_t * s) inline
Return size of a spectrum structure.
References mha_spec_t::num_channels, and mha_spec_t::num_frames.
void clear (mha_wave_t & s) inline
Set all values of waveform to zero.
References mha_wave_t::buf, and size().
Referenced by MHAMultiSrc::channels_t::channels_t(), MHAFilter::fftfilterbank_t::filter(), MHASignal::loop_wavefragment_t::playback(), MHAJack::client_avg_t::proc(), combc_t::process(), MHAFilter::partitioned_convolution_t::process(), MHAFilter::smoothspec_t::spec2fir(), io_file_t::start(), MHAFilter::fftfilter_t::update_coeffs(), and MHAFilter::fftfilterbank_t::update_coeffs().
void clear (mha_wave_t * s) inline
Set all values of waveform to zero.
References mha_wave_t::buf, and size().
void clear (mha_spec_t & s) inline
Set all values of spectrum to zero.
References mha_spec_t::buf, and size().
void clear (mha_spec_t * s) inline
Set all values of spectrum to zero.
References mha_spec_t::buf, and size().
void assign (mha_wave_t self, mha_real_t val) inline
Set all values of waveform 'self' to 'val'.
Parameters
self Waveform to be modified.
val Value to be assigned to all entries of waveform.
References channels(), range(), size(), and timeshift().
Referenced by MHASignal::waveform_t::operator()(), and MHASignal::waveform_t::operator=().
void assign (mha_wave_t self, const mha_wave_t & val)
Set all values of waveform 'self' to 'val'.
Parameters
self Waveform to be modified.
val Source waveform structure.
References mha_wave_t::buf, equal_dim(), mha_wave_t::num_channels, mha_wave_t::num_frames, and size().
Referenced by MHAFilter::fftfilter_t::filter(), overlapadd::overlapadd_t::ola1(), overlapadd::overlapadd_t::ola2(), MHAFilter::polyphase_resampling_t::read(), timeshift(), and MHAFilter::fftfilter_t::update_coeffs().
void assign (mha_spec_t self, const mha_spec_t & val)
Set all values of spectrum 'self' to 'val'.
Parameters
self Spectrum to be modified.
val Source spectrum.
References mha_spec_t::buf, equal_dim(), mha_spec_t::num_channels, mha_spec_t::num_frames, and size().
void timeshift (mha_wave_t & self, int shift)
Time shift of waveform chunk.
Shifted areas are filled with zeros.
Parameters
self Waveform chunk to be shifted
shift Shift amount, positive values shift to later times
References assign(), range(), and value().
Referenced by assign(), MHAFilter::fftfilter_t::filter(), overlapadd::overlapadd_t::ola1(), and overlapadd::overlapadd_t::ola2().
mha_real_t& value (mha_wave_t * s, unsigned int fr, unsigned int ch) inline
Access an element of a waveform structure.
Parameters
s Waveform structure
fr Frame number
ch Channel number
Returns
Reference to element
References mha_wave_t::buf, and mha_wave_t::num_channels.
Referenced by MHAOvlFilter::fftfb_t::apply_gains(), MHASignal::copy_permuted(), MHAFilter::complex_bandpass_t::filter(), fw_t::fw_until_cmd(), MHAOvlFilter::fftfb_t::get_fbpower(), DynComp::gaintable_t::get_gain(), MHASignal::hilbert_fftw_t::hilbert(), intensity(), MHASignal::matrix_t::matrix_t(), MHASignal::maxabs(), MHAFilter::o1_ar_filter_t::operator()(), MHAFilter::iir_ord1_real_t::operator()(), MHASignal::minphase_t::operator()(), MHASignal::doublebuffer_t::outer_process(), MHAFilter::gamma_flt_t::phase_correction(), MHAJack::client_noncont_t::proc(), MHAJack::client_avg_t::proc(), combc_t::process(), softclipper_t::process(), coherence::cohflt_t::process(), dc::dc_t::process(), adm_if_t::process(), MHASignal::subsample_delay_t::process(), io_parser_t::process_frame(), MHAJack::port_t::read(), MHAFilter::polyphase_resampling_t::read(), MHASignal::rmslevel(), MHASignal::saveas_mat4(), MHASignal::fft_t::sort_fftw2spec(), MHASignal::fft_t::sort_spec2fftw(), MHAFilter::smoothspec_t::spec2fir(), std_vector_vector_complex(), std_vector_vector_float(), MHASignal::sumsqr_channel(), MHASignal::sumsqr_frame(), timeshift(), MHAOvlFilter::fftfb_t::w(), and MHAJack::port_t::write().
const mha_real_t& value (const mha_wave_t * s, unsigned int fr, unsigned int ch) inline
Constant access to an element of a waveform structure.
Parameters
s Waveform structure
fr Frame number
ch Channel number
Returns
Reference to element
References mha_wave_t::buf, and mha_wave_t::num_channels.
mha_complex_t& value (mha_spec_t * s, unsigned int fr, unsigned int ch) inline
Access to an element of a spectrum.
Parameters
s Spectrum structure
fr Bin number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, and mha_spec_t::num_frames.
const mha_complex_t& value (const mha_spec_t * s, unsigned int fr, unsigned int ch) inline
Constant access to an element of a spectrum.
Parameters
s Spectrum structure
fr Bin number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, and mha_spec_t::num_frames.
mha_real_t& value (mha_wave_t & s, unsigned int fr, unsigned int ch) inline
Access to an element of a waveform structure.
Parameters
s Waveform structure
fr Frame number
ch Channel number
Returns
Reference to element
References mha_wave_t::buf, and mha_wave_t::num_channels.
const mha_real_t& value (const mha_wave_t & s, unsigned int fr, unsigned int ch) inline
Constant access to an element of a waveform structure.
Parameters
s Waveform structure
fr Frame number
ch Channel number
Returns
Reference to element
References mha_wave_t::buf, and mha_wave_t::num_channels.
mha_complex_t& value (mha_spec_t & s, unsigned int fr, unsigned int ch) inline
Access to an element of a spectrum.
Parameters
s Spectrum structure
fr Bin number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, and mha_spec_t::num_frames.
const mha_complex_t& value (const mha_spec_t & s, unsigned int fr, unsigned int ch) inline
Constant access to an element of a spectrum.
Parameters
s Spectrum structure
fr Bin number
ch Channel number
Returns
Reference to element
References mha_spec_t::buf, MHASignal::colored_intensity(), MHASignal::copy_channel(), MHASignal::max(), MHASignal::maxabs(), MHASignal::min(), mha_spec_t::num_frames, operator*=(), operator+=(), operator-=(), operator/=(), operator^=(), MHASignal::rmslevel(), safe_div(), set_minabs(), MHASignal::signal_counter, std_vector_float(), std_vector_vector_complex(), std_vector_vector_float(), MHASignal::sumsqr_channel(), and MHASignal::sumsqr_frame().
std::vector<float> std_vector_float (const mha_wave_t &)
Converts a mha_wave_t structure into a std::vector<float> (interleaved order).
Warning
This function is not real-time safe. Do not use in signal processing thread.
References mha_wave_t::buf, and MHASignal::matrix_t::size().
Referenced by combc_if_t::prepare(), adm_if_t::prepare(), and value().
std::vector<std::vector<float> > std_vector_vector_float (const mha_wave_t &)
Converts a mha_wave_t structure into a std::vector< std::vector<float> > (outer vector represents channels).
Warning
This function is not real-time safe. Do not use in signal processing thread.
References mha_wave_t::num_channels, mha_wave_t::num_frames, and value().
Referenced by value().
std::vector<std::vector<mha_complex_t> > std_vector_vector_complex (const mha_spec_t &)
Converts a mha_spec_t structure into a std::vector< std::vector<mha_complex_t> > (outer vector represents channels).
Warning
This function is not real-time safe. Do not use in signal processing thread.
References mha_spec_t::num_channels, mha_spec_t::num_frames, and value().
Referenced by value().
mha_wave_t& operator+= (mha_wave_t & , const mha_real_t &)
Addition operator.
References mha_wave_t::buf, and size().
Referenced by value().
mha_wave_t& operator+= (mha_wave_t & , const mha_wave_t &)
Addition operator.
References ASSERT_EQUAL_DIM, and MHASignal::waveform_t::value().
mha_wave_t& operator-= (mha_wave_t & , const mha_wave_t &)
Subtraction operator.
References ASSERT_EQUAL_DIM, and MHASignal::waveform_t::value().
Referenced by value().
mha_spec_t& operator-= (mha_spec_t & , const mha_spec_t &)
Subtraction operator.
References ASSERT_EQUAL_DIM, and MHASignal::waveform_t::value().
mha_wave_t& operator*= (mha_wave_t & , const mha_real_t &)
Element-wise multiplication operator.
References mha_wave_t::buf, and size().
Referenced by value().
mha_wave_t& operator*= (mha_wave_t & , const mha_wave_t &)
Element-wise multiplication operator.
References ASSERT_EQUAL_DIM, and MHASignal::waveform_t::value().
mha_spec_t& operator*= (mha_spec_t & , const mha_real_t &)
Element-wise multiplication operator.
References mha_wave_t::buf, and size().
mha_spec_t& operator*= (mha_spec_t & , const mha_wave_t &)
Element-wise multiplication operator.
References ASSERT_EQUAL_DIM, and MHASignal::waveform_t::value().
mha_spec_t& operator*= (mha_spec_t & , const mha_spec_t &)
Element-wise multiplication operator.
References ASSERT_EQUAL_DIM, and MHASignal::waveform_t::value().
mha_spec_t& operator/= (mha_spec_t & , const mha_spec_t &)
Element-wise division operator.
References safe_div().
Referenced by value().
mha_wave_t& operator/= (mha_wave_t & , const mha_wave_t &)
Element-wise division operator.
References mha_wave_t::buf, and size().
mha_spec_t& operator+= (mha_spec_t & , const mha_spec_t &)
Addition operator.
References ASSERT_EQUAL_DIM, and MHASignal::waveform_t::value().
mha_spec_t& operator+= (mha_spec_t & , const mha_real_t &)
Addition operator.
References mha_wave_t::buf, and size().
mha_wave_t& operator^= (mha_wave_t & self, const mha_real_t & arg)
Exponent operator.
Warning
This overwrites the xor operator!
References size().
Referenced by value().
void MHASignal::copy_channel (mha_spec_t & self, const mha_spec_t & src, unsigned sch, unsigned dch)
Copy one channel of a source signal.
Parameters
self Destination.
src Source
sch Source channel number
dch Destination channel number
References mha_spec_t::channel_info, MHA_ErrorMsg, mha_wave_t::num_channels, mha_spec_t::num_channels, mha_spec_t::num_frames, and MHASignal::waveform_t::value().
Referenced by MHAFilter::resampling_filter_t::resampling_filter_t(), and value().
void MHASignal::copy_channel (mha_wave_t & self, const mha_wave_t & src, unsigned src_channel, unsigned dest_channel)
Copy one channel of a source signal.
Parameters
self Destination.
src Source
src_channel Source channel number
dest_channel Destination channel number
References mha_wave_t::buf, mha_wave_t::channel_info, MHA_ErrorMsg, mha_wave_t::num_channels, and mha_wave_t::num_frames.
mha_real_t MHASignal::rmslevel (const mha_spec_t & s, unsigned int channel, unsigned int fftlen)
Return RMS level of a spectrum channel.
Parameters
s Input spectrum
channel Channel number to be tested
fftlen FFT length (to correctly count the level of the Nyquist bin)
Returns
RMS level in Pa
References intensity().
Referenced by MHAOvlFilter::fftfb_t::get_ltass_gain_db(), MHASignal::async_rmslevel_t::rmslevel(), and value().
mha_real_t MHASignal::colored_intensity (const mha_spec_t & s, unsigned int channel, unsigned int fftlen, mha_real_t sqfreq_response[])
Colored spectrum intensity.
computes the squared sum of the spectrum after filtering with the frequency response
Parameters
s Input spectrum
channel Channel number to be tested
fftlen FFT length (to correctly count the level of the Nyquist bin)
sqfreq_response A squared weighting factor for every fft bin.
Returns
sum of squares. Root of this is the colored level in Pa
References intensity().
Referenced by value().
mha_real_t MHASignal::maxabs (const mha_spec_t & s, unsigned int channel)
Find maximal absolute value.
Parameters
s Input signal
channel Channel to be tested
Returns
maximum absolute value
References abs(), MHASignal::max(), mha_spec_t::num_frames, and value().
Referenced by MHASignal::loop_wavefragment_t::loop_wavefragment_t(), MHASignal::maxabs(), MHASignal::async_rmslevel_t::peaklevel(), and value().
mha_real_t MHASignal::rmslevel (const mha_wave_t & s, unsigned int channel)
Return RMS level of a waveform channel.
Parameters
s Input waveform signal
channel Channel number to be tested
Returns
RMS level in Pa
References mha_wave_t::num_frames, and value().
mha_real_t MHASignal::maxabs (const mha_wave_t & s, unsigned int channel)
Find maximal absolute value.
Parameters
s Input signal
channel Channel to be tested
Returns
maximum absolute value
References MHASignal::max(), mha_wave_t::num_frames, and value().
mha_real_t MHASignal::maxabs (const mha_wave_t & s)
Find maximal absolute value.
Parameters
s Input signal
Returns
maximum absolute value
References MHASignal::max(), MHASignal::maxabs(), and mha_wave_t::num_channels.
mha_real_t MHASignal::max (const mha_wave_t & s)
Find maximal value.
Parameters
s Input signal
Returns
maximum absolute value
References mha_wave_t::buf, and MHASignal::matrix_t::size().
Referenced by adm_fir_decomb(), MHAWindow::blackman(), MHAFilter::blockprocessing_polyphase_resampling_t::blockprocessing_polyphase_resampling_t(), DynComp::dc_afterburn_rt_t::burn(), MHAOvlFilter::fspacing_t::cf2bands(), MHAFilter::fftfilterbank_t::filter(), MHAFilter::filter_t::filter_t(), calibrator_runtime_layer_t::firfir2fftlen(), MHAOvlFilter::fftfb_t::get_ltass_gain_db(), MHA_TCP::Timeout_Event::get_os_event(), MHATableLookup::xy_table_t::interp(), MHAJack::client_noncont_t::io(), MHASignal::limit(), MHATableLookup::linear_table_t::lookup(), MHASignal::loop_wavefragment_t::loop_wavefragment_t(), MHAFilter::make_friendly_number(), make_friendly_number(), MHASignal::maxabs(), MHASignal::stat_t::mean(), MHASignal::stat_t::mean_std(), mylogf(), normalize(), MHASignal::minphase_t::operator()(), MHASignal::quantizer_t::operator()(), MHASignal::pa22dbspl(), MHASignal::pa2dbspl(), MHASignal::async_rmslevel_t::peaklevel(), MHAFilter::polyphase_resampling_t::polyphase_resampling_t(), MHAJack::client_noncont_t::proc(), coherence::cohflt_t::process(), dc::dc_t::process(), MHAFilter::resampling_filter_t::resampling_filter_t(), MHASignal::async_rmslevel_t::rmslevel(), calibrator_t::update_tau_level(), value(), and MHA_TCP::Event_Watcher::wait().
mha_real_t MHASignal::min (const mha_wave_t & s)
Find minimal value.
Parameters
s Input signal
Returns
maximum absolute value
References mha_wave_t::buf, and MHASignal::matrix_t::size().
Referenced by adm_fir_decomb(), DynComp::dc_afterburn_rt_t::burn(), MHASignal::waveform_t::copy(), MHAFilter::fftfilterbank_t::filter(), MHAFilter::filter_t::filter_t(), MHATableLookup::xy_table_t::interp(), MHASignal::limit(), MHATableLookup::linear_table_t::lookup(), MHAFilter::make_friendly_number(), make_friendly_number(), MHASignal::quantizer_t::operator()(), MHASignal::async_rmslevel_t::peaklevel(), MHAJack::client_noncont_t::proc(), dc::dc_t::process(), MHASignal::quantile(), mha_drifter_fifo_t< T >::read(), mha_fifo_lw_t< T >::read(), MHA_TCP::Connection::read_line(), MHASignal::async_rmslevel_t::rmslevel(), MHASignal::schroeder_t::schroeder_t(), io_file_t::start(), MHAFilter::fftfilter_t::update_coeffs(), validator_length(), value(), MHASignal::fft_t::wave2spec(), MHASignal::fft_t::wave2spec_scale(), mha_drifter_fifo_t< T >::write(), mha_fifo_lw_t< T >::write(), and MHASignal::ringbuffer_t::write().
mha_real_t MHASignal::sumsqr_channel (const mha_wave_t & s, unsigned int channel)
Calculate sum of squared values in one channel.
Parameters
s Input signal
channel Channel
Returns
References mha_wave_t::num_frames, and value().
Referenced by value().
mha_real_t MHASignal::sumsqr_frame (const mha_wave_t & s, unsigned int frame)
Calculate sum over all channels of squared values.
Parameters
s Input signal
frame Frame number
Returns
References mha_wave_t::num_channels, and value().
Referenced by value().
void conjugate (mha_spec_t & self) inline
Replace (!) the value of this mha_spec_t with its conjugate.
References mha_spec_t::buf, conjugate(), and size().