openMHA Manual: MHASignal Namespace Reference
MHASignal Namespace Reference
The MHA Toolbox libraryThe MHA Toolbox library » | Vector and matrix processing toolbox
Namespace for audio signal handling and processing classes.
Classes
class async_rmslevel_t
Class for asynchronous level metering.
class delay_spec_t
class delay_t
Class to realize a simple delay of waveform streams.
class delay_wave_t
Delayline containing wave fragments.
class doublebuffer_t
Double-buffering class.
class fft_t
class hilbert_fftw_t
class hilbert_t
Hilbert transformation of a waveform segment.
class loop_wavefragment_t
Copy a fixed waveform fragment to a series of waveform fragments of other size.
class matrix_t
n-dimensional matrix with real or complex floating point values.
class minphase_t
Minimal phase function.
class quantizer_t
Simple simulation of fixpoint quantization.
class ringbuffer_t
A ringbuffer class for time domain audio signal, which makes no assumptions with respect to fragment size.
class schroeder_t
Schroeder tone complex class.
class spectrum_t
a signal processing class for spectral data (based on mha_spec_t)
class stat_t
class subsample_delay_t
implements subsample delay in spectral domain.
class uint_vector_t
Vector of unsigned values, used for size and index description of n-dimensional matrixes.
class waveform_t
signal processing class for waveform data (based on mha_wave_t)
Functions
void for_each (mha_wave_t *s, mha_real_t(*fun)(mha_real_t))
Apply a function to each element of a mha_wave_t.
mha_real_t lin2db (mha_real_t x)
Conversion from linear scale to dB (no SPL reference)
mha_real_t db2lin (mha_real_t x)
Conversion from dB scale to linear (no SPL reference)
mha_real_t pa2dbspl (mha_real_t x)
Conversion from linear Pascal scale to dB SPL.
mha_real_t pa22dbspl (mha_real_t x, mha_real_t eps=1e-20f)
Conversion from squared Pascal scale to dB SPL.
mha_real_t dbspl2pa (mha_real_t x)
Conversion from dB SPL to linear Pascal scale.
mha_real_t smp2sec (mha_real_t n, mha_real_t srate)
conversion from samples to seconds
mha_real_t sec2smp (mha_real_t sec, mha_real_t srate)
conversion from seconds to samples
mha_real_t bin2freq (mha_real_t bin, unsigned fftlen, mha_real_t srate)
conversion from fft bin index to frequency
mha_real_t freq2bin (mha_real_t freq, unsigned fftlen, mha_real_t srate)
conversion from frequency to fft bin index
mha_real_t smp2rad (mha_real_t samples, unsigned bin, unsigned fftlen)
conversion from delay in samples to phase shift
mha_real_t rad2smp (mha_real_t phase_shift, unsigned bin, unsigned fftlen)
conversion from phase shift to delay in samples
template<class elem_type >
std::vector< elem_type > dupvec (std::vector< elem_type > vec, unsigned n)
Duplicate last vector element to match desired size.
template<class elem_type >
std::vector< elem_type > dupvec_chk (std::vector< elem_type > vec, unsigned n)
Duplicate last vector element to match desired size, check for dimension.
void copy_channel (mha_spec_t &self, const mha_spec_t &src, unsigned sch, unsigned dch)
Copy one channel of a source signal.
void copy_channel (mha_wave_t &self, const mha_wave_t &src, unsigned src_channel, unsigned dest_channel)
Copy one channel of a source signal.
mha_real_t rmslevel (const mha_spec_t &s, unsigned int channel, unsigned int fftlen)
Return RMS level of a spectrum channel.
mha_real_t colored_intensity (const mha_spec_t &s, unsigned int channel, unsigned int fftlen, mha_real_t sqfreq_response[])
Colored spectrum intensity.
mha_real_t maxabs (const mha_spec_t &s, unsigned int channel)
Find maximal absolute value.
mha_real_t rmslevel (const mha_wave_t &s, unsigned int channel)
Return RMS level of a waveform channel.
mha_real_t maxabs (const mha_wave_t &s, unsigned int channel)
Find maximal absolute value.
mha_real_t maxabs (const mha_wave_t &s)
Find maximal absolute value.
mha_real_t max (const mha_wave_t &s)
Find maximal value.
mha_real_t min (const mha_wave_t &s)
Find minimal value.
mha_real_t sumsqr_channel (const mha_wave_t &s, unsigned int channel)
Calculate sum of squared values in one channel.
mha_real_t sumsqr_frame (const mha_wave_t &s, unsigned int frame)
Calculate sum over all channels of squared values.
void scale (mha_spec_t *dest, const mha_wave_t *src)
void limit (mha_wave_t &s, const mha_real_t &min, const mha_real_t &max)
Limit the singal in the waveform buffer to the range [min, max].
template<class elem_type >
elem_type kth_smallest (elem_type array[], unsigned n, unsigned k)
Fast search for the kth smallest element of an array.
template<class elem_type >
elem_type median (elem_type array[], unsigned n)
Fast median search.
template<class elem_type >
elem_type mean (const std::vector< elem_type > &data, elem_type start_val)
Calculate average of elements in a vector.
template<class elem_type >
std::vector< elem_type > quantile (std::vector< elem_type > data, const std::vector< elem_type > &p)
Calculate quantile of elements in a vector.
void saveas_mat4 (const mha_spec_t &data, const std::string &varname, FILE *fh)
Save a MHA spectrum as a variable in a Matlab4 file.
void saveas_mat4 (const mha_wave_t &data, const std::string &varname, FILE *fh)
Save a MHA waveform as a variable in a Matlab4 file.
void saveas_mat4 (const std::vector< mha_real_t > &data, const std::string &varname, FILE *fh)
Save a float vector as a variable in a Matlab4 file.
void copy_permuted (mha_wave_t *dest, const mha_wave_t *src)
Copy contents of a waveform to a permuted waveform.
Variables
unsigned long int signal_counter = 0
Signal counter to produce signal ID strings.
Detailed Description
Namespace for audio signal handling and processing classes.
Function Documentation
void MHASignal::scale (mha_spec_t * dest, const mha_wave_t * src)
References mha_wave_t::buf, mha_spec_t::buf, mha_complex_t::im, MHA_ErrorMsg, mha_wave_t::num_channels, mha_spec_t::num_channels, mha_wave_t::num_frames, mha_spec_t::num_frames, and mha_complex_t::re.
void MHASignal::limit (mha_wave_t & s, const mha_real_t & min, const mha_real_t & max)
Limit the singal in the waveform buffer to the range [min, max].
Parameters
s The signal to limit. The signal in this wave buffer is modified.
min lower limit
max upper limit
References mha_wave_t::buf, max(), min(), mha_wave_t::num_channels, and mha_wave_t::num_frames.
Referenced by MHASignal::waveform_t::get_size(), MHASignal::waveform_t::limit(), MHASignal::waveform_t::operator()(), softclipper_t::process(), and coherence::cohflt_t::process().
template<class elem_type > elem_type MHASignal::kth_smallest (elem_type array[], unsigned n, unsigned k)
Fast search for the kth smallest element of an array.
The order of elements is altered, but not completely sorted. Using the algorithm from N. Wirth, published in "Algorithms + data structures = programs", Prentice-Hall, 1976
Parameters
array Element array
Postcondition
The order of elements in the array is altered. array[k] then holds the result.
Parameters
n number of elements in array
Precondition
n >= 1
Parameters
k The k'th smalles element is returned: k = 0 returns the minimum, k = (n-1)/2 returns the median, k=(n-1) returns the maximum
Precondition
k < n
Returns
The kth smallest array element
Referenced by median().
template<class elem_type > elem_type MHASignal::median (elem_type array[], unsigned n) inline
Fast median search.
The order of elements is altered, but not completely sorted.
Parameters
array Element array
Postcondition
The order of elements in the array is altered. array[(n-1)/2] then holds the median.
Parameters
n number of elements in array
Precondition
n >= 1
Returns
The median of the array elements
References kth_smallest().
template<class elem_type > elem_type MHASignal::mean (const std::vector< elem_type > & data, elem_type start_val) inline
Calculate average of elements in a vector.
Parameters
data Input vector
start_val Value for initialization of the return value before sum.
Returns
The average of the vector elements
template<class elem_type > std::vector<elem_type> MHASignal::quantile (std::vector< elem_type > data, const std::vector< elem_type > & p) inline
Calculate quantile of elements in a vector.
Parameters
data Input vector
p Vector of probability values.
Returns
Vector of quantiles of input data, one entry for each probability value.
References copy_permuted(), min(), and saveas_mat4().
void MHASignal::saveas_mat4 (const mha_spec_t & data, const std::string & varname, FILE * fh)
Save a MHA spectrum as a variable in a Matlab4 file.
Parameters
data MHA spectrum to be saved.
varname Matlab variable name (Matlab4 limitations on maximal length are not checked).
fh File handle to Matlab4 file.
References mha_spec_t::num_channels, mha_spec_t::num_frames, size(), and value().
Referenced by quantile().
void MHASignal::saveas_mat4 (const mha_wave_t & data, const std::string & varname, FILE * fh)
Save a MHA waveform as a variable in a Matlab4 file.
Parameters
data MHA waveform to be saved.
varname Matlab variable name (Matlab4 limitations on maximal length are not checked).
fh File handle to Matlab4 file.
References mha_wave_t::num_channels, mha_wave_t::num_frames, size(), and value().
void MHASignal::saveas_mat4 (const std::vector< mha_real_t > & data, const std::string & varname, FILE * fh)
Save a float vector as a variable in a Matlab4 file.
Parameters
data Float vector to be saved.
varname Matlab variable name (Matlab4 limitations on maximal length are not checked).
fh File handle to Matlab4 file.
void MHASignal::copy_permuted (mha_wave_t * dest, const mha_wave_t * src)
Copy contents of a waveform to a permuted waveform.
Parameters
dest Destination waveform
src Source waveform
The total size of src and dest must be the same, num_frames and num_channels must be exchanged in dest.
References mha_wave_t::buf, MHA_assert_equal, mha_wave_t::num_channels, mha_wave_t::num_frames, size(), and value().
Referenced by quantile().
Variable Documentation
unsigned long int MHASignal::signal_counter = 0
Signal counter to produce signal ID strings.
Referenced by value().