openMHA Manual: MHA_TCP Namespace Reference
MHA_TCP Namespace Reference
Classes
class Async_Notify
Portable Multiplexable cross-thread notification.
class Client
class Connection
class Event_Watcher
struct OS_EVENT_TYPE
class Server
class Sockaccept_Event
class Sockread_Event
class Sockwrite_Event
class Thread
class Timeout_Event
class Timeout_Watcher
class Wakeup_Event
Typedefs
typedef int SOCKET
Functions
std::string STRERROR (int err)
std::string HSTRERROR (int err)
int N_ERRNO ()
int H_ERRNO ()
int G_ERRNO ()
double dtime ()
double dtime (const struct timeval &tv)
struct timeval stime (double d)
Detailed Description
A Namespace for TCP helper classes
Typedef Documentation
typedef int MHA_TCP::SOCKET
Function Documentation
std::string MHA_TCP::STRERROR (int err)
Portable conversion from error number to error string.
Referenced by MHA_TCP::Async_Notify::Async_Notify(), HSTRERROR(), MHA_TCP::Server::initialize(), MHA_TCP::Async_Notify::reset(), MHA_TCP::Async_Notify::set(), MHA_TCP::Sockaccept_Event::Sockaccept_Event(), MHA_TCP::Sockread_Event::Sockread_Event(), MHA_TCP::Connection::sysread(), MHA_TCP::Connection::syswrite(), tcp_connect_to(), tcp_connect_to_with_timeout(), MHA_TCP::Thread::Thread(), MHA_TCP::Timeout_Event::Timeout_Event(), MHA_TCP::Server::try_accept(), and MHA_TCP::Event_Watcher::wait().
std::string MHA_TCP::HSTRERROR (int err)
Portable conversion from hostname error number to error string.
References STRERROR().
Referenced by host_port_to_sock_addr().
int MHA_TCP::N_ERRNO ()
Portable access to last network error number.
Referenced by MHA_TCP::Server::initialize(), MHA_TCP::Sockaccept_Event::Sockaccept_Event(), MHA_TCP::Sockread_Event::Sockread_Event(), MHA_TCP::Connection::sysread(), MHA_TCP::Connection::syswrite(), tcp_connect_to(), tcp_connect_to_with_timeout(), and MHA_TCP::Server::try_accept().
int MHA_TCP::H_ERRNO ()
Portable access to last hostname error number.
Referenced by host_port_to_sock_addr().
int MHA_TCP::G_ERRNO ()
Portable access to last non-network error number.
Referenced by MHA_TCP::Async_Notify::Async_Notify(), MHA_TCP::Async_Notify::reset(), MHA_TCP::Async_Notify::set(), MHA_TCP::Thread::Thread(), MHA_TCP::Timeout_Event::Timeout_Event(), and MHA_TCP::Event_Watcher::wait().
double MHA_TCP::dtime ()
Time access function for system's high resolution time, retrieve current time as double.
References MHA_ErrorMsg.
Referenced by MHA_TCP::Timeout_Event::get_os_event(), MHA_TCP::Timeout_Event::Timeout_Event(), and MHA_TCP::Event_Watcher::wait().
double MHA_TCP::dtime (const struct timeval & tv)
Time access function for unix' high resolution time, converts struct timeval to double.
struct timeval MHA_TCP::stime (double d)
Time access function for unix' high resolution time, converts time from double to struct timeval.