openMHA Manual: MHAOvlFilter::ShapeFun Namespace Reference
MHAOvlFilter::ShapeFun Namespace Reference
Shape functions for overlapping filters.
Functions
mha_real_t rect (mha_real_t x)
Filter shape function for rectangular filters.
mha_real_t linear (mha_real_t x)
Filter shape function for sawtooth filters.
mha_real_t hann (mha_real_t x)
Filter shape function for hanning shaped filters.
mha_real_t expflt (mha_real_t)
mha_real_t gauss (mha_real_t)
Detailed Description
Shape functions for overlapping filters.
Function Documentation
mha_real_t MHAOvlFilter::ShapeFun::rect (mha_real_t x)
Filter shape function for rectangular filters.
This function creates rectangular filter shapes. The edge is exactly half way between two center frequencies (on a given scale).
Parameters
x Input value in the range [-1,1].
Returns
Weigth function in the range [0,1]
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t().
mha_real_t MHAOvlFilter::ShapeFun::linear (mha_real_t x)
Filter shape function for sawtooth filters.
This function creates sawtooth filter shapes. They rise linearly form 0 to 1 in the interval from the lower neighbor center frequency to the band center frequency and from 1 to 0 in the interval from the band center frequency to the upper neighbour band center frequency. Linear means linear on a given frequency scale.
Parameters
x Input value in the range [-1,1].
Returns
Weigth function in the range [0,1]
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t().
mha_real_t MHAOvlFilter::ShapeFun::hann (mha_real_t x)
Filter shape function for hanning shaped filters.
This function creates hanning window shaped filters.
Parameters
x Input value in the range [-1,1].
Returns
Weigth function in the range [0,1]
References M_PI.
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t(), and MHAFilter::resampling_filter_t::resampling_filter_t().
mha_real_t MHAOvlFilter::ShapeFun::expflt (mha_real_t x)
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t().
mha_real_t MHAOvlFilter::ShapeFun::gauss (mha_real_t x)
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t().