openMHA Manual: Complex aithmetics in the MHA
Complex aithmetics in the MHA
The MHA Toolbox library
Classes
struct mha_complex_t
Type for complex floating point values.
Functions
mha_complex_t & set (mha_complex_t &self, mha_real_t real, mha_real_t imag=0)
Assign real and imaginary parts to a mha_complex_t variable.
mha_complex_t mha_complex (mha_real_t real, mha_real_t imag=0)
Create a new mha_complex_t with specified real and imaginary parts.
mha_complex_t & set (mha_complex_t &self, const std::complex< mha_real_t > &stdcomplex)
Assign a mha_complex_t variable from a std::complex.
std::complex< mha_real_t > stdcomplex (const mha_complex_t &self)
Create a std::complex from mha_complex_t.
mha_complex_t & expi (mha_complex_t &self, mha_real_t angle)
replaces the value of the given mha_complex_t with exp(i*b).
double angle (const mha_complex_t &self)
Computes the angle of a complex number in the complex plane.
mha_complex_t & operator+= (mha_complex_t &self, const mha_complex_t &other)
Addition of two complex numbers, overwriting the first.
mha_complex_t operator+ (const mha_complex_t &self, const mha_complex_t &other)
Addition of two complex numbers, result is a temporary object.
mha_complex_t & operator+= (mha_complex_t &self, mha_real_t other_real)
Addition of a complex and a real number, overwriting the complex.
mha_complex_t operator+ (const mha_complex_t &self, mha_real_t other_real)
Addition of a complex and a real number, result is a temporary object.
mha_complex_t & operator-= (mha_complex_t &self, const mha_complex_t &other)
Subtraction of two complex numbers, overwriting the first.
mha_complex_t operator- (const mha_complex_t &self, const mha_complex_t &other)
Subtraction of two complex numbers, result is a temporary object.
mha_complex_t & operator-= (mha_complex_t &self, mha_real_t other_real)
Subtraction of a complex and a real number, overwriting the complex.
mha_complex_t operator- (const mha_complex_t &self, mha_real_t other_real)
Subtraction of a complex and a real number, result is a temporary object.
mha_complex_t & operator*= (mha_complex_t &self, const mha_complex_t &other)
Multiplication of two complex numbers, overwriting the first.
mha_complex_t operator* (const mha_complex_t &self, const mha_complex_t &other)
Multiplication of two complex numbers, result is a temporary object.
mha_complex_t & operator*= (mha_complex_t &self, mha_real_t other_real)
Multiplication of a complex and a real number, overwriting the complex.
mha_complex_t & expi (mha_complex_t &self, mha_real_t angle, mha_real_t factor)
replaces (!) the value of the given mha_complex_t with a * exp(i*b)
mha_complex_t operator* (const mha_complex_t &self, mha_real_t other_real)
Multiplication of a complex and a real number, result is a temporary object.
mha_real_t abs2 (const mha_complex_t &self)
Compute the square of the absolute value of a complex value.
mha_real_t abs (const mha_complex_t &self)
Compute the absolute value of a complex value.
mha_complex_t & operator/= (mha_complex_t &self, mha_real_t other_real)
Division of a complex and a real number, overwriting the complex.
mha_complex_t operator/ (const mha_complex_t &self, mha_real_t other_real)
Division of a complex and a real number, result is a temporary object.
mha_complex_t & safe_div (mha_complex_t &self, const mha_complex_t &other, mha_real_t eps, mha_real_t eps2)
mha_complex_t & operator/= (mha_complex_t &self, const mha_complex_t &other)
Division of two complex numbers, overwriting the first.
mha_complex_t operator/ (const mha_complex_t &self, const mha_complex_t &other)
Division of two complex numbers, result is a temporary object.
mha_complex_t operator- (const mha_complex_t &self)
Unary minus on a complex results in a negative temporary object.
bool operator== (const mha_complex_t &x, const mha_complex_t &y)
Compare two complex numbers for equality.
bool operator!= (const mha_complex_t &x, const mha_complex_t &y)
Compare two complex numbers for inequality.
void conjugate (mha_complex_t &self)
Replace (!) the value of this mha_complex_t with its conjugate.
mha_complex_t _conjugate (const mha_complex_t &self)
Compute the cojugate of this complex value.
void reciprocal (mha_complex_t &self)
Replace the value of this complex with its reciprocal.
mha_complex_t _reciprocal (const mha_complex_t &self)
compute the reciprocal of this complex value.
void normalize (mha_complex_t &self)
Divide a complex by its absolute value, thereby normalizing it (projecting onto the unit circle).
void normalize (mha_complex_t &self, mha_real_t margin)
Divide a complex by its absolute value, thereby normalizing it (projecting onto the unit circle), with a safety margin.
bool almost (const mha_complex_t &self, const mha_complex_t &other, mha_real_t times_epsilon=1e2)
Compare two complex numbers for equality except for a small relative error.
bool operator< (const mha_complex_t &x, const mha_complex_t &y)
Compares the absolute values of two complex numbers.
Detailed Description
Function Documentation
mha_complex_t& set (mha_complex_t & self, mha_real_t real, mha_real_t imag = 0) inline
Assign real and imaginary parts to a mha_complex_t variable.
Parameters
self The mha_complex_t variable whose value is about to change.
real The new real part.
imag The new imaginary part.
Returns
A reference to the changed variable.
References mha_complex_t::re.
mha_complex_t mha_complex (mha_real_t real, mha_real_t imag = 0) inline
Create a new mha_complex_t with specified real and imaginary parts.
Parameters
real The real part.
imag The imaginary part.
Returns
The new value.
Referenced by adm_fir_decomb(), adm_fir_lp(), speechnoise_t::creator(), MHAFilter::complex_bandpass_t::creator_B(), MHAOvlFilter::overlap_save_filterbank_t::overlap_save_filterbank_t(), MHAFilter::gamma_flt_t::phase_correction(), coherence::cohflt_t::process(), MHAFilter::complex_bandpass_t::set_state(), and MHAFilter::iir_ord1_real_t::set_state().
mha_complex_t& set (mha_complex_t & self, const std::complex< mha_real_t > & stdcomplex) inline
Assign a mha_complex_t variable from a std::complex.
Parameters
self The mha_complex_t variable whose value is about to change.
stdcomplex The new complex value.
Returns
A reference to the changed variable.
References mha_complex_t::re, and stdcomplex().
std::complex<mha_real_t> stdcomplex (const mha_complex_t & self) inline
Create a std::complex from mha_complex_t.
Referenced by set().
mha_complex_t& expi (mha_complex_t & self, mha_real_t angle) inline
replaces the value of the given mha_complex_t with exp(i*b).
Parameters
self The mha_complex_t variable whose value is about to change.
angle The angle in the complex plane [rad].
Returns
A reference to the changed variable.
Referenced by speechnoise_t::creator(), MHAFilter::complex_bandpass_t::creator_A(), expi(), MHASignal::minphase_t::operator()(), MHASignal::schroeder_t::schroeder_t(), set_minabs(), and MHASignal::subsample_delay_t::subsample_delay_t().
double angle (const mha_complex_t & self) inline
Computes the angle of a complex number in the complex plane.
Parameters
self The complex number whose angle is needed.
Returns
The angle of a complex number in the complex plane.
Referenced by set_minabs().
mha_complex_t& operator+= (mha_complex_t & self, const mha_complex_t & other) inline
Addition of two complex numbers, overwriting the first.
References mha_complex_t::im, and mha_complex_t::re.
mha_complex_t operator+ (const mha_complex_t & self, const mha_complex_t & other) inline
Addition of two complex numbers, result is a temporary object.
mha_complex_t& operator+= (mha_complex_t & self, mha_real_t other_real) inline
Addition of a complex and a real number, overwriting the complex.
mha_complex_t operator+ (const mha_complex_t & self, mha_real_t other_real) inline
Addition of a complex and a real number, result is a temporary object.
mha_complex_t& operator-= (mha_complex_t & self, const mha_complex_t & other) inline
Subtraction of two complex numbers, overwriting the first.
References mha_complex_t::im, and mha_complex_t::re.
mha_complex_t operator- (const mha_complex_t & self, const mha_complex_t & other) inline
Subtraction of two complex numbers, result is a temporary object.
mha_complex_t& operator-= (mha_complex_t & self, mha_real_t other_real) inline
Subtraction of a complex and a real number, overwriting the complex.
mha_complex_t operator- (const mha_complex_t & self, mha_real_t other_real) inline
Subtraction of a complex and a real number, result is a temporary object.
mha_complex_t& operator*= (mha_complex_t & self, const mha_complex_t & other) inline
Multiplication of two complex numbers, overwriting the first.
References mha_complex_t::im, and mha_complex_t::re.
mha_complex_t operator* (const mha_complex_t & self, const mha_complex_t & other) inline
Multiplication of two complex numbers, result is a temporary object.
mha_complex_t& operator*= (mha_complex_t & self, mha_real_t other_real) inline
Multiplication of a complex and a real number, overwriting the complex.
mha_complex_t& expi (mha_complex_t & self, mha_real_t angle, mha_real_t factor) inline
replaces (!) the value of the given mha_complex_t with a * exp(i*b)
Parameters
self The mha_complex_t variable whose value is about to change.
angle The imaginary exponent.
factor The absolute value of the result.
Returns
A reference to the changed variable.
References expi().
mha_complex_t operator* (const mha_complex_t & self, mha_real_t other_real) inline
Multiplication of a complex and a real number, result is a temporary object.
mha_real_t abs2 (const mha_complex_t & self) inline
Compute the square of the absolute value of a complex value.
Returns
The square of the absolute value of self.
Referenced by abs(), MHAOvlFilter::fftfb_t::get_fbpower(), intensity(), operator<(), coherence::cohflt_t::process(), dc::dc_t::process(), reciprocal(), and safe_div().
mha_real_t abs (const mha_complex_t & self) inline
Compute the absolute value of a complex value.
Returns
The absolute value of self.
References abs2().
Referenced by almost(), MHAFilter::complex_bandpass_t::creator_B(), coherence::getcipd(), MHASignal::maxabs(), normalize(), MHASignal::minphase_t::operator()(), MHAFilter::gamma_flt_t::phase_correction(), coherence::cohflt_t::process(), and set_minabs().
mha_complex_t& operator/= (mha_complex_t & self, mha_real_t other_real) inline
Division of a complex and a real number, overwriting the complex.
mha_complex_t operator/ (const mha_complex_t & self, mha_real_t other_real) inline
Division of a complex and a real number, result is a temporary object.
mha_complex_t& safe_div (mha_complex_t & self, const mha_complex_t & other, mha_real_t eps, mha_real_t eps2) inline
Safe division of two complex numbers, overwriting the first. If abs(divisor) < eps, then divisor is replaced by eps. eps2 = eps*eps.
References abs2(), mha_complex_t::im, and mha_complex_t::re.
mha_complex_t& operator/= (mha_complex_t & self, const mha_complex_t & other) inline
Division of two complex numbers, overwriting the first.
References safe_div().
mha_complex_t operator/ (const mha_complex_t & self, const mha_complex_t & other) inline
Division of two complex numbers, result is a temporary object.
mha_complex_t operator- (const mha_complex_t & self) inline
Unary minus on a complex results in a negative temporary object.
References mha_complex_t::re.
bool operator== (const mha_complex_t & x, const mha_complex_t & y) inline
Compare two complex numbers for equality.
References mha_complex_t::im, and mha_complex_t::re.
bool operator!= (const mha_complex_t & x, const mha_complex_t & y) inline
Compare two complex numbers for inequality.
void conjugate (mha_complex_t & self) inline
Replace (!) the value of this mha_complex_t with its conjugate.
Referenced by _conjugate(), conjugate(), and reciprocal().
mha_complex_t _conjugate (const mha_complex_t & self) inline
Compute the cojugate of this complex value.
Returns
A temporary object holding the conjugate value.
References conjugate().
void reciprocal (mha_complex_t & self) inline
Replace the value of this complex with its reciprocal.
References abs2(), and conjugate().
Referenced by _reciprocal().
mha_complex_t _reciprocal (const mha_complex_t & self) inline
compute the reciprocal of this complex value.
Returns
A temporary object holding the reciprocal value.
References reciprocal().
void normalize (mha_complex_t & self) inline
Divide a complex by its absolute value, thereby normalizing it (projecting onto the unit circle).
References abs().
Referenced by MHAFilter::gamma_flt_t::phase_correction().
void normalize (mha_complex_t & self, mha_real_t margin) inline
Divide a complex by its absolute value, thereby normalizing it (projecting onto the unit circle), with a safety margin.
References abs(), and MHASignal::max().
bool almost (const mha_complex_t & self, const mha_complex_t & other, mha_real_t times_epsilon = 1e2) inline
Compare two complex numbers for equality except for a small relative error.
Parameters
self The first complex number.
other The second complex number.
times_epsilon Permitted relative error is this number multiplied with the machine accuracy for this Floating point format (std::numeric_limits<mha_real_t>::epsilon)
Returns
true if the relative difference is below times_epsilon * std::numeric_limits<mha_real_t>::epsilon
References abs().
bool operator< (const mha_complex_t & x, const mha_complex_t & y) inline
Compares the absolute values of two complex numbers.
References abs2().