openMHA Manual: PluginLoader Namespace Reference
PluginLoader Namespace Reference
Classes
class config_file_splitter_t
class fourway_processor_t
class mhapluginloader_t
Functions
const char * mhastrdomain (mha_domain_t)
void mhaconfig_compare (const mhaconfig_t &req, const mhaconfig_t &avail, const std::string &pref="")
Compare two mhaconfig_t structures, and report differences as an error.
Function Documentation
const char * PluginLoader::mhastrdomain (mha_domain_t d)
References MHA_SPECTRUM, and MHA_WAVEFORM.
Referenced by mhaconfig_compare(), mhaconfig_compare(), and PluginLoader::mhapluginloader_t::prepare().
void PluginLoader::mhaconfig_compare (const mhaconfig_t & req, const mhaconfig_t & avail, const std::string & pref = "")
Compare two mhaconfig_t structures, and report differences as an error.
Parameters
req Expected mhaconfig_t structure
avail Available mhaconfig_t structure
pref Prefix for error messages
References mhaconfig_t::channels, mhaconfig_t::domain, mhaconfig_t::fftlen, mhaconfig_t::fragsize, MHA_SPECTRUM, mhastrdomain(), mhaconfig_t::srate, and mhaconfig_t::wndlen.