openMHA Manual: mhamain.cpp File Reference
mhamain.cpp File Reference
#include "mhafw_lib.h"
#include "mha_parser.hh"
#include <getopt.h>
#include <stdarg.h>
#include "mha_license.h"
#include <fstream>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include <string>
#include "mha_tcp.hh"
Classes
class mhaserver_t
MHA Framework listening on TCP port for commands.
Macros
#define MAX_LINE_LENGTH 0x100000
#define HELP_TEXT
#define GREETING_TEXT
Functions
void create_lock (unsigned int p, std::string s)
void remove_lock (unsigned int p)
int mhamain (int argc, char *argv[])
Macro Definition Documentation
#define MAX_LINE_LENGTH 0x100000
#define HELP_TEXT
Referenced by mhamain().
#define GREETING_TEXT
Referenced by mhamain().
Function Documentation
void create_lock (unsigned int p, std::string s)
References MHAParser::StrCnv::val2str().
Referenced by mhamain().
void remove_lock (unsigned int p)
References MHAParser::StrCnv::val2str().
Referenced by mhamain().
int mhamain (int argc, char * argv[])
References mhaserver_t::ack_fail, mhaserver_t::ack_ok, mhaserver_t::announce_port, create_lock(), MHAParser::int_t::data, fw_t::exit_request(), GREETING_TEXT, HELP_TEXT, LICENSE_AGREEMENT, mhaserver_t::logfile, mhaserver_t::logstring(), mhaserver_t::mhaserver_t(), MHAParser::base_t::parse(), mhaserver_t::port, remove_lock(), mhaserver_t::run(), and mhaserver_t::set_announce_port().
Referenced by main().