openMHA Manual: MHAOvlFilter::FreqScaleFun Namespace Reference
MHAOvlFilter::FreqScaleFun Namespace Reference
Transform functions from linear scale in Hz to new frequency scales.
Functions
mha_real_t hz2hz (mha_real_t x)
Dummy scale transformation Hz to Hz.
mha_real_t hz2khz (mha_real_t x)
mha_real_t hz2octave (mha_real_t x)
mha_real_t hz2third_octave (mha_real_t x)
mha_real_t hz2bark (mha_real_t x)
Transformation to bark scale.
mha_real_t hz2bark_analytic (mha_real_t)
mha_real_t hz2erb (mha_real_t)
mha_real_t hz2erb_glasberg1990 (mha_real_t)
mha_real_t hz2log (mha_real_t x)
Third octave frequency scale.
mha_real_t inv_scale (mha_real_t, mha_real_t(*)(mha_real_t))
Detailed Description
Transform functions from linear scale in Hz to new frequency scales.
Function Documentation
mha_real_t MHAOvlFilter::FreqScaleFun::hz2hz (mha_real_t x)
Dummy scale transformation Hz to Hz.
This function implements a dummy scale transformation (linear frequency scale).
Parameters
x Input frequency in Hz
Returns
Frequency in Hz
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t(), and MHAOvlFilter::fscale_t::fscale_t().
mha_real_t MHAOvlFilter::FreqScaleFun::hz2khz (mha_real_t x)
Referenced by MHAOvlFilter::fscale_t::fscale_t().
mha_real_t MHAOvlFilter::FreqScaleFun::hz2octave (mha_real_t x)
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t(), and MHAOvlFilter::fscale_t::fscale_t().
mha_real_t MHAOvlFilter::FreqScaleFun::hz2third_octave (mha_real_t x)
Referenced by MHAOvlFilter::fscale_t::fscale_t().
mha_real_t MHAOvlFilter::FreqScaleFun::hz2bark (mha_real_t x)
Transformation to bark scale.
This function implements a critical band rate (bark) scale.
Parameters
x Input frequency in Hz
Returns
Critical band rate in Bark
References MHATableLookup::xy_table_t::interp().
mha_real_t MHAOvlFilter::FreqScaleFun::hz2bark_analytic (mha_real_t x)
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t(), and MHAOvlFilter::fscale_t::fscale_t().
mha_real_t MHAOvlFilter::FreqScaleFun::hz2erb (mha_real_t x)
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t(), and MHAOvlFilter::fscale_t::fscale_t().
mha_real_t MHAOvlFilter::FreqScaleFun::hz2erb_glasberg1990 (mha_real_t x)
Referenced by MHAOvlFilter::fftfb_vars_t::fftfb_vars_t(), and MHAOvlFilter::fscale_t::fscale_t().
mha_real_t MHAOvlFilter::FreqScaleFun::hz2log (mha_real_t x)
Third octave frequency scale.
This function implements a third octave scale. Frequencies below 16 Hz are mapped to 16 Hz.
Parameters
x Frequency in Hz
Returns
Third octaves relative to 1000 Hz
mha_real_t MHAOvlFilter::FreqScaleFun::inv_scale (mha_real_t y, mha_real_t(*)(mha_real_t) fun)
Referenced by MHAOvlFilter::fspacing_t::get_cf_hz(), MHAOvlFilter::fspacing_t::get_ef_hz(), and MHAOvlFilter::scale_var_t::unit2hz().