openMHA Manual: MHAParser::StrCnv Namespace Reference
MHAParser::StrCnv Namespace Reference
String converter namespace.
Functions
int num_brackets (const std::string &s)
Return number of brackets at beginning and end of string.
int bracket_balance (const std::string &s)
void str2val (const std::string &, bool &)
Convert from string.
void str2val (const std::string &, float &)
Convert from string.
void str2val (const std::string &, mha_complex_t &)
Convert from string.
void str2val (const std::string &, int &)
Convert from string.
void str2val (const std::string &, keyword_list_t &)
Convert from string.
void str2val (const std::string &, std::string &)
Convert from string.
template<class arg_t >
void str2val (const std::string &s, std::vector< arg_t > &val)
Converter for vector types.
template<>
void str2val< mha_real_t > (const std::string &s, std::vector< mha_real_t > &v)
Converter for vector<mha_real_t> with Matlab-style expansion.
template<class arg_t >
void str2val (const std::string &s, std::vector< std::vector< arg_t > > &val)
Converter for matrix types.
std::string val2str (const bool &)
Convert to string.
std::string val2str (const float &)
Convert to string.
std::string val2str (const mha_complex_t &)
Convert to string.
std::string val2str (const int &)
Convert to string.
std::string val2str (const keyword_list_t &)
Convert to string.
std::string val2str (const std::string &)
Convert to string.
std::string val2str (const std::vector< float > &)
Convert to string.
std::string val2str (const std::vector< mha_complex_t > &)
Convert to string.
std::string val2str (const std::vector< int > &)
Convert to string.
std::string val2str (const std::vector< std::string > &)
Convert to string.
std::string val2str (const std::vector< std::vector< float > > &)
Convert to string.
std::string val2str (const std::vector< std::vector< mha_complex_t > > &)
Convert to string.
Detailed Description
String converter namespace.
The functions defined in this namespace manage the conversions from C++ variables to strings and back. It was tried to keep a matlab compatible string format for vectors and vectors of vectors.
Function Documentation
int MHAParser::StrCnv::num_brackets (const std::string & s)
Return number of brackets at beginning and end of string.
Parameters
s String
Returns
Number of brackets, or -1 for empty string
References MHAParser::trim().
Referenced by str2val(), and str2val< mha_real_t >().
int MHAParser::StrCnv::bracket_balance (const std::string & s)
void MHAParser::StrCnv::str2val (const std::string & s, bool & v)
Convert from string.
Referenced by MHA_AC::acspace2matrix_t::acspace2matrix_t(), MHAParser::all_dump(), MHAParser::all_ids(), MHAParser::cfg_dump(), MHAParser::cfg_dump_short(), MHAMultiSrc::channels_t::channels_t(), latex_doc_t::get_ac(), latex_doc_t::get_parser_tab(), MHAParser::mon_dump(), MHAParser::parser_t::op_setval(), MHAParser::kw_t::op_setval(), MHAParser::vstring_t::op_setval(), MHAParser::bool_t::op_setval(), MHAParser::int_t::op_setval(), MHAParser::float_t::op_setval(), MHAParser::complex_t::op_setval(), MHAParser::vint_t::op_setval(), MHAParser::vfloat_t::op_setval(), MHAParser::vcomplex_t::op_setval(), MHAParser::mfloat_t::op_setval(), MHAParser::mcomplex_t::op_setval(), print_ac(), PluginLoader::mhapluginloader_t::resolve_and_init(), pluginbrowser_t::scan_plugin(), MHAParser::keyword_list_t::set_entries(), MHAParser::range_var_t::set_range(), str2val(), and str2val< mha_real_t >().
void MHAParser::StrCnv::str2val (const std::string & s, float & v)
Convert from string.
void MHAParser::StrCnv::str2val (const std::string & s, mha_complex_t & v)
Convert from string.
References parse_1_complex().
void MHAParser::StrCnv::str2val (const std::string & s, int & v)
Convert from string.
void MHAParser::StrCnv::str2val (const std::string & s, MHAParser::keyword_list_t & v)
Convert from string.
References MHAParser::keyword_list_t::set_value().
void MHAParser::StrCnv::str2val (const std::string & s, std::string & v)
Convert from string.
template<class arg_t > void MHAParser::StrCnv::str2val (const std::string & s, std::vector< arg_t > & val)
Converter for vector types.
References num_brackets(), and str2val().
template<> void MHAParser::StrCnv::str2val< mha_real_t > (const std::string & s, std::vector< mha_real_t > & v)
Converter for vector<mha_real_t> with Matlab-style expansion.
References MHAParser::expression_t::lval, num_brackets(), MHAParser::expression_t::rval, and str2val().
template<class arg_t > void MHAParser::StrCnv::str2val (const std::string & s, std::vector< std::vector< arg_t > > & val)
Converter for matrix types.
References num_brackets(), size(), str2val(), and MHAParser::trim().
std::string MHAParser::StrCnv::val2str (const bool & v)
Convert to string.
Referenced by mhaserver_t::acceptor_started(), MHAOvlFilter::scale_var_t::add_fun(), io_tcp_t::connection_loop(), create_lock(), MHAFilter::complex_bandpass_t::inspect(), MHAFilter::gamma_flt_t::inspect(), MHASignal::delay_t::inspect(), main(), MHAParser::range_var_t::query_range(), MHAParser::kw_t::query_range(), MHAParser::kw_t::query_val(), MHAParser::vstring_t::query_val(), MHAParser::bool_t::query_val(), MHAParser::int_t::query_val(), MHAParser::float_t::query_val(), MHAParser::complex_t::query_val(), MHAParser::vint_t::query_val(), MHAParser::vfloat_t::query_val(), MHAParser::vcomplex_t::query_val(), MHAParser::mfloat_t::query_val(), MHAParser::mcomplex_t::query_val(), MHAParser::int_mon_t::query_val(), MHAParser::bool_mon_t::query_val(), MHAParser::string_mon_t::query_val(), MHAParser::vstring_mon_t::query_val(), MHAParser::vint_mon_t::query_val(), MHAParser::vfloat_mon_t::query_val(), MHAParser::mfloat_mon_t::query_val(), MHAParser::float_mon_t::query_val(), MHAParser::complex_mon_t::query_val(), MHAParser::vcomplex_mon_t::query_val(), MHAParser::mcomplex_mon_t::query_val(), mhaserver_t::received_group(), remove_lock(), mhaserver_t::run(), MHAParser::keyword_list_t::set_value(), val2str(), and MHAParser::range_var_t::validate().
std::string MHAParser::StrCnv::val2str (const float & v)
Convert to string.
References MHAParser::get_precision(), and write_float().
std::string MHAParser::StrCnv::val2str (const mha_complex_t & v)
Convert to string.
References MHAParser::get_precision(), mha_complex_t::im, mha_complex_t::re, and write_float().
std::string MHAParser::StrCnv::val2str (const int & v)
Convert to string.
std::string MHAParser::StrCnv::val2str (const keyword_list_t & v)
Convert to string.
References MHAParser::keyword_list_t::get_value().
std::string MHAParser::StrCnv::val2str (const std::string & v)
Convert to string.
std::string MHAParser::StrCnv::val2str (const std::vector< float > & v)
Convert to string.
References val2str().
std::string MHAParser::StrCnv::val2str (const std::vector< mha_complex_t > & v)
Convert to string.
References val2str().
std::string MHAParser::StrCnv::val2str (const std::vector< int > & v)
Convert to string.
References val2str().
std::string MHAParser::StrCnv::val2str (const std::vector< std::string > & v)
Convert to string.
References val2str().
std::string MHAParser::StrCnv::val2str (const std::vector< std::vector< float > > & v)
Convert to string.
References val2str().
std::string MHAParser::StrCnv::val2str (const std::vector< std::vector< mha_complex_t > > & v)
Convert to string.
References val2str().