openMHA Manual: MHAFilter Namespace Reference
MHAFilter Namespace Reference
The MHA Toolbox library
Namespace for IIR and FIR filter classes.
Classes
class adapt_filter_param_t
class adapt_filter_state_t
class adapt_filter_t
Adaptive filter.
class blockprocessing_polyphase_resampling_t
A class that does polyphase resampling and takes into account block processing.
class complex_bandpass_t
Complex bandpass filter.
class diff_t
Differentiator class (non-normalized)
class fftfilter_t
FFT based FIR filter implementation.
class fftfilterbank_t
FFT based FIR filterbank implementation.
class filter_t
Generic IIR filter class.
class gamma_flt_t
Class for gammatone filter.
class iir_filter_state_t
class iir_filter_t
IIR filter class wrapper for integration into parser structure.
class iir_ord1_real_t
First order recursive filter.
class o1_ar_filter_t
First order attack-release lowpass filter.
class o1flt_lowpass_t
First order low pass filter.
class o1flt_maxtrack_t
First order maximum tracker.
class o1flt_mintrack_t
First order minimum tracker.
class partitioned_convolution_t
A filter class for partitioned convolution.
class polyphase_resampling_t
A class that does polyphase resampling.
class resampling_filter_t
Hann shaped low pass filter for resampling.
class smoothspec_t
Smooth spectral gains, create a windowed impulse response.
class thirdoctave_analyzer_t
struct transfer_function_t
a structure containing a source channel number, a target channel number, and an impulse response.
struct transfer_matrix_t
A sparse matrix of transfer function partitionss.
Functions
void make_friendly_number (mha_real_t &x)
void make_friendly_number (mha_complex_t &x)
void make_friendly_number (double &x)
void o1_lp_coeffs (const mha_real_t tau, const mha_real_t fs, mha_real_t &c1, mha_real_t &c2)
Set first order filter coefficients from time constant and sampling rate.
void butter_stop_ord1 (double *A, double *B, double f1, double f2, double fs)
Setup a first order butterworth band stop filter.
MHASignal::waveform_t * spec2fir (const mha_spec_t *spec, const unsigned int fftlen, const MHAWindow::base_t &window, const bool minphase)
Create a windowed impulse response/FIR filter coefficients from a spectrum.
unsigned gcd (unsigned a, unsigned b)
greatest common divisor
double sinc (double x)
sin(x)/x function, coping with x=0.
std::pair< unsigned, unsigned > resampling_factors (float source_sampling_rate, float target_sampling_rate, float factor=1.0f)
Computes rational resampling factor from two sampling rates.
Detailed Description
Namespace for IIR and FIR filter classes.
Function Documentation
void MHAFilter::make_friendly_number (mha_real_t & x) inline
References MHASignal::max(), and MHASignal::min().
Referenced by MHAFilter::filter_t::filter(), make_friendly_number(), and MHAFilter::o1_ar_filter_t::operator()().
void MHAFilter::make_friendly_number (mha_complex_t & x) inline
References mha_complex_t::im, make_friendly_number(), and mha_complex_t::re.
void MHAFilter::make_friendly_number (double & x) inline
References MHASignal::max(), and MHASignal::min().
void MHAFilter::o1_lp_coeffs (const mha_real_t tau, const mha_real_t fs, mha_real_t & c1, mha_real_t & c2)
Set first order filter coefficients from time constant and sampling rate.
Parameters
tau Time constant
fs Sampling rate
Return values
c1 Recursive filter coefficient
c2 Non-recursive filter coefficient
Referenced by MHAFilter::iir_ord1_real_t::iir_ord1_real_t(), MHAFilter::o1_ar_filter_t::set_tau_attack(), and MHAFilter::o1_ar_filter_t::set_tau_release().
void MHAFilter::butter_stop_ord1 (double * A, double * B, double f1, double f2, double fs)
Setup a first order butterworth band stop filter.
This function calculates the filter coefficients of a first order butterworth band stop filter.
Return values
A recursive filter coefficients
B non recursive filter coefficients
Parameters
f1 lower frequency
f2 upper frequency
fs sample frequency
References M_PI.
MHASignal::waveform_t * MHAFilter::spec2fir (const mha_spec_t * spec, const unsigned int fftlen, const MHAWindow::base_t & window, const bool minphase)
Create a windowed impulse response/FIR filter coefficients from a spectrum.
Parameters
spec Input spectrum
fftlen FFT length of spectrum
window Window shape (with length, e.g. initialized with MHAWindow::hanning(54)).
minphase Flag, true if original phase should be discarded and replaced by a minimal phase function.
References CHECK_VAR, mha_spec_t::num_channels, mha_wave_t::num_frames, and MHAFilter::smoothspec_t::spec2fir().
Referenced by adm_fir_decomb(), adm_fir_lp(), MHAOvlFilter::overlap_save_filterbank_t::overlap_save_filterbank_t(), and MHAFilter::smoothspec_t::smoothspec().
unsigned MHAFilter::gcd (unsigned a, unsigned b) inline
greatest common divisor
References resampling_factors(), and sinc().
Referenced by MHAFilter::blockprocessing_polyphase_resampling_t::blockprocessing_polyphase_resampling_t(), and resampling_factors().
double MHAFilter::sinc (double x)
sin(x)/x function, coping with x=0.
This is the historical sinc function, not the normalized sinc function.
Referenced by gcd(), MHAFilter::polyphase_resampling_t::polyphase_resampling_t(), and MHAFilter::resampling_filter_t::resampling_filter_t().
std::pair< unsigned, unsigned > MHAFilter::resampling_factors (float source_sampling_rate, float target_sampling_rate, float factor = 1.0f)
Computes rational resampling factor from two sampling rates.
The function will fail if either sampling_rate * factor is not an integer
Parameters
source_sampling_rate The original sampling rate
target_sampling_rate The desired sampling rate
factor A helper factor to use for non-integer sampling rates
Returns
a pair that contains first the upsampling factor and second the downsampling factor required for the specified resampling.
Exceptions
MHA_Error if no rational resampling factor can be found.
References gcd(), and MHAFilter::polyphase_resampling_t::polyphase_resampling_t().
Referenced by MHAFilter::blockprocessing_polyphase_resampling_t::blockprocessing_polyphase_resampling_t(), and gcd().