# This file is part of the HörTech Open Master Hearing Aid (openMHA)
# Copyright © 2018 HörTech gGmbH
#
# openMHA is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# openMHA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License, version 3 for more details.
#
# You should have received a copy of the GNU Affero General Public License, 
# version 3 along with openMHA.  If not, see <http://www.gnu.org/licenses/>.

.PHONY: exe

exe:
	./find_and_copy_dependencies.sh
	makensis mha.nsi
	rm -rf LICENSE bin mfiles examples reference_algorithms doc
clean:
	rm -rf LICENSE bin mfiles examples reference_algorithms doc tmp* *exe

# Local Variables:
# compile-command: "make"
# End:
